### ISSUE TITLE
App crash on Swift Project using CocoaLumberjack as pod 

### ISSUE THREAD

**Issue by sumitjagdev** [CocoaLumberjack/CocoaLumberjack#1002]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [ ] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios / watchos
 Platform Version        | e.g. 12.0/12.1/12.0.1/watch 0s 5.1
 CocoaLumberjack Version | 3.4
 Integration Method      | cocoapods
 Xcode Version           | Xcode 9.4/10.0/10.1
 Repro rate              | 80%

### Issue Description and Steps

Crash on below files
```
1: DDFileLogger.m line 1104
-[DDLogFileInfo fileAttributes]

2: DDFileLogger.m line 1128
-[DDLogFileInfo creationDate]

3: DDFileLogger.m line 739
-[DDFileLogger scheduleTimerToRollLogFileDueToAge]

4: DDFileLogger.m line 955
-[DDFileLogger currentLogFileHandle]

5: DDFileLogger.m line 1004
-[DDFileLogger logMessage:]

6: DDLog.m line 840
__16-[DDLog lt_log:]_block_invoke
```

**Comment by hhanesand** [comment]
Is this a stack trace? Are you saying that DDFileLogger.m line 1104 is crashing? What is the error message?
