### ISSUE TITLE
<unknown>:0: error: unable to load standard library for target 'arm64-apple-ios8.0-simulator'

### ISSUE THREAD

**Issue by jjksam** [CocoaLumberjack/CocoaLumberjack#1004]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        | 12.1
 CocoaLumberjack Version | 3.4.2
 Integration Method      | carthage
 Xcode Version           | e.g. Xcode Version 10.1 (10B61)
 Repro rate              | all the time (100%)

### Issue Description and Steps
using the following command to update carthage
carthage update --no-use-binaries --platform iOS

#### compiler log as below
[carthage-xcodebuild.rX5eAq.log](https://github.com/CocoaLumberjack/CocoaLumberjack/files/2714052/carthage-xcodebuild.rX5eAq.log)

**Comment by jjksam** [comment]
Using Xcode to open the workspace or project file and compile will be ok to generate all the framework target.

**Comment by hhanesand** [comment]
@jjksam What device are you building on? Could you try selecting "Generic iOS Device"?

**Comment by ffried** [comment]
@jjksam The build looks fine. It's strange however, that it searches for the simulator stdlib when building for iPhoneOS...
Can you try cleaning the Carthage cache?
`rm -rf ~/Library/Caches/org.carthage.CarthageKit`

I cannot reproduce the issue here. I've added a Cartfile with CocoaLumberjack pointing to version 3.4.2 and ran the command you provided in the issue description.

**Comment by jjksam** [comment]
I ran another carthage update --no-use-binaries --platform iOS again today. It seems it had been fixed now, I can't reproduce it.
