### ISSUE TITLE
Official release for xcode10.1 timeline

### ISSUE THREAD

**Issue by mrinalsymc** [CocoaLumberjack/CocoaLumberjack#1008]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        | 12.0
 CocoaLumberjack Version | master
 Integration Method      |  carthage 
 Xcode Version           | Xcode 10.1

### Issue Description and Steps

Hi,

Currently in my project we are using the tip of the master cause 3.4.2 doesnt build with xcode 10.1. Are there any estimates when there is going to an official release for xcode 10.1

Thanks.

**Comment by hhanesand** [comment]
I'm in favor of releasing the current tip of master as 3.5.0, we've made reasonable progress towards the milestones already.

@rivera-ernesto @bpoplauschi Thoughts? It's a shame the lib doesn't compile.

**Comment by edwardvalentini** [comment]
yes current master seems to work in xcode 10.1 -- is it possible to do a release of what is currently there?

**Comment by bpoplauschi** [comment]
Agreed, let's wrap up the issues for 3.5.0 release and publish the official release.

**Comment by bpoplauschi** [comment]
Regarding Xcode 10.1, I think we are supporting it without any problem

**Comment by sushichop** [comment]
While I also can't specific date for releasing, I'm also in favor of releasing `3.5.0`.
Any thoughts? @CocoaLumberjack/collaborators 
Then, preparing for release, I have updated old demo and docs that were issued. See #1023 .
Thanks.

**Comment by bpoplauschi** [comment]
Thanks @sushichop 
I agree, let's wrap up and release 3.5.0.
Are there any PRs that need to get merged before releasing?

**Comment by ffried** [comment]
@bpoplauschi: If possible, I'd add #1019...

**Comment by sushichop** [comment]
@bdolman 
We should merge #1019.
Thanks @ffried .

**Comment by ffried** [comment]
@bpoplauschi just released version 3.5.0! 🎉

**Comment by bpoplauschi** [comment]
Yeap. Also via CocoaPods :) let's keep an eye out for feedback.
Great job @CocoaLumberjack/collaborators
