### ISSUE TITLE
Fix severity level of stale bot

### ISSUE THREAD

**Issue by lolgear** [CocoaLumberjack/CocoaLumberjack#1009]
Hm, It seems that @stalebot eats too much.
- Feature Request
- Discussion (no, of course. It is a forum post and not an issue. It can be closed only by )
- Awaiting Response ( ok, here we have fifty-fifty probability that issue was fixed and it is super rare, it can be closed ).

## Feature Request
These issues show a vector of future of this project.
Only a person can close this issue, not a bot.

## Discussion
These issues are not related to bug reporting. It is a general forum post with discussion and only for people.
Again, only a person can close this issue, not a bot.
Closing this issue by a bot is pinning "Shut your mouth" sign to community mouth.

## Awaiting Response
50/50.
This issue could be fixed and person is unreachable OR it is super rare and person is still unreachable.

What do you think?

**Comment by ffried** [comment]
**Feature request**
Yep, those might be worth excluding.

**Discussion**
I'm not a big fan of having those in issues. But on GitHub itself it seems like the only easy way to have those. Unless we have an open team for those.
We could exclude them from stale-bot. But who decides then if the discussion ended nowhere and should be closed? Who will do this job regularly? Having stale-bot slap the Stale label on them makes us aware of stale discussions. We can then still "un-stale" them by adding a simple comment, that might revive the discussion. If not, maybe it's not the wrong thing to close it. Also, why do we fear closed issues? No one says they cannot be re-opened...

**Awaiting Response**
Same as with discussions. If the OP does not respond within a given timeframe, the issue does not seem to have enough importance. For issues that seem important to use, we can still double the available timeframe by adding a simple comment.

**Comment by lolgear** [comment]
Also, all pinned issues should be invincible.

**Comment by ffried** [comment]
@lolgear Pinned issues *are* already left alone by stale-bot...

As for the other options:
- We currently don't use projects, so I'm not sure this is necessary - but it therefore wouldn't hurt, either.
- Milestones: This definitively sounds good.
- Assignees: AFAIK, anyone can assign issues on GitHub. So IMHO this is not really a good idea.

**Comment by lolgear** [comment]
@ffried 
So, it is another PR for GitHub team. :)
They still don't have starred repositories history, heh :/ I can unstar issue and forget about it :/
