### ISSUE TITLE
Travis logs should contain the reason for why tests fail.

### ISSUE THREAD

**Issue by hhanesand** [CocoaLumberjack/CocoaLumberjack#1017]
> @ffried On another note, any idea how we can see what caused a test failure while testing in Travis? Right now the log just shows which tests failed.

> @hhanesand I guess removing the output-pipe to xcpretty should give some more information (since we then get Xcode's output). Or try other options for xcpretty.

**Comment by ffried** [comment]
@hhanesand `xcpretty` didn't mess up anything in this case. It was really a crash (caused by an exception) and even `xcodebuild`'s output didn't contain the exact reason. It printed out some locations where the xctest session logs are written to and in there I found the crash report.

**Comment by ffried** [comment]
But getting those locations on Travis will be hard. I've done a little research and `xcpretty` would actually show if assertions (`XCTAssert...`) would fail. So I don't think that there's much we can do here. Also, _usually_ test failures are reproducible on local machines somehow.

**Comment by hhanesand** [comment]
Ah, okay.
