### ISSUE TITLE
Implicit conversion of 'int' to 'NSString *' is disallowed with ARC

### ISSUE THREAD

**Issue by shenguanjiejie** [CocoaLumberjack/CocoaLumberjack#1018]
### Issue Info
 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 12.0
 CocoaLumberjack Version | 3.4.2
 Integration Method      |  cocoapods
 Xcode Version           | Xcode 10
 Repro rate              |  only once

I just
```#import <CocoaLumberjack/CocoaLumberjack.h>```
And add:
![image](https://user-images.githubusercontent.com/9425605/51296243-2a422b80-1a56-11e9-8e29-244976b69486.png)

What's the problem?

**Comment by hhanesand** [comment]
You know, there's a reason we ask you for what version you're using. We'd appreciate it if you took the time to fill that out.

**Comment by lolgear** [comment]
@hhanesand @shenguanjiejie 
It seems that this is typical mistake with unloaded library - this error shows that "conversion" is happening in static analyzer head because it can't find these functions symbols.

**Comment by hhanesand** [comment]
@shenguanjiejie Unfortunately, I'm not able to reproduce your error. Have you defined `static const DDLogLevel ddLogLevel = DDLogLevel*;` somewhere? Here's the test project I'm using, if it at all helps you.

[testing.zip](https://github.com/CocoaLumberjack/CocoaLumberjack/files/2824720/testing.zip)

**Comment by shenguanjiejie** [comment]
I am sorry for my fool! I pod 'GHConsole' in my product, which had define LOG_MACRO tool. Thanks for your help 👍
