### ISSUE TITLE
File logger with buffering can't handle flush method properly (?)

### ISSUE THREAD

**Issue by lolgear** [CocoaLumberjack/CocoaLumberjack#1024]
I suppose that Buffer doesn't work well with flush. So, I would like to check it.

**Comment by hhanesand** [comment]
I implemented flushing in the buffered logger in 851d30201c1071f2323fca4e19d8ec7bf27585f0, so I believe we're good here.

**Comment by lolgear** [comment]
@hhanesand 
Sorry, miss it, thanks!
Issue could be closed.
