### ISSUE TITLE
Add missing newlines to the end of some files.

### ISSUE THREAD

**Issue by hhanesand** [CocoaLumberjack/CocoaLumberjack#1034]
Some files in the repository are missing newlines at the very end, as pointed out by @nrbrook in #1026

`Classes/CocoaLumberjack.h` was specifically mentioned, but there could be other files that are missing this as well.

**Comment by hhanesand** [comment]
lol persistent this one. Can someone configure the bot to ignore the `good first issue` tag?

**Comment by ffried** [comment]
@hhanesand See #1073
