### ISSUE TITLE
Unify repository labels.

### ISSUE THREAD

**Issue by lolgear** [CocoaLumberjack/CocoaLumberjack#1037]
I have found interesting solution in SublimeText [repository](https://github.com/SublimeTextIssues/Core/issues).

It has several types of labels. Each label has a type (letter) and a name.
Types define severity of issue, type of issue ( bug or enchantment ) and a scope of issue.

I suggest to copy this style.

**Comment by bpoplauschi** [comment]
@lolgear I think they model with 50+ labels is too complicated for what we need.
