### ISSUE TITLE
os_log_create() support

### ISSUE THREAD

**Issue by arjunkchr** [CocoaLumberjack/CocoaLumberjack#1038]
### Issue Description and Steps

Our Project utilises os_log_create and assigns different categories for different sub modules we use, so we can track which sub module is behaving erroneously. Apple provides a way to achieve it via `os_log_create` (https://developer.apple.com/documentation/os/1643744-os_log_create?language=objc) . Does Lumberjack support the same? I looked up the DDOSLogger file, but it seems like we don't. Are there any other alternatives we can achieve the same?

**Comment by lolgear** [comment]
@arjunkchr 

I asked about this issue several months ago, but we didn't come up with API that fits appropriately.
Could you suggest API or submit PR?

**Comment by lolgear** [comment]
#1039

**Comment by arjunkchr** [comment]
> #1039

@lolgear : I looked at the PR you just submitted. But we could only set one category under a sub-system. Should we let the user define an array of category under the sub-system and then use getters to choose one category against which the message should be logged. Thoughts?

**Comment by lolgear** [comment]
@arjunkchr 
Since os_log_create returns singleton object, it makes sense to add array/set of categories for specific subsystem.

Maybe it is a subclass of current OS logger?

**Comment by arjunkchr** [comment]
> @arjunkchr
> Since `os_log_create` returns singleton object, it makes sense to add array/set of categories for specific subsystem.
> 
> Maybe it is a subclass of current OS logger?

@lolgear : I did not quite get the comment about `current OS logger`. Every call to `os_log_create()` returns `os_log_t`. For the same sub system having multiple categories, we should store all instance of `os_log_t` and then return the respective instance which the user is interested in. OR do you mean we have multiple `DDLog` instance each for a subsystem and a category?

**Comment by lolgear** [comment]
> Every call to `os_log_create()` returns `os_log_t`. For the same sub system having multiple categories, we should store all instance of `os_log_t` and then return the respective instance which the user is interested in.

No, every call to `os_log_create()` returns singleton `os_log_t` object. System keeps track of them for us.

> OR do you mean we have multiple `DDLog` instance each for a subsystem and a category?

We can have several OS Logger instances, one for each valid pair `(subsystem, category)`.

However, I suggest to add subclass ( or proxy ) which has array of categories for specific subdomain if it is necessary.

With that PR you can do something like:

```swift
let subsystems = [String : [String]]()
// fill subsystems
// ...
// create loggers for each valid pair `(subsystem, category)`
let loggers = subsystems.flatMap { (key, value) in
    value.flatMap {(key, $0)}
    }.map { pair in
    OSLogger().withSubsystem(tuple.0).withCategory(tuple.0)
}
```

**Comment by lolgear** [comment]
@arjunkchr 
Hi!
Could you try latest master/version?

**Comment by arjunkchr** [comment]
Hi @lolgear : Sorry I got involved in other items and wasn't able to check with the latest. Let me try that and see if it works. Thanks for your help.

**Comment by arjunkchr** [comment]
Hi @lolgear : I am trying now to migrate to the new logger system. I have modified below:

```os_log_t UILogger = os_log_create(tunnelLogSubsystem, tunnelUICategory);```

to 

```
DDOSLogger *UILogger = [[DDOSLogger sharedInstance] initWithSubsystem:logSubsystem category:UICategory];
[DDLog addLogger:tunnelUILogger];
```

How do I migrate the existing logs to log against this defined subsystem and category? For example, migrating `os_log_info(UILogger,"Initialising...");`

**Comment by ffried** [comment]
@arjunkchr According to your input code, your migrated code should look like this:
```objc
DDOSLogger *tunnelUILogger = [[DDOSLogger alloc] initWithSubsystem:tunnelLogSubsystem category:tunnelUICategory];
[DDLog addLogger:tunnelUILogger];
```

You can then simply log messages using the default CocoaLumberjack log statements:
```objc
DDLogVerbose(@"Verbose message");
DDLogDebug(@"Debug message");
DDLogInfo(@"Info message");
DDLogWarn(@"Warning message");
DDLogError(@"Error message");
```

**Comment by arjunkchr** [comment]
@ffried : Thanks for your response.The above is fine if there is only single category against a subsystem. I still have multiple other categories that I need to migrate. How will the below log statements for different categories be translated?
```
os_log_info(UILogger,"Initialising...");
os_log_info(DeInit,"Shutdown...");
```

**Comment by ffried** [comment]
@arjunkchr In this case you can either use e.g. the `context` parameter in the `DDLog[...]()` macro calls and then add a `DDLogFormatter` subclass to your `OSLogger`s that filter the messages based on their `context`.
Or you create different `DDLog` instances for your categories. There are versions of above's macros, that take a `DDLog` instance (`DDLog[...]ToDDLog()`)...

**Comment by ffried** [comment]
Closing this since as per my previous comment the requested feature should already be possible.
