### ISSUE TITLE
lt_rollLogFileNow method not rolling the file - macOS

### ISSUE THREAD

**Issue by maniac-coder** [CocoaLumberjack/CocoaLumberjack#1041]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | osx
 Platform Version        | 10.14.2
 CocoaLumberjack Version | 3.5.1
 Integration Method      | cocoapods
 Xcode Version           | Xcode 10.1
 Repro rate              | all the time
 Demo project link       | PFA
[CocoaLumberJackTest - Sample.zip](https://github.com/CocoaLumberjack/CocoaLumberjack/files/2848032/CocoaLumberJackTest.-.Sample.zip)

### Issue Description and Steps

Issue started happening in the latest version of CocoaLumberjack framework. It happened in 3.5.0 version few weeks back and then updated the pod for same version few days back and it solved the issue. After updating to 3.5.1 still the auto file rolling based on size and manual file rolling is not working. Kindly help me with this ASAP.

**Comment by ffried** [comment]
@maniac-coder Thanks for reporting this. I've opened a PR that fixes this issue. I've also added a test so that we don't run into this problem again!

**Comment by maniac-coder** [comment]
@ffried Thanks for the quick response and good to know that you have added Unit test case for the same. Tested with your change in my main project it is working fine.

**Comment by sushichop** [comment]
Fixed by #1042 .

**Comment by maniac-coder** [comment]
This issue is happening again. @ffried

**Comment by ffried** [comment]
@maniac-coder Hmm, what's the difference between your code and the test case I've added [here](https://github.com/CocoaLumberjack/CocoaLumberjack/commit/2beadba21c9115fecf25606a1775031ff7b1dd3b#diff-d7f3769084ac2f1a43d6561f25198f5bR48)?
Can you provide a sample project that reproduces the issue?

**Comment by ffried** [comment]
@maniac-coder I've just double checked. There were no changes between 3.5.2 and 3.5.3 that could have regressed this fix.

**Comment by maniac-coder** [comment]
@ffried I think it is working after updating to the latest version, didn't notice that I was using 3.5.1. Sorry for the trouble.
