### ISSUE TITLE
swift 5 support

### ISSUE THREAD

**Issue by rickyzh** [CocoaLumberjack/CocoaLumberjack#1043]
### New Issue Checklist
* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios
 Platform Version        |  12.0
 CocoaLumberjack Version | 3.4.2
 Integration Method      |  cocoapods 
 Xcode Version           | Xcode 10.2 beta
 Repro rate              |  all the time (100%) 
 Swift version              |  5.0

### Issue Description and Steps

Please fill in the detailed description of the issue (full textual output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

![image](https://user-images.githubusercontent.com/13976644/52998628-b3d28800-345e-11e9-9162-bcd5a562896b.png)

![image](https://user-images.githubusercontent.com/13976644/52998723-f98f5080-345e-11e9-8026-c43bc2965fdb.png)

**Comment by ffried** [comment]
Fixed by #1044

**Comment by parrots** [comment]
The above commit did not cover DDAssert.swift, which has similar compiler errors when compiling on Xcode 10.2.

<img width="975" alt="Screen Shot 2019-03-25 at 5 16 42 PM" src="https://user-images.githubusercontent.com/171163/54954796-e1a96180-4f21-11e9-869c-354eb7bf7457.png">
