### ISSUE TITLE
`-[DDFileLogger currentLogFileInfo]` will always create a new info when `doNotReuseLogFiles=YES`

### ISSUE THREAD

**Issue by Whirlwind** [CocoaLumberjack/CocoaLumberjack#1048]
I set the `doNotReuseLogFiles` to `YES`, and I hope the `DDFileLogger` create the new log file when I init the `DDFileLogger`. But before I release the `DDFileLogger`, I will get the `currentLogFileInfo` many times. I will get many infos!!  I check the master branch:

```objective-c
- (DDLogFileInfo *)lt_currentLogFileInfo {

    // Check if the file we've found is still valid. Otherwise create a new one.
    if (newCurrentLogFile != nil && [self lt_shouldUseLogFile:newCurrentLogFile]) {
        if (isResuming) {
            NSLogVerbose(@"DDFileLogger: Resuming logging with file %@", newCurrentLogFile.fileName);
        }
        _currentLogFileInfo = newCurrentLogFile;
    } else {
        NSString *currentLogFilePath = [_logFileManager createNewLogFile];
        _currentLogFileInfo = [[DDLogFileInfo alloc] initWithFilePath:currentLogFilePath];
    }
}

- (BOOL)lt_shouldUseLogFile:(nonnull DDLogFileInfo *)logFileInfo {
    NSAssert([self isOnInternalLoggerQueue], @"lt_ methods should be on logger queue.");
    NSParameterAssert(logFileInfo);

    if (logFileInfo.isArchived) { // Archived log files are no longer valid for use.
        return NO;
    }

    if (_doNotReuseLogFiles || [self lt_shouldLogFileBeArchived:logFileInfo]) { // This log file needs to be archived. No longer valid.
        logFileInfo.isArchived = YES;
        NSString *archivedLogFilePath = [logFileInfo.fileName copy];

        if ([_logFileManager respondsToSelector:@selector(didArchiveLogFile:)]) {
            dispatch_async(_completionQueue, ^{
                [self->_logFileManager didArchiveLogFile:archivedLogFilePath];
            });
        }

        return NO;
    }

    // All checks have passed. It's valid.
    return YES;
}
```
The `[self lt_shouldUseLogFile:newCurrentLogFile]` always be `NO`, because the `_doNotReuseLogFiles` is `YES`. So it will call `createNewLogFile` everytime!

I think that `currentLogFileInfo` should be a getter mathod, and it should not be a handler method! Right?

**Comment by ffried** [comment]
Thanks for reporting this.
We were simply missing a check whether we're currently resuming or not. Fixed in #1049, which also includes a test case that makes sure this won't happen again...

**Comment by vladiulianbogdan** [comment]
Do you have an estimation when 3.5.2 is going to be released?

**Comment by sushichop** [comment]
While I can't give you any specific date right now, I want to release these current tip of master as 3.5.2. 
Any thoughts? @CocoaLumberjack/collaborators

**Comment by rivera-ernesto** [comment]
IMO we should release often. We have a lot of contributors, so any hot fix will show up soon as well.

**Comment by sushichop** [comment]
Then I'll prepare for the release from now!

**Comment by sushichop** [comment]
@rivera-ernesto @ffried @lolgear 
Thanks for your help! I have just released `CocoaLubmerjack 3.5.2` and registered it CocoaPods.

**Comment by sushichop** [comment]
@Whirlwind @vladiulianbogdan 

Thanks for watting!
Could you try to use `CocoaLumberjack 3.5.2`?
https://github.com/CocoaLumberjack/CocoaLumberjack/releases/tag/3.5.2

**Comment by Whirlwind** [comment]
It seems not work at 3.5.2.

**Comment by ffried** [comment]
@Whirlwind Can you reproduce the bug in a sample project you could attach to this issue? What's different than the setup in the test case I've added in [this commit](https://github.com/CocoaLumberjack/CocoaLumberjack/commit/22fd0e42818b8cf264b48c459a6b4d31469a4766)?

**Comment by dreampiggy** [comment]
We face this issue, only when we are writing a runnig sessions's new log, at the same time, we start a new session. It will output a empty log file with nothing to output.

Maybe we need some demo code for this.
