### ISSUE TITLE
Security enhancements

### ISSUE THREAD

**Issue by stonedauwg** [CocoaLumberjack/CocoaLumberjack#1050]
There are a few instances of This project using so-called banned C standard APIs, banned from an OWASP perspective. For example strlen, strncpy etc. Can these be replaced with security friendly alternatives? [Here is a list](https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/StaticAnalyzer/views/ios/binary_analysis.py) of some code smells looked for during binary analysis. Running a scan on a app that uses CocoaLumberjack flags some of these "bad" C API calls

**Comment by lolgear** [comment]
@stonedauwg 
Could you show an actual result of testing which contains a list of C API calls that smell?

**Comment by stonedauwg** [comment]
Sure thing. A test with the following lines of code:

`
[DDLog addLogger:[DDOSLogger sharedInstance]]; // Uses os_log
DDFileLogger *fileLogger = [[DDFileLogger alloc] init]; // File Logger
fileLogger.rollingFrequency = 60 * 60 * 24; // 24 hour rolling
fileLogger.logFileManager.maximumNumberOfLogFiles = 7;
[DDLog addLogger:fileLogger];
`
produced this "banned API" report from MobSF

Binary make use of banned API(s)
Insecure The binary may contain the following banned API(s) _strlen.

Binary make use of malloc Function
Insecure The binary may use malloc function instead of calloc

Note that I had to include the actual source for CL instad of use it as a carthage built framework to get it to be flagged for anything. That may be as result of the binary getting further obfuscated when using as a framework. MobSF does a simple string search for static analysis on the iOS binary so is sensative to that (see link in my prev post)

The results do make sense as a simple search on this project's github repo shows use of C API calls included in the "banned" list like strlen, malloc etc
