### ISSUE TITLE
error: use of undeclared identifier 'LONG_LONG_MAX'

### ISSUE THREAD

**Issue by grebulon** [CocoaLumberjack/CocoaLumberjack#1061]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 12.0
 CocoaLumberjack Version | 3.5.2
 Integration Method      | manually
 Xcode Version           | Xcode 10.1
 Repro rate              | all the time (100%)

### Issue Description and Steps

Compilation error
`error: use of undeclared identifier 'LONG_LONG_MAX'` in `DDFileLogger.m:829`

Had to change:
`static NSTimeInterval const kDDMaxTimerDelay = LONG_LONG_MAX / NSEC_PER_SEC;`
to:
`static NSTimeInterval const kDDMaxTimerDelay = LLONG_MAX / NSEC_PER_SEC;`

**Comment by sushichop** [comment]
@grebulon 
Thanks for reporting issue.
This issue will be fixed by #1062 soon.
