### ISSUE TITLE
DDFileLogger mixed log messages from framework and main project

### ISSUE THREAD

**Issue by zhangjirui** [CocoaLumberjack/CocoaLumberjack#1063]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 12.0
 CocoaLumberjack Version | 3.5.1
 Integration Method      | cocoapods
 Xcode Version           | Xcode 10.1
 Repro rate              | all the time (100%)
 Demo project link       | 

### Issue Description and Steps

Both main project and framework have a different DDFileLogger, and I want that framework fileLogger only record logs from framework. And The current result is both two loggers record all logs from framework and main project.

**Comment by ffried** [comment]
There are multiple ways to achieve this. For one, you could use your own `DDLog` instance in the main app (instead of the shared one). Or you could use a DDLogFormatter that filters logs from your main app (using e.g. the `context` parameter).

**Comment by zhangjirui** [comment]
> There are multiple ways to achieve this. For one, you could use your own `DDLog` instance in the main app (instead of the shared one). Or you could use a DDLogFormatter that filters logs from your main app (using e.g. the `context` parameter).

Thanks a lot. I'll try DDLogFormatter.
