### ISSUE TITLE
Bump and release 3.5.3

### ISSUE THREAD

**Issue by sushichop** [CocoaLumberjack/CocoaLumberjack#1069]
@CocoaLumberjack/collaborators 

About 6 weeks have passed since CocoaLumberjack 3.5.2 was released.
So I think we should the next version(3.5.3). Do you agree? 
It supports Swift 5.0 using CocoaPods and Swift 5.0 has the advantage of ABI stability. 
If necessary, I'll wrap up CHANGELOGs by creating a pull request and release 3.5.3. 

Thanks.

**Comment by bpoplauschi** [comment]
@sushichop that sounds great, let's do it

**Comment by sushichop** [comment]
@bpoplauschi Thanks for your response. I'll do it from now!

**Comment by sushichop** [comment]
Thanks everyone!
I have released [CocoaLubmerjack 3.5.3](https://github.com/CocoaLumberjack/CocoaLumberjack/releases/tag/3.5.3) and registered it to [CocoaPods](https://github.com/CocoaPods/Specs/blob/bfc9afbd6d064842b7ef90a0a1ff5438b6b343ce/Specs/d/1/8/CocoaLumberjack/3.5.3/CocoaLumberjack.podspec.json).

**Comment by bpoplauschi** [comment]
Thanks guys for releasing
