### ISSUE TITLE
Cannot build on macOS 10.13 (SWIFT 5.0 not supported)

### ISSUE THREAD

**Issue by mmower** [CocoaLumberjack/CocoaLumberjack#1072]
### New Issue Checklist

* [X] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [X] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [X] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | macOS
 Platform Version        | 10.13.6
 CocoaLumberjack Version | 3.5.3
 Integration Method      | carthage
 Xcode Version           | Xcode 10.1
 Repro rate              | 100%
 Demo project link       | 

### Issue Description and Steps

I recently did a `carthage update` and CocoaLumberjack went from 3.5.1 to 3.5.3 however when it tried to build the project I got the following error:

```
*** Building scheme "CocoaLumberjack" in Demos.xcworkspace
*** Building scheme "CocoaLumberjackSwift" in Demos.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/matt/Projects/TAON/Mentat/Carthage/Checkouts/CocoaLumberjack/Demos/Demos.xcworkspace -scheme CocoaLumberjackSwift -configuration Release -derivedDataPath /Users/matt/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/CocoaLumberjack/3.5.3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/dw/tmf07r7n1cv6khc7rc35q4cw0000gn/T/CocoaLumberjack SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/matt/Projects/TAON/Mentat/Carthage/Checkouts/CocoaLumberjack)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/dw/tmf07r7n1cv6khc7rc35q4cw0000gn/T/carthage-xcodebuild.gLrrkU.log
```

The pertinent part of that log file (preceding that is an ** ARCHIVE SUCCEEDED **)appears to be:

```
/usr/bin/xcrun xcodebuild -workspace /Users/matt/Projects/TAON/Mentat/Carthage/Checkouts/CocoaLumberjack/Demos/Demos.xcworkspace -scheme CocoaLumberjackSwift -configuration Release -derivedDataPath /Users/matt/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/CocoaLumberjack/3.5.3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/dw/tmf07r7n1cv6khc7rc35q4cw0000gn/T/CocoaLumberjack SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/matt/Projects/TAON/Mentat/Carthage/Checkouts/CocoaLumberjack)User defaults from command line:
    IDEArchivePathOverride = /var/folders/dw/tmf07r7n1cv6khc7rc35q4cw0000gn/T/CocoaLumberjack
    IDEDerivedDataPathOverride = /Users/matt/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/CocoaLumberjack/3.5.3

Build settings from command line:
    CARTHAGE = YES
    CLANG_ENABLE_CODE_COVERAGE = NO
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS = NO
    ONLY_ACTIVE_ARCH = NO
    SKIP_INSTALL = YES
    STRIP_INSTALLED_PRODUCT = NO

note: Using new build system
note: Planning build
note: Constructing build description
Build system information
error: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'CocoaLumberjackSwift')


** ARCHIVE FAILED **
```

Going back to the CocoaLumberjack website I see you now say that it requires Xcode 10.2 or later. I guess that is related to Swift 5 support.

Unfortunately I cannot update Xcode as the latest version, 10.2.1, refuses to install on 10.13.

I can appreciate using any Swift features might force updating Xcode but it seems like between 3.5.1 and 3.5.3 it may have become impossible to build CocoaLumberjack on macOS 10.13.

I'll rev back to 3.5.1 for now.

I don't use Swift, is there a way to build without Swift support that would allow me to continue updating CocoaLumberjack?

Thanks.

Matt

**Comment by mmower** [comment]
Okay I've reverted to 3.5.2 which does build okay.

**Comment by bpoplauschi** [comment]
@mmower the error you are seeing with 3.5.3 version is, unfortunately, expected.
Our 3.5.2 version is using Swift 4.2 while the 3.5.3 version has the updated support for Swift 5. Since Swift 5 is not backwards compatible, there is no way of supporting both.

**Comment by mmower** [comment]
Fair enough… unfortunately, that means I jump ship here.

As a general comment though I wouldn't expect such a major breaking change in a minor revision.

Many thanks for your efforts on the library up to now.
