### ISSUE TITLE
Custom log formatter with thread name

### ISSUE THREAD

**Issue by tbago** [CocoaLumberjack/CocoaLumberjack#1079]
I want to use custom lumberjack log format. So I create one custom DDLog Formatter. I want  to print the thread name, but for main thread the name is nil, but i found there is one _queueLabel member in DDLogMessage. Does i can check the _queueLabel value for main thread check. 
`
    if (logMessage->_queueLabel isEqualToString:@["com.apple.main-thread"])  {
        ///< is main thread
    }
`

**Comment by sushichop** [comment]
@tbago 

> Does i can check the _queueLabel value for main thread check.
> `if (logMessage->_queueLabel isEqualToString:@["com.apple.main-thread"]) { ///< is main thread }`

Yes. You can check it. See [CustomFormatters.md](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/CustomFormatters.md) to create a custom log formatter.

**Comment by sushichop** [comment]
I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Feel free to reopen or create another issue if you still encounter a problem.
