### ISSUE TITLE
 warning: parameter of 'swift_name' attribute must be a Swift function name string

### ISSUE THREAD

**Issue by Whirlwind** [CocoaLumberjack/CocoaLumberjack#1086]
I got many warnings in my other project which is a Objective-C project.
```
/Pods/Headers/Private/CocoaLumberjack/DDLog.h:340:40: warning: parameter of 'swift_name' attribute must be a Swift function name string [-Wswift-name-attribute]
    message:(DDLogMessage *)logMessage NS_SWIFT_NAME(log(asynchronous:message:));
```

There are 50+ warnings about it. I could not find the reason, it is OK in other project. Could somebody help me?

**Comment by Whirlwind** [comment]
I found that. Somebody import the `usr/include/tgmath.h`，there is a macro define:
```
#undef log
#define log(__x) __tg_log(__tg_promote1((__x))(__x))
```
So the CocoaLumberjack will expand: 
```

+ (void)log:(BOOL)asynchronous
    message:(DDLogMessage *)logMessage __attribute__((swift_name("__tg_log((__typeof__(__tg_promote((asynchronous:message:))))(asynchronous:message:))")));
```

**Comment by ffried** [comment]
This is not something we can fix I think... Import order has always been important in the C-world (and still is in a different way in Swift).
