### ISSUE TITLE
Java 8 projects built with 11 now

### ISSUE THREAD

**Issue by kjluyr435** [CocoaLumberjack/CocoaLumberjack#1088]
Hi, my builds here [www.diplomaclub.net](https://www.diplomaclub.net)
are still "failing", because even though it's a java 8 project, it's being compiled by java 10 or 11, and setting the flag: --release 8 doesn't seem to work.
Any way to compile with JDK 8 on jitpack now?

**Comment by sushichop** [comment]
Here is a Objective-C or Swift based repository, not Java. So I'm going to close this issue.
Feel free to reopen or recreate an issue filled out the default information if you have any problem.
