### ISSUE TITLE
maximumFileSize does not take effect

### ISSUE THREAD

**Issue by buptwsg** [CocoaLumberjack/CocoaLumberjack#1089]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 12.1.4
 CocoaLumberjack Version | 3.5.1
 Integration Method      | cocoapods
 Xcode Version           | Xcode 10.2
 Repro rate              | all the time (100%)
 Demo project link       | None

### Issue Description and Steps

I have below codes to setup File Logger:

```
fileLogger.maximumFileSize = 3 * 1024 * 1024;
fileLogger.rollingFrequency = 0;
fileLogger.logFileManager.maximumNumberOfLogFiles = 3;
```

But I found that a log file is 5.2 MB, and when I re-launch my application, new logs are still added to the file. 

What I expect is that a new log file is created for new logs, because the file size has exceeded the maximumFileSize.

Could anyone help me?Thanks.

**Comment by ffried** [comment]
@buptwsg Can you please fill out the default issue template (the table with e.g. all the version info)? I've added it back for you.

Can you create a separate sample project, where this issue is also occurring and attach it to the issue? That would help a lot.

**Comment by buptwsg** [comment]
I have edited my post to fill out the issue template. For sample project, I will try to provide one in one week.

**Comment by sushichop** [comment]
@buptwsg 
Thanks for reporting this issue. While repro projects is preferable, can you try CocoaLumberjack 3.5.2 or 3.5.3 first? 
Related issue should have be fixed by #1042 that is merged to CocoaLumberjack 3.5.2. 
Thanks.

**Comment by buptwsg** [comment]
ok, I will try new version and give you a reply.
Today, I solved the problem by:
1. override - (void)didRollAndArchiveLogFile:(NSString *)logFilePath in my subclass of DDLogFileManagerDefault

2. in the method, call [self createNewLogFile];

**Comment by sushichop** [comment]
I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Feel free to reopen or create another issue if you still encounter a problem.
