### ISSUE TITLE
Print url crash 

### ISSUE THREAD

**Issue by shixueqian** [CocoaLumberjack/CocoaLumberjack#1091]
```objective-c
   [DDLog addLogger:[DDOSLogger sharedInstance]]; // Uses os_log
    
    DDFileLogger *fileLogger = [[DDFileLogger alloc] init]; // File Logger
    fileLogger.rollingFrequency = 60 * 60 * 24; // 24 hour rolling
    fileLogger.logFileManager.maximumNumberOfLogFiles = 7;
    [DDLog addLogger:fileLogger];
    
    NSString *urlString = @"https://abc.com/platform/passport.html?deviceName=iPhone%20XR&phoneModel=iPhone%20Simulator";
    DDLogError(urlString);
```
print this urlString will crash.
<img width="1220" alt="QQ20190718-1@2x" src="https://user-images.githubusercontent.com/20392001/61451192-79c4ce00-a98b-11e9-8ab3-69f2480bc8c4.png">

**Comment by sushichop** [comment]
@shixueqian 

This is not really an issue with CocoaLumberjack.

You should use `DDLogError(@"%@", urlString);` instead of `DDLogError(urlString);`.
Even if you use NSLog, you should handle it in the same way😉
