### ISSUE TITLE
Multiple commands produce CocoaLumberjack.framework

### ISSUE THREAD

**Issue by Diarrhio** [CocoaLumberjack/CocoaLumberjack#1102]
### New Issue Checklist

* [ X] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [ X] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [ X] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 13.1
 CocoaLumberjack Version | 3.6
 Integration Method      | Cocoapods
 Xcode Version           | Xcode 11.1
 Repro rate              | 100%
 Demo project link       | [Here](https://drive.google.com/open?id=108TPVOcOSw8gpcyI4UUEZEXfSrE44pxX)

### Issue Description and Steps

I've attached a simple project reproducing the issue, which only occurs when archiving. The workspace setup is as follows:

* `TheLib`: Static lib objective-c project which has a pod reference to `CocoaLumberjack`
* `TheFramework`: Dynamic framework Objective-c project, which also has a pod reference to `CocoaLumberjack`. It depends on `TheLib` and links to it statically
* `TheApp`: Swift iOS App project, which has pod references to both `CocoaLumberjack` and `CocoaLumberjack/Swift`. It depends on `TheFramework` and links to it dynamically. Note that even though this is a Swift only project, without the `CocoaLumberjack` pod reference, Xcode bombs during normal builds. Adding it in allows Xcode to build normally.

The bug occurs when archiving, however Xcode has a bunch of warnings in the Issue Navigator related to multiple targets, etc. To reproduce:
* Download unzip attached project
* `pod install` to install CocoaLumberjack pods
* Open workspace
* Menu->Product->Build. Successfully builds (though with warnings listed below)
* Menu->Product->Archive. Immediately fails with:

```
Multiple commands produce '/Users/dario/Dev/DerivedData/CocoapodsIssue-cdxgurmzoznltveeomaatykgcbxb/Build/Intermediates.noindex/ArchiveIntermediates/TheApp/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/CocoaLumberjack.framework':
1) Target 'CocoaLumberjack' has create directory command with output '/Users/dario/Dev/DerivedData/CocoapodsIssue-cdxgurmzoznltveeomaatykgcbxb/Build/Intermediates.noindex/ArchiveIntermediates/TheApp/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/CocoaLumberjack.framework'
2) Target 'CocoaLumberjack.default-Swift' has create directory command with output '/Users/dario/Dev/DerivedData/CocoapodsIssue-cdxgurmzoznltveeomaatykgcbxb/Build/Intermediates.noindex/ArchiveIntermediates/TheApp/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/CocoaLumberjack.framework'
```

Warnings in the Issue Navigator are as follows:

```
Multiple targets match implicit dependency for linker flags '-framework CocoaLumberjack'. Consider adding an explicit dependency on the intended target to resolve this ambiguity. (in target 'TheApp' from project 'TheApp')
Target 'CocoaLumberjack' (in project 'Pods')
Target 'CocoaLumberjack.default-Swift' (in project 'Pods')
```

I guess I'm wondering if this is something that is/should be supported by CocoaLumberjack... mixing Objective-C CocoaLumberjack and Swift CocoaLumberjack/Swift in the same worksapace.

In my googling, I found a similar issue on here, but it was with Carthage integration. It's workaround seemed to be to use the Legacy Xcode build system. That actually does work around this issue, though it's not a long term solution as it's not clear when Xcode will abandon support of the Legacy Build System., We can use for now as a temporary workaround for now.

**Comment by ffried** [comment]
@Diarrhio I'm not sure this is an issue on our side. Doing a quick search in the Issues of the CocoaPods repository spit out this one: https://github.com/CocoaPods/CocoaPods/issues/8206

Sounds pretty much like your problem.

**Comment by Diarrhio** [comment]
@ffried thanks for getting back to me. Not sure how that one didn't turn up on my googling. Anyways, seems like ultimately it's an Xcode issue for which Apple hasn't even responded :/

**Comment by ffried** [comment]
@Diarrhio Yea, sounds like it. Maybe some of the workarounds mentioned there work for you? TBH, I'm not too familiar with CocoaPods, so I didn't fully understand all of the things mentioned there. But AFAIK there is also a "manual integration" mode in cocoa pods, where you can manually link the dependencies together and CocoaPods only performs the tree resolution.

See https://guides.cocoapods.org/syntax/podfile.html#install_bang for more information.
Depending on the size of your original project, that might help as well.

**Comment by Diarrhio** [comment]
I don't think the workarounds on the cocoapods issue page will work for CocoaLumberjack, but I will give them a shot nonetheless. Unfortunately the install_bang thing won't work for us as well due to us using our own build system to produce our xcode project files (last step of the build system process is to call cocoapods on our generated xcode workspace). Thanks tho

**Comment by ffried** [comment]
@Diarrhio I'm closing this, since there's not really much we can do here AFAICT. If there should be anything, feel free to re-open.
