### ISSUE TITLE
ENAMETOOLONG - File name too long @ rb_sysopen

### ISSUE THREAD

**Issue by LYMelody** [CocoaLumberjack/CocoaLumberjack#1113]
pod install appear this problem.

Is something woring with my code?

 CocoaPods : 1.7.3
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.7.7
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 11.1 (11A1027)
         Git : git version 2.21.0 (Apple Git-122)
Ruby lib dir : /Users/zhouhuiping/.rvm/rubies/ruby-2.4.1/lib

**Comment by ffried** [comment]
I don't think this is problem with CocoaLumberjack, but rather with CocoaPods. Please file a bug report in their repository.
