### ISSUE TITLE
Dynamic Logging in Swift

### ISSUE THREAD

**Issue by D0miH** [CocoaLumberjack/CocoaLumberjack#1115]
Hello,

first of all thanks for this awesome logging library. I am currently trying to use CocoaLumberjack with a dynamic logging level in swift. All info I found about this was using Objective-C and I couldn't find any information how to achieve this using Swift. 
I found `dynamicLogLevel`. However when I set this variable to a log level apparently this log level is not working/ is ignored.

Does anyone has a tip for me how I can achieve this?

Thanks

**Comment by ffried** [comment]
@D0miH The `dynamicLogLevel` is the second stage of level-based filters. First there's a Preprocessor Macro called `DD_LOG_LEVEL` that you can set (by adding it to `GCC_PREPROCESSOR_DEFINITIONS`) to statically limit the messages in your app. Be aware, though, that you cannot go beyond that level once the binary is built. This static level is used for the compiler to be able to strip log messages that are beyond that level.
By default, `DD_LOG_LEVEL` is set to `DDLogLevelAll` and thus not filtering any messages.

`dynamicLogLevel` is checked next. If the message passes both checks, it's forwarded to the loggers that you have set up. `dynamicLogLevel`, like `DD_LOG_LEVEL`, is set to `DDLogLevel.all` by default.

Here's an example (assuming `DD_LOG_LEVEL` is left untouched or set to `DDLogLevelAll`):
```swift
dynamicLogLevel = .info
DDLogVerbose("My Verbose Message") -> Will not be logged
DDLogError("My Error Message") -> Will be logged


dynamicLogLevel = .all
DDLogVerbose("My Verbose Message") -> Will be logged
DDLogError("My Error Message") -> Will be logged
```

**Comment by D0miH** [comment]
Hi @ffried,

thanks for your fast and detailed response. 
Your example helped me to get it running in my project! 

Thank you!👍🏼😁
