### ISSUE TITLE
Issue in creating a cross platform swift framework with importing "CocoaLumberjack/swift"

### ISSUE THREAD

**Issue by MohamedJaffer-24** [CocoaLumberjack/CocoaLumberjack#1125]
[Error occuring.txt](https://github.com/CocoaLumberjack/CocoaLumberjack/files/4171058/Error.occuring.txt)

 Platform Name           ios / osx 
 Platform Version        ios - 8.0, mac- 10.10
 CocoaLumberjack Version | latest
 Integration Method      | Cocoapods
 Xcode Version           | e.g. Xcode 11.3
 Demo project link       |  "https://github.com/MohamedJaffer-24/ExMj/tree/master"

Description :
I have created a cross platform framework(Swift) named "ExMj" . It passed the pod spec validation It is working well when imported in different projects.  But when i changed the pod by importing CocoaLumberjack/Swift,  it is not validating the pod spec .  Pod spec validation gives errors. I have attached the github link and attached a file having errors posting in my terminal.

This is how my pod look and warning message shown after **pod install** and opening in workspace
<img width="1395" alt="Screenshot 2020-02-07 at 17 56 19" src="https://user-images.githubusercontent.com/60511157/74030918-3937ab00-49d6-11ea-801e-029a01959ed5.png">

When i xcode is cleaned it is showing,
<img width="1344" alt="Screenshot 2020-02-07 at 18 24 53" src="https://user-images.githubusercontent.com/60511157/74031311-27a2d300-49d7-11ea-9cd1-47c25c432a81.png">

Thank u in advance if u have time to view my issue

[Error occuring.txt](https://github.com/CocoaLumberjack/CocoaLumberjack/files/4171060/Error.occuring.txt)

**Comment by ffried** [comment]
For library evolution you should use the branch `binary_framework`. Can you try this branch and see if this works for you?

**Comment by MohamedJaffer-24** [comment]
Thank uu
