### ISSUE TITLE
Using lumberjack swift package within my own swift package?

### ISSUE THREAD

**Issue by chrisriner** [CocoaLumberjack/CocoaLumberjack#1127]
I am creating my own swift package and I wanted to have logging in it so I added the swift package version of lumberjack to my own swift package but I get an error of: SoCoLoginService.swift:11:8: Missing required modules: 'CocoaLumberjack', 'CocoaLumberjackSwiftSupport'

Can I use the lumberjack swift package within another swift package?

**Comment by ffried** [comment]
Does this happen with the latest version (3.6.1) as well? If so, how does your Package.swift look like?

**Comment by rainhead** [comment]
I had this trouble because I selected only one of the two modules when adding the package to my project.

**Comment by ffried** [comment]
Is this still an issue with the latest versions of Xcode and CocoaLumberjack?

**Comment by sl-benjaminpayen** [comment]
Yes I also have this issue with Xcode 11.5 and CocoaLumberjack 3.6.1 😢

**Comment by ffried** [comment]
@sl-benjaminpayen How does your Package.swift look like?

**Comment by ffried** [comment]
@sl-benjaminpayen Or when integrating with Xcode: Are you linking both `CocoaLumberjack` and `CocoaLumberjackSwift`?

**Comment by ffried** [comment]
There is still an issue with Xcode not automatically linking `CocoaLumberjack` if only `CocoaLumberjackSwift` is linked, even though the former is a dependency of the latter.
The workaround is to link both. I've usually only seen this when integrating with Xcode, but it might happen SPM targets having CocoaLumberjack as dependency as well.

**Comment by imran20487** [comment]
On XCode 11.6. This Package.swift works for me. It was working with CocoaLumberJack 3.6.1 too.
```
// swift-tools-version:5.2
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "MyPackageName",
    platforms: [
        // Add support for platforms starting from a specific version.
        .macOS(.v10_13),
        .iOS(.v12)
    ],
    products: [
        // Products define the executables and libraries produced by a package, and make them visible to other packages.
        .library(name: "MyPackageName",
                 targets: ["MyPackageName"]),
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        .package(url: "https://github.com/CocoaLumberjack/CocoaLumberjack.git", .exact("3.6.2")),
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages which this package depends on.
        .target(
                name: "MyPackageName",
                dependencies: [
                    .product(name: "CocoaLumberjackSwift", package: "CocoaLumberjack")
                ]),
        .testTarget(
                    name: "MyPackageNameTests",
                    dependencies: ["MyPackageName",
                        .product(name: "CocoaLumberjackSwift", package: "CocoaLumberjack")
                    ]),
    ]
)
```

**Comment by ffried** [comment]
@imran20487 Thanks for the info! That sounds like Apple has fixed the issues... Nevertheless, there's now also a note in the README about potentially having to link both products.

I'm closing this now. If anyone still has this issue, please re-open.

**Comment by snipking** [comment]
Same Issue here.

XCode 12.4
CocoaLumberjack 3.7.0

Project A & B in same workspace, Project A build as a Framework and embedded into Project B. Both add CocoaLumberjack dependence on SPM. Project A build success. Project B build with error `Missing required modules: 'CocoaLumberjack', 'CocoaLumberjackSwiftSupport'`. And the error components is which using cocoaLumberjack in Project A.

**Comment by rehannali** [comment]
@snipking Did you find the solution to this problem?

**Comment by snipking** [comment]
> @snipking Did you find the solution to this problem?

Just remove CocoaLumberjackSwift in Project B SMP.

**Comment by rehannali** [comment]
@snipking did it worked with swift? I think `CocoaLumberjackSwift` is used for swift Framwork.

**Comment by snipking** [comment]
> @snipking did it worked with swift? I think `CocoaLumberjackSwift` is used for swift Framwork.

yes.
