### ISSUE TITLE
Duplicate interface definition for class 'DDLog'

### ISSUE THREAD

**Issue by lll3** [CocoaLumberjack/CocoaLumberjack#1129]
Type 'enum DDLogLevel' has incompatible definitions in different translation units

Xcode 11.3  error

**Comment by adib** [comment]
What was the solution? I'm experiencing this in Xcode 11.5 with CocoaLumberjack 3.6.1.

**Comment by olivaresf** [comment]
@adib Not OP... I couldn't figure it out, so I created a new unit testing target and it worked. 🤷🏻‍♂️
