### ISSUE TITLE
Branch binary_framework does not solve warning about binary compatibility.

### ISSUE THREAD

**Issue by rodmaz** [CocoaLumberjack/CocoaLumberjack#1141]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 13.4
 CocoaLumberjack Version | 3.6.1
 Integration Method      | Swift Package Manager
 Xcode Version           | Xcode 11.4.1
 Repro rate              | All the time (100%)

### Issue Description and Steps

My project integrates CocoaLumberjack using Swift Package Manager and compiler generates the warning below:

<img width="1019" alt="Screen Shot 2020-04-28 at 11 28 07" src="https://user-images.githubusercontent.com/55300/80499461-62b40300-8943-11ea-82d8-5243c00aedfc.png">

```
Module 'CocoaLumberjackSwift' was not compiled with library evolution support; using it means binary compatibility for 'MyTarget' can't be guaranteed.
```

I am currently using the branch `binary_framework`, which supposedly solved the issue but the problem persists.

**Comment by rodmaz** [comment]
Duplicate. See https://github.com/CocoaLumberjack/CocoaLumberjack/pull/1110

**Comment by ffried** [comment]
@rodmaz Actually, your case is a little different here. You stated that you use Swift Package Manager as integration method. SPM and library evolution don't work together since SPM is (currently) based on an approach where the sources will always be re-built. So the changes we currently provide on the `binary_framework` branch will not affect SPM.

In your case, you seem to use CocoaLumberjack in a framework that has library evolution enabled. In this case, you'd have to integrate with e.g. submodules and use the Xcode project provided in this repository. Then your warning will go away. However, the issues described in #1110 will still persist.

**Comment by rodmaz** [comment]
@ffried Correct, it is a framework with `BUILD_LIBRARY_FOR_DISTRIBUTION` enabled. 
Would you mind to elaborate a bite more on "you'd have to integrate with e.g. submodules"? So the files in folder `Configs` under SPM are not actually used during compilation?

The file `Module-Shared.xcconfig` has it also turned on:

```
// !!!: EXPERIMENTAL
// Ensures that your libraries are built for distribution. For Swift, this enables support for library evolution and generation of a module interface file.
BUILD_LIBRARY_FOR_DISTRIBUTION = YES
```

**Comment by ffried** [comment]
@rodmaz Correct. SPM has its completely own build process. It does not need any Xcode projects and thus also does not use any xcconfigs.

I you want a version of CocoaLumberjack with library evolution enabled, you would need to use an integration method that uses the Xcode project we provide (and thus also uses our xcconfigs). Git submodules would be one option that does so. Carthage does so, too.
