### ISSUE TITLE
Logging in Privileged Helper tool

### ISSUE THREAD

**Issue by patmasterson** [CocoaLumberjack/CocoaLumberjack#1142]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |OSX
 Platform Version        | e.g. 10.15.3
 CocoaLumberjack Version | e.g. 2.3.0
 Integration Method      | e.g. submodules
 Xcode Version           | e.g. Xcode 11.4.1
 Repro rate              | e.g. all the time (100%) 

### Issue Description and Steps

I am integrating Lumberjack in my OSX application.  It works great in the main thread but keeps crashing the helper tool.  I have attempted to codesign the framework but still getting the following error:

```
Dyld Error Message:
  Library not loaded: @rpath/CocoaLumberjack.framework/Versions/A/CocoaLumberjack
  Referenced from: /Library/PrivilegedHelperTools/com.cinematiq.DCP-Transfer.Helper1
  Reason: no suitable image found.  Did find:
	/Library/Frameworks/CocoaLumberjack.framework/Versions/A/CocoaLumberjack: code signature in (/Library/Frameworks/CocoaLumberjack.framework/Versions/A/CocoaLumberjack) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
	/Library/Frameworks/CocoaLumberjack.framework/Versions/A/CocoaLumberjack: stat() failed with errno=1
```
Does Lumberjack work with helper tools?  Is there a different approach to using it in  helper tools.

Thanks for the assistance.
Pat Masterson

**Comment by bpoplauschi** [comment]
Hi @patmasterson and thanks for creating this issue. 
I didn't work with "Privileged Helper tools", but from what I see, it does look like the binary is missing code signing.
@CocoaLumberjack/collaborators does anyone know if we have support for privileged helper tools on Mac?

@patmasterson could you create a small demo project that you can share with us where this issue is visible?
