### ISSUE TITLE
Version 3.6.1 is compatible with Swift 5.2.2?

### ISSUE THREAD

**Issue by TroiKM** [CocoaLumberjack/CocoaLumberjack#1143]
### New Issue Checklist

* [X] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [X] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [X] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 CocoaLumberjack Version | 3.6.1
 Integration Method      | cocoapods
 Xcode Version           | Xcode 11.4

### Issue Description and Steps

I'm currently updating a library that we have to be compatible with Swift 5.2.2 on the latest XCode 11.4 where we use your library and others one:

Installing CocoaLumberjack (3.6.1)

I have all updated to the last version and when I try to include my library to an example project, and I get this error:

module compiled with Swift 5.1.2 cannot be imported by the Swift 5.2.2 compiler

CocoaLumberjack (SWIFT_VERSION 5.0)

Can you confirm that your library is compatible with Swift 5.2.2? In case that the answer is no, Will you update it soon to make it compatible?

**Comment by ffried** [comment]
@TroiKM CocoaLumberjack is compatible with Swift 5.2.2. The problem here is that there is a binary built with Swift 5.1.2 that is being used. You need to do a clean build so that Swift re-compiles CocoaLumberjack with the latest version of Swift.

**Comment by bpoplauschi** [comment]
I think we can close the issue (per the above response). Feel free to continue the conversation or even reopen if it's something that is indeed broken on our side.
