### ISSUE TITLE
Swift log "Any"

### ISSUE THREAD

**Issue by Sunnyyoung** [CocoaLumberjack/CocoaLumberjack#1144]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 CocoaLumberjack Version | 3.6.1
 Demo project link       | https://github.com/Sunnyyoung/CocoaLumberjack/commit/6cb29f1c4cbd0825b17dddf47eb5301077659451

Update

```swift
_DDLogMessage(_ message: @autoclosure () -> String, ...
```

to

```swift
_DDLogMessage(_ message: @autoclosure () -> Any?, ...
```

would be more convenient to use.

**Comment by ffried** [comment]
Looking at `Swift.print`, we could go with `_DDLogMessage(_ message: @autoclosure () -> Any, ...`. I would not use `Any?`, however, since any optional can also fit in `Any`.

Feel free to open a PR!
