### ISSUE TITLE
Xcode complains about 'ignoring broken simlink'

### ISSUE THREAD

**Issue by varahash** [CocoaLumberjack/CocoaLumberjack#1149]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 11.0
 CocoaLumberjack Version | 3.6.1
 Integration Method      | SPM
 Xcode Version           | Xcode 11.5
 Repro rate              | all the time (100%)
 Demo project link       | 

### Issue Description and Steps

When integrating CocoaLumberjack using Swift Package Manager and build project, Xcode shows the following warning:
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/6864532/87256657-4b45da00-c49d-11ea-8dc0-cb2e7bf5720c.png">

**Comment by ffried** [comment]
This is already fixed on `master`.

**Comment by varahash** [comment]
Could you share some insight on when you plan to release the 3.6.2 version?

**Comment by ffried** [comment]
@varahash There are no concrete plans yet, but I think we could release it within the next couple of weeks. No promises, though 🙂
