### ISSUE TITLE
Add customized logger to specific context (not level) 

### ISSUE THREAD

**Issue by levey** [CocoaLumberjack/CocoaLumberjack#1154]
Hi team, any plan to support adding customized logger for specific context?
for example:
I have different log sources in my app, but their contexts are different, but I want to upload one of them to cloud and leave the other one local.

**Comment by ffried** [comment]
Thanks for sharing your idea!

Given that a logger receives the context of a message, loggers can quite easily filter which log messages they'll process and which not. If you use an existing logger (that you didn't implement yourself), you can also choose to use a LogFormatter to filter log messages. If the log formatter returns `nil`, the message won't be logged.

**Comment by ffried** [comment]
I'm closing this since as per my previous comment, this should already be possible using a filtering log formatter.
