### ISSUE TITLE
Timestamps, directory and using via wrapper

### ISSUE THREAD

**Issue by TarekSalama** [CocoaLumberjack/CocoaLumberjack#1162]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Description and Steps
I have some questions about CocoaLumberjack and 
 1. How do I remove the extra timestamps that appear? I'm already using a custom formatter and they still appear in my console, but not in the log files.
 2. How do I change the save directory to somewhere that's not the cache?
 3. I had to create a wrapper class that manages all CocoaLumberjack's methods and properties but whenever I log via my wrapper - which in turn uses DDLog(level) method depending on which level I pass - the function name and line name would be interpreted as the function name for the wrapper's method as well as its line. I don't want to import `CocoaLumberjack` in every viewcontroller, viewmodel and view that I log stuff in.

**Comment by ffried** [comment]
Hi @TarekSalama 
Let me see if I can help you there:

1. The extra time stamps you see in the console are outside of our control. Those are written by os_log. You could, however, attach a different (or differently configured) log formatter to the `DDOSLogger` to not print any timestamps yourself there.
2. You can create your own `DDLogFileManagerDefault` and pass a custom directory to it. Then you can use it to create your `DDFileLogger`.
3. You need to add file, line and function parameters, and then pass those on to CocoaLumberjack. In Swift, this would look something like this: 
```swift
func log(message: @autoclosure () -> Any, level: DDLogLevel, file: StaticString = #file, line: UInt = #line, function: StaticString = #function) { /*...*/ }
```

**Comment by TarekSalama** [comment]
Can you explain number 2 in more detail? I tried this already but I got
lost. Which method am I supposed to override? If it's not too much to ask,
an example snippet would be appreciated.

Thanks again!

**Comment by ffried** [comment]
@TarekSalama Sure! It's fairly simple really... 🙂 These lines of code should get you started:

```swift
let path = "/path/to/where/you/want/to/store/the/log/files"
let logFileManager = DDLogFileManagerDefault(logsDirectory: path)
let fileLogger = DDFileLogger(logFileManager: logFileManager)
```

Let me know if you need anything more!

**Comment by TarekSalama** [comment]
> Hi @TarekSalama
> Let me see if I can help you there:
> 
> 1. The extra time stamps you see in the console are outside of our control. Those are written by os_log. You could, however, attach a different (or differently configured) log formatter to the `DDOSLogger` to not print any timestamps yourself there.
> 2. You can create your own `DDLogFileManagerDefault` and pass a custom directory to it. Then you can use it to create your `DDFileLogger`.
> 3. You need to add file, line and function parameters, and then pass those on to CocoaLumberjack. In Swift, this would look something like this:
> 
> ```swift
> func log(message: @autoclosure () -> Any, level: DDLogLevel, file: StaticString = #file, line: UInt = #line, function: StaticString = #function) { /*...*/ }
> ```

Thanks for all the help so far 👍

I have a couple of questions:

1. Is there a specific reason for using a closure here `@autoclosure` rather than just passing an `Any` message?
2. Is there a way to get DDLog to use the `line` and `function`? Right now it seems like I can add them manually to the message that `DDLogVerbose` will print but that would completely bypass the formatter if I ever wanted to do something fancy with them.

**Comment by ffried** [comment]
@TarekSalama 

1. Imagine logging a message with debug level, but the (dynamic or static) level of DDLog being info. In this case, your message isn't even created with `@autoclosure`, including any parameters: `log("abc: \(1 + 1)", level: .debug)` -> The `1 + 1` calculation wouldn't even be excused if `DDLog` only logs messages with level `.info` or greater. If it's the static (compile time) level that is set to `.info`, Swift should even strip the string completely from the binary if you add `@inlinable` to your log function (as we do for e.g. `DDLogInfo` etc).

2. As I mentioned above, you need to add the necessary parameters to your log function and then pass them on to `DDLog`. They will end up in the corresponding properties of `DDLogMessage` which you can then use to format it.

Let me give you a complete example on that one:

```swift
enum Log {
    static func setUp() {
       /* set up loggers etc */
    }

    @inlinable
    static func verbose(_ message: @autoclosure () -> Any, file: StaticString = #file, function: StaticString = #function, line: UInt = #line) {
       DDLogVerbose(message(), file: file, function: function, line: line)
    }

    @inlinable
    static func debug(_ message: @autoclosure () -> Any, file: StaticString = #file, function: StaticString = #function, line: UInt = #line) {
       DDLogDebug(message(), file: file, function: function, line: line)
    }

    @inlinable
    static func info(_ message: @autoclosure () -> Any, file: StaticString = #file, function: StaticString = #function, line: UInt = #line) {
       DDLogInfo(message(), file: file, function: function, line: line)
    }

    @inlinable
    static func warn(_ message: @autoclosure () -> Any, file: StaticString = #file, function: StaticString = #function, line: UInt = #line) {
       DDLogWarn(message(), file: file, function: function, line: line)
    }

    @inlinable
    static func error(_ message: @autoclosure () -> Any, file: StaticString = #file, function: StaticString = #function, line: UInt = #line) {
       DDLogError(message(), file: file, function: function, line: line)
    }
}
```

You can then use above's implementation e.g. as follows:
```swift
Log.warn("Some warning log message!")
```

**Comment by TarekSalama** [comment]
Thanks a lot @ffried !
