### ISSUE TITLE
DDOSLogger user guide

### ISSUE THREAD

**Issue by tospery** [CocoaLumberjack/CocoaLumberjack#1170]
I used the DDOSLogger, but the console.app don't show the log.

**Comment by ffried** [comment]
Can you provide some sample code or a sample project where you see the issue?

Can you try the following code:

```swift
DDLog.add(DDOSLogger.sharedInstance)
DDLogError("Test Error Message")
```

**Comment by bpoplauschi** [comment]
Closing due to lack of response. Feel free to reopen
