### ISSUE TITLE
Carthage CocoaLumberjack framework won't compile for simulator in Xcode 12

### ISSUE THREAD

**Issue by guidedways** [CocoaLumberjack/CocoaLumberjack#1171]
I'm consistently seeing the following error when compiling our project in Xcode 12 GM. Works if I compile for the device instead.

```
Showing All Errors Only
Building for iOS Simulator, but linking in dylib file (../Carthage/Build/iOS/CocoaLumberjack.framework/CocoaLumberjack) built for iOS, file '../Carthage/Build/iOS/CocoaLumberjack.framework/CocoaLumberjack' for architecture arm64

```

**Comment by guidedways** [comment]
Looks like I need to remove VALID_ARCHS from the project configuration.

**Comment by guidedways** [comment]
It seems removing `VALID_ARCH` from all the dependent targets didn't help

**Comment by ffried** [comment]
Seems like this is an issue with Carthage... See https://github.com/Carthage/Carthage/issues/3020 and https://github.com/Carthage/Carthage/issues/3019
