### ISSUE TITLE
Can't build for watchos simulator using Xcode 12 GM

### ISSUE THREAD

**Issue by mozeryansky** [CocoaLumberjack/CocoaLumberjack#1172]
### New Issue Checklist

* [X] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [X] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [X] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | watchos
 Platform Version        | 6.0
 CocoaLumberjack Version | 3.6.2
 Integration Method      | carthage
 Xcode Version           | Xcode 12.0
 Repro rate              | 100%

### Issue Description and Steps

When I import CocoaLumberjackSwift and compile my project for tests I get the following error:
```
Could not find module 'CocoaLumberjackSwift' for target 'arm64-apple-watchos-simulator'; found: x86_64-apple-watchos-simulator, i386, i386-apple-watchos-simulator, x86_64, arm64_32-apple-watchos, armv7k, armv7k-apple-watchos, arm, arm64_32
```

I am able to build and run for my iOS 13.7 device, and I am able to build/run on the iOS 14.0 simulator, but not for my watch extension on simulator.

**Comment by ffried** [comment]
That is strange. 'arm64-apple-watchos-simulator' is not a valid target (unless you're on a Apple Silicon DTK). Simulators are either x86_64 or i386 - both of which are available (according to the message).
I assume that something is wrong with the ARCHS build settings. Are you setting any VALID_ARCHS (or the new EXCLUDED_ARCHS)?

**Comment by mozeryansky** [comment]
I am not setting either VALID_ARCHS or EXCLUDED_ARCHS. Do you have Xcode 12 to try to reproduce?

I am able to build and run my iOS app. I can build my watchOS app for a real device and for 'Any watchOS Device'. But I can't build for watch OS simulator.

**Comment by sushichop** [comment]
I confirmed I was able to build a small sample project and import `CocoaLumberjackSwift`.

Info | Value
-- | --
Platform Name | watchOS
Platform Version | 7.0
CocoaLumberjack Version | 3.6.2
Integration Method | Carthage 0.36.0
Xcode Version | Xcode 12.0.1

- How to repro
  - Create a Watch App project using Xcode 12.0.1.
  - Add Cartfile.
  - Execute Carthage command.
  - Add `CocoaLumberjack.framwork` and `CocoaLumberjackSwift.framwork` to the target.

```
github "CocoaLumberjack/CocoaLumberjack"
```

```
carthage update --platform watchOS --no-use-binaries
```

I hope this information is helpful for you.
Thanks.

**Comment by mozeryansky** [comment]
@sushichop Were you able to build for the watchOS simulator? Like I said, I can build for most targets just not the watchOS simulator specifically.

**Comment by sushichop** [comment]
@mozeryansky 

I was able to build for the simulator(Apple Watch Series 6 - 44mm).
Do you still encounter this issue even if you create a new project using Xcode 12.0.1?

**Comment by mozeryansky** [comment]
@sushichop Thanks for verifying. I recreated a watch only project as you described and that worked. Except my project is not watch only.

- Created a "iOS App with Watch App"
- Add Cartfile: `github "CocoaLumberjack/CocoaLumberjack"`
- Carthage: `carthage update --platform watchOS --no-use-binaries`
- Add CocoaLumberjack.framwork and CocoaLumberjackSwift.framwork to the target.

Build for "Apple Watch Series 6 - 44mm" Xcode fails with "Building for iOS Simulator, but the linked framework 'CocoaLumberjackSwift.framework' was built for watchOS + watchOS Simulator."

- Carthage: `carthage update --platform iOS,watchOS --no-use-binaries`

Carthage fails during `/usr/bin/xcrun lipo`.

- Create Carthage workaround script (https://github.com/Carthage/Carthage/issues/3019) (copied below)
- `./carthage-xc12.sh update --platform iOS,watchOS --no-use-binaries `

"Cannot retrive binary file from bundle at file:///Users/michaelozeryansky/Desktop/Sample/Carthage/Build/watchOS/CocoaLumberjack.framwork/"

My main project has a much larger setup and I'm running into a lot of problems trying to make a new sample, but are you able to build and iOS app with a watch app? Thanks for helping!

**Carthage workaround: `carthage-xc12.sh`**
```
#!/bin/sh -e
echo "Carthage wrapper"
echo "Applying Xcode 12 workaround..."
xcconfig="/tmp/xc12-carthage.xcconfig"
CURRENT_XCODE_VERSION=$(xcodebuild -version | grep "Build version" | cut -d' ' -f3)
echo "EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200__BUILD_$CURRENT_XCODE_VERSION = arm64 arm64e armv7 armv7s armv6 armv8" >> $xcconfig
echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200 = $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200__BUILD_$(XCODE_PRODUCT_BUILD_VERSION))' >> $xcconfig
echo 'EXCLUDED_ARCHS = $(inherited) $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT)__XCODE_$(XCODE_VERSION_MAJOR))' >> $xcconfig

echo 'ONLY_ACTIVE_ARCH=NO' >> $xcconfig
echo 'VALID_ARCHS = $(inherited) x86_64' >> $xcconfig
export XCODE_XCCONFIG_FILE="$xcconfig"
echo "Workaround applied. xcconfig here: $XCODE_XCCONFIG_FILE"

carthage $@
```

**Comment by sushichop** [comment]
@mozeryansky 
The workaround for Carthage is only for iOS target. Then you need a more complex solution when you choose `iOS App with Watch App`.
In short words, my solution is as followings.

carthage-workaround.sh

```bash
#!/bin/sh

set -euo pipefail

xcconfig=$(mktemp /tmp/static.xcconfig.XXXXXX)
trap 'rm -f "$xcconfig"' INT TERM HUP EXIT

CURRENT_XCODE_VERSION=$(xcodebuild -version | grep "Build version" | cut -d' ' -f3)
echo "EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200__BUILD_$CURRENT_XCODE_VERSION = arm64 arm64e armv7 armv7s armv6 armv8" >> $xcconfig

echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200 = $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200__BUILD_$(XCODE_PRODUCT_BUILD_VERSION))' >> $xcconfig
echo 'EXCLUDED_ARCHS = $(inherited) $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT)__XCODE_$(XCODE_VERSION_MAJOR))' >> $xcconfig

export XCODE_XCCONFIG_FILE="$xcconfig"
carthage "$@"
```

**IMPORTANT:** You need to execute command for each platform as follows.

```bash
carthage update --platform watchOS --no-use-binaries
./carthage-workaround.sh update --platform iOS --no-use-binaries
```

And I was able to build iOS app with a watch app.
I hope this information is helpful for you🙂

**Comment by mozeryansky** [comment]
This did work! Thank you.
