### ISSUE TITLE
Official release with Xcode 12 support?

### ISSUE THREAD

**Issue by geoffclifton** [CocoaLumberjack/CocoaLumberjack#1173]
### New Issue Checklist

* [x ] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x ] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x ] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 14.0
 CocoaLumberjack Version | 2.3.2
 Integration Method      | cocoapods
 Xcode Version           | Xcode 12.0

### Issue Description and Steps

I have seen on issue #1160 that @ffried mentioned that for Xcode 12 support you must use the `master` branch.

When can we expect an official tagged version of CocoaLumberjack with Xcode 12/ iOS 14 support?

**Comment by ffried** [comment]
@geoffclifton Thanks for reminding me!
I was a bit undecided on this, given the chaotic release of iOS 14 and Xcode 12.
But I agree that tagging a release is probably beneficial, so there's #1174 for preparing this.

**Comment by ffried** [comment]
3.7.0 is live! 🙂

**Comment by geoffclifton** [comment]
> 3.7.0 is live! 🙂

Thanks.
Appreciate the quick action on this!
