### ISSUE TITLE
missing framework UIKit CoreGraphics

### ISSUE THREAD

**Issue by yishuiliunian** [CocoaLumberjack/CocoaLumberjack#1176]
### New Issue Checklist

* [ v] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [ v] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [ v] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 14
 CocoaLumberjack Version | latest (3.6.2)
 Integration Method      | cocoapods 
 Xcode Version           | Xcode 12
 Repro rate              | all the time (100%) 

### Issue Description and Steps

use CocoaLumberjack with cocoapods then build

```
Undefined symbols for architecture x86_64:
  "_CGBitmapContextCreate", referenced from:
      +[DDTTYLogger getRed:green:blue:fromColor:] in DDTTYLogger.o
  "_CGColorSpaceCreateDeviceRGB", referenced from:
      +[DDTTYLogger getRed:green:blue:fromColor:] in DDTTYLogger.o
  "_CGColorSpaceRelease", referenced from:
      +[DDTTYLogger getRed:green:blue:fromColor:] in DDTTYLogger.o
  "_CGContextFillRect", referenced from:
      +[DDTTYLogger getRed:green:blue:fromColor:] in DDTTYLogger.o
  "_CGContextRelease", referenced from:
      +[DDTTYLogger getRed:green:blue:fromColor:] in DDTTYLogger.o
  "_CGContextSetFillColorWithColor", referenced from:
      +[DDTTYLogger getRed:green:blue:fromColor:] in DDTTYLogger.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by sushichop** [comment]
@yishuiliunian 
Thanks for your opening issue.
But this seems to be a duplicated issue. https://github.com/CocoaLumberjack/CocoaLumberjack/pull/1139#pullrequestreview-410897173 https://github.com/CocoaLumberjack/CocoaLumberjack/pull/1071

Could you try this?

```Ruby
platform :ios, '9.0'

target 'SampleIOSApp' do
  use_frameworks!

  pod 'CocoaLumberjack'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # config.build_settings['CLANG_ENABLE_MODULES'] = 'NO'
        # e.g. Sets Build Settings to use `ccache`.
        # config.build_settings['CC'] = '$(PODS_ROOT)/../ccache-clang'
      end

      target.add_system_framework(['CoreGraphics', 'UIKit'])
    end
  end

end
```

**Comment by yishuiliunian** [comment]
yes, it works

**Comment by sushichop** [comment]
I'm going to close this issue because the issue has been resolved. 
Please feel free to reopen it if you have any questions.

**Comment by sisoje** [comment]
this does not work on SPM

**Comment by sisoje** [comment]
there is a line missing in the target:
`                linkerSettings: [.linkedFramework("UiKit"), .linkedFramework("CoreGraphics")]`

**Comment by ffried** [comment]
@sisoje We cannot add that line since the package also needs to build for macOS.

However, I've never had issues with SPM in that regards. Can you provide a sample project that is integrating CocoaLumberjack with SPM and fails to build?
