### ISSUE TITLE
Exclude swift-log dependency if not using

### ISSUE THREAD

**Issue by andreynl** [CocoaLumberjack/CocoaLumberjack#1183]
Hey, guys

Is there any possibility to exclude swift-log dependency while using SPM if we don't need it?

**Comment by ffried** [comment]
This is actually SPM's job. As long as you don't use the product/target that has a dependency on swift-log, it should not use it. However, SPM currently only prevents _building_ unused dependencies. It will always checkout all of the declared dependencies - and there is not much we can do about it.

See [SE-0226](https://github.com/apple/swift-evolution/blob/master/proposals/0226-package-manager-target-based-dep-resolution.md) and the [corresponding forum thread](https://forums.swift.org/t/se-0226-package-manager-target-based-dependency-resolution/15404/1).
