### ISSUE TITLE
Log has lost when user manually kill app with `[fileLogger wrapWithBuffer]` 

### ISSUE THREAD

**Issue by kinarobin** [CocoaLumberjack/CocoaLumberjack#1185]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios 
 Platform Version        | e.g. 13.5.1
 CocoaLumberjack Version | e.g. 3.7.0
 Integration Method      | e.g. cocoapods 
 Xcode Version           | e.g. Xcode 12.1
 Repro rate              | e.g. all the time (100%) 

### Issue Description and Steps

Please fill in the detailed description of the issue (full textual output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

steps:
1. use `[DDLog addLogger:[fileLogger wrapWithBuffer]];`
2. back the app to the background
3. kill the app from background

Then the log had lost.

**Comment by ffried** [comment]
As mentioned in [this comment](https://github.com/CocoaLumberjack/CocoaLumberjack/pull/1186#issuecomment-724625427), this is somewhat intentional. It's the tradeoff for improved speeds. As also mentioned in the comment, there is an easy way to work around this if this is an issue in client apps.
