### ISSUE TITLE
Dynamic Package too?

### ISSUE THREAD

**Issue by guidedways** [CocoaLumberjack/CocoaLumberjack#1190]
Can we please have `Package.swift` declare a dynamic framework as well so that we can use this in multiple app-targets. Xcode won't let the same static library used multiple times in different frameworks / targets. A dynamic package will solve this problem.

**Comment by guidedways** [comment]
For now I've been able to create a wrapper dynamic package and set Cocoalumberjack as the only dependency.

**Comment by ffried** [comment]
This is actually an issue with Xcode. We're following Apple's recommendation by not specifying the product type.
The workaround for now is really to use a dynamic framework as dependency collector for now. We're doing the same in some of our projects and it works just fine.

If we were to add a dynamic package, it would be a breaking change to remove it in the future (once Xcode fixed its bugs around this).
