### ISSUE TITLE
Tag [DDLogFileManagerDefault initWithLogsDirectory:defaultFileProtectionLevel:] with NS_DESIGNATED_INITIALIZER

### ISSUE THREAD

**Issue by leontiy** [CocoaLumberjack/CocoaLumberjack#1192]
DDFileManagerDefault class is not fully configurable if subclassed as there's no straightforward way to change `_defaultLogFileProtectionType` value because convenience initialisers [cannot be called from any subclass initialisers](https://docs.swift.org/swift-book/LanguageGuide/Initialization.html#ID217) unless [automatically inherited](https://docs.swift.org/swift-book/LanguageGuide/Initialization.html#ID222) which makes subclassing unnecessarily restrictive.

> A designated initializer fully initializes all properties introduced by that class and calls an appropriate superclass initializer to continue the initialization process up the superclass chain.

https://github.com/CocoaLumberjack/CocoaLumberjack/blob/48c2b965155c8c0158f2a77837c21d464ca47029/Sources/CocoaLumberjack/DDFileLogger.m#L103

### Impact on existing Swift code

1. If there's no subclassing to `DDLogFileManagerDefault`, no change is required – both initialisers will continue to work as before.
2. If a subclass overrides `[DDLogFileManagerDefault initWithLogsDirectory:]` and makes use of the automatically inherited convenience initialiser  `[DDLogFileManagerDefault initWithLogsDirectory:defaultFileProtectionLevel:]`, now a straightforward override will be required to continue using `[DDLogFileManagerDefault initWithLogsDirectory:defaultFileProtectionLevel:]`.
[CocoaLumberjackChange.zip]

Example project that demonstrates the problems is attached
(https://github.com/CocoaLumberjack/CocoaLumberjack/files/5555027/CocoaLumberjackChange.zip)
This is linked against CocoaLumberjack 3.7.0.

**Comment by leontiy** [comment]
Simply adding NS_DESIGNATED_INITIALIZER to the initialiser in the corresponding header fixes the issue.

**Comment by ffried** [comment]
Sorry for the late response! And thanks for pointing this out!
Would it be possible for you to open a PR for this? Given that it potentially impacts existing code, we need to check which release we're going to include it, but generally I don't see any problems with this change.
