### ISSUE TITLE
Macros not in scope when loaded as pod in iOS project

### ISSUE THREAD

**Issue by ryanmeasel** [CocoaLumberjack/CocoaLumberjack#1194]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 13.0
 CocoaLumberjack Version | 3.7.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 12.2
 Repro rate              | all the time (100%) 
 Demo project link       | [Demo project](https://drive.google.com/file/d/1s_uIxHK1OZEXjnuCxZYzzb-V1DKa2KUZ/view?usp=sharing)

### Issue Description and Steps

If setup a fresh iOS project, install CocoaLumberjack via pods and then copy the example code from `Swift Usage` in the documentation, then none of the macros are in scope. `DDLog` is though. 

![image](https://user-images.githubusercontent.com/186849/100551775-e70b9300-3250-11eb-9e6b-3edbda0cded5.png)

**Comment by sushichop** [comment]
@ryanmeasel 
Thanks for reporting.
You need to specify not `CocoaLumberjack` but `CocoaLumberjack/Swift` when you use pods with Swift.

```ruby
platform :ios, '9.0'

target 'SampleTarget' do
  use_frameworks!
  pod 'CocoaLumberjack/Swift'
end
```

Could you try the above?

Thanks.

**Comment by ryanmeasel** [comment]
@sushichop That worked! Thanks. I realized that was notated in the docs. My apologies for missing it.
