### ISSUE TITLE
crash [DDLog log:level:flag:context:file:function:line:tag:format:] (DDLog.m:385)

### ISSUE THREAD

**Issue by zhaokunhaoa** [CocoaLumberjack/CocoaLumberjack#1198]
### New Issue Checklist

* [ ✓ ] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [ ✓ ] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [ ✓ ] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios
 Platform Version        | e.g. 14.2
 CocoaLumberjack Version | e.g. 3.7.0
 Integration Method      | e.g. cocoapods 
 Xcode Version           | e.g. Xcode 12.1
 Repro rate              | e.g.  sometimes x%  

### Issue Description and Steps

0 libobjc.A.dylib | objc_opt_respondsToSelector + 20
1 Foundation | _NSDescriptionWithStringProxyFunc + 56
2 CoreFoundation | ___CFStringAppendFormatCore + 8528
3 CoreFoundation | _CFStringCreateWithFormatAndArgumentsAux2 + 152
4 AgoraVideoCall | +[DDLog log:level:flag:context:file:function:line:tag:format:] (DDLog.m:385)
5 AgoraVideoCall | +[DDLogWrapper logInfo:] (DDLogWrapper.m:30)

**Comment by chengssir** [comment]
I also encountered the same problem, has it been solved?
