### ISSUE TITLE
lipo failing during build process Xcode 12 for Mac M1

### ISSUE THREAD

**Issue by pbmorton** [CocoaLumberjack/CocoaLumberjack#1205]
I'm building on a Mac M1 BigSur 11.1, Xcode 12.4, Carthage 0.36.1 

```

paul@Pauls-Mac-mini nannup % xcodebuild -version
Xcode 12.4
Build version 12D4e
paul@Pauls-Mac-mini nannup % cat carthage.sh 
#!/usr/bin/env bash

# carthage.sh
# Usage example: ./carthage.sh build --platform iOS

set -euov pipefail

xcconfig=$(mktemp /tmp/static.xcconfig.XXXXXX)
trap 'rm -f "$xcconfig"' INT TERM HUP EXIT

# For Xcode 12 make sure EXCLUDED_ARCHS is set to arm architectures otherwise
# the build will fail on lipo due to duplicate architectures.
echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200 = arm64 arm64e armv7 armv7s armv6 armv8' >> $xcconfig
echo 'EXCLUDED_ARCHS = $(inherited) $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT)__XCODE_$(XCODE_VERSION_MAJOR))' >> $xcconfig

export XCODE_XCCONFIG_FILE="$xcconfig"
carthage "$@"


[carthage-xcodebuild.RiyKvN.log](https://github.com/CocoaLumberjack/CocoaLumberjack/files/5903186/carthage-xcodebuild.RiyKvN.log)
paul@Pauls-Mac-mini nannup % ./carthage.sh update SVGKit --platform iOS

xcconfig=$(mktemp /tmp/static.xcconfig.XXXXXX)
mktemp /tmp/static.xcconfig.XXXXXX
trap 'rm -f "$xcconfig"' INT TERM HUP EXIT

# For Xcode 12 make sure EXCLUDED_ARCHS is set to arm architectures otherwise
# the build will fail on lipo due to duplicate architectures.
echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200 = arm64 arm64e armv7 armv7s armv6 armv8' >> $xcconfig
echo 'EXCLUDED_ARCHS = $(inherited) $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT)__XCODE_$(XCODE_VERSION_MAJOR))' >> $xcconfig

export XCODE_XCCONFIG_FILE="$xcconfig"
carthage "$@"
*** Fetching SVGKit
*** Fetching Toaster
*** Fetching CocoaLumberjack
*** Checking out SVGKit at "2.1.0"
*** Checking out CocoaLumberjack at "3.7.0"
*** xcodebuild output can be found in /var/folders/gw/93qnhkwj56j8fhhxptfkg_3w0000gn/T/carthage-xcodebuild.RiyKvN.log
*** Building scheme "CocoaLumberjack" in Demos.xcworkspace
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/paul/Library/Caches/org.carthage.CarthageKit/DerivedData/12.4_12D4e/CocoaLumberjack/3.7.0/Build/Intermediates.noindex/ArchiveIntermediates/CocoaLumberjack/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/CocoaLumberjack.framework/CocoaLumberjack /Users/paul/Library/Caches/org.carthage.CarthageKit/DerivedData/12.4_12D4e/CocoaLumberjack/3.7.0/Build/Products/Release-iphonesimulator/CocoaLumberjack.framework/CocoaLumberjack -output /Users/paul/projects/nannup/Carthage/Build/iOS/CocoaLumberjack.framework/CocoaLumberjack

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/gw/93qnhkwj56j8fhhxptfkg_3w0000gn/T/carthage-xcodebuild.RiyKvN.log
rm -f "$xcconfig"
paul@Pauls-Mac-mini nannup % 
```

The build xcodebuild log shows no errors. In fact at the bottom it says "** BUILD SUCCEEDED **".

The xcodebuild log does not show the lipo command that failed - that is, the lipo command printed on the console. I did run the command on the terminal - the output is below. Please see the error in the terminal capture below. I understand that this may be a nonsense error because the environment variable are not set when running lipo like this. But it is interesting.

```

paul@Pauls-Mac-mini nannup % /usr/bin/xcrun lipo -create /Users/paul/Library/Caches/org.carthage.CarthageKit/DerivedData/12.4_12D4e/CocoaLumberjack/3.7.0/Build/Intermediates.noindex/ArchiveIntermediates/CocoaLumberjack/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/CocoaLumberjack.framework/CocoaLumberjack /Users/paul/Library/Caches/org.carthage.CarthageKit/DerivedData/12.4_12D4e/CocoaLumberjack/3.7.0/Build/Products/Release-iphonesimulator/CocoaLumberjack.framework/CocoaLumberjack -output /Users/paul/projects/nannup/Carthage/Build/iOS/CocoaLumberjack.framework/CocoaLumberjack
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /Users/paul/Library/Caches/org.carthage.CarthageKit/DerivedData/12.4_12D4e/CocoaLumberjack/3.7.0/Build/Intermediates.noindex/ArchiveIntermediates/CocoaLumberjack/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/CocoaLumberjack.framework/CocoaLumberjack and /Users/paul/Library/Caches/org.carthage.CarthageKit/DerivedData/12.4_12D4e/CocoaLumberjack/3.7.0/Build/Products/Release-iphonesimulator/CocoaLumberjack.framework/CocoaLumberjack have the same architectures (arm64) and can't be in the same fat output file
```
Anyway, my question: Can you see any reason why this lipo step may have failed, and what to do about it?

**Comment by ffried** [comment]
The reason for the `lipo` step to fail is that on M1 machines, the simulator also runs on arm64 and Carthage is now telling to "merge" two arm64 binaries here, which isn't supported.
See [this Carthage issue](https://github.com/Carthage/Carthage/issues/3019) for more details (it's a lengthy discussion, though).

My _personal_ recommendation would be to use SPM as dependency management if possible (YMMV). I think I've read somewhere, that even the creators of Carthage recommended SPM at some point...

From Carthage's side, XCFrameworks would be one solution (which is mentioned a few times in the referenced issue as well), but I have no clue how far that solution's implementation currently is.

So in this case, I'm afraid there's really not much we can do from our side.

**Comment by pbmorton** [comment]
The Carthage.sh script is meant to take care of that ARM issue according to [this workaround](https://github.com/Carthage/Carthage/issues/3019). I'm using it. But I don't trust it. I will try your suggestion (thanks!) and if not I still have a 2014 Mac mini that can build my App successfully. Although it is easily 20 times slower and I'm scared it will die very soon. Soon enough Carthage will support XCFrameworks. I do not want to be on the leading edge for that. Thanks for your help.

**Comment by ffried** [comment]
You're welcome!
If I understood it correctly, the script prevents general `lipo` failures with Carthage on Xcode 12. The M1 issue is an additional layer on top of that. At least that's what I got from scrolling through that lengthy discussion there... I may as well be wrong, though...

**Comment by sushichop** [comment]
@pbmorton 
Thanks for your info.

I was not able to reproduce the same issue using Intel Mac(macOS 11.2, Xcode 12.4, Carthage 0.37.0).
I don't have M1 Mac unfortunately, but have you tried the following(Rosetta)?
https://github.com/Carthage/Carthage/issues/3019#issuecomment-768634110

I hope this info is helpful for you.

**Comment by ffried** [comment]
@sushichop This will likely only make the Carthage build succeed, but Xcode will behave strangely with the resulting binary because its missing the arm64 slice for the simulator on M1.

**Comment by sushichop** [comment]
@ffried I see 🤣
