### ISSUE TITLE
Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3.2 compiler

### ISSUE THREAD

**Issue by nitinkumardb** [CocoaLumberjack/CocoaLumberjack#1211]
I'm getting this error while building the code.

Xcode Version: 12.3

**Comment by ffried** [comment]
Are you using Carthage? If so you need to tell Carthage to rebuild the dependencies. Otherwise you need to do a clean build in Xcode.

**Comment by nitinkumardb** [comment]
@ffried  I'm using CocoaPods in my project. I have tried everything clean project, restart, etc.

**Comment by ffried** [comment]
Are you using toolchains? Or simply a standard Xcode installation? Are you having multiple versions of Xcode installed on your machine?
What's the output of `xcode-select -p`? Is that the same Xcode you're trying to build with?

**Comment by nitinkumardb** [comment]
No, I'm not using toolchains. 
Yes, I have two xcodes 11.7 & 12.3
Output for xcode-select -p:   /Applications/Xcode.app/Contents/Developer
Yes

**Comment by ffried** [comment]
Ok, that's weird.
What does `swift --version` say?
Have you tried deleting derived data and module cache yet?
- DerivedData -> `~/Library/Developer/Xcode/DerivedData/YourProjectName-someSuffix`
- ModuleCache ->  `~/Library/Developer/Xcode/DerivedData/ModuleCache.noindex`

**Comment by nitinkumardb** [comment]
swift --version
Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
Target: x86_64-apple-darwin20.2.0

I tried to clear both things.

**Comment by nitinkumardb** [comment]
Actually, before updating to Xcode 12.3, I was building the project on Xcode 11.7. Getting this error when I run on Xcode 12.3

**Comment by ffried** [comment]
It seems like there's a binary built with Xcode 11.7 (which contained Swift 5.2.4) referenced somewhere.

Could you please check the following for me:
- In the project navigator (left pane, first tab), select your project.
- Then select the target you're trying to build.
- Go to Build Phases
- Expand the "Link Binary With Libraries" build phase.
- Find CocoaLumberjackSwift and right-click it.
- Select "Show in Finder"

<img width="714" alt="image" src="https://user-images.githubusercontent.com/1689782/106900080-6193db80-66f6-11eb-960a-3a36195a0863.png">


If you don't end up somewhere in DerivedData, you likely need to re-link the dependency.

**Comment by ffried** [comment]
Since you're using CocoaPods, you might need to check this in the Pods Project. Not sure how CocoaPods splits things up nowadays...

**Comment by sushichop** [comment]
@nitinkumardb 
CocoaPods is strongly connected to Xcode (version). So you need to change Xcode version to 12.3 first.

```
# Select your Xcode 12.3's path.
sudo xcode-select -s /Applications/Xcode_12.3.app/Contents/Developer
````

Then, please make sure that your Swift version has changed to 5.3.2 and CocoaPods version is 1.4.0 or later

```
swift --version
pod --version
```

Next, please clean data, cache, and Pofile.lock

```
rm -rf ~/Library/Developer/Xcode/DerivedData
pod deintegrate 
pod cache clean
rm Podfile.lock
```

Finally rebuild!

```
pod repo update
pod install 
```

I hope this information is helpful for you:)

**Comment by nitinkumardb** [comment]
@sushichop I have tried these steps but bad luck, still getting the same error.

**Comment by sushichop** [comment]
@nitinkumardb It's strange... 
Did you build using Xcode 12.3 only ? If your answer is yes, please check SWIFT_VERSION about Pods' project. Or you may need to uninstall Xcode 11.3...
