### ISSUE TITLE
Issues when trying to update the library i am getting error the following error(old version 3.4.1 and try to update for 3.5.1 or above)

### ISSUE THREAD

**Issue by sunil28011** [CocoaLumberjack/CocoaLumberjack#1215]
New Issue Checklist
 I have read and understood the CONTRIBUTING guide
 I have read the Documentation or CocoaDocs
 I have searched for a similar issue in the project and found none

Info | Value
-- | --
Platform Name |  ios  / watchos
Platform Version |  12.0
CocoaLumberjack Version |  3.6.2
Integration Method |  carthage / cocoapods / manually
Xcode Version | Xcode 11.5
Swift Version | 4.2
Repro rate |  all the time (100%) 

@ffried 
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_DDASLLogger", referenced from:
      objc-class-ref in Logger.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ffried** [comment]
@sunil28011 Can you please fill out the form for new issues? There are some important details that make it easier for us to help you.
e.g. it would be interesting how you integrate CocoaLumberjack into your project.

**Comment by sunil28011** [comment]
@ffried 
Actually, I have started to work on an old project currently which was built on ios 8. Now I have to update that project.
it used the lumberjack library of version 3.4.1 and I thought it should update to 3.6.2  and I did it but found these issues when I try to build the project.
I am not familiar with this issue.
