### ISSUE TITLE
Possible crash in CocoaLumberjack 3.7.1?

### ISSUE THREAD

**Issue by latenitefilms** [CocoaLumberjack/CocoaLumberjack#1223]
Howdy!

I just updated the CocoaLumberjack pod from v3.7.0 to v3.7.1 for our open source project [CommandPost](https://commandpost.io), and I started to get crashes on launch, when a webview was loading. CommandPost is a fork of [Hammerspoon](http://www.hammerspoon.org).

To be honest, I'm not sure if CocoaLumberjack is to blame, but reverting back to v3.5.3, along with some other pod downgrades seemed to fix things. You can see the commit [here](https://github.com/CommandPost/CommandPost-App/commit/5edfeaaf4f5dd8846a85bd0f13693474b084cb05).

These were the crash logs I was seeing:

https://sentry.io/share/issue/af7d880991cc4303ba970985f908c083/
https://sentry.io/share/issue/53f9e892ea6e4784872b980bea67da34/

```
EXC_BAD_ACCESS
gldGetVersion >
Attempted to dereference garbage pointer 0x7fff87fb7158.

EXC_BAD_ACCESS
gldGetVersion > ZTUM >
Attempted to dereference garbage pointer 0x7fff8cf2b340.n
```

I was building on the latest public version of Big Sur and Xcode. It was crashing on both Big Sur & Mojave.

I'll do some more digging, but just wanted to create an initial issue, incase anyone else comes across similar crashes.

Thank you!

**Comment by christocracy** [comment]
I'm using `CocoaLumberjack` in a library of my own.  `3.7.1` broke me with this allegedly "*deprectated*" `DDLogMessage._tag` property.  That property was actually **removed**.  That's not fun for me on a *point release*.

![](https://dl.dropbox.com/s/gt3rxro4xwp7jn4/Screen%20Shot%202021-04-08%20at%206.42.12%20PM.png?dl=1)

I'm pinning my Pod to `3.7.0`

**Comment by ffried** [comment]
@christocracy `_tag` has always been the (private) field, so yes, `_tag` was removed completely. However, you should be accessing this field via its property `tag`, which is still there and has been deprecated. See [this line](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Sources/CocoaLumberjack/include/CocoaLumberjack/DDLog.h#L853) (note that the define is set to 1 by default).

**Comment by ffried** [comment]
@christocracy I've just released version 3.7.2 which re-introduces the `_tag` field and correctly marks it as deprecated. Again, sorry for that!

I'm closing this now, but feel free to re-open (or open a new issue) should there still be any problems.

**Comment by latenitefilms** [comment]
Is the `_tag` issue definitely related to those crash logs I posted?

**Comment by ffried** [comment]
@latenitefilms Huh, I just realized this issue contains two problems and the `_tag` issue is actually completely different.

Nevertheless I've had a look at your issue and IMHO it's not related to CocoaLumberjack. It appears nowhere in the stack trace and we don't do anything related to web views.
Any luck running the app with zombies enabled?

(I'll still re-open the issue for now - sorry for the confusion)

**Comment by christocracy** [comment]
Thanks very much @ffried!   

I've been using `logMessage->_tag` in a custom log-formatter I wrote about 5 years ago.  I will review my code to migrate away from using `_tag`.

```obj-c
@implementation TSLogFormatter

- (NSString *)formatLogMessage:(DDLogMessage *)logMessage
{
    NSString *icon;

    if (logMessage->_tag != nil) {
        NSString *tag = logMessage->_tag;
        if ([tag isEqualToString:TSLogTagNotice]) {
            icon = @"🔵";
        } else if ([tag isEqualToString:TSLogTagHeader]) {
            return [NSString stringWithFormat:@"\n%@\n%@ %@ %@\n%@", BOX_HEADER_TOP, BOX_HEADER_MIDDLE, logMessage->_function, logMessage->_message, BOX_BOTTOM];
        } else if ([tag isEqualToString:TSLogTagOk]) {
            icon = ICON_CHECK;
        } else if ([tag isEqualToString:TSLogTagOn]) {
            icon = ICON_ON;
            //return [NSString stringWithFormat:@"%@%@ %@", icon, logMessage->_function, logMessage->_message];
        } else if ([tag isEqualToString:TSLogTagOff]) {
            icon = ICON_OFF;
            //return [NSString stringWithFormat:@"%@%@ %@", icon, logMessage->_function, logMessage->_message];
        } else if ([tag isEqualToString:TSLogTagDump]) {
            return [NSString stringWithFormat:@"%@", logMessage->_message];
        }
        return [NSString stringWithFormat:@"%@%@ %@", icon, logMessage->_function, logMessage->_message];
    }
    if (!icon) {
        switch (logMessage->_flag) {
            case DDLogFlagError : icon = @"‼️"; break;
            case DDLogFlagWarning  : icon = @"⚠️"; break;
            case DDLogFlagInfo  : icon = @"ℹ️"; break;
            case DDLogFlagDebug : icon = ICON_DEBUG; break;
            default             : icon = ICON_DEBUG; break;
        }
    }
    return [NSString stringWithFormat:@"%@%@ %@", icon, logMessage->_function, logMessage->_message];
}

@end
```

**Comment by ffried** [comment]
@christocracy This should now work again (showing warnings on about the deprecated `_tag` field). If you're able to use properties (e.g. `logMessage.message`) instead of directly accessing the fields (e.g. `logMessage->_message`), it would be great - given that it's easier to provide a legacy implementation for properties than it is for fields. 🙂

**Comment by christocracy** [comment]
I see, thanks.  This seems to work fine for me now:

```obj-c
@implementation TSLogFormatter

- (NSString *)formatLogMessage:(DDLogMessage *)logMessage
{
    NSString *icon;

    if (logMessage.representedObject != nil) {
        NSString *tag = logMessage.representedObject;
        if ([tag isEqualToString:TSLogTagNotice]) {
            icon = @"🔵";
        } else if ([tag isEqualToString:TSLogTagHeader]) {
            return [NSString stringWithFormat:@"\n%@\n%@ %@ %@\n%@", BOX_HEADER_TOP, BOX_HEADER_MIDDLE, logMessage.function, logMessage.message, BOX_BOTTOM];
        } else if ([tag isEqualToString:TSLogTagOk]) {
            icon = ICON_CHECK;
        } else if ([tag isEqualToString:TSLogTagOn]) {
            icon = ICON_ON;
        } else if ([tag isEqualToString:TSLogTagOff]) {
            icon = ICON_OFF;
        } else if ([tag isEqualToString:TSLogTagDump]) {
            return [NSString stringWithFormat:@"%@", logMessage.message];
        }
        return [NSString stringWithFormat:@"%@%@ %@", icon, logMessage.function, logMessage.message];
    }
    if (!icon) {
        switch (logMessage.flag) {
            case DDLogFlagError : icon = @"‼️"; break;
            case DDLogFlagWarning  : icon = @"⚠️"; break;
            case DDLogFlagInfo  : icon = @"ℹ️"; break;
            case DDLogFlagDebug : icon = ICON_DEBUG; break;
            default             : icon = ICON_DEBUG; break;
        }
    }
    return [NSString stringWithFormat:@"%@%@ %@", icon, logMessage.function, logMessage.message];
}

@end
```

**Comment by ffried** [comment]
@christocracy Looks good! 👍
