### ISSUE TITLE
Not Really An Issue - using Lumberjack from a .framework - where to embed it?

### ISSUE THREAD

**Issue by erichfrazer** [CocoaLumberjack/CocoaLumberjack#1225]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | latest
 CocoaLumberjack Version | latest
 Integration Method      | cocoapods
 Xcode Version           | latest
 Repro rate              | 100%
 Demo project link       | not worth it?

### Issue Description and Steps

This isn't really an 'issue', this is me, a newb, trying to figure out Xcode and Cocopods and Lumberjack... go ahead and close this, if you've read this far and are immediately annoyed. 

Here's the goal, and you don't spell this out in your docs: I am trying to make an iOS framework, that includes Lumberjack. I've gotten far enough in cocoapods that LJ is included and the project compiles. (This is in Swift). Now I want to make an iOS app that consumes the framework I just made, and when I try and run it, it crashes and tells me Lumberjack isn't loaded. Somewhere, I need to include the LJ framework or binary, or whatever it's called. But I don't know where I need to do this, or how. I tried including the LJ framework in my general settings for the .framework I am building. It wouldn't compile when I did that, because it can't find the Lumberjack.framework. I don't know if I need to link against it, or what. It's pretty weird, since because it is swift, it seems to need to build the LJ framework from scratch?

Anyhow, some kind of message about how to do this would be great. I'm not seeing how to do this in the GitHub code, even the examples. Too complicated for me to follow!

some help would be great...
thanks

**Comment by erichfrazer** [comment]
Hey... think I figured something out... In my framework that I am building, I am trying to add to General/Frameworks the CocoaLumberjack.framework, and turning on embed... if I don't select embed, the project compiles, but crashes when I run it, because it can't find LJ.If I turn on embed, it says, 

`error: /Users/ericfrazer/Projects/FrameworkTestMaster/FrameworkTest/DerivedData/FrameworkTest/Build/Products/Debug-iphonesimulator/CocoaLumberjack.framework: No such file or directory (in target 'FrameworkTest' from project 'FrameworkTest')
`

well I guess I wasn't looking closely enough in Finder. If I go to finder, to Debug-iphonesimulator, I see CocoaLumberjack, a folder, and FrameworkTest.framework (a folder), and Pods_FrameworkTest.framework. Okay, what's the outlier here? The CocoaLumberjack folder doesn't have a .framework in the name. If I open it up, there you go, there is a CocoaLumberjack.framework folder in it! If I copy & paste this SUBFOLDRE parallel to the other .framework folders, lo & behold, the project now builds, with the embedded LJ framework. Plus, added bonus, it runs w/o crashing.

I'm thinking for whatever reason, the LJ.framework folder is building one level too deep! I'm so new at Xcode, I'm not even sure where to look for the answer to WHY. What specifies the output folder in a Cocoapods project for where the framework builds to?!

**Comment by erichfrazer** [comment]
Looking into my Pods project, under Targets/CocoaLumberjack, the user-defined CONFIGURATION_BUILD_DIR's debug and release paths both end in /CocoaLumberjack. If I remove the /CocoaLumberjack, the project builds correctly and everything is coming up roses. How does CONFIGURATION_BUILD_DIR get set, and boy, this was sure confusing.

**Comment by ffried** [comment]
Seems like this has been resolved. Sorry for not being of any help here...
