### ISSUE TITLE
 Log time print in file is always 8 hours late in my iPad 

### ISSUE THREAD

**Issue by EddieMa** [CocoaLumberjack/CocoaLumberjack#1226]
I use a iPad(OS version: 12.3.1) to print the log. Log in console works fine, but log in the file, the time is always 8 hours late.

When I tried another iPad, it works all right no matter in console or in the file.

Anyone know what is wrong with that iPad or do I need set some config for the iPad?

**Comment by 778477** [comment]
check log format timeZone

**Comment by ffried** [comment]
This sure sounds like a time zone issue. The default formatter for `DDFileLogger` will use the GMT time zone. If you configured your own log formatter, make sure you use a properly configured date formatter.

If there's still an issue, please re-open and provide a sample project if possible.
