### ISSUE TITLE
Missing Required Module

### ISSUE THREAD

**Issue by rehannali** [CocoaLumberjack/CocoaLumberjack#1231]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios 
 Platform Version        | 11.0
 CocoaLumberjack Version |  3.7.2
 Integration Method      |  SPM
 Xcode Version           | Xcode 12.5.1
 Repro rate              |  all the time (100%) 

### Issue Description and Steps

Hi, I have built a swift framework and want only to distribute binaries that have some dependencies including `CocoaLumberjack`.  

As per documentation, I added a framework explicitly for `CocoaLumberjackSwift`.

I successfully managed to add binaries with dependencies. After I added to another actual project, I got this error.

```
Missing required modules: 'CocoaLumberjack', 'CocoaLumberjackSwiftSupport'
```

I also tried to add these modules: `CocoaLumberjack`, `CocoaLumberjackSwiftSupport` using `Package.swift`, still doesn't solve the problem because `CocoaLumberjackSwiftSupport` doesn't exist in `CocoaLumberjack`.

This block I added in `Package.swift`

```
...
dependencies: [
        .package(name: "CocoaLumberjack", url: "https://github.com/CocoaLumberjack/CocoaLumberjack.git" , .upToNextMajor(from: "3.7.2"))
    ],
...
.target(
            name: "MyFrameworkTarget", dependencies: [
                .product(name: "CocoaLumberjack", package: "CocoaLumberjack"),
                .product(name: "CocoaLumberjackSwift", package: "CocoaLumberjack"),
                .product(name: "CocoaLumberjackSwiftSupport", package: "CocoaLumberjack")
            ]),
...
```

`.product(name: "CocoaLumberjackSwiftSupport", package: "CocoaLumberjack")` with this line, I'm unable to compile framework and if i don't include it, I can compile framework but in another project, I got an error again.

**Comment by PauliusLiekis** [comment]
I'm getting the same issue. Oddly it worked fine for a while, but now the error started appearing. I can discard my local changes, but it still complains about it...

**Comment by ffried** [comment]
The reason `.product(name: "CocoaLumberjackSwiftSupport", package: "CocoaLumberjack")` does not work, is because `CocoaLumberjackSwiftSupport` isn't exported as product. It's an internal target that Swift should build when building `CocoaLumberjackSwift`.
I still think this is an issue with Swift and I don't really have a workaround here - especially since I can't reproduce the issue.

If someone can provide a sample project that reproduces the issue, I can take a look and see if there's a workaround - either on the consumer side or on our side.

**Comment by PauliusLiekis** [comment]
> I'm getting the same issue. Oddly it worked fine for a while, but now the error started appearing. I can discard my local changes, but it still complains about it...

In my case, it was my own fault. I did `import MyApp` into the test code instead of `@testable import MyApp`. Removing the import fixed the issue. So don't mind me.

**Comment by ffried** [comment]
> I can compile framework but in another project

Do you link CocoaLumberjack in that other project? If possible, please provide a sample project.
