### ISSUE TITLE
lldb reference to 'DDLog' is ambiguous 

### ISSUE THREAD

**Issue by 778477** [CocoaLumberjack/CocoaLumberjack#1232]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 14.0
 CocoaLumberjack Version | 2.4.0.7
 Integration Method      | cocoapos
 Xcode Version           | Xcode 12.3

### Issue Description and Steps

when i debug on my iPhone SE2(iOS 14.0) device. 

pause the program execution and `po [DDLog allLoggers]` 

```
error: <user expression 0>:1:2: reference to 'DDLog' is ambiguous
[DDLog allLoggers]
 ^
note: candidate found by name lookup is 'DDLog'

note: candidate found by name lookup is 'DDLog'
```

lookup DDLog， We find the symbol in DataDetectorsCore.framework.  The class prefix `DD` is a trouble
```
(lldb) image lookup -vn DDLog
1 match found in /Users/miaoyou.gmy/Library/Developer/Xcode/iOS DeviceSupport/14.0 (18A373) arm64e/Symbols/System/Library/PrivateFrameworks/DataDetectorsCore.framework/DataDetectorsCore:
        Address: DataDetectorsCore[0x0000000194fbefe0] (DataDetectorsCore.__TEXT.__text + 78304)
        Summary: DataDetectorsCore`DDLog
         Module: file = "/Users/miaoyou.gmy/Library/Developer/Xcode/iOS DeviceSupport/14.0 (18A373) arm64e/Symbols/System/Library/PrivateFrameworks/DataDetectorsCore.framework/DataDetectorsCore", arch = "arm64e"
         Symbol: id = {0x0000005a}, range = [0x00000001984cafe0-0x00000001984cafe4), name="DDLog"
```

```Shell
-> nm /Users/miaoyou.gmy/Library/Developer/Xcode/iOS\ DeviceSupport/14.0\ \(18A373\)\ arm64e/Symbols/System/Library/PrivateFrameworks/DataDetectorsCore.framework/DataDetectorsCore | grep DDLog

0000000194fbefe0 T _DDLog
0000000194fbefe4 T _DDLogAssertionFailure
0000000194fbeeec T _DDLogErrD
0000000194fbed88 T _DDLogHandle
00000001d41e23c0 b _DDLogHandle.error_log_handle
00000001d41e23b8 b _DDLogHandle.onceToken
0000000194fbefdc T _DDLogv
0000000194fbedcc t ___DDLogHandle_block_invoke


```

**Comment by 778477** [comment]
@ffried take a look

**Comment by ffried** [comment]
I don't think there's much we can do here. Apple is using CocoaLumberjack as well. Since the introduction and improvements of `os_log` this has become less and less of a problem, but apparently `DataDetectorsCore` still uses CocoaLumberjack (likely for historical reasons).
The only thing you can do here is to fully qualify the symbol in `lldb`.
