### ISSUE TITLE
你好 升级到3.7.2版本 报一堆错

### ISSUE THREAD

**Issue by MoShenGuo** [CocoaLumberjack/CocoaLumberjack#1233]
### New Issue Checklist

* [ ☑️] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [  ☑️] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [  ☑️] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
--------------|-------------------------------------|
 Platform Name                                                ios 
 Platform Version                                             9.0
 CocoaLumberjack                                        Version  3.7.2
 Integration Method                                       cocoapods 
 Xcode Version                                               xcode12.5
 Repro rate                                                     all the time (100%) 
 Demo project link                                      link to a demo project that highlights the issue

### Issue Description and Steps
你好 pod update 你的版本到3.7.2,编译报错
目前在DDLog.h就通不过编译
![图片](https://user-images.githubusercontent.com/21171688/123942124-6a4ebc00-d9cd-11eb-8fb7-29895b9297d0.png)
![图片](https://user-images.githubusercontent.com/21171688/123942229-86525d80-d9cd-11eb-8bba-1a8f134bfa65.png)

**Comment by 778477** [comment]
> Duplicate Interface definition for class `DDLog`

检查一下工程里是否存在 两份`DDLog`

**Comment by ffried** [comment]
Please try cleaning your project. It seems like there are some leftovers. Also make sure that CocoaPods isn't linked twice...

To further investigate this, we'd need a demo project that reproduces this issue. Feel free to re-open this issue by providing such a project.
