### ISSUE TITLE
Crash [DDLog log:level:flag:context:file:function:line:tag:format:] (DDLog.m:352)

### ISSUE THREAD

**Issue by Running2snail** [CocoaLumberjack/CocoaLumberjack#1235]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [ ] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios 
 Platform Version        | e.g. 14.6
 CocoaLumberjack Version | e.g. 3.7.2
 Xcode Version           | e.g. Xcode 12.4

### Issue Description and Steps

Please fill in the detailed description of the issue (full textual output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

Are you reporting a queue deadlock? If so, you must include a complete backtrace of all threads, which you can generate by typing `bt all` in the debugger after you hit the deadlock. Failure to do so will prevent us from helping you.

**Comment by Goallying** [comment]
i have this problem too,how to handle it ?

**Comment by ffried** [comment]
There are no details here, so we can't really investigate the issue.
The line that is given in the title refers to this code in the current version:

```objc
NSString *message = [[NSString alloc] initWithFormat:format arguments:args];
```

This sounds like an issue with the message and its parameters. However, to investigate this further, we need some more details (the log message being logged and its parameters). This can be found in the stack trace of the crash and in the code calling the `DDLogXYZ`-macros.
Feel free to re-open this with more details.

**Comment by ffried** [comment]
(btw. this usually is a bug in the code calling us, not in our code)
