### ISSUE TITLE
iOS Version Issue with DDOSLogger

### ISSUE THREAD

**Issue by LowAmmo** [CocoaLumberjack/CocoaLumberjack#1243]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | e.g. 10.0+
 CocoaLumberjack Version | e.g. 3.7.2
 Integration Method      | cocoapods
 Xcode Version           | e.g. Xcode 13 beta 3
 Repro rate              | 100%
 Demo project link       | (just build with Xcode 13)

### Issue Description and Steps

Just seeing a build warning about DDOSLogger only being available in iOS 10.0+, but the deployment target is set to 9.0.

Which is fine, except for the `DDOSLogger *sharedInstance` in DDOSLogger.m - https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Sources/CocoaLumberjack/DDOSLogger.m#L51

Full error from the build:

```
/Users/.../Pods/CocoaLumberjack/Sources/CocoaLumberjack/DDOSLogger.m:51:8: warning: 'DDOSLogger' is only available on iOS 10.0 or newer [-Wunguarded-availability]
static DDOSLogger *sharedInstance;
       ^
In file included from /Users/.../Pods/CocoaLumberjack/Sources/CocoaLumberjack/DDOSLogger.m:18:
/Users/.../Pods/CocoaLumberjack/Sources/CocoaLumberjack/include/CocoaLumberjack/DDOSLogger.h:31:12: note: 'DDOSLogger' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 9.0.0
@interface DDOSLogger : DDAbstractLogger <DDLogger>
           ^
/Users/.../Pods/CocoaLumberjack/Sources/CocoaLumberjack/DDOSLogger.m:51:20: note: annotate 'sharedInstance' with an availability attribute to silence this warning
static DDOSLogger *sharedInstance;
                   ^
1 warning generated.
```

So, looks like either:

1. Mark the sharedInstance with with "available" in 10.0
2. Update the minimum supported iOS version of the cocoapod to 10.0

Obviously, not the most complicated issue in the world. My vote would be to just set the minimum iOS version to 10.0, and then remove the "availability" attributes from the code. But, don't know if that is compatible with any longer term strategies in place, etc.

-Thanks!

**Comment by sushichop** [comment]
@LowAmmo 

Thanks for letting us know. I created a pull request to fix this issue. #1248
Since we need to do a careful upgrade for multi platforms, I chose option 1.

Thanks.
