### ISSUE TITLE
No colors for iOS 14 SwiftUI

### ISSUE THREAD

**Issue by afern247** [CocoaLumberjack/CocoaLumberjack#1247]
I followed the guide: https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/XcodeColors.md

and when I declare: `[[DDTTYLogger sharedInstance] setColorsEnabled:YES];    // Enable console debugging colors` it says:

`Cannot find 'sharedInstance' in scope`

this is how I first declared it: `DDLog.add(DDOSLogger.sharedInstance) // Uses os_log` because if I do `[DDLog addLogger:[DDTTYLogger sharedInstance]];` it says it cannot find it in scope.

**Comment by ffried** [comment]
`DDTTYLogger` is deprecated and `DDOSLogger` does not support colors (because OSLog doesn't either).
There's not much we can do here, sorry!

Btw. the reason that `[DDLog addLogger:[DDTTYLogger sharedInstance]];` doesn't work, is because it's Objective-C while your project apparently uses Swift 😉
