### ISSUE TITLE
nullability conflict in DDDispatchQueueLogFormatter.h

### ISSUE THREAD

**Issue by futuretap** [CocoaLumberjack/CocoaLumberjack#1250]
I'm wondering why 

https://github.com/CocoaLumberjack/CocoaLumberjack/blob/7b4185d05157f7050d28bf3c36a4ae26d10030d0/Sources/CocoaLumberjack/include/CocoaLumberjack/DDDispatchQueueLogFormatter.h#L208

redeclares the `formatLogMessage:` method from the `DDLogFormatter` protocol with a different nullability for the return value. While I understand that the `DDDispatchQueueLogFormatter` implementation never returns `nil`, the implementation of a subclass might.

The redeclaration creates a warning if an overridden method in a subclass actually returns `nil`: 

`nil returned from a method that is expected to return a non-null value`

If there's no specific reason for that redeclaration, I'd recommend to remove it.

**Comment by ffried** [comment]
That's a fair point, thanks!
Could you please open a PR for this?

**Comment by ffried** [comment]
Fixed in #1252
