### ISSUE TITLE
CocoaLumberjack/DDFileLogger.h' file not found

### ISSUE THREAD

**Issue by Justhateulol** [CocoaLumberjack/CocoaLumberjack#1258]
Hello everyone, i tried to run a project, but i got an error "CocoaLumberjack/DDFileLogger.h not found". I installed package through SPM and it installed perfectly fine, but when i try to import this, it keeps giving me an error. My xcode version is 13.0 and i'm working on mac big sur, could it be a problem with version or with m1?

**Comment by ffried** [comment]
What packages are you linking? You need to link both, `CocoaLumberjack` and `CocoaLumberjackSwift`.

**Comment by ffried** [comment]
What version of CocoaLumberjack are you integrating? What target are you building (app, framework)?
