### ISSUE TITLE
CocoaLumberjack/DDLog.h File Not Found

### ISSUE THREAD

**Issue by Swapnali-Kulkarni** [CocoaLumberjack/CocoaLumberjack#1261]
Hi,

I tried to run Xcode project but it shows me error "CocoaLumberjack/DDLog.h File not found".
I have integrated CocoaLumberjack using pod.
when I try to go to source code of file DDLog.h I can clearly see the source code.
not sure why it is showing me that error.
Any help would be appreciated.
Thanks.

**Comment by ffried** [comment]
Can you please provide the CocoaPods version and CocoaLumberjack version you're using?

**Comment by mohitgarg-vt** [comment]
Hi, facing same issue on my Obje-c project and in podfile version is 1.9

"pod 'CocoaLumberjack', '~> 1.9'"

**Comment by mohitgarg-vt** [comment]
@ffried  I guess I found the solution  [Here](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/README.md#objective-c-arc-semantic-issue)

```
Objective-C ARC Semantic Issue
When integrating Lumberjack into an existing Objective-C it is possible to run into Multiple methods named 'tag' found with mismatched result, parameter type or attributes build error.

Add #define DD_LEGACY_MESSAGE_TAG 0 before importing CocoaLumberjack or add #define DD_LEGACY_MESSAGE_TAG 0 or add -DDD_LEGACY_MESSAGE_TAG=0 to Other C Flags/OTHER_CFLAGS in your Xcode project.

**Comment by GalaevAlexey** [comment]
Same issue I have trying to build project under Xcode Cloud!

**Comment by GalaevAlexey** [comment]
![Screen Shot 2022-07-05 at 13 14 08](https://user-images.githubusercontent.com/2743752/177254356-cc232ecc-4526-4276-8538-345358c07179.png)

**Comment by woaiqiu947** [comment]
![WeChat6bd2fa8a33daff369e7b33449e8cea0b](https://github.com/CocoaLumberjack/CocoaLumberjack/assets/1888953/383afd6b-b723-49f0-a6b5-035927bc8072)

Not Found.....
