### ISSUE TITLE
Undefined symbols for architecture x86_64:   "_islessgreater"

### ISSUE THREAD

**Issue by Roman-Andreyenko** [CocoaLumberjack/CocoaLumberjack#1264]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 CocoaLumberjack Version | 2.7.2
 Integration Method      | cocoapods
 Xcode Version           | Xcode 13.1
 Repro rate              | all the time (100%)

### Issue Description and Steps

When I tried to build my project for iOS simulator, I received the following issue:

Undefined symbols for architecture x86_64:
  "_islessgreater", referenced from:
      ___44-[DDAbstractDatabaseLogger setSaveInterval:]_block_invoke in DDAbstractDatabaseLogger.o
      ___38-[DDAbstractDatabaseLogger setMaxAge:]_block_invoke in DDAbstractDatabaseLogger.o
      ___46-[DDAbstractDatabaseLogger setDeleteInterval:]_block_invoke in DDAbstractDatabaseLogger.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by sushichop** [comment]
Can you try to use the latest version(CocoaLumberjack 3.7.2 and CocoaPods 1.11.2)?
