### ISSUE TITLE
How to disable CocoaLumberjack Warning when it is not necessary

### ISSUE THREAD

**Issue by oyljerry** [CocoaLumberjack/CocoaLumberjack#1267]
### New Issue Checklist

* [*] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [*] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [*] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Description and Steps

I want to print DDLog in terminal, so I use `[DDLog addLogger:[DDTTYLogger sharedInstance]];`, when running, It will print `CocoaLumberjack: Warning: Usage of DDTTYLogger detected when DDOSLogger is available and can be used! Please consider migrating to DDOSLogger.`, but I want to print it in TTY terminal, so I think this warning is annoy.   

How can I get rid of this warning. Thanks.

**Comment by oyljerry** [comment]
@ffried : For command line tool, I want that this warning can also be disable, because when I build a command line tool, and print DDLog in terminal, It will show this warning, I think it is not friendly for command line.

**Comment by ffried** [comment]
@oyljerry It should no longer print the warning for command line tools. Only for AppKit apps or iOS apps.

**Comment by oyljerry** [comment]
@ffried  I use latest 3.7.4, But it still shows "CocoaLumberjack: Warning: Usage of DDTTYLogger detected when DDOSLogger is available and can be used! Please consider migrating to DDOSLogger."
PS. I create my project with Xcode in macOS->Command Line Tool, I think that I do not need to add extra code after import 3.7.4 version.

**Comment by ffried** [comment]
@oyljerry How are you integrating CocoaLumberjack? What language do you use for your command line tool?

**Comment by ffried** [comment]
@oyljerry Scratch the second question - the code you provided is Objective-C.

In this case, add the following before importing CocoaLumberjack:
`#define DD_CLI 1`

Then it shouldn't print the warning anymore.

**Comment by mcicak** [comment]
But how to disable this warning in Swift?

**Comment by ffried** [comment]
@mcicak You should be able to do this by adding `DD_CLI=1` to the `OTHER_CFLAGS` build setting (depending on how you integrate CocoaLumberjack).
