### ISSUE TITLE
Question: Is there a new version planned?

### ISSUE THREAD

**Issue by gongzhang** [CocoaLumberjack/CocoaLumberjack#1268]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 CocoaLumberjack Version | 3.7.2
Installation Method | SPM

### Issue Description

Hello! 😄 I've been using `CocoaLumberjack` for a long time, thanks for providing such a nice and stable logging library.

I noticed that no new version or tag has been released since version `3.7.2` earlier this year, even though the repo still keeps getting new PRs merged in.

Are there any plans to release a new version in the near future? Or should I just use the latest code from the `master` branch?

**Comment by ffried** [comment]
I'm hoping to release a version some time next week. I've said that before in a different issue, but things came up and I was quite busy.

**Comment by gongzhang** [comment]
@ffried Thanks for the reply! I totally understand.

**Comment by ffried** [comment]
@gongzhang CocoaLumberjack version 3.7.3 is live now :)

**Comment by gongzhang** [comment]
@ffried That's great! Can't wait to use it in Swift Playgrounds 4!
