### ISSUE TITLE
Swift Tools Version 5.3 now inadvertently unsupported

### ISSUE THREAD

**Issue by nickg-ifit** [CocoaLumberjack/CocoaLumberjack#1270]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

I am attempting to update to CocoaLumberjack 3.7.3, however I am getting this issue:

> xcodebuild: error: Could not resolve package dependencies:
>   because CocoaLumberjack 3.7.3 contains incompatible tools version and no versions of CocoaLumberjack match the requirement 3.7.4..<4.0.0, CocoaLumberjack >=3.7.3 is forbidden.
> And because root depends on CocoaLumberjack 3.7.3..<4.0.0, version solving failed.

In looking at the diff from 3.7.2 to 3.7.3, it appears multiple versioned Package.swift files were added.  Each specified a swift tools version that matched the file name, **EXCEPT** the file for Swift 5.3.

The [`Package@swift-5.3.swift`](https://github.com/CocoaLumberjack/CocoaLumberjack/compare/3.7.2...3.7.3#diff-62bd2b94df67e500d0bcc4f14bba20a84ffe68db558b43094b5f464dbafabe3eR1) file specifies `// swift-tools-version:5.5`.  I believe this should be `// swift-tools-version:5.3`.

I have opened a PR: https://github.com/CocoaLumberjack/CocoaLumberjack/pull/1271

However, either the version 3.7.3 tag should be moved, or a version 3.7.4 should be immediately released so that those on swift tools version 5.3 can get the latest code from the 3.7.3 release.

**Comment by ffried** [comment]
@nickg-ifit Should be fixed now. Release 3.7.4 is live.
