### ISSUE TITLE
This is not rigth

### ISSUE THREAD

**Issue by wendongsheng** [CocoaLumberjack/CocoaLumberjack#1297]
// Using "self." syntax to go through this method will cause immediate deadlock.
// This is the intended result. Fix it by accessing the ivar directly.
// Great strides have been take to ensure this is safe to do. Plus it's MUCH faster.

NSAssert(![self isOnGlobalLoggingQueue], @"Core architecture requirement failure");
    NSAssert(![self isOnInternalLoggerQueue], @"MUST access ivar directly, NOT via self.* syntax.");

    dispatch_queue_t globalLoggingQueue = [DDLog loggingQueue];

    __block id <DDLogFormatter> result;

    dispatch_sync(globalLoggingQueue, ^{
        dispatch_sync(self->_loggerQueue, ^{
            result = self->_logFormatter;
        });
    });

    return result;

Hello, author, through my experimental test, it is found that this does not cause deadlock, I would like to ask whether this point is wrong

**Comment by ffried** [comment]
This heavily depends on where you call it. For example inside `-logMessage:` it _is_ going to deadlock. If you are outside of it (e.g. in the initializer) it will not necessarily deadlock.

Long story short: It deadlocks if you are on the global logging queue or on the bloggers internal queue.
