### ISSUE TITLE
swift5.6.1版本，目前不支持，无法使用DDLogVerbose等宏定义方法

### ISSUE THREAD

**Issue by tianzhilan0** [CocoaLumberjack/CocoaLumberjack#1306]
swift5.6.1版本，目前不支持，无法使用DDLogVerbose等宏定义方法，只能使用DDLogMessage来用

**Comment by ffried** [comment]
*Note*: This comment is based on the following translation using Google Translate:
> swift5.6.1 version, currently not supported, cannot use DDLogVerbose and other macro definition methods, can only use DDLogMessage to use

For Swift, you need to use `CocoaLumberjackSwift` target which provides logging functions. The Objective-C macros won't work in Swift.
