### ISSUE TITLE
Crash -[DDLogMessage .cxx_destruct] (DDLog.m:1037)

### ISSUE THREAD

**Issue by xgycc** [CocoaLumberjack/CocoaLumberjack#1307]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [ ] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 15.1-15.6
 CocoaLumberjack Version | 3.5.3
 Integration Method      | cocoapods
 Xcode Version           | Xcode 13.4.1
 Repro rate              | sometimes

### Issue Description and Steps

0 libobjc.A.dylib   _objc_release + 16
1 HiStor_release   -[DDLogMessage .cxx_destruct] (DDLog.m:1037)
2 libobjc.A.dylib   object_cxxDestructFromClass(objc_object*, objc_class*) + 112
4 libobjc.A.dylib   __objc_rootDealloc + 52
5 HiStor_release  ___destroy_helper_block_e8_32s40s (HSBigPhotoNewRebuildViewController+lookDetail.m:0)
6 libsystem_blocks.dylib    __Block_release + 184
7 libdispatch.dylib   __dispatch_client_callout + 16
8 libdispatch.dylib   __dispatch_lane_serial_drain$VARIANT$armv81 + 600
9 libdispatch.dylib   __dispatch_lane_invoke$VARIANT$armv81 + 388
10 libdispatch.dylib    __dispatch_workloop_worker_thread + 608
11 libsystem_pthread.dylib    __pthread_wqthread + 284

**Comment by ffried** [comment]
@xgycc Version 3.5.3 is fairly old. Can you try a recent version (e.g. the latest 3.7.4) please?

**Comment by xgycc** [comment]
> @xgycc Version 3.5.3 is fairly old. Can you try a recent version (e.g. the latest 3.7.4) please?

Ok, I will download the latest version and try it out, thank you.

**Comment by xgycc** [comment]
I have the same problem when I updated to V3.7.4, may I ask under what circumstances will this problem occur.

**Comment by ffried** [comment]
That's what we (would) need to figure out.

I see that in your stack trace, there's a mention of a class named `HSBigPhotoNewRebuildViewController`. Is this a class in your project? Is it doing anything special with regards to logging?

I find it a bit odd that the crash happens within `DDLogMessage`'s destructor, since `DDLogMessage` is a very simple class.
This could also be a memory leak where `DDLogMessage` just happens to reside at that location.
Do you have any more information about the crash? Exception code and/or message?
