### ISSUE TITLE
xcode 14

### ISSUE THREAD

**Issue by supervtb** [CocoaLumberjack/CocoaLumberjack#1315]
**Checklist**
- [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
- [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation)
- [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

**Describe the bug**
When i try to build project on mac m1 without rosetta - i have an error like Cannot find 'DDLogDebug' in scope and etc.. it works fine on xcode 13 but not in xcode 14.0.1 (I use cocoapods as dependencies manager)
**To Reproduce**
1. Create project using cocoapods
2. Add pod 'CocoaLumberjack/Swift', '= 3.7.2'
3. Try to add in viewdidload some logs 
**Expected behavior**
Project should be built
**Screenshots**

**Environment info**
  Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 16.0
 CocoaLumberjack Version | 3.7.2
 Integration Method    | cocoapods
 Xcode Version           | Xcode 14.0.1
 Repro rate              | all the time (100%)

**Comment by ffried** [comment]
I've tried to reproduce this, but am unable to do so. I've created an Xcode project on my M1 MacBook Pro and added the dependency line as you specified.
**Note:** I'd recommend using the latest version 3.7.4!

Then I ran `pod install` and added a log message. I've created a SwiftUI project (forgot to switch to Storyboards during the project creation), but that is irrelevant for the dependency setup. The only difference is that the message is logged in `onAppear` in the content view instead of `viewDidLoad`.

The project builds and runs fine. I've attached it in case you want to compare notes.
[LoggingTester.zip](https://github.com/CocoaLumberjack/CocoaLumberjack/files/9713097/LoggingTester.zip)

**Comment by ffried** [comment]
I'm sorry, but I don't think we can help in this case. I've proven that CocoaLumberjack works fine when integrated using CocoaPods on an M1 Mac using Xcode 14.

I know most of these are "obvious", but just to be sure:

- Have you tried a clean build? (CMD-Shift-K in Xcode to clean the build folder, then build again)
- Updated CocoaPods?
- Installed/updated developer tools?

**Comment by supervtb** [comment]
> 

Yep, exactly i tried all of them (clean build, remove derived data, update cocoapods, update lib to the latest version and etc) also i have xcode 13 release and it still works fine.. weird

**Comment by ffried** [comment]
@supervtb I'm very sorry that we cannot be of more help here. If you're able to reproduce this in a small project, please re-open this issue and attach it. Then I can take another look at it!

**Comment by supervtb** [comment]
@ffried hello, after trying to run project on iPhone, i have another error like 

 warning: Building with bitcode is deprecated. Please update your project and/or target settings to disable bitcode. (in target 'SiriShortcuts' from project '')
libCocoaLumberjack-iOS.a(DDAbstractDatabaseLogger.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Debug-iphoneos/CocoaLumberjack-iOS/libCocoaLumberjack-iOS.a' for architecture arm64

**Comment by ffried** [comment]
@supervtb This is just a warning and shouldn't prevent the application from working. I've started #1316 which will include full Xcode 14 support. I'll release a new version including this PR once the new macOS version is out.

**Comment by supervtb** [comment]
@ffried okay, I see. thanks. I see also in logs more error like Cannot find ddlogdebug in scope: Macro ddlogdebug not imported: function like macros not supported. Maybe you have some ideas where I need to check it?

**Comment by ffried** [comment]
@supervtb Sounds like you're integrating without CocoaPods. In this case you need to add `CocoaLumberjackSwift` to your target and import it.

**Comment by supervtb** [comment]
@ffried nope, should not, i use always cocoapods and did not change nothing: 
platform :ios, '14.0'
use_modular_headers!
pod 'CocoaLumberjack/Swift', '= 3.7.2'

**Comment by ffried** [comment]
Hmm, ok. Then I have no idea what's the issue here. Tried that pod file locally again and it works fine.
