### ISSUE TITLE
How to generate a new file log every single day ? not create new one every 24 hours.

### ISSUE THREAD

**Issue by Goallying** [CocoaLumberjack/CocoaLumberjack#1325]
I want to generate a new file log every day, but i can only  set " rollingFrequency " value  to "60 * 60 * 24" , That doesn't mean the same thing 。This may result in two dates in one file！

**Comment by ffried** [comment]
This is currently not supported out of the box. But you can always subclass `DDFileLogger`.

A few tips for doing so:
- Schedule a timer or listen to the [NSCalendarDayChanged](https://developer.apple.com/documentation/foundation/nsnotification/name/1408062-nscalendardaychanged) notification to get informed when you need to roll a log file.
- Rolling a log file can be done by calling `-rollLogFileWithCompletionBlock:`.
- Override `-shouldArchiveRecentLogFileInfo:` to make sure a log file created on a different day is not re-used.

**Comment by Kingamattack** [comment]
@Goallying did you find a way to do it?
