### ISSUE TITLE
Crash -[DDLogMessage initWithMessage:level:flag:context:file:function:line:tag:options:timestamp:]

### ISSUE THREAD

**Issue by iCodeWoods** [CocoaLumberjack/CocoaLumberjack#1330]
**Checklist**
- [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
- [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation)
- [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

**Describe the bug**
Crash in -[DDLogMessage initWithMessage:level:flag:context:file:function:line:tag:options:timestamp:]

**To Reproduce**
Online issus, can't repro.

**Expected behavior**
Don't crash

**Environment info**
  Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | All iOS15、iOS16 version
 CocoaLumberjack Version | 3.8.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 14.2

**Additional context**
Here are some crash reports:
[report-2517261657930009999-39b5e77d-79ba-41c7-bf37-994c2d4492bc.txt](https://github.com/CocoaLumberjack/CocoaLumberjack/files/10719652/report-2517261657930009999-39b5e77d-79ba-41c7-bf37-994c2d4492bc.txt)
[report-2517261271690009999-31d71c3f-136a-4332-92a8-a122659b653e.txt](https://github.com/CocoaLumberjack/CocoaLumberjack/files/10719653/report-2517261271690009999-31d71c3f-136a-4332-92a8-a122659b653e.txt)
[report-2517260722810009999-d6fd1e87-9035-4f5e-93c4-babc1702940f.txt](https://github.com/CocoaLumberjack/CocoaLumberjack/files/10719654/report-2517260722810009999-d6fd1e87-9035-4f5e-93c4-babc1702940f.txt)
[report-2517260688240009999-c02caf4f-3dfa-4201-8429-9822253d1a1c.txt](https://github.com/CocoaLumberjack/CocoaLumberjack/files/10719655/report-2517260688240009999-c02caf4f-3dfa-4201-8429-9822253d1a1c.txt)

**Comment by ffried** [comment]
The crashes all happen on [this line](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Sources/CocoaLumberjack/DDLog.m#L1020).

However, I have no idea why this would be. `pthread_threadid_np` should only return `0` if it succeeded - in which case the thread id should be initialized.
If anyone has an idea what's happening here (or a reliable reproduction project), it would help a lot.

**Comment by ffried** [comment]
@iCodeWoods Can you try again with the latest release (3.8.1)? We've changed the way we handle some format strings. I'm nut 100% sure it's the cause here, but if it fixes it, I'll take it.

**Comment by iCodeWoods** [comment]
Hi @ffried Thanks for your help. Version 3.8.1 doesn't seem to be a stable release yet. I'm not sure if it might introduce new issues, so I need to discuss it with the team. If we decide to update and it's fixed, I will let you know.

**Comment by iCodeWoods** [comment]
@ffried  I checked our latest App just now, there are only 2 users encounter this crash now. And the stack symbols contains some keywords like `malloc`, so i think it might be a memory issue and not DDLog's fault. Anyway i think i can close this issue now.
[report-2517093859890009999-dc1ec487-a5c7-4a06-a38e-b7932fe6afbb.txt](https://github.com/CocoaLumberjack/CocoaLumberjack/files/12452071/report-2517093859890009999-dc1ec487-a5c7-4a06-a38e-b7932fe6afbb.txt)
[report-2517095145720009999-b8a7a683-e1bb-4238-8813-fae270207dc9.txt](https://github.com/CocoaLumberjack/CocoaLumberjack/files/12452072/report-2517095145720009999-b8a7a683-e1bb-4238-8813-fae270207dc9.txt)
