### ISSUE TITLE
Unable to set log levels on release builds

### ISSUE THREAD

**Issue by dyang** [CocoaLumberjack/CocoaLumberjack#1333]
**Checklist**
- [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
- [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation)
- [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

**Describe the bug**
I'd like to enable info, warn and error levels in my iOS app on release builds, but after several hours of troubleshooting, I'm only  getting warn and error level messages, not info level ones.

I've read the [documentation](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/XcodeTricks.md) on how to set different log levels based on the current debug/release configuration. The doc is based on Objective-C and very old version of Xcode, so it doesn't help. 

I've also searched through older issues and discovered the use of `dynamicLogLevel`, but that doesn't seem to help either (included in the code snippets below). 

**To Reproduce**

This is my setup:

```
import CocoaLumberjackSwift

class LogUtil {
    static func initLogging() {
        // Set global log level
#if DEBUG
        dynamicLogLevel = DDLogLevel.all
#else
        dynamicLogLevel = DDLogLevel.info
#endif

        // Use os_log
        DDLog.add(DDOSLogger.sharedInstance)

        let fileLogger = DDFileLogger()
        fileLogger.rollingFrequency = 60 * 60 * 24 // 24 hours
        fileLogger.logFileManager.maximumNumberOfLogFiles = 5
        DDLog.add(fileLogger) // have also used DDLog.add(fileLogge, with: .info) here to no avail
    }
}
```

To log:

```
func debug(_ message: String) {
    DDLogDebug("[\(name)] \(message)")
}

func info(_ message: String) {
    DDLogInfo("[\(name)] \(message)")
}
```

Any ideas or solutions would be greatly appreciated!

**Environment info**
  Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 16.0
 CocoaLumberjack Version | e.g. 3.8.0
 Integration Method      | spm
 Xcode Version           | Xcode 14.2
 Repro rate              | 100%

**Comment by ffried** [comment]
I'm afraid I can't reproduce the issue. I've attached a small sample project.
It runs the same setup code as you provided. In addition to that, it allows to dynamically switch the configuration (debug, release). However, the configuration is also initialized using the build configuration. So you can also change the build configuration in the scheme and the picker in the sample app will automatically adjust.

With the buttons you can log various messages and in the Xcode console you can see that in release configuration, the debug messages aren't logged, but info and everything above is.

And I've also checked the file that the file logger creates - which shows the same log messages as the Xcode console.

[DynamicLogLevelChange.zip](https://github.com/CocoaLumberjack/CocoaLumberjack/files/10837176/DynamicLogLevelChange.zip)

**Comment by dyang** [comment]
@ffried Thank you for the input! I'll try out the sample project and get back with more info.

**Comment by dyang** [comment]
@ffried I tested your sample project and found that it worked flawlessly. While I've used a similar setup in a few other projects without encountering any issues, my current project began to experience this problem only recently, which is quite strange.

At this point, I believe it's best to close this ticket and investigate further. Thanks again for your input!
