### ISSUE TITLE
Fix Compile Time Warnings about "a function declaration without a prototype is deprecated"

### ISSUE THREAD

**Issue by LowAmmo** [CocoaLumberjack/CocoaLumberjack#1338]
**Checklist**
- [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
- [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation)
- [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

**Describe the bug**
Just seeing compile time warnings (3x) when building with Xcode 14.3 - 

     CocoaLumberjack/Sources/CocoaLumberjack/DDFileLogger.m:1809:28: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
     BOOL doesAppRunInBackground() {
                           ^
                            void
     1 warning generated.

&nbsp;

     CocoaLumberjack/Sources/CocoaLumberjack/Extensions/DDFileLogger+Buffering.m:44:42: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
     static NSUInteger DDGetMaxBufferSizeBytes() {
                                         ^
                                          void
     CocoaLumberjack/Sources/CocoaLumberjack/Extensions/DDFileLogger+Buffering.m:53:46: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
     static NSUInteger DDGetDefaultBufferSizeBytes() {
                                             ^
                                              void
     2 warnings generated.

**To Reproduce**
1. Include via cocoapods in a project
2. Build with Xcode 14.3

**Expected behavior**
No warnings when building

**Screenshots**
(not included)

**Environment info**
  Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS 
 Platform Version        | 16.4 
 CocoaLumberjack Version | 3.8.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 14.3
 Repro rate              | 100%
 Repro project link      | n/a

**Additional context**
I can put together a PR...but if someone already has one in the works, don't want to waste time or cause a headache for others to have to go in and review (also don't want to make a PR that would just sit out there for years 😉 )

**Comment by ffried** [comment]
@LowAmmo if you don't mind, please do open a PR for this. I don't know of any work on this, so it wouldn't be wasted time!

**Comment by LowAmmo** [comment]
@ffried  - added the PR - CocoaLumberjack/CocoaLumberjack#1340
