### ISSUE TITLE
Multiple logger output files

### ISSUE THREAD

**Issue by pkasson** [CocoaLumberjack/CocoaLumberjack#1339]
Is the following possible (in Swift only):

1.  have a custom logger, to log to a separate output log file
2.  have separate log files for info, error, custom (as in number 1 above) 

Great project - been using it since my early Obj-C days !

**Comment by ffried** [comment]
@pkasson This is totally possible. You even have multiple ways to achieve this...

First, you could subclass `DDFileLogger`, make it configurable with the log level you want and add it multiple times - using the corresponding log level.

Second, you could use a `DDLogFormatter` as a filter. Simply return `nil` from its formatting method to prevent the message from being logged.
Then add multiple `DDFileLogger`s (using different files), each having its own log formatter that filters the messages.

Both is possible in both Swift and Objective-C.

**Comment by pkasson** [comment]
Thanks for the overview ... but not clear some of the steps.  Some post said you can only do this with Obj-C .. any examples or direction would be great and I would push that back as a PR

**Comment by ffried** [comment]
You would need a custom `DDLogFileManager` for both solutions (unless you're using completely distinct directories per level, in which case you could pass it to the `DDLogFileManagerDefault` directly).

```swift
final class LevelBasedLogFileManager: DDLogFileManagerDefault {
    let level: DDLogFlag

    private var levelString: String {
        switch level {
        case .verbose: return "VERBOSE"
        case .debug: return "DEBUG"
        case .info: return "INFO"
        case .warning: return "WARNING"
        case .error: return "ERROR"
        default: return "DEFAULT"
        }
    }

    private var logFilePrefix: String {
        levelString + "_"
    }

    init(level: DDLogFlag) {
        self.level = level
        super.init()
    }

    override var newLogFileName: String {
       logFilePrefix + super.newLogFileName
    }

    override func isLogFile(withName fileName: String) -> Bool {
        return fileName.hasPrefix(logFilePrefix)
            // The log file prefix needs to be dropped for `super.isLogFile(withName:)` to recognize the log file name.
            && super.isLogFile(withName: String(fileName.dropFirst(logFilePrefix.count)))
    }
}
```

Then you can either have a subclass of `DDFileLogger`, that filters out the corresponding messages:

```swift
final class LogLevelFileLogger: DDFileLogger {
    let level: DDLogFlag

    init(level: DDLogFlag) {
        self.level = level
        super.init(logFileManager: LevelBasedLogFileManager(level: level))
    }

    override func log(message logMessage: DDLogMessage) {
        guard logMessage.flag == level else { return }
        super.log(message: logMessage)
    }
}
```

Or use the default `DDFileLogger` (passing it the `LevelBasedLogFileManager`) and assign it a `DDLogFormatter` that filters the log messages (possibly combined with further log formatters using `DDMultiFormatter`:
```swift
final class LogLevelFilteringFormatter: NSObject, DDLogFormatter {
    let level: DDLogFlag

    init(level: DDLogFlag) {
        self.level = level
    }

    func format(message logMessage: DDLogMessage) -> String? {
        guard logMessage.flag == level else { return nil }
        // TODO: Add whatever formatting is necessary. Or chain using DDMultiFormatter.
        return logMessage.message
    }
}
```
