### ISSUE TITLE
No logs saved when hosted in am iOS Network Extension 

### ISSUE THREAD

**Issue by lukaspechar** [CocoaLumberjack/CocoaLumberjack#1343]
**Checklist**
- [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
- [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation)
- [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

**Describe the bug**
I've added CocoaLumberjack (CLJ from now on) to my project using CocoaPods. The project has a Network Extension (appex) in which I'm trying to log. Unfortunately nothing is logged. I've even used the recommended `#define LOG_ASYNC_ENABLED NO` flag to write the logs synchronously as described in the documentation. Anyone have any idea why it is not logging. I've had no issues with CLJ in the main app. Thank you.

**To Reproduce**
1. Create an app and add network extension. (https://developer.apple.com/documentation/networkextension?language=objc)
2. Add CLJ as a pod and install the pod. Initialise a ` DDFileLogger` as per the documentation.
3. Log using any of the DDLog commands for example `DDLogInfo` or `DDLogError`
4. If you try to load the files there are none being returned. Note that I have used a `DDLogFileManager` and initialised it with a custom directory pointing to the app group shared location (this works well when logging from the main app)

**Expected behavior**
Should show any logged messages in the loaded file.

**Environment info**
  Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS 
 Platform Version        | 16.4.1 (a)
 CocoaLumberjack Version | 3.8.0
 Integration Method      | cocoapods 
 Xcode Version           | Xcode 14.3
 Repro rate              | all the time (100%)

**Comment by ffried** [comment]
Hmm, not sure what's going on here. Logging from extensions usually works. I've used it in various extensions like WidgetKit and Notification Extensions.
Resource usage is always a critical point with them, though. I've no experience with network extensions and their limitations, but I could imagine them being quite restrictive.

Have you tried manually creating files from the extension in the app group storage? Does this work? Are other loggers like `OSLogger` working? - if that's even possible to debug given that extensions and debugging can be quite a ride.

**Comment by avivil** [comment]
While it is possible to write to local storage (in the app group folder) in some specific extensions in iOS (widget extension, safari extension etc) this isn't true to all the different kinds of extensions. Some extensions don't allow writing (and allow read only access to local storage) by design.

Two examples for extensions in iOS that allow read only access to local storage:

Networking extension - Content Filter Provider (read only access allowed in the filter data provider, read/write access allowed in the filter control provider).

SMS and MMS Message Filtering - Read only access.

**Comment by ffried** [comment]
@avivil thanks for the explanation!

**Comment by lukaspechar** [comment]
Hi @ffried apologies for the late reply. Terribly busy. I've managed to create the files in the app group folder through on the network extension. Unfortunately nothing is being logged anyway. The Network Extension I'm using is the `PacketTunnelProvider`. OSLogger works without any issues.

**Comment by ffried** [comment]
@lukaspechar Hmm, interesting. Still could be a restriction of these extensions. E.g. only being allowed to create files, but not constantly update them.
Either way, you can try to debug it by checking the logs for errors logged by `DDFileLogger` (e.g. https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Sources/CocoaLumberjack/DDFileLogger.m#L1356).
Also, you can set breakpoints in these methods. If you reach them, you might be able to find out what happens. If not, it could be an issue with the CocoaLumberjack setup (which I doubt if `OSLogger` works).

**Comment by lukaspechar** [comment]
Thanks for your reply. I'll give that a go. A little busy at the moment but as soon as I have some time I'll try debug it and update the ticket with any findings. Thanks all for your suggestions.

**Comment by lukaspechar** [comment]
Hi @ffried, apologies for the very very late reply. I've finally had a moment to look into this. I've debugged through the file you suggested, everything points to the logs being successfully saved. So I peeked at the actual file naming logic and that's where I noticed a separate file is being created for each bundle! The logs were actually being saved but to a different file. I've since overridden the `newLogFileName` and `isLogFile` functions as per the comments in the source and now use a single file for both the targets - i.e. the app and the network extension and save it to the app group folder on the disk.

Thanks for the help. Turns out the problem was PEBKAC

**Comment by ffried** [comment]
@lukaspechar Ah, that makes sense. Thanks for the feedback here! Recent versions of CocoaLumberjack have file locking, so your setup should work fine.

**Comment by lukaspechar** [comment]
If I were to keep the logs separate, as they are by default, how can I retrieve the filenames of the network extension from within the app? I guess I'd need to override the `sortedLogFilePaths` array to return file paths for all the targets, at the moment it returns only the current target files.

**Comment by ffried** [comment]
I usually just used a subfolder for logs and then iterated the files in there (or compressed the whole subfolder)...
