### ISSUE TITLE
Call to undeclared function 'DDLogInfo'; ISO C99 and later do not support implicit function declarations

### ISSUE THREAD

**Issue by zkrige** [CocoaLumberjack/CocoaLumberjack#1344]
**Describe the bug**
compile time error messages

**To Reproduce**
call any of the DDLog* methods

**Expected behavior**
no warnings or errors

**Screenshots**
<img width="1081" alt="image" src="https://github.com/CocoaLumberjack/CocoaLumberjack/assets/968412/578bcc3d-ea3e-49a6-94a5-684023740635">

**Environment info**
  Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | N/A
 Platform Version        | N/A
 CocoaLumberjack Version | e.g. 3.8.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 14.3.1
 Repro rate              | all the time (100%) but after a while of background processing it dissappears until app rebuild

**Additional context**
It shows "errors" but the app runs fine. If I open the file where the "error" is, the error disappears after a few seconds

**Comment by ffried** [comment]
This could either be a missing import (`DDLogMacros.h`) or an Xcode quirk.
Given the build works, it's obviously a spurious error. Not sure we can do much here.
