### ISSUE TITLE
Release a new version - 3.9.0 or 3.8.1?

### ISSUE THREAD

**Issue by LowAmmo** [CocoaLumberjack/CocoaLumberjack#1348]
**Is your feature request related to a problem? Please describe.**
Requesting to tag/create a new release of the changes since 3.8.0.

**Describe the solution you'd like**
Releasing the current changes on master as either 3.9.0 or 3.8.1

**Describe alternatives you've considered**
n/a

**Additional context**
Not sure on the preferred release process, etc. I know I wouldn't be able to publish to cocoapods, but I can put together a PR if that is the preferred way to start down the path.

But, we do consume via cocoapods - so would definitely want to coordinate and ensure that updating versions would also trigger releasing to the cocoapods' spec repo.

-Thanks!

**Comment by mackworth** [comment]
This would be great! I also use CocoaPods, and this would fix some Xcode warnings.

**Comment by ffried** [comment]
I agree and will see if I can release a version in the coming weeks.
I'd like to run the codebase through Xcode 15 and Swift 5.9 first, though. Just to make sure we have we are running fine on this year's OS releases as well.

**Comment by mackworth** [comment]
Great to hear! 

Just FYI, other than the deprecations, Xcode 15 is working fine for me.

**Comment by mackworth** [comment]
Sorry to confuse; I meant against the current Cocoapods release; I believe all those are indeed fixed in `master`.

**Comment by ffried** [comment]
I've just released version 3.8.1.

**Comment by LowAmmo** [comment]
Thanks, @ffried !
