### ISSUE TITLE
Question about dynamicLogLevel

### ISSUE THREAD

**Issue by leo150** [CocoaLumberjack/CocoaLumberjack#1349]
**Checklist**
- [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
- [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation)
- [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

**Describe the bug**
When I start my app and call `DDLogVerbose`, the messages are ignored because `dynamicLogLevel` is `.off`.

My setup is very basic:
```
let osLogger = DDOSLogger.sharedInstance		
// dynamicLogLevel = .all
DDLog.add(osLogger, with: .all)
DDLogVerbose("Verbose")
``` 
I even tried to add `didSet` to `dynamicLogLevel` but is not called from anywhere before `DDLogVerbose`. Until I explicitly set `dynamicLogLevel` to `.all` it stays `0`.

<details>
  <summary>Image</summary>
  
<img width="721" alt="Screenshot 2023-07-21 at 1 21 32 PM" src="https://github.com/CocoaLumberjack/CocoaLumberjack/assets/3484524/5213afd8-38c0-47e8-abd5-cd3439dd90d3">
  
</details>

Why `dynamicLogLevel` is `.off`?

**To Reproduce**
1. Create logger 
2. Log message
3. See nothing

**Expected behavior**
Get verbose messages

**Environment info**
  Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 16.5.1
 CocoaLumberjack Version | 3.8.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 14.2
 Repro rate              | 100%
 Repro project link      | n/a

**Comment by ffried** [comment]
Tbh, I have no idea why it's `.off` in your case. It's definitively initialized with `.all` as can be seen in [this line](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/c8f86e6c9dc15ae6afcadbad6255cf9cbc6bc9f0/Sources/CocoaLumberjackSwift/CocoaLumberjack.swift#L53).

Also, our tests perform the same task. For example the [publisher tests](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/c8f86e6c9dc15ae6afcadbad6255cf9cbc6bc9f0/Tests/CocoaLumberjackSwiftTests/DDLogCombineTests.swift#L24) never set the dynamic log level anywhere, but [do log in verbose](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Tests/CocoaLumberjackSwiftTests/DDLogCombineTests.swift#L95) and the message goes through.
