### ISSUE TITLE
Sandbox error when building my app that includes CocoaLumberjack with latest Xcode beta 6

### ISSUE THREAD

**Issue by nemesyssoft** [CocoaLumberjack/CocoaLumberjack#1353]
**Checklist**
- [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
- [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation)
- [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

**Describe the bug**
All of a sudden, when trying to build my project, Xcode generates an error when it's trying to build my app wrapper:

error: Sandbox: rsync.samba(9049) deny(1) file-write-create /Users/laurent/Library/Developer/Xcode/DerivedData/MyApp-echjohfiigsxiqdtidypaamprogl/Build/Products/Debug/MyApp.app/Contents/Frameworks/CocoaLumberjack.framework/CocoaLumberjack

**To Reproduce**
1. Get Xcode Beta 6
2. Open a project that uses CocoaLumberjack
3. Build the project

**Expected behavior**
The CocoaLumberjack framework should be placed inside my app wrapper.

**Environment info**
  Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |macos
 Platform Version       |14.0
 CocoaLumberjack Version |3.8.0
 Integration Method      |cocoapods
 Xcode Version           |Version 15.0 beta 6 (15A5219j)
 Repro rate              |all the time (100%)
 Repro project link     |I don't think that's needed, any project will exhibit the problem with this version of Xcode and/or macOS Sonoma 14.0

**Comment by ffried** [comment]
@nemesyssoft I can't reproduce the issue here using Xcode 15 beta 6.
Is your project using custom run scripts? If so, [this SO answer](https://stackoverflow.com/a/76626156/1388842) could maybe help.

**Comment by nemesyssoft** [comment]
> @nemesyssoft I can't reproduce the issue here using Xcode 15 beta 6. Is your project using custom run scripts? If so, [this SO answer](https://stackoverflow.com/a/76626156/1388842) could maybe help.

That was it, Florian. I completely missed this build setting. Sorry about the bother.
