### ISSUE TITLE
CocoaLumberjackSwiftLogBackend not importable when using Cocoapods

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [CocoaLumberjack/CocoaLumberjack#1354]
**Checklist**
- [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
- [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation)
- [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

**Describe the bug**
CocoaLumberjackSwiftLogBackend not importable

**To Reproduce**
1. Use the line `pod 'CocoaLumberjack/Swift'` in your podspec
2. Try to do `import CocoaLumberjackSwiftLogBackend` in swift
3. See error

**Expected behavior**
CocoaLumberjackSwiftLogBackend being importable

**Environment info**
  Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios and macos
 Platform Version        | 14.0+
 CocoaLumberjack Version | e.g. 3.8.1
 Integration Method      | cocoapods
 Xcode Version           | Xcode 14.3.1
 Repro rate              | 100%
 Repro project link      | https://github.com/monal-im/Monal

**Comment by ffried** [comment]
When the swift-log backend was added, swift-log had no CocoaPods support.
Also, it would have to be a separate spec since we need to add swift-log as a dependency.

To be honest, I'm not sure if it makes that much sense, though. Adding it means maintaining the swift-log dependency in one more place. We could think about generating it on the fly maybe. This would also allow us to not have to update Swift versions, SDK versions and spec versions in multiple places...

**Comment by ffried** [comment]
@tmolitor-stud-tu I just found out that most of Apple's libraries actually dropped CocoaPods support. See [this forum tread](https://forums.swift.org/t/swiftnio-is-dropping-support-for-cocoapods/56840/9).

The current podspec of swift-log is also completely outdated (1.4.0): https://cocoapods.org/pods/Logging

So I'll update #1360 to not add a subspec for the swift-log backend. The recommended integration method stays SPM here.

**Comment by tmolitor-stud-tu** [comment]
Well, great news :( one reason more to not be an apple fan.

Anyways, thanks for all your work!
