### ISSUE TITLE
"Use an interpolated DDLogMessageFormat instead" waring is displayed after updating to 3.8.1 when passing "String" to DDLog methods

### ISSUE THREAD

**Issue by fzy-spyro** [CocoaLumberjack/CocoaLumberjack#1370]
**Checklist**
- [X] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
- [X] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation)
- [X] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

**Describe the bug**
After updating to CocoaLumberjackSwift 3.8.1 I am getting following warnings in XCode:
```
'DDLogError(_:level:context:file:function:line:tag:asynchronous:ddlog:)' is deprecated: Use an interpolated DDLogMessageFormat instead
```

**To Reproduce**
1. Create logger '...' N/A
2. Warning is displayed in eg. following code:

```
private func logError(_ name: String, error: Error, message: String) {
        // some other code
        DDLogError(message) // warning displayed here
    }
```

**Expected behavior**
No warning or clear instructions how to migrate

**Screenshots**
N/A

**Environment info**
  Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios
 Platform Version        | e.g. 16
 CocoaLumberjack Version | e.g. 3.8.1
 Integration Method      | e.g. spm 
 Xcode Version           | e.g. Xcode 14.2
 Repro rate              | e.g. all the time (100%) 

**Additional context**
I've been able to pinpoint the change that is now causing the warning to be displayed: https://github.com/CocoaLumberjack/CocoaLumberjack/commit/29bca377c9e08c878cf4e667bff27034cb732073 which was part of this PR: https://github.com/CocoaLumberjack/CocoaLumberjack/pull/1347 

After playing around a bit with the code I was able to get rid of the warining but this seems a like hack. In the code shared above replacing DDLogError with below code removes the warning:

```
DDLogError("\(message)")
```

**Comment by ffried** [comment]
This is intended. The new version uses a fully typed message format. This is similar to e.g. [swift-log](https://github.com/apple/swift-log/blob/cb28750240a9389e0023ee3e3cb6c83ce0960f5c/Sources/Logging/Logging.swift#L80) which also uses a typed message parameter.

There are two solutions to this. Either the one you chose with an interpolation (`"\(message)"`) or by changing your `message` parameter from `String` to `DDLogMessageFormat`.

**Comment by vlvs** [comment]
I'm confused as to how to properly use `DDLogMessageFormat` to preserve message format, could you give an example @ffried? 🤔

**Comment by ffried** [comment]
@vlvs What exactly are you trying to achieve?

**Comment by vlvs** [comment]
Say I have something like this:
```
DDLogDebug(String(format:"commentInfo=%@", comment))
```
Where `comment` is a variable consisting of a bunch of concatenated strings. How would you use `DDLogMessageFormat` to represent/replace that?

**Comment by ffried** [comment]
@vlvs This could be converted to simply `DDLogDebug("commentInfo=\(comment)")`

**Comment by ffried** [comment]
@vlvs You can learn more about string interpolation in the [swift documentation](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/stringsandcharacters/#String-Interpolation). The only difference with CocoaLumberjack is, that you're not creating a `String` directly, but instead a `DDLogMessageFormat` is created under the hood.

**Comment by ffried** [comment]
Actually, the `"\(result)"` _is_ creating a `DDLogMessageFormat` here. It looks like a string, but the underlying conformance to Swift's `ExpressibleByStringInterpolation` will turn it into a `DDLogMessageFormat` instead.

So generally speaking, unless you're writing some kind of wrapper around CocoaLumberjack, you shouldn't be creating `DDLogMessageFormat`s manually, but instead use string interpolation as the parameter to the DDLogXYZ functions.

**Comment by vlvs** [comment]
Oh, I see. Got it, thanks! ✨

**Comment by ffried** [comment]
@algrid The same design decision was made by Apple _twice_ for logging. Both [swift-log](https://github.com/apple/swift-log) and [OSLog](https://developer.apple.com/documentation/os/logging) use a type that conforms to `ExpressibleByStringInterpolation`.
Doing so gives much more insight into the structure of a log message - something a plain `String` could never provide.

**Comment by algrid** [comment]
Frankly, I don't know how those Apple libraries work, I'm just curious what kind of structure we're talking about when it's just a plain string? Something about the contents of the string? But why would a logging library need that?

**Comment by ffried** [comment]
It usually isn't a plain string. Most log messages carry some kind of information. A value, an error, ...
We currently use it to be able to reconstruct the format of the message string (similar to format strings in C). 

In OSLog, Apple uses the interpolation arguments to mask those values when not attached to a debugger (unless the values are classified as public).
But since you are in full control of what interpolations you accept, you can go as far as have a formatter for every possible type.
If you compose the string before passing it to a logging library, the only thing the logging library sees is the string. If it was created using string interpolation, the values are already "stringified".

Basically, the following gives insight into the log message:

```swift
let bool = true
let int = 42
let str = "hello"

DDLogInfo("We have some values: A bool being \(bool), an int \(int) and a string saying: \(str)")
```

With this version, there's a separate method called for each `\()` inside the interpolation. If there's no matching method, the compiler will emit an error, stating that this interpolation is not supported. In OSLog for example, not all types are accepted (due to the way those messages are stored).

However, in this example, all values are already converted to strings before they reach the logging library:

```swift
let bool = true
let int = 42
let str = "hello"

let message: String = "We have some values: A bool being \(bool), an int \(int) and a string saying: \(str)"

DDLogInfo("\(message)")
```

We only get one `\()` where the pre-composed message is contained. This is *not* the recommended way.

**Comment by algrid** [comment]
@ffried Thank you for detailed explanation! All I need from a logging library is ability to log strings (and probably errors/exceptions with some special processing). I guess more smart people at Apple have more advanced needs and priorities that require custom string interpolation handling.
