### ISSUE TITLE
Make `lt_dataForMessage:` behaviour customizable

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [CocoaLumberjack/CocoaLumberjack#1371]
Currently I'm overwriting [`lt_dataForMessage:`](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Sources/CocoaLumberjack/DDFileLogger.m#L1395) [in Monal](https://github.com/monal-im/Monal/blob/develop/Monal/Classes/MLFileLogger.m#L109) to write my logfile in a binary format (length prefixed json).
I was wondering, if we could somehow make the behaviour of `lt_dataForMessage:` customizable.

Two solutions I have in mind:
- Add a optional callback to the logfile manager and call it to convert a given `DDLogMessage*` to `NSData*`, if the logfile manager responds to that optional selector (not doing the default conversion in `lt_dataForMessage:`).
- Make `lt_dataForMessage:` an official extension point that can be overwritten by child classes (renaming it to something like `dataForMessage:`). _(I'd prefer this one)_

@ffried What do you think? Do you have some other/better ideas to accomplish this?
Once we've decided how to implement it, I'm happy to create a pull request for this :)

**Comment by ffried** [comment]
Just a quick note that I haven't forgotten about this!
But I also haven't found the time to think about this some more.
My initial thoughts so far: I somehow like the general idea, but I'm not sure whether opening `DDFileLogger` for this is the right idea. It's a rather advanced use case where rolling your own logger might actually be the right solution. Though I can understand using `DDFileLogger` to have it deal with the whole rolling and file management code.

**Comment by tmolitor-stud-tu** [comment]
@ffried oh, thanks for that update!!

I think the reason I want this upstream is exactly what you already said: all the file management and rolling code would have to be duplicated, if I'd really wrote my own logger and I think this is kind of an overkill if one only needs a different on-disk format of the log data.

Another option would be to split `DDFileLogger` into a base class containing all this file management stuff and a child class doing the rest. That would allow users that need more control over the file contents to just create a new child class inheriting from this base class.
Maybe `DDAbstractFileLogger` with its default child `DDFileLogger`.

**Comment by ffried** [comment]
@tmolitor-stud-tu I created a little PR (#1380) for it. It's similar to your first solution, but it's separated from the log file manager into a separate type. The reason it needs to be on the log file manager is e.g. the `logFileHeader` on `DDLogFileManagerDefault` which needs to go through this new serialization as well.

**Comment by tmolitor-stud-tu** [comment]
I like the idea, but I see some problems with your approach:

I (and I suspect most other people, too) want to use this custom `NSData*` conversion function to do structured logging. For this, the original `DDLogMessage*` must be available to the conversion function to consume its individual fields.

My proposed change is simple, though:
`-(NSData*) dataForMessageString:(NSString*) message andLogMessage:(DDLogMessage* _Nullable) logMessage`.
This way both, the formatted string and the original `DDLogMessage*` is available to the conversion function and the parameter taking the `DDLogMessage*` can be set to nil if there is no such object (e.g. when converting the `logFileHeader`).

I'll do a review of the pull request and propose my changes so you can just merge them in :)

**Comment by ffried** [comment]
Hmm, I kept the `DDLogMessage` out of the serializer on purpose to prevent people from doing formatting in there.

Looking at your implementation, I wonder if this couldn't all be simply done using a formatter anyways?

E.g. just create an `NSString` from your JSON `NSData` object, prepend the length and let the current behavior write that into the file.
There's the downside of going through `NSData` -> `NSString` -> `NSData`, but that should not be too bad for these small strings.

**Comment by tmolitor-stud-tu** [comment]
Well, no. The length should be a binary 32bit unsigned integer, which (normally) is not a valid UTF-8 sequence that can be encoded in an `NSString*`. Or: imagine someone wanting to compress each logline individually, or create structured logging (based on json or whatever) and compress it before writing that to disk: this is not possible with the current code due to the hardcoded UTF-8 encoding.

What I could do with your original PR would be the following: write a "formatter" creating an `NSData*` through `dataWithJSONObject:options:error:`, converting this to an `NSString*` using `UTF-8` encoding and returning that.
Then write a MessageSerializer that takes this `NSString*`, converts it back to `NSData*`, calculates its length and prepends this to the `NSData*` before return it.
Compressing this `NSData*` is possible with this approach, too.

**But:**
This is a bit inflexible. If I, for example, want to do "normal" formatting **and** structured logging (for example by adding a "formattedMessage" key to my structured loggin json), I'd have to call the real formatter inside my JSON formatter myself and loose all those convenient framework methods for setting and configuring a formatter.

I guess this inflexibility arising from the need to manually manage the formatter is another side of the reason why you don't want users to do formatting inside the MessageSerializer.

**So, what should we do now?**
Well. I'm torn. Both, your original PR and my suggestions in your PR have drawbacks. Maybe we should take a step back and think about an entire different approach: what about creating an abstract base class handling all the file creation, rollover, locking etc. stuff and a concrete class for writing text logs. I, for example, could take the base class and write a concrete implementation for writing structured logfiles.
The abstract method to be implemented by the child class would be exactly the method used in the MessageSerializer (the one I did suggest in my PR suggestions): `- (NSData *)dataForMessageString:(NSString *)message andLogMessage:(nullable DDLogMessage *)logMessage;`.
I think, for the users, the hurdles of creating a concrete implementation of this base class are a bit higher than trying to incorrectly use the MessageSerializer to format a message. Maybe this is a compromise avoiding the drawbacks of bot, your original PR and my changes in that PR.

If you like this approach, I can create a PR implementing it :)

**Comment by ffried** [comment]
After thinking more about this, let's just pass the log message to the serializer. We have quite a few "assumptions" within CocoaLumberjack. So I've added it, documented it and will live with it.

Restructuring the DDFileLogger like that would be an option, but it requires heavy testing and I'm not sure what "special subclasses" (similar to yours) exist in the wild. I'd like to avoid breaking them for now. I'm aware that the change can be implemented without breaking the public interface, but in Objective-C world, not everyone sticks to public interfaces.

**Comment by tmolitor-stud-tu** [comment]
Great, thanks!!

Yes, as an example, currently my subclass overwrites the non-public `lt_dataForMessage:`, too ;)

**Comment by tmolitor-stud-tu** [comment]
Thanks for merging #1380!!
