### ISSUE TITLE
Building swift-log backend for watchOS fails on Xcode 15

### ISSUE THREAD

**Issue by allenlooplee** [CocoaLumberjack/CocoaLumberjack#1375]
**Checklist**
- [✅] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
- [✅] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation)
- [✅] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

**Describe the bug**
I'm currently using CocoaLumberjack as a backend of SwiftLog. It worked fine previously until I updated Xcode to 15 and watchOS simulator to 10 last night. Below is the error message during build:

> Build target CocoaLumberjackSwiftLogBackend with configuration Debug
> error: The package product 'Logging' requires minimum platform version 5.0 for the watchOS platform, but this target supports 4.0 (in target 'CocoaLumberjackSwiftLogBackend' from project 'CocoaLumberjack')
> 
> The package product 'Logging' requires minimum platform version 5.0 for the watchOS platform, but this target supports 4.0

**To Reproduce**
1. Add CocoaLumberjack and use it as a backend of SwiftLog
2. Update Xcode to 15 and watchOS simulator to 10
3. Build the project

**Expected behavior**
The project should build successfully.

**Screenshots**

<img width="733" alt="Screenshot 2023-09-20 at 12 01 05" src="https://github.com/CocoaLumberjack/CocoaLumberjack/assets/132692/beb15f4b-be5e-45d6-b015-201bc2988530">

**Environment info**
  Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | watchos
 Platform Version        | 10
 CocoaLumberjack Version | 3.8.1
 Integration Method      | spm
 Xcode Version           | Xcode 15.0
 Repro rate              | all the time (100%)
 Repro project link      |N/A

**Additional context**
SwiftLog was added automatically as a dependency of CocoaLumberjack by SPM. The version of SwiftLog is 1.5.3.

**Comment by ffried** [comment]
This is a weird one.
According to [Xcode 15's Release Notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes), the minimum supported watchOS version is 4.0:

<img width="966" alt="image" src="https://github.com/CocoaLumberjack/CocoaLumberjack/assets/1689782/da0db380-74ad-4711-8b85-a76795dcdf5e">


[The manifest for swift-log](https://github.com/apple/swift-log/blob/1.5.3/Package.swift) does not list any supported platforms. In my understanding, this should result in Xcode's / Swift's lowest supported platform version.

I'll have to investigate further, but this could be a bug on Apple's side.

**Comment by ffried** [comment]
For the record, I've opened [an issue](https://github.com/apple/swift-package-manager/issues/6974) with the Swift package manager for this.

**Comment by wunderk1nd-e** [comment]
Has anyone found a workaround for this by any chance?
