### ISSUE TITLE
Duplicated declarations ObjC + Swift

### ISSUE THREAD

**Issue by matteogobbi** [CocoaLumberjack/CocoaLumberjack#1376]
Hello,

I'm using this pod on ObjC since years, but now that we also use Swift in the project, I installed the version with Swift too.
As soon as I import the library in a swift files and compile, I get a lot of duplications errors:

<img width="1723" alt="Screenshot 2023-09-20 at 12 40 26 PM" src="https://github.com/CocoaLumberjack/CocoaLumberjack/assets/1998171/7cc99393-7a9e-4a0f-bb71-643ac66df48b">

**Comment by ffried** [comment]
I'm not too familiar with how CocoaPods works, but I assume that it now links `CocoaLumberjack` twice, since `CocoaLumberjackSwift` includes `CocoaLumberjack`.

**Comment by ffried** [comment]
Can you paste your Podfile?

**Comment by wsrGitHub** [comment]
Use swift version or objc version. You can only choose one or the other, not both at the same time.
