### ISSUE TITLE
Dynamically setting log level does not update `DDOSLogger` (or other library-provided loggers)

### ISSUE THREAD

**Issue by l3ender** [CocoaLumberjack/CocoaLumberjack#1381]
**Checklist**
- [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
- [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation)
- [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

**Describe the bug**

We are trying to use [dynamic log levels](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/590a4b2d104a444e1e2ed120bfe2dc9fb284502f/Documentation/DynamicLogLevels.md) in order to set level for all registered Lumberjack loggers. However, when trying to utilize the `DDLog` methods for retrieving (`registeredClassNames`, `registeredClasses`) and configuring log levels (`setLevel`), we are not observing the built-in `DDOSLogger` as supporting this feature. We have a feature in our app to change log levels dynamically and want to extend this to the built-in loggers.

**To Reproduce**

1. In AppDelegate, register the library-provided `DDOSLogger` (as well as any other desired loggers):
    ```objc
    [DDLog addLogger:[DDOSLogger sharedInstance]];
    [DDLog addLogger:[CustomLogger alloc]];
    ```
2. Try and retrieve all registered classes:
    ```objc
    NSArray *registeredClassNames = [DDLog registeredClassNames];
    NSLog(@"registeredClassNames: %@", registeredClassNames); // <----- does not include DDOSLogger!
    
    NSArray *registeredClasses = [DDLog registeredClasses];
    for (Class class in registeredClasses) { } // <-----registeredClasses does not include DDOSLogger!
    ```

**Expected behavior**

Our expectation is that `DDOSLogger` would support dynamic logging out of the box, so that its log level can be dynamically configured in the same way as any other custom logger.

There are scenarios where sensitive data may be logged and it would be undesirable to log these to the built-in loggers.

**Environment info**
  Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 15.0
 CocoaLumberjack Version | 3.8.1
 Integration Method      | cocoapods
 Xcode Version           | Xcode 15.0
 Repro rate              | all the time (100%)
 Repro project link      | n/a

**Additional context**

It appears the built-in/provided loggers do not support this feature (we believe this same problem applies to other library loggers besides `DDOSLogger`).

**Comment by ffried** [comment]
Registered dynamic logging is a very advanced feature, that is not intended for loggers themselves (or at least not most of them). Thus none of the built-in loggers have the required methods. As described in the documentation you linked, it's basically based on two class methods: `+ddLogLevel` and `+ ddSetLogLevel:`. 

Furthermore, it's only used to give users of CocoaLumberjack the option to easily list all classes that use registered dynamic logging. CocoaLumberjack itself does not do much with it - except for collecting the classes when you ask for them, as well as calling the two methods when you use `setLevel:forClass:` or `levelForClass:`.
