### ISSUE TITLE
Log advanced log messages (`DDLogMessage` object) and have Lumberjack handle log level

### ISSUE THREAD

**Issue by l3ender** [CocoaLumberjack/CocoaLumberjack#1384]
**Is your feature request related to a problem? Please describe.**

We have the need to have a generic logging interface where a different part of our application generates events for which we want to send to Lumberjack. We have a custom class which intercepts these events and are trying to determine how to best handle them with Lumberjack.

The events contain log level and have additional detail (dictionary/map) for which we want to generate a `DDLogMessage` message and send to Lumberjack.

**However**, when we generate a `DDLogMessage` and use the generic interface on `DDLog`, we are seeing Lumberjack process the log regardless of the logger's configured log level.

**Describe the solution you'd like**

Our event handler generates log messages and dispatches to Lumberjack as follows:

```objc
NSString* message = ... // derived from event;
DDLogLevel level = ... // derived from event;
DDLogFlag flag = ... // derived from event;
NSDictionary* properties = ... // derived from event <----- this is critical for us, to be able to provide additional log detail!
DDLogMessage* logMessage = [[DDLogMessage alloc]
                            initWithFormat: message
                            formatted: message
                            level: level
                            flag: flag
                            context: 0
                            file: @(__FILE__)
                            function: @(__func__)
                            line: __LINE__
                            tag: properties
                            options: (DDLogMessageOptions)0
                            timestamp: [NSDate date]];
[DDLog log:TRUE message:logMessage];
```

For the above, all configured loggers will process the message, even if if the configured logger's level is such that it should not process the message.

**Describe alternatives you've considered**

We could handle log level detail within the event handler/interceptor, but it feels like this is duplicating logic from Lumberjack (and defeating its purpose for handling log levels to determine whether log events should be processed).

**Additional context**

Example:
* Logger A - level set to error
* Logger B - level set to warn
* Event received by interceptor which dispatches message with `level=DDLogLevelDebug` and `flag=DDLogFlagDebug`.

When our event interceptor/handler sends `DDLogMessage`, we are seeing Logger A and B still receive the message when we would expect that Lumberjack would not send those messages to those loggers because their level is higher than the incoming message.

We are hoping there is a way that Lumberjack can handle these advanced log messages without us needing to reimplement log level logic in our interceptor. Please let us know--thanks!!

**Comment by ffried** [comment]
This should already be possible out of the box.

- Add the logger with the desired level: `[DDLog addLogger:yourLogger withLevel:DDLogLevelWarning]`
- Log a message with the appropriate flag.
- Only messages whose flag match the loggers level should be passed to the logger.

If that doesn't work, please re-open this with a small reproduction project.

**Comment by l3ender** [comment]
Thanks for the quick response!

I've modified one of the demo projects to show the issue: https://github.com/l3ender/CocoaLumberjack/tree/log-level-troubleshooting/Demos/RegisteredDynamicLogging/Mobile ([permalink for main repo](https://github.com/CocoaLumberjack/CocoaLumberjack/tree/d663083ddfd625d293a4e3d7e3c8dc035e8fa7b0/Demos/RegisteredDynamicLogging/Mobile)). I updated it to use CocoaLumberjack version 3.8.1 via pod so please open xcworkspace.

The app has a simple custom logger which is added at error level on app start:
```objc
[DDLog addLogger:[CustomLogger alloc] withLevel:DDLogLevelError];
```

As expected, issuing any log message below that level is not handled by the custom logger.

However, when the log level is updated to a different level, sending log messages for a lower level (such as info or warn) are still not handled by the custom logger.

<img width="1056" alt="image" src="https://github.com/CocoaLumberjack/CocoaLumberjack/assets/2243641/ac318adf-6f47-451e-9497-0e68438bd6f7">

The goal is to be able to inform CocoaLumberjack of any changes in log level and have it update and handle future log messages which now meet level criteria. Otherwise log level logic needs to be implemented in every custom logger.

Thanks!

**Comment by ffried** [comment]
Thanks for this update! I think I understand now what you are trying to achieve. However, this is not currently supported by CocoaLumberjack. The log level of a logger cannot be changed after it has been added.
The `+setLevel:forClass:` methods are just convenience implementations over the `DDRegisteredDynamicLogging` protocol - as in they will just set the `ddLogLevel` of that class. Handling that change is the responsibility of the consumer code, not CocoaLumberjack.


You _can_ use this mechanism to control your loggers, though. By adopting the `DDRegisteredDynamicLogging` protocol (or simply implementing its requirements), you can use the `+setLevel:forClass:` methods to change the level. However, you still need to handle the level in your class.
It's not that much of work, though. A simple `if (!(logMessage.flag & self.currentLevel)) return;` (where `self.currentLevel` returns the current level of this logger) at the start of your `-logMessage:` implementation will do the trick.
You can even create your own logger base class and implement it in the base class.

**Comment by l3ender** [comment]
Thanks for the response. I'll dig more into handling logging in the custom logger.

Also, thanks for the heads up on `DDRegisteredDynamicLogging`--wasn't aware of that. I'll likely open a PR for updating doc regarding dynamic logging, both to mention this protocol and the caveats/expected behavior of using a custom logger.

Thanks again!
