### ISSUE TITLE
crash in [DDLogMessage initWithFormat:args:level:flag:context:file:function:line:tag:options:timestamp]

### ISSUE THREAD

**Issue by ywqqqqq** [CocoaLumberjack/CocoaLumberjack#1387]
**Describe the bug**
Specific strings without params causes a crash. The affected strings are those that have undergone URL encoding.

**To Reproduce**
`
NSString *test = @"https%3A%2F%2Ftest.test.com%2Fspa%2Ftest%3Ftest%3Dtest-value%26test_params_1%3Dtest-client.19c8631db3c5a%26scope%3Dtest%3A%3test%3Aaccount_linking%26test_stage%3Ddevelopment%26response_type%3Dcode%26redirect_uri%3Dhttps%3A%2F%2Ftest.com%2Ftest%26state%3Dall&webUrl=https%3A%2F%2Fwww.test.com%2Fap%2Foa%3Ftest_id%3Dtest.ggbvghmdndd%26scope%3Dtest%3A%3Askills%3test_linking%26response_type%3Dcode%26redirect_uri%3Dhttps%3A%2F%2Ftest.com%2Ftest%26test%3Dall";`
`DDLogVerbose(test);`

**Screenshots**
![image](https://github.com/CocoaLumberjack/CocoaLumberjack/assets/17809646/39885220-1351-49e5-94af-ba4b1388f307)

**Environment info**
  Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios 
 Platform Version        | e.g. 17.0
 CocoaLumberjack Version | e.g. 3.8.1
 Integration Method      | e.g.  cocoapods
 Xcode Version           | e.g. Xcode 15.0
 Repro rate              | e.g. all the time (100%)

**Comment by ffried** [comment]
This isn't a valid Objective-C DDLog-call. If you pass arbitrary strings, you need to either make sure, all format arguments are escaped, or pass it using the `%@` format argument.
You can trigger the same crash when swapping `DDLogVerbose` with `NSLog` in your example.

**Comment by ywqqqqq** [comment]
Hey ffried

> This isn't a valid Objective-C DDLog-call. If you pass arbitrary strings, you need to either make sure, all format arguments are escaped, or pass it using the `%@` format argument. You can trigger the same crash when swapping `DDLogVerbose` with `NSLog` in your example.

Both NSLog(@"%@", test); and NSLog(@"https%%3A%%2F%%2F"); do not cause a crash, but they exhibit different output in the console.

Hey ffried:

When I use `NSLog(@"%@", test);`, it treats test as a string literal and prints all the content of test in the console, including the % symbol. 
However, when I use `NSLog(@"https%%3A%%2F%%2F");`, it interprets % as an escape character. In my case, the output is "https0X1.6D8F88CP-10420.0000000.000000".

Thank you for you time.

**Comment by ffried** [comment]
Both of your examples are valid calls - which is why they don't crash.

But using `NSLog(@"%@", test)` is the better of the two solutions IMHO.
