### ISSUE TITLE
Thread running at QOS_CLASS_USER_INTERACTIVE waiting on a lower QoS thread running at QOS_CLASS_BACKGROUND. Investigate ways to avoid priority inversions

### ISSUE THREAD

**Issue by neeliakash2696** [CocoaLumberjack/CocoaLumberjack#1396]
**Checklist**
- [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
- [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation)
- [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

**Describe the bug**

**To Reproduce**
1. Create logger '...'
2. Log message '...'
3. See error

**Expected behavior**

**Screenshots**

**Environment info**
  Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios / macos / tvos / watchos
 Platform Version        | e.g. 13.0
 CocoaLumberjack Version | e.g. 3.7.4
 Integration Method      | e.g. spm / carthage / cocoapods / manually
 Xcode Version           | e.g. Xcode 13.4
 Repro rate              | e.g. all the time (100%) / sometimes x% / only once
 Repro project link      | e.g. link to a reproduction project that highlights the issue

**Additional context**
Are you reporting a queue deadlock? If so, please include a complete backtrace of all threads, which you can generate by typing `bt all` in the debugger after you hit the deadlock. We might not be able to fix deadlock reports without a backtrace!

**Comment by ffried** [comment]
@neeliakash2696 Can you please fill out the form? How does it affect CocoaLumberjack? What are you trying to do? What exactly is the problem? How does it show?
