### ISSUE TITLE
Library is not visible in ObjC when using SPM

### ISSUE THREAD

**Issue by smadsenjc** [CocoaLumberjack/CocoaLumberjack#1401]
**Checklist**
- [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
- [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation)
- [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

**Describe the bug**
If I add CocoaLumberjack as a dependency to my project using SPM, I cannot `@import` or `#import` it in an ObjC file. The compiler error is either "Module CocoaLumberjack not found" or "CocoaLumberjack.h file not found", depending on how I try to import it.

**To Reproduce**
1. Add CocoaLumberjack to a mixed Swift and Objective-C project using Swift Package Manager.
2. Add an `@import` or `#import` statement to reference CocoaLumberjack types in an Objective-C file.

**Expected behavior**
Should be able to use CocoaLumberjack Objective-C types from an Objective-C file.

**Environment info**
  Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | macOS in my case, but probably everything
 Platform Version        | 14.x
 CocoaLumberjack Version | 3.8.2
 Integration Method      | spm
 Xcode Version           | Xcode 15.1
 Repro rate              | all of the time
 Repro project link      |

**Comment by smadsenjc** [comment]
Interesting. Yours is a pure SPM project. Good to know that works.

I'm trying to do this in an `.xcodeproj`. Here is a sample that does not compile, although I get a different error in this one than my real project: 
[CL-ObjC.zip](https://github.com/CocoaLumberjack/CocoaLumberjack/files/13875472/CL-ObjC.zip)

I have a fork where I'm trying to fix it. I have it working locally, but I haven't made sure that it doesn't break CocoaPods/Cartage/other use cases. The main changes are the addition of a `module.modulemap`, naming the `publicHeadersPath` in `Package.swift*` and moving a couple of header files.

**Comment by ffried** [comment]
I'm guessing the error you're getting here is `Use of undeclared identifier 'ddLogLevel'`?

This is because the `DDLogXYZ` macros reference a `LOG_LEVEL_DEF` define (that defaults to `ddLogLevel`) as the current log level.

Adding the following line after the `@import` makes your project build for me:

`static DDLogLevel ddLogLevel = DDLogLevelAll;`

**Comment by smadsenjc** [comment]
Yes. The curse of a too-simple sample project! 😄

It's time to start comparing project settings between that sample and the real one.

**Comment by ffried** [comment]
@smadsenjc Thanks for the feedback. Good to hear that it works now.
