### ISSUE TITLE
Bump `IPHONEOS_DEPLOYMENT_TARGET` in podspec to appease Cocoapods on Xcode15

### ISSUE THREAD

**Issue by tachtevrenidis** [CocoaLumberjack/CocoaLumberjack#1404]
**Is your feature request related to a problem? Please describe.**
The problem is that in this library's podspec, IPHONEOS_DEPLOYMENT_TARGET is specified at 11.
```
"platforms": {
    "osx": "10.13",
    "ios": "11.0",
    "tvos": "11.0",
    "watchos": "4.0"
  }
```
Xcode 15 apparently has a minimum deployment target of 12 for ios. This is easy to circumvent by doing some post install rewrites in Cocoapods EXCEPT for when you want to `pod lib lint` or `pod spec lint` your own component prior to `pod repo push`.

The error Cocoapods throws is:
```
xcodebuild:  Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'CocoaLumberjack' from project 'Pods')``
```

**Describe the solution you'd like**
Change podspec to:
```
"platforms": {
    "osx": "10.13",
    "ios": "12.0",
    "tvos": "12.0",
    "watchos": "4.0"
  }
```
and publish a new version of this library.

**Describe alternatives you've considered**
I have not found any alternatives.

**Comment by ffried** [comment]
Since this breaks the minimum compatibility, we'll have to release a new minor version for this. I've just released a version that contains the new privacy manifest. Once this has settled, I'll bump the minimums for the next minor release.

**Comment by ZClee128** [comment]
meet too，Quick solution
