### ISSUE TITLE
NSGenericDeallocHandler release crash when calling registeredClasses

### ISSUE THREAD

**Issue by cweymann** [CocoaLumberjack/CocoaLumberjack#1406]
**Checklist**
- [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
- [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation)
- [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

**Describe the bug**
When we call DDLog.registeredClassNames from our app it crashes in [DDLog registeredClasses]

**To Reproduce**
1. Call DDLog.registeredClassNames

**Expected behavior**
A list of all logging classes printed to the console

**Screenshots**
-

**Environment info**
  Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 17.0.1
 CocoaLumberjack Version | 3.8.3
 Integration Method      |  cocoapods 
 Xcode Version           | 15.2.0
 Repro rate              | 100%
 Repro project link      |[example](https://github.com/cweymann/CocoaLumberjackIssue/tree/main)

**Additional context**
Stacktrace:

#0	0x00000001a50af940 in -[__NSGenericDeallocHandler release] ()
#1	0x00000001040b28a4 in +[DDLog registeredClasses] at /Users/cweymann/Lab/CocoaLumberjackIssue/Pods/CocoaLumberjack/Sources/CocoaLumberjack/DDLog.m:572
#2	0x00000001040b2948 in +[DDLog registeredClassNames] at /Users/cweymann/Lab/CocoaLumberjackIssue/Pods/CocoaLumberjack/Sources/CocoaLumberjack/DDLog.m:580
#3	0x000000010409b94c in implicit closure #2 in ViewModel.logInfo() ()
#4	0x00000001040c4128 in implicit closure #1 in DDLogInfo(_:level:context:file:function:line:tag:asynchronous:ddlog:) ()
#5	0x00000001040c3cc4 in _DDLogMessage(_:level:flag:context:file:function:line:tag:asynchronous:ddlog:) at /Users/cweymann/Lab/CocoaLumberjackIssue/Pods/CocoaLumberjack/Sources/CocoaLumberjackSwift/CocoaLumberjack.swift:325
#6	0x00000001040c40f4 in DDLogInfo(_:level:context:file:function:line:tag:asynchronous:ddlog:) at /Users/cweymann/Lab/CocoaLumberjackIssue/Pods/CocoaLumberjack/Sources/CocoaLumberjackSwift/CocoaLumberjack.swift:369
#7	0x000000010409b70c in ViewModel.logInfo() at /Users/cweymann/Lab/CocoaLumberjackIssue/CocoaLumberjackIssue/ViewModel.swift:15
#8	0x0000000104099914 in closure #1 in closure #1 in ContentView.body.getter at /Users/cweymann/Lab/CocoaLumberjackIssue/CocoaLumberjackIssue/ContentView.swift:19
#9	0x00000001aa614770 in ___lldb_unnamed_symbol236252 ()
#10	0x00000001a9bba5a4 in ___lldb_unnamed_symbol156439 ()
#11	0x00000001a9bc07c8 in ___lldb_unnamed_symbol156614 ()
#12	0x00000001a9bbe494 in ___lldb_unnamed_symbol156526 ()
#13	0x00000001a9bbe3e0 in ___lldb_unnamed_symbol156525 ()
#14	0x00000001aa263a10 in ___lldb_unnamed_symbol207845 ()
#15	0x00000001aa262d04 in ___lldb_unnamed_symbol207796 ()
#16	0x00000001aa2626d4 in ___lldb_unnamed_symbol207785 ()
#17	0x00000001a9d93624 in ___lldb_unnamed_symbol172191 ()
#18	0x00000001a9d9364c in ___lldb_unnamed_symbol172192 ()
#19	0x00000001a9d93624 in ___lldb_unnamed_symbol172191 ()
#20	0x00000001aa5feebc in ___lldb_unnamed_symbol235502 ()
#21	0x00000001aa5ff5d4 in ___lldb_unnamed_symbol235506 ()
#22	0x00000001aa7d1d98 in ___lldb_unnamed_symbol249989 ()
#23	0x00000001aa547260 in ___lldb_unnamed_symbol229555 ()
#24	0x00000001aa545774 in ___lldb_unnamed_symbol229523 ()
#25	0x00000001aa545904 in ___lldb_unnamed_symbol229529 ()
#26	0x00000001a72c19e0 in -[UIGestureRecognizer _componentsEnded:withEvent:] ()
#27	0x00000001a717bb2c in -[UITouchesEvent _sendEventToGestureRecognizer:] ()
#28	0x00000001a71781ac in -[UIGestureEnvironment _deliverEvent:toGestureRecognizers:usingBlock:] ()
#29	0x00000001a71780d8 in -[UIGestureEnvironment _updateForEvent:window:] ()
#30	0x00000001a735f62c in -[UIWindow sendEvent:] ()
#31	0x00000001a735e8bc in -[UIApplication sendEvent:] ()
#32	0x000000023bd80934 in -[UIApplicationAccessibility sendEvent:] ()
#33	0x00000001a73211f8 in __dispatchPreprocessedEventFromEventQueue ()
#34	0x00000001a731f4fc in __processEventQueue ()
#35	0x00000001a731df08 in updateCycleEntry ()
#36	0x00000001a72077e4 in _UIUpdateSequenceRun ()
#37	0x00000001a7206ed4 in schedulerStepScheduledMainSection ()
#38	0x00000001a7206f90 in runloopSourceCallback ()
#39	0x00000001a4f6912c in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ ()
#40	0x00000001a4f683a8 in __CFRunLoopDoSource0 ()
#41	0x00000001a4f66b5c in __CFRunLoopDoSources0 ()
#42	0x00000001a4f65898 in __CFRunLoopRun ()
#43	0x00000001a4f65478 in CFRunLoopRunSpecific ()
#44	0x00000001e84e64f8 in GSEventRunModal ()
#45	0x00000001a738962c in -[UIApplication _run] ()
#46	0x00000001a7388c68 in UIApplicationMain ()
#47	0x00000001a9d994b8 in ___lldb_unnamed_symbol172573 ()
#48	0x00000001a9d992fc in ___lldb_unnamed_symbol172571 ()
#49	0x00000001a9a09e90 in ___lldb_unnamed_symbol143436 ()
#50	0x000000010409bf94 in static CocoaLumberjackIssueApp.$main() ()
#51	0x000000010409c1f8 in main at /Users/cweymann/Lab/CocoaLumberjackIssue/CocoaLumberjackIssue/CocoaLumberjackIssueApp.swift:11

**Comment by ffried** [comment]
@cweymann good catch and a perfect issue description! The repro project helped a lot!!
I've fixed this in master and would release it in a new version at the end of the week (just in case some more bugs come up).

As a workaround you can revert back to 3.8.2 until then if needed.
