### ISSUE TITLE
CocoaLumberjack v3.8.3 - Privacy Manifest - Missing an expected key: 'NSPrivacyCollectedDataTypes'

### ISSUE THREAD

**Issue by mejim707** [CocoaLumberjack/CocoaLumberjack#1407]
We have updated to the latest 3.8.3 version which includes the Apple required Privacy Manifest.

However, when I run the Privacy Report against our archive using Xcode I'm receiving the below error which will likely lead to an app rejection unless it's resolved.

Can this fix be included in the upcoming release? Apple will discontinue submissions for apps in April unless all SDKs comply with this new standard.

Thanks

Error: 
Missing an expected key: 'NSPrivacyCollectedDataTypes'
CocoaLumberjack_CocoaLumberjack.bundle/PrivacyInfo.xcprivacy

**Comment by ffried** [comment]
This is already fixed in v3.8.4

**Comment by mejim707** [comment]
Thanks for the fast turn around here. As of the new 3.8.4 version the SDK no longer appears in the privacy manifest. I'm unsure if this is expected.

**Comment by ffried** [comment]
Neither am I. Haven't personally used them before. But since the SDK itself does not _track_ anything, this might be expected. Not sure if the (platform) API's we're using should show up or not.
