### ISSUE TITLE
Multiple commands produce PrivacyInfo.xcprivacy

### ISSUE THREAD

**Issue by SandroDahl** [CocoaLumberjack/CocoaLumberjack#1408]
**Describe the bug**

In version 3.8.4 there is a build error when static linking is used (without it is working fine). 

Error: Multiple commands produce '../Library/Developer/Xcode/DerivedData/example/Build/Products/Debug-iphonesimulator/example.app/PrivacyInfo.xcprivacy'

One possible solution might be to use a resource bundle.

**To Reproduce**
1. Create a privacy manifest in the app target
2. Use this Podfile configuration for pod install
```ruby
platform :ios, '17.0'

target 'example' do
  use_frameworks! :linkage => :static

  pod 'CocoaLumberjack/Swift'
end
```
3. Run a build

**Environment info**
  Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 17.0
 CocoaLumberjack Version | 3.8.4
 Integration Method      | cocoapods
 Xcode Version           | Xcode 15.2
 Repro rate              | all the time (100%)

**Comment by ffried** [comment]
We're already adding the privacy manifest as resource...

In the [script that generates the pod spec](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Scripts/generate-podspec.sh#L158), we're declaring the manifest as a resource:

```ruby
ss.resources  = 'Sources/CocoaLumberjack/PrivacyInfo.xcprivacy'
```

Not sure if this is a cocoapods bug or not.

**Comment by SandroDahl** [comment]
What I meant is [resource_bundle](https://guides.cocoapods.org/syntax/podspec.html#resource_bundles).This description refers to this type of problem. 

I saw the usage of resource_bundle e.g. in the [lottie-ios podspec](https://github.com/airbnb/lottie-ios/blob/d4b75a089ef42d7c7db094671632aa311cbe1d83/lottie-ios.podspec#L31). That's why I proposed this as a solution.

**Comment by ffried** [comment]
Ah, thanks. I have little experience with CocoaPods, but I've read through a few threads over in the Lottie repository. Seems like this should work for all cases.

**Comment by nabs-m** [comment]
Was just about to post a new issue when I saw this. We've had the same problem with another library, and the fix you pushed will indeed solve this 🙏 I'm assuming this will go in the next hotfix?

**Comment by ffried** [comment]
See [3.8.5](https://github.com/CocoaLumberjack/CocoaLumberjack/releases/tag/3.8.5).
CocoaPods Release should happen automatically in a sec.

**Comment by mlch911** [comment]
I'm using version 3.8.5 and I still got this error.

**Comment by mlch911** [comment]
After changing all the sub pod dependencies to CocoaLumberjack/Swift, the error was gone.
