### ISSUE TITLE
 Confused about DDFileLog。

### ISSUE THREAD

**Issue by Goallying** [CocoaLumberjack/CocoaLumberjack#1414]
I'm not sure if it's a bug。

I override  "shouldArchiveRecentLogFileInfo" method that I can create a log File  for Every Each Day. it works !
But when I changed the phone date to the next day, a new log file was not created, and my app was not killed in the process.

**Comment by ffried** [comment]
It's very well possible that the logic won't work when manually changing time. This isn't a use-case that we consider, given that it's usually not happening very often.
The dispatch timer we use internally probably doesn't notice the time change here.

**Comment by Goallying** [comment]
> It's very well possible that the logic won't work when manually changing time. This isn't a use-case that we consider, given that it's usually not happening very often. The dispatch timer we use internally probably doesn't notice the time change here.


If you do automated testing overnight, there will be bugs
