### ISSUE TITLE
osLogTypeForLogFlag for FAULT

### ISSUE THREAD

**Issue by xueyongwei** [CocoaLumberjack/CocoaLumberjack#1419]
**Is your feature request related to a problem? Please describe.**
`DDLogFlag` not contains `Fault`, which will display red background in xcode. In `DDOSLogger.m` file, if function `osLogTypeForLogFlag()`  return `OS_LOG_TYPE_FAULT` if `logFlag` is `DDLogFlagError` will display red background. I want to konw why didnot do this?

```
- (os_log_type_t)osLogTypeForLogFlag:(DDLogFlag)logFlag {
    switch (logFlag) {
        case DDLogFlagError:
            return OS_LOG_TYPE_FAULT;
        case DDLogFlagWarning:
            return OS_LOG_TYPE_ERROR;
        case DDLogFlagInfo:
            return OS_LOG_TYPE_INFO;
        case DDLogFlagDebug:
        case DDLogFlagVerbose:
            return OS_LOG_TYPE_DEBUG;
        default:
            return OS_LOG_TYPE_DEFAULT;
    }
}
```
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ffried** [comment]
This was discussed in #1410, specifically in [this comment](https://github.com/CocoaLumberjack/CocoaLumberjack/pull/1410/files#r1509269270).

If needed, a custom `DDOSLogLevelMapper` can be used for this,

**Comment by xueyongwei** [comment]
I see,thank you!
