### ISSUE TITLE
File logger stops logging after rolling or creating new file

### ISSUE THREAD

**Issue by felislynx-silae** [CocoaLumberjack/CocoaLumberjack#1423]
**Checklist**
- [X] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
- [X] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation)
- [X] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

**Describe the bug**
1. Create logger:
let fileLogger = DDFileLogger()
fileLogger.rollingFrequency = 60 * 60 * 24
fileLogger.logFileManager.maximumNumberOfLogFiles = 20
ddLog.add(fileLogger)
2. Make app work
3. After some time invoke logger.retrieveLatest(upToNumLines: 50) and verify they are up to date

**Expected behavior**

**Environment info**
  Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 17.5.1
 CocoaLumberjack Version | 3.8.5
 Integration Method      | spm
 Xcode Version           | Xcode 15.4
 Repro rate              | sometimes 70% rate, conditions must be met

**Additional context**
```
CurrentFile: Optional({
    age = "0.00876772403717041";
    creationDate = "2024-06-21 08:45:36 +0000";
    fileAttributes =     {
        NSFileCreationDate = "2024-06-21 08:45:36 +0000";
        NSFileExtensionHidden = 0;
        NSFileGroupOwnerAccountID = 501;
        NSFileGroupOwnerAccountName = mobile;
        NSFileModificationDate = "2024-06-21 08:45:36 +0000";
        NSFileOwnerAccountID = 501;
        NSFileOwnerAccountName = mobile;
        NSFilePosixPermissions = 420;
        NSFileProtectionKey = NSFileProtectionCompleteUnlessOpen;
        NSFileReferenceCount = 1;
        NSFileSize = 0;
        NSFileSystemFileNumber = 39036822;
        NSFileSystemNumber = 16777220;
        NSFileType = NSFileTypeRegular;
    };
    fileName = "com.myapp 2024-06-21--08-45-36-279.log";
    filePath = "/var/mobile/Containers/Data/Application/FB843CD7-DAA5-4AB8-BFAA-F251A8EA1622/Library/Caches/Logs/com.myapp 2024-06-21--08-45-36-279.log";
    fileSize = 0;
    isArchived = 0;
    modificationDate = "2024-06-21 08:45:36 +0000";
})
```
I see new file is created, it is empty so no logs are written there.
If i manually write something to it, logger.retrieveLatest will return this test. So from my perspective it looks like logger is not writing logs if file is rolled or new one is created.

**Comment by ffried** [comment]
Not sure if it's related, but `retrieveLatest(upToNumLines: 50)` is not a function offered by `DDFileLogger`. Is this simply an _extension_ on your side, or are you using a subclass by any chance?

**Comment by felislynx-silae** [comment]
@ffried ok, this is oversimplification from my side, sorry. If i iterate through files in app cache and just read content, it is the same as i wrote in bugreport.

**Comment by ffried** [comment]
@felislynx-silae I can't really reproduce this issue. If you can create a small project that reproduces this issue and attach it here, that would help a lot.

What happens internally is that we set the current log file handle ivar to `nil`. It will then automatically be re-recreated (using the `lt_currentLogFileHandle` accessor) the next time a message is logged.

I've even just added another test case (which succeeds) for testing this scenario: https://github.com/CocoaLumberjack/CocoaLumberjack/commit/9e93f68f1b030f21d6a1ae4f8cf3fa8f3182db8a
