### ISSUE TITLE
Capturing system log messages inline with DDLog messages

### ISSUE THREAD

**Issue by adamgit** [CocoaLumberjack/CocoaLumberjack#168]
Sometimes, you need more than the app's messages. For instance, we have a bug in a 3rdparty hardware accessory for iPhone which is crashing the OS (!) with a kernel panic.

(NB: a side-effect of this is that iOS wipes the system logs, when it reboots)

Lumberjack is great for capturing the logs to a large file in parallel, so that we can still read them even after a reboot. This is good.

However, we need to capture the OS messages leading up to the kernel panic (from what I've seen, I suspect an Apple daemon probably spews something _very helpful_ just before the crash)

Pre-Lumberjack, I'd do pipes of stderr and stdout, at the process-level, into memory, and then save those messages out to file. With LJ, I'm not sure how to do this - it's not mentioned in the FAQs, but it seems a pretty important thing?

Obviously, I don't want to re-write the entirtey of log-rotation, management, etc. And if I did, it would be unhelpful to have two streams of logfiles. I'd like to get stderr/out redirected into the same stream DDLog is outputing.

Is this possible today? If so, what do I need to do?

If not ... please make this a feature request ;).

**Comment by hyling** [comment]
I think this is still useful for capturing logs from libraries I'm using that don't use CocoaLumberjack.  This this feature ever get added?

**Comment by hyling** [comment]
The way the ASL works if you have to poll it and get all messages that occurred between time X and Y.  Does CocoaLumberjack add a timestamp to all entries so I can insert the messages at the correct place in the CocoaLumberjack stream?

**Comment by rivera-ernesto** [comment]
I think it does. You should give it a try to be sure.

**Comment by hyling** [comment]
I'm not familiar with the CocoaLumberjack codebase, hints as to here to look to insert into the stream?

**Comment by rivera-ernesto** [comment]
Check `DDLogMessage` properties. I think there is a `timestamp`. Then check where it is set.

**Comment by learnopengles** [comment]
I'm noticing something odd; when I try to redirect stderr, Cocoa Lumberjack is somehow adding all of the stderr messages to its own logs automatically. This is what I wanted, but I'm not sure what's going on here.

Here's how i'm able to reproduce:

1) Add instance of ASLLogger:

DDLog.add(DDASLLogger.sharedInstance)

2) Redirect stderr somewhere:

freopen(logFile.path.cString(using: .ascii), "a+", stderr)

Any idea why ASLLogger is capturing stderr, and if there'd be a way to do this without having to do the manual redirect (and having to manage the file myself)?

**Comment by ffried** [comment]
As of iOS 10 with os_log it's no longer possible for ASLLogger to capture system logs (see #791). Closing with [this comment](https://github.com/CocoaLumberjack/CocoaLumberjack/issues/791#issuecomment-430153144).
