### ISSUE TITLE
Lumberjack 2.x.x discussion

### ISSUE THREAD

**Issue by bpoplauschi** [CocoaLumberjack/CocoaLumberjack#225]
#### Testing

`pod 'CocoaLumberjack', '~> 2.0.0-rc2'`

#### New organization

- [x] `DDLog.h`/`DDLog.m`: Only Objective-C classes with ~~no~~ core macros. Anyone can create their own log library on top of it.
- [x] New `CocoaLumberjack.h`: Convenience macros, default log levels, etc. Most users will only know about this file. Macros use objects defined above.
- [x] New `CocoaLumberjack.swift`: Swift versions of the macros (Related to #299, #358, #338,  http://thehustudio.com/taste-of-ios-bridging-cocoalumberjack-for-swift/).

#### Required for 2.0.0 release

- [ ] Revamp log levels handling.

#### Potential features for 2.1.x

- [ ] dynamic log levels
- [ ] modules
- [ ] log level depth: app level, user level, module level, file level (in case someone needs multiple files), logger level
For those, we could have some config files (i.e. plist) where the developer set which files go under a certain module, the log level for the app/user/module/file/logger, ...
- [ ] ability to hook to the NSLogger OSX desktop viewer (or do our own variant)
- [ ] log images or other BLOB ?
- [ ] see bpoplauschi/BusghotKit, with a few changes I integrated this nice library with Lumberjack
- [ ] #88 Coalesce repeating log messages
- [ ] avoid queue overrun by large number of messages -> throttle
- ...

#### Coding style

- [x] make it easy to subclass the standard loggers
- [x] ~~use properties instead of directly referencing ivars (see performance).~~ Anyway, we need to rename ivars from ```variable``` to ```_variable```. UPDATE: for now, we will not switch to properties as the performance impact is not something we can easily check. Just making sure the ivars have the _ prefix
- [x] ~~each entity should be in a dedicated file (i.e. DDLogMessage, DDLogger, DDLogFormatter, DDAbstractLogger) - easier to track changes and to read the code~~ UPDATE: increadibly hard to achieve, leaving those "nested" classes and protocols as they are
- [x] replace C functions with methods, where possible
- [x] replace defines with consts (compiler can do type checking)
- [x] I would suggest we switch to the default Obj-C style: opening bracket on the same line (i.e. ```if (something) {``` or ```+ (void)initialize {``` )
- [x] ~~might want to rename private methods from ```method``` to ```_method```~~
- [x] singletons implemented properly using dispatch_once

#### Unit testing
- [ ] we need a strong set of unit tests for start, that validate the framework's main capabilities.

#### Inspiration
- [NSLogger](https://github.com/fpillet/NSLogger)
- [NBULog] (https://github.com/CyberAgent/iOS-NBULog)
- [LumberjackConsole] (https://github.com/PTEz/LumberjackConsole)

#### Revisit and update benchmarks
- [ ] we could try to do the benchmarks in a separate tests target instead of multiple projects that have to be maintained

#### New disk structure
@rivera-ernesto proposed something like:
- [x] `/Lumberjack` -> `/Classes` for library source files.
- [x] `/Xcode/LumberjackFramework` -> `/Framework` for static frameworks and their supporting files.
- [x] `/Xcode` -> `/Demos` for all the other projects.

**Comment by rivera-ernesto** [comment]
Closing this for no longer being relevant.
