### ISSUE TITLE
Crashing in +[DDLog isRegisteredClass] in ARC+Simulator

### ISSUE THREAD

**Issue by samkrishna** [CocoaLumberjack/CocoaLumberjack#24]
Hi,

It _SEEMS_ like the method +[DDLog isRegisteredClass] will crash a project when using it with ARC + Simulator.

Environment:
Lion 10.7.3
iOS 5 SDK
Xcode 4.2.1
iPhone 5.0 Simulator

Currently, the method contains a macro #if check that reads:
# if TARGET_OS_IPHONE (near line 307)

For running in the Simulator, it needs to read:
# if TARGET_OS_IPHONE && !TARGET_IPHONE_SIMULATOR

such that the non-iOS code gets executed.

If the code is allowed to stand, it will trip up on the following classes:

"**ARCLite**"
"__NSGenericDeallocHandler"
"_NSZombie_"
"Object"
"__IncompleteProtocol"
"NSLeafProxy"
"Protocol"
"NSMessageBuilder"

which will throw a does not implement "-methodSignatureForSelector" exception on NSInvocation.

Thanks.

**Comment by cmdrsabre** [comment]
With iOS 17 the non-IOS code in the Simulator part does have some weird issues!
UserDefaults stop working!
But with iOS 17, the normal iOS Code just works fine, even in the simulator.

So the current version does not work on iOS 17 simulators (or at least UserDefaults do not work after calling)
