### ISSUE TITLE
Absorbing third party NSLog statements

### ISSUE THREAD

**Issue by DarioAhdoot** [CocoaLumberjack/CocoaLumberjack#241]
Is there a way for NSLog statements generated by Cocoa libraries (and third party libraries for which we have no control over) to be absorbed by Lumberjack? Most specifically, we'd like those to be included in the FileLogger, since the file logger will miss out on important log statements.

**Comment by azinman** [comment]
It's not evident anywhere easily, but for future people finding this (which is #1 on google for me) this feature is now a part of CocoaLumberjack via the DDASLLogCapture class:

https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Classes/DDASLLogCapture.h

Pretty much all you have to do is:
[DDASLLogCapture start];
