### ISSUE TITLE
Issue in Rolling Frequency.

### ISSUE THREAD

**Issue by Anantvijay** [CocoaLumberjack/CocoaLumberjack#243]
I have integrated the framework and followed the very same steps that was provided in the gitHub home page. i wrote the code as follows:

DDFileLogger _fileLogger = [[DDFileLogger alloc] init];
[fileLogger setRollingFrequency:60_60];
[fileLogger.logFileManager setMaximumNumberOfLogFiles:7];
[fileLogger setMaximumFileSize:3145728];
[DDLog addLogger:fileLogger];
[DDLog addLogger:[DDTTYLogger sharedInstance]];

But the rolling feature doesnt seems to be working. It is still appending logs to the same file even after it crossed an hour's time.
    DDLogVerbose(@"%@",[fileLogger.logFileManager logsDirectory]);

**Comment by kimieno** [comment]
I'm still having this issue.
I'm using CocoaLumberjack/Swift 3.5.1.

```
let fileLogger: DDFileLogger = DDFileLogger() // File Logger
fileLogger.rollingFrequency = 60 * 60 * 24 // 24 hours
fileLogger.logFileManager.maximumNumberOfLogFiles = 7
fileLogger.maximumFileSize = 1024 * 1024 // 1 Mega bytes

#if DEBUG
DDLog.add(DDOSLogger.sharedInstance, with: .verbose)
DDLog.add(fileLogger, with: .verbose)
#else
DDLog.add(DDOSLogger.sharedInstance, with: .info)
DDLog.add(fileLogger, with: .info)
#endif
```

**Comment by KimiChiu** [comment]
I'm still having this issue.
I'm using CocoaLumberjack/Swift 3.5.1.

let fileLogger: DDFileLogger = DDFileLogger() // File Logger
fileLogger.rollingFrequency = 60 * 60 * 24 // 24 hours
fileLogger.logFileManager.maximumNumberOfLogFiles = 7
fileLogger.maximumFileSize = 1024 * 1024 // 1 Mega bytes

#if DEBUG
DDLog.add(DDOSLogger.sharedInstance, with: .verbose)
DDLog.add(fileLogger, with: .verbose)
#else
DDLog.add(DDOSLogger.sharedInstance, with: .info)
DDLog.add(fileLogger, with: .info)
#endif
