### ISSUE TITLE
Color for Xcode and AppCode together?

### ISSUE THREAD

**Issue by x2on** [CocoaLumberjack/CocoaLumberjack#283]
Hi,

is there a possibility to activate color support for Xcode and AppCode?

If i add the `XcodeColors` env variable and the `TERM=color` env variable it works in appcode, but not in Xcode.
If i remove the `TERM=color` it works in Xcode, but then not in AppCode.

Any ideas?

**Comment by x2on** [comment]
@bpoplauschi sorry for late response: If i copy the schemes i have to do it on 20 schemes in this project and then i have 20 more schemes to maintenance... would be nice if we could solve this directly in this project.

**Comment by jasonpeterson** [comment]
If anyone figures this out, I'd love to know.  I use AppCode and my co-worker uses Xcode.  Thanks :)

**Comment by hashier** [comment]
@x2on What's your workaround for now?

**Comment by bpoplauschi** [comment]
Any updates here? Does the problem still exist?

**Comment by rivera-ernesto** [comment]
Closing this for now. Feel free to update/reopen.

**Comment by hashier** [comment]
It's still a problem

**Comment by bpoplauschi** [comment]
@hashier could you help us fix this? I mean with a PR. I don't use AppCode so I can't debug this issue.

**Comment by hashier** [comment]
I don't know how to fix it unfortunately but I have a slight hunch that it actually needs some fixing inside AppCode?

**Comment by rivera-ernesto** [comment]
The thing is that we try to keep track of "active" issues to avoid having hundreds of open issues that get no attention just for the fact of being open.

I think this issue in particular can be closed and will still show up when someone searches for AppCode support for instance.
