### ISSUE TITLE
Thread Id print mismatch between NSLog and DDTTYLogger

### ISSUE THREAD

**Issue by maximveksler** [CocoaLumberjack/CocoaLumberjack#311]
I’m just began playing with CocoaLumberjack git master, running on Xcode 6 Beta 3, iOS8, iPhone 5s. It seems that Lumberjack and NSLog can’t agree on the mach port thread id.

    - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:    (NSDictionary *)launchOptions {
        
        [DDLog addLogger:[DDTTYLogger sharedInstance]];
        
        DDLogInfo(@"App loaded");
        NSLog(@"App loaded");
        
        return YES;
    }

This outputs:

    2014-07-20 02:32:17:085 Festival[931:807] App loaded
    2014-07-20 02:32:17.086 Festival[931:224090] App loaded

I would expect same value for both, probably the one NSLog prints, in this case `224090`

Not sure if this is a bug or a feature request, looking at the source code I do see that DDTTYLogger forces the machThreadID to be chopped at 8 characters.

**Comment by ahknight** [comment]
Nope.  It's this (iOS 8 changed which thread ID it used in NSLog): http://stackoverflow.com/a/8995737/108928

**Comment by rivera-ernesto** [comment]
Could you try to make a pull request?

**Comment by bpoplauschi** [comment]
Fixed by #514
