### ISSUE TITLE
Uniform SDK, system version and available frameworks checks.

### ISSUE THREAD

**Issue by rivera-ernesto** [CocoaLumberjack/CocoaLumberjack#324]
We have a big mess on the way we check for these things and we should uniform and keep only the best and recommended way to check for these things.

Feel free to comment or edit this description directly.

Concretely we need to adopt the best way to:

### Check the platform

a. `#ifdef TARGET_OS_MAC`
b. `#ifdef TARGET_OS_IPHONE`
c. `#if defined(TARGET_OS_IPHONE) || defined(TARGET_IPHONE_SIMULATOR)`

### Check the build time SDK version

a. `#ifdef __IPHONE_8_0`/`__MAC_10_10`
b. `#if __IPHONE_OS_VERSION_MIN_REQUIRED >= 60000`/`#if MAC_OS_X_VERSION_MIN_REQUIRED >= MAC_OS_X_VERSION_10_9`
c. `#if MACOSX_DEPLOYMENT_TARGET < __MAC_10_10 || IOS_DEPLOYMENT_TARGET < __IPHONE_7_0`
### Check the runtime system version

a. `[[[UIDevice currentDevice] systemVersion] floatValue] >= 7.0`
b. `#define SYSTEM_VERSION_GREATER_THAN_OR_EQUAL_TO(v)  ([[[UIDevice currentDevice] systemVersion] compare:v options:NSNumericSearch] != NSOrderedAscending)`
c. `floor(NSFoundationVersionNumber) > NSFoundationVersionNumber_iOS_6_1`

OS X?

### Check if AppKit is available (for CLI tools)

a. `#ifdef NSAppKitVersionNumber10_0`
b. `respondsToSelector:`?
c. `__has_import(<AppKit/NSColor.h>)`

### Check if defined vs check value

a. Prefer `#ifdef VALUE`
b. Prefer directly `#if VALUE`
c. Use both `#if defined(VALUE) && VALUE` as it may be defined but set to `0` (never the case?).

### Other check used in CocoaLumberjack that hopefully won't be longer needed

a. `#ifdef MAC_OS_X_VERSION_10_9`
b. `[NSTimer instancesRespondToSelector:@selector(tolerance)]`
c. `#if !OS_OBJECT_USE_OBJC`
d. `#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 50000`

**Comment by bpoplauschi** [comment]
I think we solved those issues and the issue can be closed.
