### ISSUE TITLE
2.0.0 release

### ISSUE THREAD

**Issue by rivera-ernesto** [CocoaLumberjack/CocoaLumberjack#329]
After #269 I was thinking that maybe we should release 2.0.0 as it is. It is as stable as 1.9.x and all it requires is some more documentation about the `#import` updates to do in apps and libraries.

Then I realized that for the first release we should focus in the non-backward compatible changes that we would like to make to the library but couldn't in 1.9.x releases.

For me the biggest is the log level handling:

* Requiring apps to create an arbitrary named variable just to start using CocoaLumberjack is clumsy.
* Third party libraries have no guideline on how to set their own log levels, how to avoid interfering with the apps level and how to let users adjust the levels.

Possible solutions:

##### 1. NBULog-like [dynamic log levels](https://github.com/CyberAgent/iOS-NBULog#dynamic-log-levels) 

While good and working it still requires [defining not conflicting context values and registering](https://github.com/CyberAgent/iOS-NBULog#2-register-a-log-context-and-optional-modules). A more automated way of doing it would be great.

##### 2. [slf4j](http://www.slf4j.org)-like

Abstract the underlying log framework and fallback to `NSLog` or none otherwise.

##### 2. Other?

Related to #225 discussions.

**Comment by bpoplauschi** [comment]
@rivera-ernesto about the items you raised in this issue's header:
> Requiring apps to create an arbitrary named variable just to start using CocoaLumberjack is clumsy.

I created #473, please look at this approach and let me know what you think. I think it's enough, as it would only affect people that don't set `ddLogLevel`.

> Third party libraries have no guideline on how to set their own log levels, how to avoid interfering with the apps level and how to let users adjust the levels.

I really think your initial work in [SL4C](https://github.com/SLF4C/SLF4C) is a great way to handle that.

**Comment by rivera-ernesto** [comment]
I think we're good for a 2.0.0 release. I'm pretty sure that with lots of people upgrading we'll quickly get any fix we may need. for 2.0.1, etc.
