### ISSUE TITLE
Implicit declaration of function 'DDLogError' is invalid in C99

### ISSUE THREAD

**Issue by dpbataller** [CocoaLumberjack/CocoaLumberjack#331]
Hi! I'm trying to use this amazing framework but I'm getting some errors, how can I solve it?I

![screen shot 2014-08-28 at 20 48 20](https://cloud.githubusercontent.com/assets/1285920/4081041/13892644-2ee4-11e4-9ffe-f27e7b140ade.png)

**Comment by ccallawa** [comment]
I got this problem when I followed the "GettingStarted.md" file in the Documentation.  You might want to update it.

**Comment by bpoplauschi** [comment]
The documentation is updated

**Comment by rivera-ernesto** [comment]
Also feel free to make pull request for documentation files.

**Comment by ssourabh** [comment]
Importing `"CocoaLumberjack.h"` worked for me
