### ISSUE TITLE
Use of undeclared identifier 'ddLogLevel' (version 1.92)

### ISSUE THREAD

**Issue by eremzeit** [CocoaLumberjack/CocoaLumberjack#332]
I've included the `DDLog.h` header into my project, but when I go to use any of the logging macros (ie. `DDLogError`) I get the error `Use of undeclared identifier 'ddLogLevel`.  This happens in 1.92.

**Comment by TaoistKing** [comment]
How to fix this???  I tried put these line into my pch file, but still got errors.

#define DDLogLevelInfo ddLogLevel
#import <CocoaLumberjack/CocoaLumberjack.h>

IS this correct?
