### ISSUE TITLE
Fishy behavior using file logger - stops logging after clearing

### ISSUE THREAD

**Issue by iamcam** [CocoaLumberjack/CocoaLumberjack#335]
I'm using two separate file loggers for the purpose of a detailed, debug-level logging and a truncated version for easier on-device diagnostics.
The full debug-level log uses an out-of-box file logging experience. This is the one that seems to be exhibiting issues. When I clear the log files (I've tried both deletion and rewriting with empty NSData), the logger is unable to write to the file until the application is restarted.

The setup:

``` obj-c
 DDFileLogger *fileLogger = [[DDFileLogger alloc] init];
    fileLogger.logFormatter = [[HPDDLogFormatter alloc] init];
    fileLogger.rollingFrequency = 60 * 60 * 24 * 7;
    fileLogger.logFileManager.maximumNumberOfLogFiles = 1;
    self.fileLogger = fileLogger;
    [DDLog addLogger:self.fileLogger withLogLevel:ddLogLevel];
```

The clear:

``` obj-c
    NSArray *paths = [self.appDelegate.fileLogger.logFileManager unsortedLogFileInfos];
    for( DDLogFileInfo *logFileInfo in paths ){
        [[NSFileManager defaultManager] removeItemAtPath:logFileInfo.filePath error:nil];
        [logFileInfo reset];
        DDLogInfo(@"Deleting log file: %@", logFileInfo.filePath);
    }
```

I'm not sure why this doesn't work - there aren't any logs .
_[edit]_ Typically I see this after running my -clearLogs method twice in a row. The first time sometimes logging is still there if logged at the time of deletion. The second time is usually good to destroy the files completely. Either way, the truncated log repopulates just fine.

---

Performing a custom configuration seems to be immune to the above-stated problems:

``` obj-c
 // Configure separate trunctaed log file location
    NSArray *paths = NSSearchPathForDirectoriesInDomains(NSCachesDirectory, NSUserDomainMask, YES);
    NSString *baseDir = ([paths count] > 0) ? [paths objectAtIndex:0] : nil;
    NSString *specialLogsDirectory = [baseDir stringByAppendingPathComponent:@"TruncatedLogs"];
    DDLogFileManagerDefault *specialLogFileManager = [[DDLogFileManagerDefault alloc] initWithLogsDirectory:specialLogsDirectory];

    // This is for truncated logging to file. See Live Link-Prefix.pch
    DDFileLogger *specialFileLogger = [[DDFileLogger alloc] initWithLogFileManager:specialLogFileManager];
    specialFileLogger.logFormatter = [[HPDDTruncatedLogFormatter alloc] init];
    specialFileLogger.rollingFrequency = 60 * 60 * 24 * 7; // 24 hour rolling
    specialFileLogger.logFileManager.maximumNumberOfLogFiles = 1;
    specialFileLogger.maximumFileSize = 1024.0f * 256.0f; // 256k max special log size
    self.specialFileLogger = specialFileLogger;
    [DDLog addLogger:self.specialFileLogger withLogLevel:LOG_FLAG_ERROR];
```

...logging behaves as expected after the log files are deleted.

Any ideas? Am I doing something wrong?

**Comment by bpoplauschi** [comment]
Guys, could someone patch this up?

**Comment by watershade-apps** [comment]
@dvor That was so helpful. I would like to clarify to others that it worked perfectly. will testing I let tester to send me log file using MFMailComposeViewController. then I cleared the log file using the code snippet you provided.

**Comment by Autoc0diq** [comment]
We're experiencing the same issue on iOS 8. We follow the solution dvor suggested with rolling files. Our app runs in the background. However we don't delete the files, we move them into a separate folder for upload. Somehow after a while, the logger stops writing to the file system and we have no idea why.

**Comment by andmix** [comment]
how to get the rolled file,guys? I want to get the rolled file's content for uploading

**Comment by rivera-ernesto** [comment]
I think we need more maintainers for the file logger which is the part with more issues right now.

**Comment by dgutzeit** [comment]
Was there any progress on this issue ? We see similar behaviour when file is supposed to be rolled at the background.

**Comment by bengotow** [comment]
Hey folks - ran into this today and was originally trying to roll the log file and then delete the old one. That only works the first time (maybe because something deeper down is designed to ensure it's not needlessly rolling files?) I tried truncating the files using the code below and it's working fine even after many repeated rounds of log + truncate + log + truncate:

```
        appDelegate.fileLogger.logFileManager.unsortedLogFilePaths.forEach { (path) in
            FileHandle.init(forWritingAtPath: path)?.truncateFile(atOffset: 0)
        }
```

**Comment by ffried** [comment]
Is this still an issue? There were some changes to DDFileLogger, maybe one of them fixed it?
