### ISSUE TITLE
Lumberjack logs from 3rd party framework not showing up

### ISSUE THREAD

**Issue by alexandre-normand** [CocoaLumberjack/CocoaLumberjack#337]
I'm sorry to create an issue to ask a question that will most likely result in a confirmation that I overlooked a basic thing.

I have a [framework](https://github.com/alexandre-normand/bloodSheltie) that I built myself that now uses CocoaLumberjack to log its output. It works fine from within the framework itself (there's a [command-line usage example](https://github.com/alexandre-normand/bloodSheltie/blob/master/bloodSheltie-example/main.m#L10) that adds the TTY and ASL loggers. 

However, when trying to integrate with my app (which I'm also writing), I get my app's Lumberjack logs but I don't get any of the logs written by the framework. My initialization of the logger is done during the `awakeFromNib` and before any logs are written by the framework code. The debug/release config shouldn't be an issue I think since I pretty much hardcoded `static const int ddLogLevel = LOG_LEVEL_VERBOSE;` in the framework for now. 

For reference, my logger initialization in my app looks something like this:

```
    [DDLog addLogger:[DDASLLogger sharedInstance] withLogLevel:LOG_LEVEL_VERBOSE];
    [DDLog addLogger:[DDTTYLogger sharedInstance] withLogLevel:LOG_LEVEL_VERBOSE];

    DDLogFileManagerDefault *logFileManager =
            [[DDLogFileManagerDefault alloc] initWithLogsDirectory:[self pathForFilename:@"Logs"]];
    DDFileLogger *fileLogger = [[DDFileLogger alloc] initWithLogFileManager:logFileManager];
    fileLogger.rollingFrequency = 60 * 60 * 24;
    fileLogger.maximumFileSize = 3000000;
    fileLogger.logFileManager.maximumNumberOfLogFiles = 7;

    [DDLog addLogger:fileLogger withLogLevel:LOG_LEVEL_VERBOSE];
```

Note that this is my first experience with Cocoa/objective-C and it's been years since I've dealt with pre-processors. I think I looked at the basics but I must have missed something. 

Any ideas?

**Comment by rivera-ernesto** [comment]
I think this issue is becoming more and more important as we make new releases and 3rd party frameworks keep *requiring* certain Lumberjack versions which conflict among them.

We really need a façade and fallback to `NSLog` when the user chooses not to use a logging framework.

Should we pay some attention to https://github.com/SLF4C/SLF4C/issues/1?

**Comment by weissazool** [comment]
I'm working on apps that incorporate a number of internal frameworks, and managing logging levels separately for each individual framework is becoming a greater and greater challenge. It seems like a logging façade is the way forward.

In fact, there seems to be an [SLF4Swift](https://github.com/phimage/SLF4Swift) that can use CocoaLumberjack as a back-end, but I'm still primarily working in Objective-C. 

What needs to be done to move SLF4C forward?

**Comment by rivera-ernesto** [comment]
I think it was already working. What is needed is some more testing and then the hardest part, make frameworks adopt it.

**Comment by weissazool** [comment]
Great! Is there an example or a demo of it being integrated somewhere?

**Comment by rivera-ernesto** [comment]
I think it is yet to be done and added to the repository ;)

**Comment by bpoplauschi** [comment]
Not sure what to do here. @rivera-ernesto any ideas what actions to take?
