### ISSUE TITLE
EXC_BAD_ACCESS when DDTTYLogger's -logMessage: is getting called

### ISSUE THREAD

**Issue by jtoly** [CocoaLumberjack/CocoaLumberjack#340]
NSString *logMsg = logMessage->logMsg;

Debugger is saying logMessage is nil.  I believe the object sending a message to DDLog is going away, and so the string object being passed along is going away as well. (I believe this because I do not call DDLog with nil parameters ;-) and in doing some test coding, I can reduce the frequency of the crash by testing for nil inside the -logMessage: method straight away).

Am I supposed to code the call to, for instance, DDLogVerbose(@"this is a test"); differently, like some block execution where the parameters are either retained or passed by value into the block?

**Comment by rivera-ernesto** [comment]
Please feel free to reopen this if the issue persists.
