### ISSUE TITLE
CocoaLumberjack doesn't showing up

### ISSUE THREAD

**Issue by DamianSheldon** [CocoaLumberjack/CocoaLumberjack#342]
I following Get Start and a quick refresher in CocoaLumberjack.h set up project, but it doesn't showing up. Is there anything I have missed?

**Comment by DanSkeel** [comment]
I think about configuring DDLog in main.m, is that a bad idea? @DamianSheldon

**Comment by DamianSheldon** [comment]
I recommend you to configure DDLog in application:didFinishLaunchingWithOptions:,Apple reduce the main function to minimum, so I think application:didFinishLaunchingWithOptions: will be a better place.
