### ISSUE TITLE
Swift Compatibility Status

### ISSUE THREAD

**Issue by rivera-ernesto** [CocoaLumberjack/CocoaLumberjack#383]
Following #299, #338, #358 and more broadly 2.x.x discussion in #225.

- [x] CocoaLumberjack.swift and CocoaLumberjackSwift framework wrappers (#362, #382).

Ideally users would install the Objective-C CocoaLumberjack library though CocoaPods, then either manually add CocoaLumberjack.swift, link CocoaLumberjackSwift?? Until there is official CocoaPods support for Swift.

To do:

- [x] Fix iOSSwift demo project.
- [x] Add Travis build steps for Swift code. iOS 8 SDK is already supported by Travis, OS X 10.10 SDK not yet.
- [x] Merge mobile and desktop frameworks/static libraries. iOS now supports frameworks as well so we could probably move to a single framework or at least single project.
- [x] Move framework/static libraries demo projects out to the Demos directory.

**Comment by mackuba** [comment]
What version/branch/tag should I use at the moment to get Swift support?

**Comment by MaddTheSane** [comment]
For Xcode 6.3 and Swift 1.2, the [swift_support](https://github.com/CocoaLumberjack/CocoaLumberjack/tree/swift_support) branch will compile.

**Comment by guidomb** [comment]
I think that merging #466 will help using Cocoalumberjack in several Swift project / libraries.

**Comment by rivera-ernesto** [comment]
I would like to but I was waiting for an answer from the contributor. If you want you can contribute to that pull request too so we can merge it.
