### ISSUE TITLE
Please change the type of `logContext` from `int` to `NSUInteger`

### ISSUE THREAD

**Issue by xareelee** [CocoaLumberjack/CocoaLumberjack#390]
I found that the DDLog takes a `logContext` parameter to create a corresponding `DDLogMessage` which could be used for filtering logs (black list or white list), though the default DDLog macros only pass a value of `0` to DDLog. I think it's a powerful feature to filter log messages at runtime.

Could you please change the type of `logContext` from `int` to `NSUInteger`? I want to use an object address as the `logContext`. But the size of address (`uintptr_t`) is 8 bytes on 64-bit OS and 4 bytes on 32-bit OS while the size of `int` is always 4 bytes on both architectures.

I think it's a good idea to use object addresses to indicate the log context. Doesn't it?

**Comment by bpoplauschi** [comment]
Fixed by #419
