### ISSUE TITLE
Exclude branches in macros from coverage reporting

### ISSUE THREAD

**Issue by Ashton-W** [CocoaLumberjack/CocoaLumberjack#396]
Tools like **LCOV** report log statements as if-branches that are not executed when the log level is too low. This makes sense, however it is not useful to include in the report. 

``` objc
#define LOG_MAYBE(async, lvl, flg, ctx, fnct, frmt, ...) \
        do { if(lvl & flg) LOG_MACRO(async, lvl, flg, ctx, nil, fnct, frmt, ##__VA_ARGS__); } while(0)
```

There are markers that can be added to inform coverage exclusion: `LCOV_EXCL_LINE` for example.

Adding a marker to the `LOG_MAYBE` macro should be the only needed change:

``` objc
#define LOG_MAYBE(async, lvl, flg, ctx, fnct, frmt, ...) \
        do { if(lvl & flg) LOG_MACRO(async, lvl, flg, ctx, nil, fnct, frmt, ##__VA_ARGS__); } while(0) /* LCOV_EXCL_LINE */
```

**Comment by bpoplauschi** [comment]
@Ashton-W any updates with the PR?

**Comment by Ashton-W** [comment]
Embarrassing, must have been a long week. I'll dig up my experiments and get back to you - calendar reminder activated ⏰

**Comment by Ashton-W** [comment]
#398 looks related in that it too might be solved by adding annotations to the logging macros.

I'm creating a simple test bed using the latest release of CocoaLumberjack, generating reports with *gcovr*. I'll duplicate these tests with a modified set of log macros.

**Comment by Ashton-W** [comment]
I've put a repo here [Ashton-W/LumberjackCoverage](https://github.com/Ashton-W/LumberjackCoverage) with a sample project. Run `coverage.sh` to generate the reports - where you will see the poor branch coverage.

**Comment by rivera-ernesto** [comment]
I think those files could be included in the main repository and any coverage exclusion code as well.

**Comment by Ashton-W** [comment]
@rivera-ernesto I don't intend for this to be included in the main repository as is. We'll need to figure out how to deal with the dependency on [GCOVR](http://gcovr.com/), and how to integrate tests for this.

I've also got a problem adding the LCOV exclusion markers - they are added as comments like:

```objc
- (void)foo {
  // LCOV_EXCL_START
  
  // LCOV_EXCL_STOP
}
```

but `DDLog*` are macros and macros strip all comments - so they don't work there, they would work in a C function, however that is a big change.

**Comment by bpoplauschi** [comment]
Not sure how to continue on this matter. Closing for now as it's stale
