### ISSUE TITLE
OCLint Cyclomatic Complexity and CocoaLumberjack

### ISSUE THREAD

**Issue by jimrutherford** [CocoaLumberjack/CocoaLumberjack#398]
Hello,

A little background first: My client runs all my code through OCLint.  They do this with all their vendors to ensure their coding standards are being adhered to.  All vendors are given a score based on OCLint results and future work depends on having better scores than other vendors.  It is a very good client so I take their OCLint requirement very seriously.

I've started a new and rather large project for them and I want to offer a more robust logging system that what we've used in the past for this particular client.  I've always loved CocoaLumberjack and it fits the bill perfectly.

However, we have noticed that using the DDLogXXXXX macros increases the Cyclomatic Complexity scores in many of the places where we are using logging.  The complexity threshold is being exceeded and is causing OCLint to report warnings.  As Cyclomatic Complexity is a level 2 OCLint warning, our client scores that quite high.

I'm interested if anyone has come up with a workaround or has a reasonable solution to dealing with this.  I've fixed this with my own set of macros/methods but that solution does not feel right.

Thanks for any input!

**Comment by Ashton-W** [comment]
I'm interested in seeing what you have done @jimrutherford. We might need to add something users can `#define` to put lint/coverage markers on the DDLog macros - or provide a standard set.

**Comment by bpoplauschi** [comment]
Closing per lack of activity.
