### ISSUE TITLE
in this case:service automatically wakes up my app, logging system does't work sometimes

### ISSUE THREAD

**Issue by niushuiniu1999** [CocoaLumberjack/CocoaLumberjack#404]
My app user significant-change location service,it may be automatically wakes up,but logging system does't work sometimes in the case. I can't see the log in log file sometimes. alway logging system sometimes work, sometimes does not work in the case。but I use writeToFile method.It can write the log string to file.

1.I turn my app in background.
2.I close iphone
3.wait a moment,i restart iphone.
4.app be automatically wakes up
most of time ddlog work well,sometime it does not work,but writeToFile method work,i can see log in the file wiche writed by writeToFile method.

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    NSString *ddlogfilePath = ...
   NSString *myFilePath = ...    

 //use ddlog
   DDLogFileManagerDefault *fileManagerOne = [[DDLogFileManagerDefault alloc]    initWithLogsDirectory:ddlogfilePath
    DDFileLogger *loggerOne = [[DDFileLogger alloc] initWithLogFileManager:fileManagerOne];
    [DDLog addLogger:loggerOne withLevel:DDLogLevelAll];
   DDLogInfo("app lanch");

   // use wirteToFile method
    NSString *newString = [NSString stringWithFormat:@"app lanch"];
    [newString writeToFile:myFilePath atomically:YES encoding:NSUTF8StringEncoding error:nil];
    ......
}

**Comment by bpoplauschi** [comment]
@niushuiniu1999 is this still an issue?
