### ISSUE TITLE
Fail to find CocoaLumberjack.h

### ISSUE THREAD

**Issue by nexon** [CocoaLumberjack/CocoaLumberjack#409]
When install CocoaLumberjack via cocoapods:

`pod 'CocoaLumberjack', '2.0.0-beta4'`

and then add to my `.pch` file this line:

`#import <CocoaLumberjack/CocoaLumberjack.h>`

its says that the file can't be found. And its there and even xcode autocomplete the route.

I don't found any related problem in the closed issues.

**Comment by bpoplauschi** [comment]
@nexon does this issue still apply or did you manage to get passed it?

**Comment by ivo-ustr-00002** [comment]
I have the same problem, where should be located CocoaLumberjack.h after pod install? I can't find it in Pods folder.

**Comment by rivera-ernesto** [comment]
It should be inside the [`Default`](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/CocoaLumberjack.podspec#L29) files group of the Pods project inside your workspace.

**Comment by bpoplauschi** [comment]
@ivo-ustr-00002 any updates? Does this answer your question?

**Comment by webhive** [comment]
Same problem

> It should be inside the Default files group of the Pods project inside your workspace.

Yes - it is there. But anyway got an error ``'CocoaLumberjack/CocoaLumberjack.h' file not found``

**Comment by bpoplauschi** [comment]
Please try to delete de DerivedData folder for the Xcode project. If that doesn't help, remote Lumberjack from the `Podfile`, do a `pod update/install`, then add it back and redo the `pod update/install`. This way you would refresh the Pods installation.

**Comment by webhive** [comment]
Sorry - false alarm. Problem was not in CocoaLumberjack. For some reasons cocoapods was not able to find header files. Fixed by manually add cocoapods header files directory to project's ``Header Search Path`` option.

**Comment by rivera-ernesto** [comment]
Glad to hear that, but not a good idea to do that manually, better clean/update CocoaPods.

**Comment by webhive** [comment]
Tried it, but without success. Seems CocoaPods has some issues with generation of correct project workspace file.

**Comment by rivera-ernesto** [comment]
I would be surprised as that is one of the main features of CocoaPods. You should try [reporting the issue](https://github.com/CocoaPods/CocoaPods/issues).

**Comment by inix** [comment]
I have this issue too.

1.pod version 0.36.0
2.podfile
`# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'myTarget' do
       pod 'CocoaLumberjack'
end

target 'myTargetTests' do

end
`

4.podfile.lock
`PODS:
  - CocoaLumberjack (2.0.0):
    - CocoaLumberjack/Default (= 2.0.0)
    - CocoaLumberjack/Extensions (= 2.0.0)
  - CocoaLumberjack/Core (2.0.0)
  - CocoaLumberjack/Default (2.0.0):
    - CocoaLumberjack/Core
  - CocoaLumberjack/Extensions (2.0.0):
    - CocoaLumberjack/Default

DEPENDENCIES:
  - CocoaLumberjack

SPEC CHECKSUMS:
  CocoaLumberjack: fd2b1031c6c4e0f08b5ea928ef677fa0a5de517d

COCOAPODS: 0.36.0
`

**Comment by inix** [comment]
@webhive hi,it seems that if you open *.xcworkspace instead of *.xcodeprj,this issue can be resolved.

**Comment by bpoplauschi** [comment]
@inix could you create a demo project with this issue so we can investigate it further?

**Comment by inix** [comment]
@bpoplauschi 
hi,I finally resolve it by delete podfile.lock and pod install again.
I do not know how to repeat this issue steadily.

**Comment by bpoplauschi** [comment]
Great, @inix

**Comment by yuyedaidao** [comment]
I have the same problem...And,I still can not resolve it.

**Comment by joelfischerr** [comment]
I have had the same problem and was too unable to resolve it until I changed my podfile from pod 'CocoaLumberjack' to pod 'CocoaLumberjack', '~> 2.0'. Cocoapods did not seem to load the correct version of CocoaLumberjack.

**Comment by rivera-ernesto** [comment]
There's no "correct" version for CocoaPods. If unspecified it uses the latest but we had some compatibility issues with 2.0.1.

**Comment by joelfischerr** [comment]
There is a more correct version. If you're importing Cocoalumberjack.h you need to be using at least 2.0.  And for my case cocoapods did not use the latest version when leaving the version number unspecified.

**Comment by wangpeiyan** [comment]
still have the problem

**Comment by psi-gh** [comment]
Same problem.
Solved by removing Pod folder, cleaning a project, removing DerivedData folder, then pod install.

**Comment by lucasluca** [comment]
in React native this resolved here => Found it. You have to open the xcode workspace, not the project.

**Comment by marcel-hof** [comment]
I had the same issue but only for iOS simulator. For my iPhone there were no trouble to run the app. The issue appeared because there was no correct valid cpu architecture for a simulator in my project. 
[Have a look here](https://stackoverflow.com/questions/64245802/cocoalumberjack-h-file-not-found)
