### ISSUE TITLE
CocoaLumberjackSwift does not compile. Issue with creating DDLogMessage

### ISSUE THREAD

**Issue by mowens** [CocoaLumberjack/CocoaLumberjack#422]
Unable to compile the CocoaLumberjackSwift framework due to issues with the way the SwiftMacro creates the DDLogMessage:
![screen shot 2014-12-16 at 10 37 19 pm](https://cloud.githubusercontent.com/assets/4575216/5467457/98717a8c-8574-11e4-8941-5651fc2a04b4.png)
```
/Users/mikeowens/Desktop/github/CocoaLumberjack/Classes/CocoaLumberjack.swift:67:19: Could not find member 'CopyFile'
```

Original error with no changes cannot file the .CopyFile or .CopyFunction. Prefixed both classes with DDLogMessageOptions but compiler still complains about the mask:
![screen shot 2014-12-16 at 10 37 47 pm](https://cloud.githubusercontent.com/assets/4575216/5467473/d8b6a194-8574-11e4-95b5-04b195b8663b.png)
```
/Users/mikeowens/Desktop/github/CocoaLumberjack/Classes/CocoaLumberjack.swift:67:19: Cannot invoke '|' with an argument list of type '(message: String, level: DDLogLevel, flag: DDLogFlag, context: UInt, file: String, function: String, line: UInt, tag: AnyObject?, options: $T11, timestamp: NilLiteralConvertible)'
```

Moving the mask to a local constant still a no go:
![screen shot 2014-12-16 at 10 38 43 pm](https://cloud.githubusercontent.com/assets/4575216/5467479/eb51fe0c-8574-11e4-9923-499db19a8bc3.png)
```
/Users/mikeowens/Desktop/github/CocoaLumberjack/Classes/CocoaLumberjack.swift:68:22: Cannot invoke 'init' with an argument list of type '(message: String, level: DDLogLevel, flag: DDLogFlag, context: UInt, file: String, function: String, line: UInt, tag: AnyObject?, options: DDLogMessageOptions, timestamp: NilLiteralConvertible)'
```

Is this currently expected? Based on the comments on #383 it would appear that the iOSSwift demo project should be building. Any thoughts?

**Comment by bpoplauschi** [comment]
This should be fixed by #437
