### ISSUE TITLE
Manually Clear Logs

### ISSUE THREAD

**Issue by shortstuffsushi** [CocoaLumberjack/CocoaLumberjack#423]
I've been looking through the source for a method to clear logs manually, for a case such as "logout" where the next user shouldn't see any of the old user's logs. It doesn't seem that there are any exposed methods to do this, and at least in the past, deleting the files out from under the logger seemed to cause it to crash.

Any thoughts on how I could accomplish this?

**Comment by izikl** [comment]
+1

**Comment by salyasev** [comment]
+1

**Comment by itsniper** [comment]
+1

**Comment by loslislo-lshift** [comment]
+1

**Comment by xiaoyaoworm** [comment]
+1

**Comment by ruangchupa** [comment]
+1

**Comment by bart-kneepkens** [comment]
+1

**Comment by AhirePawan** [comment]
Any update on this Question? As I'm facing the same issue.

**Comment by nburyak** [comment]
+1

**Comment by shortstuffsushi** [comment]
I no longer develop actively on iOS, so this issue isn't really important for me. If anyone else cares, feel free to comment, otherwise I'll allow stalebot to close things out.

**Comment by bpoplauschi** [comment]
Sorry @shortstuffsushi for taking so long until you are doing something else :)

**Comment by shortstuffsushi** [comment]
Oh no worries, I worked around this in the one case I needed to, and continued to use exclusively this library for years. I just haven't been in the mobile space for a few years now.
