### ISSUE TITLE
Typos/Wrong values in DDTTYLogger

### ISSUE THREAD

**Issue by MinusZwei** [CocoaLumberjack/CocoaLumberjack#429]
Hi!

I have just noticed some slight differences when comparing the output of NSLog() and DDTTYLogger:
2014-12-28 23:56:02.013 TestApp[6247:281476] NSLog
2014-12-28 23:56:02:013 TestApp[6247:30b] DDLogVerbose

First thing, I think there is a minor typo in the date string: The milliseconds should be separated with a 'dot' character, and not a ':'. In 'DDTTYLogger.m', line 1271, I would replace the snprintf() format string with:
"%04ld-%02ld-%02ld %02ld:%02ld:%02ld.%03d", // yyyy-MM-dd HH:mm:ss.SSS

Also, more importantly, it seems that the TID of the standard NSLog() call has been changed (at least on OS X 10.10, not tested with iOS nor older version OS X)... and honestly spoken, for this one, I don't have the replacement yet...

**Comment by rivera-ernesto** [comment]
Thank you for noticing. Could you create a pull request for the first issue?

We can still leave this open for the second one.

**Comment by bpoplauschi** [comment]
The thread id was fixed already by #514
