### ISSUE TITLE
Integrating cocoaLumberjack with swift project

### ISSUE THREAD

**Issue by rajeevprasanna** [CocoaLumberjack/CocoaLumberjack#435]
I have integrated cocoalumberjack project in objective-c project. Now i have added swift files into that project. I am not able to use DDLogInfo in swift file. 

I tried to change import from DDLog.h to #import <CocoaLumberjack/CocoaLumberjack.h> but no luck 

Can you please suggest steps to integrate them?

**Comment by rivera-ernesto** [comment]
Please take a look at #383 and #405.
