### ISSUE TITLE
How to manipulate contents of variables while writing Lumberjack logger custom formatters

### ISSUE THREAD

**Issue by abbood** [CocoaLumberjack/CocoaLumberjack#438]
I got an app that uses [MPMediaItems](https://developer.apple.com/library/ios/documentation/MediaPlayer/Reference/MPMediaItem_ClassReference/index.html) extensively, and the contents of the said items matter a lot. Using this framework, I was hoping to use [custom formatters](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/CustomFormatters.md) like so:

    - (NSString *)formatLogMessage:(DDLogMessage *)logMessage logMsgVariable:(id)variable
    {
      if ([variable isKindOfClass:[MPMediaItem class]) {
        return [NSString stringWithFormat:@"artist: %@, title: [item valueForProperty:MPMediaItemPropertyAlbumArtist], [item valueForProperty:MPMediaItemPropertyTitle]"];
      } 
      return logMessage->logMsg;
    }

Currently the only variable the method `formatLogMessage` accepts is of type `DDLogMessage`, which has only a `logMessage` member variable.. with no reference to the variables supplied to the original log message.

I know one way of doing this is simply creating a category for MPItem or something and make it generate the `NSString` I want and simply supply that at the log call.. but i was hoping to do this at the formatter level.. any help?

**Comment by rivera-ernesto** [comment]
I think you could call `DDLogXXX(@"artist: %@, title: [item valueForProperty:MPMediaItemPropertyAlbumArtist], [item valueForProperty:MPMediaItemPropertyTitle]")` directly.

Or create your own `#define LogMediaItem(...) LOG_MACRO...` directly.

A log formatter should not infer/handle this kind of information.

**Comment by bpoplauschi** [comment]
@abbood does this answer your question?

**Comment by bpoplauschi** [comment]
Closing, based on the lack of response. A solution was provided.
