### ISSUE TITLE
Crash in isRegisteredClass: when running tests

### ISSUE THREAD

**Issue by mabrat** [CocoaLumberjack/CocoaLumberjack#441]
When running my test suite, calling `[DDLog registeredClasses]` results in a crash in `[DDLog isRegisteredClass:]` on the line `Method getter = class_getClassMethod(class, getterSel); (EXC_BAD_ACCESS)`. I have updated the registeredClasses method to the newest version because of the reports of numClasses changing (generally I'm running 2.0.0-beta3) but that didn't help. When using the first version of the isRegisteredClass: method that's supposed to not work with ARC in the simulator, I don't get said crash. I am running this in an ARC enabled project on the 8.1 simulator.

This only happens when running tests, in the app proper, it works just fine.

Anything I can do to provide more information or anything I can do to test, please let me know.

**Comment by rivera-ernesto** [comment]
This functionality seems to be broken. May be related to #425 as well.

**Comment by bpoplauschi** [comment]
Does this issue still happen? If yes, please reopen it and we can discuss it.

**Comment by vevo-sterling-li** [comment]
Just ran into the same issue. It crashed at the exact same line when running unit test. I am using XCode 7.3.

**Comment by bpoplauschi** [comment]
@vevo-sterling-li could you add some details here? Look at https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/ISSUE_TEMPLATE.md for what we would need
