### ISSUE TITLE
DDTTYLogger not working on device but works fine in simulator

### ISSUE THREAD

**Issue by barrettj** [CocoaLumberjack/CocoaLumberjack#442]
Nothing is being output to the Xcode console when I'm running on device.  Works fine in simulator.

Using pod 'CocoaLumberjack', '~> 2.0.0-rc'

Any ideas what might be causing this?

**Comment by barrettj** [comment]
If I go to Window -> Devices, choose my device, then click on the arrow in the bottom left I do see the output there, just not in the xcode window (with "All Output" set)

**Comment by barrettj** [comment]
It appears this is the result of having an NSLog (the default, apple implementation) called before DDLog is setup (which is being done by a framework outside of my control).

**Comment by rivera-ernesto** [comment]
So it doesn't show any log even after DDLog setup?

**Comment by barrettj** [comment]
Correct.  It's very strange.  I can't reproduce it in another project, either.  Only this one project I have.  And doubly strange is that regular NSLog command will "lag" by one.

i.e

if I have:

```NSLog(@"1");
```NSLog(@"2");

Only 1 will be printed.  If then did an NSLog(@"3"); it would finally print 2.

**Comment by dev4dev** [comment]
+1

**Comment by rivera-ernesto** [comment]
Are you manually adding the TTY logger at startup? Because you should, it is only added automatically for Debug configurations.

Also using ACL capture may delay NSLogs.

**Comment by dev4dev** [comment]
``` objc
- (void)
setupLogger
{
	self.fileLogger = [DDFileLogger new];
	self.fileLogger.maximumFileSize = 1024 * 64;
	self.fileLogger.logFileManager.maximumNumberOfLogFiles = 1;
	self.fileLogger.rollingFrequency = 86400; // one day
	[self.fileLogger rollLogFileWithCompletionBlock:nil];
	[DDLog addLogger:self.fileLogger withLevel:DDLogLevelWarning];
	
#ifndef AppStore
	[DDLog addLogger:[DDTTYLogger sharedInstance]];
	[DDTTYLogger sharedInstance].colorsEnabled = YES;
	
	[[DDTTYLogger sharedInstance] setForegroundColor:[UIColor greenColor] backgroundColor:nil forFlag:DDLogFlagInfo];
	[[DDTTYLogger sharedInstance] setForegroundColor:[UIColor whiteColor] backgroundColor:nil forFlag:DDLogFlagVerbose];
	UIColor *pink = [UIColor colorWithRed:(255/255.0) green:(58/255.0) blue:(159/255.0) alpha:1.0];
	[[DDTTYLogger sharedInstance] setForegroundColor:pink backgroundColor:nil forFlag:DDLogFlagDebug];
#endif
}
```

p.s. by the way, colors glitch too. for ex. first line of Info log is actually green, but 2nd is white

**Comment by bpoplauschi** [comment]
Any updates here?

**Comment by rivera-ernesto** [comment]
Closing this for now. Feel free to update/reopen.
