### ISSUE TITLE
How to define custom log levels with 2.x?

### ISSUE THREAD

**Issue by angeloalduino** [CocoaLumberjack/CocoaLumberjack#445]
I've previously created a custom log level using CocoaLumberjack 1.9.x, but it appears that the changes in 2.x make that a bit different. The documentation appears to be out of date here since #define is no longer used in favor of NS_ENUM and NS_OPTIONS: https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/CustomLogLevels.md

I can't find a way to re-define a typedef in order to add custom levels. I was able to work around this issue by just defining an arbitrary level and flag outside of the enumerations, but then there are compiler warnings. Is there a new method of achieving this correctly?

Thanks!

**Comment by rivera-ernesto** [comment]
As far as I know there is no way to extend enumerations. You could use alias for the existing levels.

Do you need more levels?

**Comment by angeloalduino** [comment]
Ultimately I wanted to create a new type of log statement (like DDLogNetwork()), so I did that by giving it its own level. The documentation appears to still be defining the 1.9.x method of creating new levels. Is there an official way to do it correctly using the new 2.x syntax?

**Comment by rivera-ernesto** [comment]
As I said, there is no way to extend enumerations (to my knowledge), and we prefer them to the old defines.

As for your need, I think you would be better served by setting the log [context](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Classes/DDLogMacros.h#L77) (which defaults to `0`) or using [modules](https://github.com/CyberAgent/NBULog#2-register-a-log-context-and-optional-modules).

**Comment by angeloalduino** [comment]
Yes, the context should work fine in my case. Thanks for the response! The documentation confusion is mainly what brought my question.

**Comment by rivera-ernesto** [comment]
Any help with documentation is welcome!
