### ISSUE TITLE
Swift integration crashing on formatter

### ISSUE THREAD

**Issue by depl0y** [CocoaLumberjack/CocoaLumberjack#448]
I really wanted to make a more descriptive title, but I think it would soon be too long.

I am using the Swift integration and for me it is working fine, except when I try to log the path to my SQLite database, on my device.

I am using MagicalRecord and I am calling the following code:

````
		var dbPath = NSPersistentStore.MR_defaultLocalStoreUrl();
		DDLogVerbose("SQLite database store: \(dbPath)");
````

And this is where it goes wrong. If I understand the Swift macro's correctly, I am sending a NSString format with no arguments. This isn't a problem for most of the stuff I am logging, but my `dbPath` variable contains the following text:

`file:///var/mobile/Containers/Data/Application/51C4C379-8E8B-418A-9FBB-26F7116ED348/Library/Application%20Support/HomeManager/CoreDataStore.sqlite`

If I just perform the following line of code, it crashes on the same error:

````
		DDLogVerbose("SQLite database store: file:///var/mobile/Containers/Data/Application/51C4C379-8E8B-418A-9FBB-26F7116ED348/Library/Application%20Support/HomeManager/CoreDataStore.sqlite");
````

It seems that because %20 in there it crashes, because there are no "arguments" for the NSString formatter to process. So maybe there should be a check somewhere, that if no arguments are specified, the formatter shouldn't be called (I am not sure).

When I perform the line of code mentioned above, and manually replace the `%20` with a space, it works without problems.

**Comment by MaddTheSane** [comment]
Ooh, nice catch. I'll look into possible solutions later today.

And yes, I can see any string that has a "%" in it to be a problem with the current implementation. I'll probably change it to not be a printf-style argument.

**Comment by rivera-ernesto** [comment]
Please @depl0y try the latest commit!
