### ISSUE TITLE
setFormattedBehavior: call not needed in custom formatter doc

### ISSUE THREAD

**Issue by jlnbuiles** [CocoaLumberjack/CocoaLumberjack#452]
i could be wrong, but after looking at apple's documentation (https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSDateFormatter_Class/index.html#//apple_ref/occ/clm/NSDateFormatter/defaultFormatterBehavior) i believe this line isn't needed here, given that the default formatted behavior is the same as what you are setting it to be.

"For iOS and for OS X applications linked against OS X v10.5 and later, the default is NSDateFormatterBehavior10_4."

**Comment by rivera-ernesto** [comment]
You're probably right. Would you like to make a pull request ;)

**Comment by jlnbuiles** [comment]
done! https://github.com/CocoaLumberjack/CocoaLumberjack/pull/454
