### ISSUE TITLE
Crash in DDFileLogger when running unit tests

### ISSUE THREAD

**Issue by radhap** [CocoaLumberjack/CocoaLumberjack#453]
Crashes at below line in DDFileLogger.m when running unit tests

[self addObserver:self forKeyPath:NSStringFromSelector(@selector(maximumNumberOfLogFiles)) options:kvoOptions context:nil];

Solution: 

change addObserver to below 
*************
 NSString *keyPath = NSStringFromSelector(@selector(maximumNumberOfLogFiles));
        if ([self respondsToSelector:NSSelectorFromString(keyPath)]) {
            [self addObserver:self forKeyPath:keyPath options:kvoOptions context:nil];
        }
*************
Add below method

+ (BOOL)automaticallyNotifiesObserversForKey:(NSString *)theKey {
    BOOL automatic = NO;
    if ([theKey isEqualToString:@"maximumNumberOfLogFiles"]) {
        automatic = NO;
    }
    else {
        automatic = [super automaticallyNotifiesObserversForKey:theKey];
    }
    return automatic;
}

**Comment by rivera-ernesto** [comment]
Related to #447.

**Comment by rivera-ernesto** [comment]
As long as it doesn't crash in actual apps I think we can move this to a different milestone.
