### ISSUE TITLE
CocoaLumberjack not available

### ISSUE THREAD

**Issue by goodcyg** [CocoaLumberjack/CocoaLumberjack#456]
1. Add the lumberjack files to your project.
    2.Configure the framework.
 2.1 Write in the test.pch files  
  #import "./CocoaLumberjack/Classes/CocoaLumberjack.h"
    #import "./CocoaLumberjack/Classes/DDLegacyMacros.h"

#ifdef DEBUG
static const int ddLogLevel =LOG_LEVEL_VERBOSE;
#else
static const int ddLogLevel = LOG_LEVEL_OFF;
#endif
2.2 YGAppDelegate.m
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    [DDLog addLogger:[DDASLLogger sharedInstance]];
    [DDLog addLogger:[DDTTYLogger sharedInstance]];

    return YES;
}			
- (void)applicationWillResignActive:(UIApplication *)application
{
    DDLogError(@"ok");  
}
Compile the project .Report an error  

Ld /Users/Jackson/Library/Developer/Xcode/DerivedData/testlog-ahnjaufjbbzpuicykofoftfdpque/Build/Products/Debug-iphonesimulator/testlog.app/testlog normal x86_64
    cd /Users/Jackson/Desktop/oc/testlog
    export IPHONEOS_DEPLOYMENT_TARGET=7.1
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk -L/Users/Jackson/Library/Developer/Xcode/DerivedData/testlog-ahnjaufjbbzpuicykofoftfdpque/Build/Products/Debug-iphonesimulator -L/Users/Jackson/Desktop/oc/testlog/testlog/CocoaLumberjack/Framework/Mobile/build/Debug-iphoneos -L/Users/Jackson/Desktop/oc/testlog -L/Users/Jackson/Desktop/oc/testlog/testlog/CocoaLumberjack/Framework/Mobile/Build/Debug-iphoneos -F/Users/Jackson/Library/Developer/Xcode/DerivedData/testlog-ahnjaufjbbzpuicykofoftfdpque/Build/Products/Debug-iphonesimulator -F/Users/Jackson/Desktop/oc/testlog/testlog/CocoaLumberjack/Framework/Desktop/build/Debug -F/Users/Jackson/Library/Developer/Xcode/DerivedData/Lumberjack-hagiutaowmyznjdswctloqoaktgh/Build/Products/Release -F/Users/Jackson/Library/Developer/Xcode/DerivedData/Lumberjack-dknsbwmeyhqxyugzaxspmmklmamb/Build/Products/Release -F/Users/Jackson/Desktop/oc/testlog/testlog/CocoaLumberjack/Framework/Desktop/Build/Debug -filelist /Users/Jackson/Library/Developer/Xcode/DerivedData/testlog-ahnjaufjbbzpuicykofoftfdpque/Build/Intermediates/testlog.build/Debug-iphonesimulator/testlog.build/Objects-normal/x86_64/testlog.LinkFileList -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -Xlinker -no_implicit_dylibs -mios-simulator-version-min=7.1 -Xlinker -dependency_info -Xlinker /Users/Jackson/Library/Developer/Xcode/DerivedData/testlog-ahnjaufjbbzpuicykofoftfdpque/Build/Intermediates/testlog.build/Debug-iphonesimulator/testlog.build/Objects-normal/x86_64/testlog_dependency_info.dat -o /Users/Jackson/Library/Developer/Xcode/DerivedData/testlog-ahnjaufjbbzpuicykofoftfdpque/Build/Products/Debug-iphonesimulator/testlog.app/testlog

ld: warning: directory not found for option '-L/Users/Jackson/Desktop/oc/testlog/testlog/CocoaLumberjack/Framework/Mobile/build/Debug-iphoneos'
ld: warning: directory not found for option '-L/Users/Jackson/Desktop/oc/testlog/testlog/CocoaLumberjack/Framework/Mobile/Build/Debug-iphoneos'
ld: warning: directory not found for option '-F/Users/Jackson/Library/Developer/Xcode/DerivedData/Lumberjack-hagiutaowmyznjdswctloqoaktgh/Build/Products/Release'
ld: warning: directory not found for option '-F/Users/Jackson/Library/Developer/Xcode/DerivedData/Lumberjack-dknsbwmeyhqxyugzaxspmmklmamb/Build/Products/Release'
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_DDASLLogger", referenced from:
      objc-class-ref in YGAppDelegate.o
  "_OBJC_CLASS_$_DDLog", referenced from:
      objc-class-ref in YGAppDelegate.o
  "_OBJC_CLASS_$_DDTTYLogger", referenced from:
      objc-class-ref in YGAppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

help me！！！

**Comment by goodcyg** [comment]
my system is Xcode 6.1,help me...

**Comment by DD-P** [comment]
I would first search [StackOverflow] (http://stackoverflow.com/search?q=%5Bios%5D+symbol%28s%29+not+found+for+architecture+x86_64) for the error "ld: symbol(s) not found for architecture x86_64" when building for iPhone / simulator.  GitHub project issues tend to focus on specific project bugs / feature requests.  (I'm not experienced on mobile, but I would expect x86_64 to be for MacOS X builds, so it may be that an Xcode project setting is incorrect).

**Comment by goodcyg** [comment]
I guess where settings are not correct, try many times will not work, so I posted to ask? 
Embedded dylibs/frameworks are only supported on iOS 8.0 and later for architecture x86_64
I compiled here the old error? Xcode6 how to set up? Can give a detailed explanation?

**Comment by goodcyg** [comment]
help,help...

**Comment by goodcyg** [comment]
Still  errors . why?why?
Embedded dylibs/frameworks are only supported on iOS 8.0 and later for architecture x86_64

**Comment by rivera-ernesto** [comment]
So this is when not using CocoaPods right?

**Comment by goodcyg** [comment]
CocoaPods Already installed  right.

**Comment by rivera-ernesto** [comment]
CocoaPods may be installed but I think you're adding the files manually or using the Lumberjack project.

Can you try using a [`Podfile`](http://guides.cocoapods.org/syntax/podfile.html) with `pod 'CocoaLumberjack'` in it?

**Comment by robpearson** [comment]
:+1:  I hit this as well.  I've been using CocoaLumberjack for ages w/ Cocoapods and v2.0 rc2 broke my build. I haven't investigated it much though.  I'll add any additional details I can find.

**Comment by rivera-ernesto** [comment]
Was it working with the previous rc?
Cleaning the project before building may also help.

**Comment by robpearson** [comment]
Resolved my issue tonight.  I thought it was similar to this issue but it was completely different.  I accidentally opened the xcode project instead of the workspace so it was a very easy fix.

**Comment by rivera-ernesto** [comment]
Good to know! Does it solve your problem @goodcyg ?

**Comment by bpoplauschi** [comment]
Closing, it should be fine now, since we also have the [Manual install section doc](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/GettingStarted.md#manual-installation)
