### ISSUE TITLE
Add instructions for installing without cocoapods

### ISSUE THREAD

**Issue by nrbrook** [CocoaLumberjack/CocoaLumberjack#460]
As per title, I don't want to use CocoaPods, so how can I install CocoaLumberjack?

**Comment by rivera-ernesto** [comment]
Please take a look at the [documentation](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/), specially [here](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/GettingStarted.md). There may be some outdated information, but you can always make a documentation pull request ;)

Besides manually adding files you can also use the Lumberjack Xcode project, and then add it as a build dependency and to the link step. Much like [this](https://github.com/RestKit/RestKit/wiki/Installing-RestKit-v0.20.x-as-a-Git-Submodule#adding-restkit-to-your-project).

**Comment by bpoplauschi** [comment]
The Getting Started doc was added a [Manual installation section](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/GettingStarted.md#manual-installation).
