### ISSUE TITLE
How can I store custom data fields as part of a log message?

### ISSUE THREAD

**Issue by dhilowitz** [CocoaLumberjack/CocoaLumberjack#465]
**Here's my use-case:**

I am using CocoaLumberjack to log data in my app. I have six different severity levels. Some of the data is trivial (severity 6), some is not (severity 1). I have two "loggers" such that all of the data gets logged to console and all of the data also gets sent to an API for storage. The API accepts log messages in JSON format. I've got the code that sends the logs to the API (a custom `DDFileLoggerManager`). So far, I have been using a custom `DDLogFormatter` to to turn my log messages into JSON objects that then get written to disk by the DDFileLogger. This custom format has thus far only been used by the file logger, so that the console messages are still fairly readable. (I wouldn't necessarily want to be piping thousands of JSON objects to the console.) This whole system has been working flawlessly so far. 

**Here's the problem:**

For the version of the log data that's going to the API server, I sometimes need to also submit data statistics as part of the log message. I need to be able to attach key-value pairs to the log messages. My JSON objects will eventually look like this:

    {
        'time': '2015-03-01T13:54:03-05:00', 
        'message': 'User logged in',
        'severity': 6,
        'data': {
            'username':'testuser',
            'deviceType': 'iPad Air 2'
        }
    }

**And finally, the Question**

**How can I get CocoaLumberjack to allow me to store arbitrary key-value data as part of logging, and then retrieve this when doing custom formatting?**

The only solution I've come up with so far is to make a custom function that I use for all my logging needs. This function will take a data parameter (`NSDictionary`) and do all of the JSONification up-front:

    + (void) logWithSeverity: (uint) severity 
        data:(NSDictionary *) data 
        andFormat:(NSString *)formatString, ...
    {
        va_list args;
        va_start(args, formatString);
        NSString *message = [[NSString alloc] initWithFormat:formatString 
            arguments:args];
        va_end(args);
        
        NSDateFormatter *dateFormatter = [[NSDateFormatter alloc] init];
        NSLocale *enUSPOSIXLocale = 
            [NSLocale localeWithLocaleIdentifier:@"en_US_POSIX"];
        [dateFormatter setLocale:enUSPOSIXLocale];
        [dateFormatter setDateFormat:@"yyyy-MM-dd'T'HH:mm:ssZZZZZ"];
        
        if (data == nil) {
            data = @{};
        }
        
        // Since we are going to be using the pipe character as a data demarcation, 
        // we want to remove any that might naturally be occuring in the string
        NSDictionary *jsonDictionary = @{
         @"time": [dateFormatter stringFromDate:[NSDate date]],
         @"message": message,
         @"severity": [NSNumber numberWithUnsignedInt:severity],
         @"data": data
         };
        
        NSError* error;
        NSData *jsonData = [NSJSONSerialization 
            dataWithJSONObject:jsonDictionary options:0 error:&error];
        
        if(error) {
            NSLog(@"ERROR: We were unable to serialize JSON .");
            return;
        }

        
        NSString *jsonString = [[NSString alloc] initWithData:jsonData 
            encoding:NSUTF8StringEncoding];

        DDLogVerbose(jsonString);
    }

I'll be the first to admit this is a terrible solution:

 - Since implementing it, I've had to turn off output to the console because everything being logged is now a big clunky JSON object that contains all sorts of data I have no desire to output to the console.
 - Since my severity level is now internal to the JSON object, I am no longer making use of the CocoaLumberjack logLevel concept. My logger will always be set to 'Verbose.' I'm thus getting rid of one of the biggest benefits of using a logging library at all.

**Does anyone have a solution for me that is more elegant?** In a perfect world, there would be a function like this: `DDLogVerboseWithData(*someObject, @"User logged in.");` and then that data would get stored as part of DDLogMessage and would be accessible via a custom formatter.

**Comment by rivera-ernesto** [comment]
Well you could store arbitrary "fixed" key/values in your formatter. Things like username, device, etc., that won't change on every log message.

As for things that do change you can use the [`tag:`](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Classes/DDLog.m#L315) parameter in the log function to store anything, for instance a dictionary. This is ignored by all current formatters so only your custom formatter would be use it. Finally define your [own macros](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Classes/DDLogMacros.h) that support your new tag objects.

**Comment by dhilowitz** [comment]
Thanks! That works perfectly. FWIW, I'm still working off version 1.x. Here's what I ended up with:

	/***
	 *
	 * Contains custom logging definitions that allow us to do our control server logging
	 * 
	 ****/

	#import "DDLog.h"

	#undef LOG_FLAG_ERROR
	#undef LOG_FLAG_WARN
	#undef LOG_FLAG_INFO
	#undef LOG_FLAG_DEBUG
	#undef LOG_FLAG_VERBOSE

	#undef LOG_LEVEL_ERROR
	#undef LOG_LEVEL_WARN
	#undef LOG_LEVEL_INFO
	#undef LOG_LEVEL_DEBUG
	#undef LOG_LEVEL_VERBOSE

	#undef LOG_ERROR
	#undef LOG_WARN
	#undef LOG_INFO
	#undef LOG_DEBUG
	#undef LOG_VERBOSE

	#undef DDLogError
	#undef DDLogWarn
	#undef DDLogInfo
	#undef DDLogDebug
	#undef DDLogVerbose

	#undef DDLogCError
	#undef DDLogCWarn
	#undef DDLogCInfo
	#undef DDLogCDebug
	#undef DDLogCVerbose

	// Now define everything how we want it

	#define LOG_FLAG_SEV_1   (1 << 0)  // 0...000001
	#define LOG_FLAG_SEV_2   (1 << 1)  // 0...000010
	#define LOG_FLAG_SEV_3   (1 << 2)  // 0...000100
	#define LOG_FLAG_SEV_4   (1 << 3)  // 0...001000
	#define LOG_FLAG_SEV_5   (1 << 4)  // 0...010000
	#define LOG_FLAG_SEV_6   (1 << 5)  // 0...100000

	#define LOG_LEVEL_SEV_1   (LOG_FLAG_SEV_1)                      // 0...000001
	#define LOG_LEVEL_SEV_2   (LOG_FLAG_SEV_2 | LOG_LEVEL_SEV_1 ) // 0...000011
	#define LOG_LEVEL_SEV_3   (LOG_FLAG_SEV_3 | LOG_LEVEL_SEV_2 ) // 0...000111
	#define LOG_LEVEL_SEV_4   (LOG_FLAG_SEV_4 | LOG_LEVEL_SEV_3 ) // 0...001111
	#define LOG_LEVEL_SEV_5   (LOG_FLAG_SEV_5 | LOG_LEVEL_SEV_4 ) // 0...011111
	#define LOG_LEVEL_SEV_6   (LOG_FLAG_SEV_6 | LOG_LEVEL_SEV_5 ) // 0...111111

	#define LOG_SEV_1   (ddLogLevel & LOG_FLAG_SEV_1 )
	#define LOG_SEV_2   (ddLogLevel & LOG_FLAG_SEV_2 )
	#define LOG_SEV_3   (ddLogLevel & LOG_FLAG_SEV_3 )
	#define LOG_SEV_4   (ddLogLevel & LOG_FLAG_SEV_4 )
	#define LOG_SEV_5   (ddLogLevel & LOG_FLAG_SEV_5 )
	#define LOG_SEV_6   (ddLogLevel & LOG_FLAG_SEV_6 )

	#define DDLogSeverity1(frmt, ...)    SYNC_LOG_OBJC_MAYBE(ddLogLevel, LOG_FLAG_SEV_1,  0, frmt, ##__VA_ARGS__)
	#define DDLogSeverity2(frmt, ...)    SYNC_LOG_OBJC_MAYBE(ddLogLevel, LOG_FLAG_SEV_2,  0, frmt, ##__VA_ARGS__)
	#define DDLogSeverity3(frmt, ...)    ASYNC_LOG_OBJC_MAYBE(ddLogLevel, LOG_FLAG_SEV_3,   0, frmt, ##__VA_ARGS__)
	#define DDLogSeverity4(frmt, ...)    ASYNC_LOG_OBJC_MAYBE(ddLogLevel, LOG_FLAG_SEV_4, 0, frmt, ##__VA_ARGS__)
	#define DDLogSeverity5(frmt, ...)    ASYNC_LOG_OBJC_MAYBE(ddLogLevel, LOG_FLAG_SEV_5,   0, frmt, ##__VA_ARGS__)
	#define DDLogSeverity6(frmt, ...)    ASYNC_LOG_OBJC_MAYBE(ddLogLevel, LOG_FLAG_SEV_6,  0, frmt, ##__VA_ARGS__)

	#define DDLogCSeverity1(frmt, ...)   SYNC_LOG_C_MAYBE(ddLogLevel, LOG_FLAG_SEV_1,  0, frmt, ##__VA_ARGS__)
	#define DDLogCSeverity2(frmt, ...)   SYNC_LOG_C_MAYBE(ddLogLevel, LOG_FLAG_SEV_2,  0, frmt, ##__VA_ARGS__)
	#define DDLogCSeverity3(frmt, ...)   ASYNC_LOG_C_MAYBE(ddLogLevel, LOG_FLAG_SEV_3,   0, frmt, ##__VA_ARGS__)
	#define DDLogCSeverity4(frmt, ...)   ASYNC_LOG_C_MAYBE(ddLogLevel, LOG_FLAG_SEV_4, 0, frmt, ##__VA_ARGS__)
	#define DDLogCSeverity5(frmt, ...)   ASYNC_LOG_C_MAYBE(ddLogLevel, LOG_FLAG_SEV_5,   0, frmt, ##__VA_ARGS__)
	#define DDLogCSeverity6(frmt, ...)   ASYNC_LOG_C_MAYBE(ddLogLevel, LOG_FLAG_SEV_6,  0, frmt, ##__VA_ARGS__)

	#define DDLogSeverity1WithData(theData, frmt, ...) LOG_MACRO(LOG_ASYNC_ENABLED, LOG_LEVEL_DEF, LOG_FLAG_SEV_1, 0, theData, __PRETTY_FUNCTION__, frmt, ##__VA_ARGS__)
	#define DDLogSeverity2WithData(theData, frmt, ...) LOG_MACRO(LOG_ASYNC_ENABLED, LOG_LEVEL_DEF, LOG_FLAG_SEV_2, 0, theData, __PRETTY_FUNCTION__, frmt, ##__VA_ARGS__)
	#define DDLogSeverity3WithData(theData, frmt, ...) LOG_MACRO(LOG_ASYNC_ENABLED, LOG_LEVEL_DEF, LOG_FLAG_SEV_3, 0, theData, __PRETTY_FUNCTION__, frmt, ##__VA_ARGS__)
	#define DDLogSeverity4WithData(theData, frmt, ...) LOG_MACRO(LOG_ASYNC_ENABLED, LOG_LEVEL_DEF, LOG_FLAG_SEV_4, 0, theData, __PRETTY_FUNCTION__, frmt, ##__VA_ARGS__)
	#define DDLogSeverity5WithData(theData, frmt, ...) LOG_MACRO(LOG_ASYNC_ENABLED, LOG_LEVEL_DEF, LOG_FLAG_SEV_5, 0, theData, __PRETTY_FUNCTION__, frmt, ##__VA_ARGS__)
	#define DDLogSeverity6WithData(theData, frmt, ...) LOG_MACRO(LOG_ASYNC_ENABLED, LOG_LEVEL_DEF, LOG_FLAG_SEV_6, 0, theData, __PRETTY_FUNCTION__, frmt, ##__VA_ARGS__)

	/**
	 * Controls the verbosity of the entire app's logging.
	 */
	static const int ddLogLevel = LOG_LEVEL_SEV_6;

**Comment by rivera-ernesto** [comment]
Good to know!

**Comment by joshwand** [comment]
If you're doing remote logging, [Antenna](https://github.com/mattt/Antenna) + [DDAntennaLogger](https://github.com/mokagio/DDAntennaLogger) does this automatically for you. Just give it an NSDictionary and it will output key-val pairs. See the relevant code [here](https://github.com/mattt/Antenna/blob/master/Antenna/Antenna.m#L29).
