### ISSUE TITLE
enabling colors with DDTTYLogger has no effect [Swift]

### ISSUE THREAD

**Issue by vercruesse** [CocoaLumberjack/CocoaLumberjack#470]
Configuration: CocoaLumberjack 2.0.0-rc2 and Xcode 6.1.1, latest XcodeColors plugin is installed, of course (ColorLog example as found in the XcodeColors README works as expected)

```swift
defaultDebugLevel = DDLogLevel.All // workaround so that loggers work as expected regarding explicitly set log level (see #469)
let ttyLogger = DDTTYLogger.sharedInstance()
ttyLogger.colorsEnabled = true
ttyLogger.setForegroundColor(UIColor.redColor(), backgroundColor: UIColor.blackColor(), forFlag: .Error)
DDLog.addLogger(ttyLogger, withLevel: DDLogLevel.Info)
DDLogError("error!")
```

**Comment by h0lyalg0rithm** [comment]
I tried your exact configuration and it works for me.
![screen shot 2015-03-06 at 5 28 33 pm](https://cloud.githubusercontent.com/assets/676507/6526016/4f7576d0-c426-11e4-8cd6-bd740b43096a.png)

**Comment by vercruesse** [comment]
Perhaps it has to do with the way I've integrated the framework into my project? I've put together a complete Xcode project to demonstrate the issue.

https://www.dropbox.com/s/k97j6lxousj60dj/cljtest.zip?dl=0

**Comment by vercruesse** [comment]
I've just tried the same with an OSX project (instead of iOS) and that worked. So the issue is specific to iOS only.

**Comment by vercruesse** [comment]
OK, my bad. It turned out that I have to set the XcodeColors environment variable to get it working for my iOS project.

**Comment by rivera-ernesto** [comment]
It is weird, but I needed the variable set only for some projects but couldn't find the reason.

**Comment by cytryn** [comment]
@vercruesse what XcodeColors environment variable are you talking about?
its not working for me either
