### ISSUE TITLE
Unused variable ddLogLevel Xcode 6.2

### ISSUE THREAD

**Issue by DoctorG** [CocoaLumberjack/CocoaLumberjack#479]
I was using the 2.0rc previously without an issue, but now I get warnings in every class for: 

`static const DDLogLevel ddLogLevel = DDLogLevelInfo;`

**Comment by rivera-ernesto** [comment]
Related to https://github.com/CocoaLumberjack/CocoaLumberjack/issues/478#issuecomment-81632833.
