### ISSUE TITLE
Compilation errors with 2.0.0

### ISSUE THREAD

**Issue by pavm035** [CocoaLumberjack/CocoaLumberjack#480]
Hi,

After i upgraded CocoaLumberjack getting errors in following method, i think this class not updated to latest properties where these have to be replaced.

- (NSString *)formatLogMessage:(DDLogMessage *)logMessage
{
    return [NSString stringWithFormat:@"%@ | %@ | %s @ %i | %@",
                                      [self stringFromDate:(logMessage->timestamp)], [logMessage fileName], logMessage->function, logMessage->lineNumber, logMessage->logMsg];
}

Also getting error on tag property, like it's redeclared

**Comment by DD-P** [comment]
Regarding the **tag** warnings, I think they are more commonly seen with "older" style Cocoa conventions. There are a couple of solutions, both of which worked for my application. They give the compiler a hint about which method will actually be called on a generic class.  E.g.,

*replace*
`- (IBAction) doSomething: (id) sender`
*with*
`- (IBAction) doSomething: (NSPopUpButton*) sender`

*or*
```
if ([sender respondsToSelector: @selector(tag)])
	{
	NSMenuItem *menuItem=sender;
	[someController doSomething: [menuItem tag]];
	}
```

See http://stackoverflow.com/a/8818052/3342547 and others for details.
--DDP

**Comment by rivera-ernesto** [comment]
Also if you could share a demo project that reproduces the error it would help a lot.

**Comment by bpoplauschi** [comment]
Any updated here?
