### ISSUE TITLE
Change logFlag In a formatter

### ISSUE THREAD

**Issue by Whirlwind** [CocoaLumberjack/CocoaLumberjack#486]
I have some log like: `<ERROR> xxxxx` or `<WARN> xxxx` and so on.

I want to set the log flag to `DDLogFlagError` for `<ERROR> xxx`, so I add a formatter to do it, but it failed!
```
@implementation MYLogLevelInMessage

- (NSString *)formatLogMessage:(DDLogMessage *)logMessage {
    if ([logMessage->_message hasPrefix:@"<ERROR>"]) {
        logMessage->_flag = DDLogFlagError;
    } else if ([logMessage->_message hasPrefix:@"<WARN>"]) {
        logMessage->_flag = DDLogFlagWarning;
    } else if ([logMessage->_message hasPrefix:@"<INFO>"]) {
        logMessage->_flag = DDLogFlagInfo;
    } else if ([logMessage->_message hasPrefix:@"<DEBUG>"]) {
        logMessage->_flag = DDLogFlagDebug;
    }
    return logMessage->_message;
}

@end

```

Because these code: (DDMultiFormatter.m)
```
- (NSString *)formatLogMessage:(DDLogMessage *)logMessage {
    __block NSString *line = logMessage->_message;

    dispatch_sync(_queue, ^{
        for (id<DDLogFormatter> formatter in _formatters) {
            DDLogMessage *message = [self logMessageForLine:line originalMessage:logMessage];
            line = [formatter formatLogMessage:message];

            if (!line) {
                break;
            }
        }
    });

    return line;
}

- (DDLogMessage *)logMessageForLine:(NSString *)line originalMessage:(DDLogMessage *)message {
    DDLogMessage *newMessage = [message copy];

    newMessage->_message = line;
    return newMessage;
}
```
The `DDLogMessage` be copied for every formatter!!

I don't know why to copy. But I think it is well:
```
 - (NSString *)formatLogMessage:(DDLogMessage *)logMessage {
     __block NSString *line = logMessage->_message;
+    DDLogMessage *message = [self logMessageForLine:line originalMessage:logMessage];
 
     dispatch_sync(_queue, ^{
         for (id<DDLogFormatter> formatter in _formatters) {
-            DDLogMessage *message = [self logMessageForLine:line originalMessage:logMessage];
-            line = [formatter formatLogMessage:message];
+            message->_message = [formatter formatLogMessage:message];
 
-            if (!line) {
+            if (!message->_message) {
                 break;
             }
         }
     });
 
     return line;
 }
```
It will use same DDLogMessage for the all multi formatter.

**Comment by rivera-ernesto** [comment]
Do you want to make a pull request?

**Comment by Whirlwind** [comment]
I think there are more things to do for change the level in the formatter. I will think about how to do it.

**Comment by Whirlwind** [comment]
@rivera-ernesto 
I think that why not use `- (void)formatLogMessage:(DDLogMessage *)logMessage` instead of `- (NSString *)formatLogMessage:(DDLogMessage *)logMessage`?

So the formatter just change the logMessage->_message and other properties, not return message.

**Comment by bpoplauschi** [comment]
I'm not sure this is right. We will have a method `formatLogMessage` that changes the internal state of the `DDLogMessage`. Plus I think the original intent was that the formatting is applied just before the actual output, so it doesn't compromise the internal state of the messages. Thoughts?

**Comment by rivera-ernesto** [comment]
Yes, I think they should be separate without touching the original message. For instance you may want minimalist logs in a HUD view in your app, but have more detailed content in Xcode console, for the same log messages.

Formatters mix many different log message variables, flags, levels, into a string, not only the actual `_message` which would get squashed.

**Comment by Whirlwind** [comment]
@rivera-ernesto you are right. I think we can just touch the message in same multiFormatter:

```
 - (NSString *)formatLogMessage:(DDLogMessage *)logMessage {
-    __block NSString *line = logMessage->_message;
+    DDLogMessage *message = [self logMessageForLine:logMessage->_message originalMessage:logMessage];
 
     dispatch_sync(_queue, ^{
         for (id<DDLogFormatter> formatter in _formatters) {
-            DDLogMessage *message = [self logMessageForLine:line originalMessage:logMessage];
-            line = [formatter formatLogMessage:message];
+            logMessage->_message = [formatter formatLogMessage:message];
 
-            if (!line) {
+            if (!logMessage->_message) {
                 break;
             }
         }
     });
 
-    return line;
+    return logMessage->_message;
 }
```

Other changes will be reverted.

**Comment by rivera-ernesto** [comment]
Sure. You can add commits to your existing pull request or close it a make a new one.

**Comment by zhouguangming** [comment]
@Whirlwind :+1:

**Comment by rivera-ernesto** [comment]
Reading again the issue description makes it clear to me that the approach is wrong.

We shouldn't turn a log message into an error message inside a formatter. It is completely unexpected.

You should init the `DDLogMessage` with an error flag since creation. For that you have to create your won [custom macros](https://github.com/CocoaLumberjack/CocoaLumberjack/search?utf8=✓&q=custom+macro&type=Issues) that parse the string message and create a log message accordingly.

But then parsing strings is less effective than calling `DDLogError` in the first place, so I would search all messages in your code that start with "Error" and use the proper built-in macro instead.

**Comment by Whirlwind** [comment]
You are right.

**Comment by rivera-ernesto** [comment]
Thanks for collaborating @Whirlwind . Let's come up with a different solution.
