### ISSUE TITLE
Log to file and NOT to console for AUDIT logging

### ISSUE THREAD

**Issue by tonov** [CocoaLumberjack/CocoaLumberjack#490]
Hello, 
I went through all issues, and didnt find any info on how to enable file logging only without printing to console. Could you please advise? Many thanks.

**Comment by wizzardchao** [comment]
I don't know which is the AUDIT logging. Is it some part of your log of things like credential?
If so, I think you can use log level to control. For example, your set level for file logger to Verbose, and set level for console to Debug. Then you use DDLogVerbose with your AUDIT logging.

If there is no logs that should go into console. You can just add file logger and not add tty logger.

**Comment by rivera-ernesto** [comment]
You could [removeLogger:](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Classes/DDLog.m#L221) undesired loggers.
