### ISSUE TITLE
CocoaLumberjack.swift is incompatible with swift 1.2/xcode 6.3

### ISSUE THREAD

**Issue by mcmurrym** [CocoaLumberjack/CocoaLumberjack#491]
The problem is `@autoclosure` has changed: first it is not an attribute and should change from ```#string: @autoclosure``` to  ```@autoclosure #string:```.

Second `@autoclosure` now also implements the behavior of `@noescape` this means in a function like DDLogDebug the logText parameter is not allowed to be passed on to the SwiftLogMacro. It can only be called.

**Comment by MaddTheSane** [comment]
At first I was wondering why I *wasn't* having an issue. Then I realized the App Store version hadn't updated.

I'll look into this when my Xcode updates.

**Comment by bpoplauschi** [comment]
Resolved nicely by @MaddTheSane , integrated into our `swift_support` branch.
