### ISSUE TITLE
maximumNumberOfLogFiles&logFilesDiskQuota of DDLogFileManagerDefault is not KVO

### ISSUE THREAD

**Issue by wizzardchao** [CocoaLumberjack/CocoaLumberjack#493]
`maximumNumberOfLogFiles` & `logFilesDiskQuota` of `DDLogFileManagerDefault` is not KVO, I find they are disabled intentionally. Is it means we should do the KVO in our customized subclass as the default one is not exposed as an api?(In such case, no KVO code is needed as it's of no use) And I think KVO is not clearer than setter.

**Comment by bpoplauschi** [comment]
@wizzardchao could you create a PR with this fix?

**Comment by bpoplauschi** [comment]
The KVO notifications on those 2 properties were explicitly disabled by #463 to fix a crash in the tests.
