### ISSUE TITLE
XcodeColors doesn't work

### ISSUE THREAD

**Issue by lanvige** [CocoaLumberjack/CocoaLumberjack#50]
I follow the step to configured  the xcode but the content in output did't render with color but with messy code.

```
    //Adds the logger to the console (similar to nslog)
    [DDLog addLogger:[DDTTYLogger sharedInstance]];
    // And we also enable colors
    [[DDTTYLogger sharedInstance] setColorsEnabled:YES];

    DDLogWarn(@"waring");
    DDLogError(@"error");
```
```
[38;5;130m2012-08-03 22:22:50:735[10875:c07] waring
[0m[38;5;124m2012-08-03 22:22:50:735[10875:c07] error
[0m
```
[38;5;130m and [0m[38;5;124m are the messy code.

I also test with *xcodecolor* test project and it works fine.

Thanks.

**Comment by nateuni** [comment]
I am having the same issue in CocoaLumberjack (installed from cocoapods with Swift. 

Though even when I build XcodeColors... close xcode and reopen I see nothing in the terminal.

1. I can see the XcodeColors plug in "~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XcodeColors.xcplugin"
2. In CocoaaLumberjack in my AppDelegate I have set:
````
        DDLog.addLogger(DDASLLogger.sharedInstance())
        DDLog.addLogger(DDTTYLogger.sharedInstance())
        DDTTYLogger.sharedInstance().colorsEnabled = true
````
3. I have checked the plist file as stated [here] (https://github.com/robbiehanson/XcodeColors/wiki/XcodeUpdates) 

4. I went into the scheme editor and added XcodeColors as stated [here](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/XcodeColors.md).

XCode Version 6.3.2 (6D2102)

````
platform :ios, '8.3'
use_frameworks!

target 'myApp' do
 link_with ['myApp', 'myAppTests']
 pod 'CocoaLumberjack', :git => 'https://github.com/CocoaLumberjack/CocoaLumberjack.git', :branch => 'swift_support'
 pod 'FMDB', :git => 'https://github.com/robertmryan/fmdb.git'
 pod 'FBSDKCoreKit', :git => 'https://github.com/facebook/facebook-ios-sdk.git', :branch => 'dev'
 pod 'FBSDKLoginKit', :git => 'https://github.com/facebook/facebook-ios-sdk.git', :branch => 'dev'
end
````

Running out of options.. anyone got a fix for this?

**Comment by webdevotion** [comment]
Using Xcode 6.3.2 I had the same problem as @nateuni although I'm using Obj-C in combination with the Cocoapod.  Once I added the env var using 'edit scheme' things started working for me.  My test code that I use in `application:didFinishLaunchingWithOptions:` is:

```objc
#import <CocoaLumberjack/CocoaLumberjack.h>

@interface AppDelegate ()
@property (strong, nonatomic) DDFileLogger *fileLogger;
@end

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    ...
    [DDLog addLogger:[DDASLLogger sharedInstance]];
    [DDLog addLogger:[DDTTYLogger sharedInstance]];
    [[DDTTYLogger sharedInstance] setColorsEnabled:YES];
    
    DDFileLogger *fileLogger = [[DDFileLogger alloc] init];
    fileLogger.rollingFrequency = 60 * 60 * 24; // 24 hour rolling
    fileLogger.logFileManager.maximumNumberOfLogFiles = 7;
    
    [DDLog addLogger:fileLogger];
    self.fileLogger = fileLogger;
    
    // pinkify all the things
    UIColor *pink = [UIColor colorWithRed:(255/255.0) green:(58/255.0) blue:(159/255.0) alpha:1.0];
    [[DDTTYLogger sharedInstance] setForegroundColor:pink backgroundColor:nil forFlag:DDLogFlagInfo];
    [[DDTTYLogger sharedInstance] setForegroundColor:pink backgroundColor:nil forFlag:DDLogFlagWarning];
    [[DDTTYLogger sharedInstance] setForegroundColor:pink backgroundColor:nil forFlag:DDLogFlagDebug];
    
    DDLogInfo(@"Warming up printer (post-customization)"); // Pink
    
    DDLogDebug(@"%s", __PRETTY_FUNCTION__);
    ...
    return YES;
}
```

![screen shot 2015-05-26 at 10 49 05](https://cloud.githubusercontent.com/assets/50583/7808616/dd8d7456-0394-11e5-9bd0-283dad86b135.png)

![screen shot 2015-05-26 at 10 50 54](https://cloud.githubusercontent.com/assets/50583/7808657/1dcc21b6-0395-11e5-9fc6-3b99138dfd10.png)

**Comment by nateuni** [comment]
I have the env var set exactly the same, but still no colours. It is set for the main project, should it be set for something else?

**Comment by rivera-ernesto** [comment]
It is also case sensitive.

**Comment by bpoplauschi** [comment]
Any updates here? Does XcodeColors still fail to work?

**Comment by rivera-ernesto** [comment]
Closing this for now. Feel free to update/reopen.

**Comment by MadBurea** [comment]
I have followed all steps but still failed to work

**Comment by dirtyhenry** [comment]
@MadBurea: if you're using Xcode 8+, XcodeColors is not supported any more: cf. https://github.com/robbiehanson/XcodeColors's README.
