### ISSUE TITLE
Tag is readonly

### ISSUE THREAD

**Issue by Zyphrax** [CocoaLumberjack/CocoaLumberjack#501]
I'm migrating my project to CocoaLumberjack version 2 and I'm running into a little snag.
In my LogFormatter I want to tag specific log messages and output them with a different color:	
```obj-c
- (NSString *)formatLogMessage:(DDLogMessage *)logMessage {
   if ([logMessage.message hasPrefix:@"*"]) {
      logMessage.tag = @1;
      ...
```
```obj-c
[ddttyLogger setForegroundColor:color backgroundColor:nil forTag:@1];
```
My problem is that tag is no longer writable in the formatter.

Would you guys consider changing it to a read/write property?
Or is what I'm doing too hackish :)?

For now I'm sneaking around the problem with `logMessage->_tag = @1;`

**Comment by rivera-ernesto** [comment]
The formatter should not change `DDLogMessage` information in any way. It should only interpret it and output as desired.

> I'm migrating my project to CocoaLumberjack version 2 and I'm running into a little snag.
In my LogFormatter I want to tag specific log messages and output them with a different color.

You should just set the tag calling your [custom log macros](https://github.com/CocoaLumberjack/CocoaLumberjack/search?q=custom+macro&type=Issues&utf8=✓).

**Comment by Zyphrax** [comment]
Thanks @rivera-ernesto I'll check that out

**Comment by rivera-ernesto** [comment]
Feel free to reopen or comment back here your findings.
