### ISSUE TITLE
DDLogLevelOff doesn't seem to work

### ISSUE THREAD

**Issue by ayoy** [CocoaLumberjack/CocoaLumberjack#502]
Setting:

    const int ddLogLevel = DDLogLevelOff;

has no effect on recent versions of CocoaLumberjack. Can't say when it was introduced as I haven't updated your lib for a while and it used to work earlier on.

By quickly investigating your code it seems that `DDLogLevelOff` enum value being defined as `0` causes this issue. The following code:

    /**
     * The constant/variable/method responsible for controlling the current log level.
     **/
    #ifndef LOG_LEVEL_DEF
        #ifdef ddLogLevel
            #define LOG_LEVEL_DEF ddLogLevel
        #else
            #define LOG_LEVEL_DEF DDLogLevelVerbose
        #endif
    #endif

for `ddLogLevel == DDLogLevelOff` (which is `0`), causes the `#ifdef ddLogLevel` check to fail and fall back to seting log level to verbose.

I'm currently working around this by defining `LOG_LEVEL_DEF` myself, but perhaps it's not the desired solution.

**Comment by rivera-ernesto** [comment]
Yes, for now you have to define it your self as described [here](https://github.com/CocoaLumberjack/CocoaLumberjack/pull/172#issuecomment-29042477) and the [README](https://github.com/CocoaLumberjack/CocoaLumberjack#migrating-to-2x) file.

**Comment by ayoy** [comment]
Oh, so this actually is a feature. Fine then :) thank you!

**Comment by rivera-ernesto** [comment]
We had to make a choice and for now chose to make the library "just work" for new users. Maybe we can find a better way to do so.
