### ISSUE TITLE
EXC_BAD_ACCESS [DDTTYLogger logMessage:] 

### ISSUE THREAD

**Issue by SakthikalaPalanisamy** [CocoaLumberjack/CocoaLumberjack#505]
I am getting EXC_BAD_ACCESS crash for most of the time. Reason for the crash may the calendar object.
Kindly help me to resolve this issue. I have more crashes on this in App store build
Crash Log
Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x00000000
Crashed Thread:  14
Thread 14 Crashed:
0   CoreFoundation                  0x2311a19a 0x230df000 + 242074 (_CFXNotificationRemoveObservers + 606)
1   Foundation                      0x23e5ae78 0x23e55000 + 24184 (<redacted> + 212)
2   Foundation                      0x23e5afa8 0x23e55000 + 24488 (<redacted> + 28)
3   Foundation                      0x23ed7018 0x23e55000 + 532504 (<redacted> + 48)
4   libobjc.A.dylib                 0x3174ed58 0x3172e000 + 134488 (<redacted> + 160)
5   SampleApp              0x00300200 -[DDTTYLogger logMessage:] (DDTTYLogger.m:1279)
6   SampleApp              0x00241540 __16+[DDLog lt_log:]_block_invoke (DDLog.m:653)
7   libdispatch.dylib               0x31c9f2e0 0x31c9e000 + 4832 (<redacted> + 8)
8   libdispatch.dylib               0x31ca7728 0x31c9e000 + 38696 (<redacted> + 1468)
9   libdispatch.dylib               0x31ca1aa8 0x31c9e000 + 15016 (<redacted> + 80)
10  libdispatch.dylib               0x31ca8f98 0x31c9e000 + 44952 (<redacted> + 388)
11  libdispatch.dylib               0x31caa3c0 0x31c9e000 + 50112 (<redacted> + 92)
12  libsystem_pthread.dylib         0x31e06dc0 0x31e06000 + 3520 (_pthread_wqthread + 668)

**Comment by rivera-ernesto** [comment]
Why do you think is the calendar?

We had similar issues that may need to be reopened. Please make a [search](https://github.com/CocoaLumberjack/CocoaLumberjack/search?q=calendar&type=Issues&utf8=✓).

**Comment by SakthikalaPalanisamy** [comment]
Referred:https://github.com/CocoaLumberjack/CocoaLumberjack/pull/277/files#r12619305
Calendar crash was fixed in May 2014.
I have updated the code in September14. 
I having still the crash which I have mentioned. 
Kindly help me to resolve this issue.

**Comment by rivera-ernesto** [comment]
You have a non symbolicated crash, which makes it hard to have an idea of why it crashes. You should try to reproduce the crash locally.

**Comment by bpoplauschi** [comment]
This doesn't seem to be related to Lumberjack.

**Comment by ww1234** [comment]
@SakthikalaPalanisamy, how do you fix it? my app hava the same crash.

**Comment by schartyom** [comment]
@ww1234 same for me, did you find any workaround?
