### ISSUE TITLE
Issue with File Rolling

### ISSUE THREAD

**Issue by karnroshan** [CocoaLumberjack/CocoaLumberjack#513]
I have integrated CocoaLumberjack in my project and have issue with file rolling.
The rolling frequency is set to 24 hours.
NSTimeInterval     const kDDDefaultLogRollingFrequency = 60 * 60 * 24;     // 24 Hours

There are inconsistency seen with file rolling. The log gets appended to the same file even after 24 hours.

#243 fix is already present. Am I missing any thing that needs to be done.

**Comment by rivera-ernesto** [comment]
I think we do have a few file logger remaining bugs. It is better to use one of the [existing issues](https://github.com/CocoaLumberjack/CocoaLumberjack/search?q=rolling&type=Issues&utf8=✓) (and reopen them if needed), instead of opening new ones.

**Comment by bpoplauschi** [comment]
This sounds like a configuration issue. Closing. Please reopen if it's still an issue for you
