### ISSUE TITLE
Issue: Docs would benefit from suggestion on how to access log files on iOS devices

### ISSUE THREAD

**Issue by SteveMinar** [CocoaLumberjack/CocoaLumberjack#519]
Hi,

Enjoying CocoaLumberjack so far. I'm trying to debug an iOS WatchKit Extension / iPhone Parent Application communication issue. The issue relates to the app lifecycle of the parent app. I need to debug from the point the parent app is not running so I can't attach to it in the debugger (haven't found a way to auto-attach at app startup, perhaps there's a way with a debug break command?)

I switched to relying on using a file logger using the defaults. In my case on iOS 8 this puts the log files in:
filePath = @"/var/mobile/Containers/Data/Application/220EBA9B-A69C-4EC7-A904-79DB1311572B/Library/Caches/Logs/com.domain.MyApp 2015-05-22 22-18.log"

I initially had a challenging time figuring out how to retrieve the logs or watch them live.
Early attempts to find them using Xcode's Device Window or using iExplorer proved challenging. It wasn't clear that I could download the "bundle" from Xcode and access the contents. For some reason, iExplorer wasn't showing the Logs directory being created in the Caches directory even on refresh.

I figured out the Xcode solution and iExplorer seems to work properly after updating the app. Interestingly, iExplorer would show updates to the Documents directory, verified by changing the Logs Directory via DDLogFileManagerDefault initWithLogsDirectory:.

A note about accessing these logs in the docs/wiki would be most helpful.

If there are better solutions for accessing live logs on the device or debugging an app before manually attaching to a process is possible, I'd love to hear about it. I have done some initial testing of the NSLog-CocoaLumberjack-connector which looks promising, but needs to be updated for 2.x.

Thanks,
Steve

**Comment by ffried** [comment]
One can always get the current path from the `DDLogFileManager`. For the simulator, there are tools like SimPholders that allow access to the simulators file system (even with Xcode sometimes changing the UUID).
If you're using DDOSLogger, you can also view logs using Console.app.

If you have any concrete suggestions on how to improve the docs, please do open a PR.
