### ISSUE TITLE
Format String Error

### ISSUE THREAD

**Issue by parkej60** [CocoaLumberjack/CocoaLumberjack#523]
I'm getting a warning saying format string is not a string literal (potentially insecure) after updating my library. If I switch the statements to NSLog I don't get the warning anymore.

Both the values being logged are NSNumber values. 

```
DDLogInfo(@"FEATURE ID %@",cdFeatureId.featureId);
DDLogInfo(@"FEATURE @%@",featureId);
```

**Comment by parkej60** [comment]
Also it seems like these cause the app to crash. So they're not just warnings.

**Comment by bpoplauschi** [comment]
This doesn't sound related to our library. Please add extra details if you have them

**Comment by rivera-ernesto** [comment]
Also please try either 2.0.3 or 2.1.0-beta.
