### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by idanhaviv** [CocoaLumberjack/CocoaLumberjack#524]
Hi,

I'm trying to follow the instructions in getting started but i'm unable to use CocoaPods in my company and the git 'submodule' command fails because of permissions:

"Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:CocoaLumberjack/CocoaLumberjack.git' into submodule path 'CocoaLumberjack' failed"

I tried downloading and extracting the zip file and following the rest of the instructions but it doesn't compile.
does the git submodule command does anything different from just downloading the zip file?

any other ideas?

thanks,

idan

**Comment by rivera-ernesto** [comment]
Try cloning using HTTPS instead `https://github.com/CocoaLumberjack/CocoaLumberjack.git`.

You don't have correctly setup your SSH keys in GitHub, so `git@` won't work.

**Comment by idanhaviv** [comment]
worked liked a charm! but now i have another issue:

after going through the installation process the build fails with this error:
'/CocoaLumberjack/Framework/Mobile/Lumberjack/Lumberjack-Prefix.pch'

that file doesn't exist in the project tree. and there's no directory named 'Lumberjack' under 'Mobile'
i do have CocoaLumberjack-Prefix.pch under a different directory
'/CocoaLumberjack/Framework/Lumberjack/CocoaLumberjack-Prefix.pch'

**Comment by rivera-ernesto** [comment]
Yes, probably you need to modify the Prefix File path in Build Settings. If that works could you try to make a pull request for it?
