### ISSUE TITLE
Central repository of contexts

### ISSUE THREAD

**Issue by 0xced** [CocoaLumberjack/CocoaLumberjack#529]
Third party framework authors [are encouraged](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/8adde11d0b16843cb45b81dc9b60d1430eb9b538/Documentation/CustomContext.md#example-2) to define custom contexts.

It would be nice to have a centralized place where all known contexts are listed, maybe in that same CustomContext.md file?

**Comment by rivera-ernesto** [comment]
Good idea. Maybe better inside a header file so it can be easily imported and used from code.

**Comment by nickolas-pohilets** [comment]
In my custom logger I want to display log contexts in ~~human~~developer-readable form. Would be nice also to have some kind of repository in the runtime.
Is there a reason why contexts are NSInteger's? Making them NSString's would minimize chances of context clashes without a centralized repo and would be readable without extra processing.
