### ISSUE TITLE
semaphore_wait_trap : failed to resume in time

### ISSUE THREAD

**Issue by sgadhvi** [CocoaLumberjack/CocoaLumberjack#53]
I get the below error while resuming the application there is some code in on resume which does the loging. but after showing splash screen app crashes with below logs.
What could be going wrong?

0   libsystem_kernel.dylib        	0x306eb060 semaphore_wait_trap + 8
1   libdispatch.dylib             	0x33879472 _dispatch_group_wait_slow + 146
2   libdispatch.dylib             	0x338793d2 dispatch_group_wait$VARIANT$mp + 22
3   XXXX                          	0x0012d38c +[DDLog lt_log:] (DDLog.m:959)
4   XXXX                          	0x0012c824 __+[DDLog queueLogMessage:asynchronously:]_block_invoke_1 (DDLog.m:476)
5   libdispatch.dylib             	0x338778c8 _dispatch_barrier_sync_f_invoke + 20
6   libdispatch.dylib             	0x33877728 dispatch_barrier_sync_f$VARIANT$mp + 56
7   libdispatch.dylib             	0x33877348 dispatch_sync_f$VARIANT$mp + 12
8   libdispatch.dylib             	0x338779f2 dispatch_sync$VARIANT$mp + 26
9    XXXX                          	0x0012c7d0 +[DDLog queueLogMessage:asynchronously:] (DDLog.m:484)
10  XXXX                         	0x0012ca8a +[DDLog log:level:flag:context:file:function:line:withTag:format:] (DDLog.m:554)

**Comment by rivera-ernesto** [comment]
Can someone share a simple project that reproduces the bug?

**Comment by bpoplauschi** [comment]
Closing, due to lack of response. Please comment and we can reopen it if you can provide a simple demo project.
