### ISSUE TITLE
swift_support branch fails to compile with cocoapods - can't find Classes/CocoaLumberjack.modulemap

### ISSUE THREAD

**Issue by mattlilek** [CocoaLumberjack/CocoaLumberjack#531]
My iOS project has cocoalumberjack configured to track the swift_support branch without locking to a specific commit (bad, I know). I discovered it was failing this morning, unable to find Classes/CocoaLumberjack.modulemap (you can also see this by running `pod lib lint` from within the CocoaLumberjack repo).

It looks like when #525 was merged into swift_support in fb70080, a couple of commits might have gotten lost along the way, specifically bd4d756 and ae92aea. Cherry-picking those seems to get things going farther.

Not sure if anything else got lost along the way or if something else is going on here, otherwise I'd just submit a PR.

**Comment by sbhklr** [comment]
+1 Just discovered that as well. I will stick to commit 9b31277c90d7c3968038af09a7bddd003aa28da9 meanwhile.

**Comment by rivera-ernesto** [comment]
Yes please do submit a pull request while we find out why commits got lost.

**Comment by bpoplauschi** [comment]
@mattlilek sorry for this, there was an issue with the modulemap being moved and the podspec was not updated with this new path. Also, I fixed another issue that was causing `pod lib lint` to fail.
Please not that now you have to work with the `Swift` subspec. All the details are here: af40293
