### ISSUE TITLE
Using "tag" as a property with a type of "id" causes a conflict with lots of code

### ISSUE THREAD

**Issue by akac** [CocoaLumberjack/CocoaLumberjack#532]
Lots of inherited code, projects, etc... use an "int" tag in the frameworks such as in NSMenuitem or NSCell or elsewhere. The fact that you have a property "tag" with a type of "id" - on one hand it forces us to update all code to specify the type, but on the other hand we have some code _we can't touch_ that now breaks because there is more than one type of "tag".

I'd suggest please to change "tag" to something else within the lumberjack framework.

**Comment by bpoplauschi** [comment]
I'm not sure we can downgrade our `tag` to an int. Right now, it can pretty much be anything.

**Comment by akac** [comment]
I am not recommending that - but renaming it. I renamed my copy to
referenceObject. That way it doesn't interfere with the method signature of
tag for everything else.

On Wed, Jun 24, 2015 at 2:11 PM, Bogdan Poplauschi <notifications@github.com
> wrote:

> I'm not sure we can downgrade our tag to an int. Right now, it can pretty
> much be anything.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CocoaLumberjack/CocoaLumberjack/issues/532#issuecomment-114996311>
> .
>



-- 

*Alex Kac - **President and Founder*

*Web Information Solutions, Inc.*

**Comment by gonefish** [comment]
I have a same problem, such as ViewUtils

**Comment by rivera-ernesto** [comment]
This is 2.x.x non-backwards compatible change so we can't go back to it. What you could do is define your own log macros where you handle the `id` <-> `int` conversion before passing it to `[DDLog log:...]`.

**Comment by bupojung** [comment]
have the same problem

**Comment by rivera-ernesto** [comment]
What about my suggestion?

**Comment by akac** [comment]
That doesn't work for us. Just the existence of the definition is the problem. The problem is that just existing means that other frameworks that may have a method of (id)sender and then call [sender tag] will get a compiler error because it doesn't know which tag is being used.

In our case, we had two choices - go and change EVERY third party framework/library we used, and all of our code to be more specific (which I think is a good thing too - but goes against our guidelines of not messing with third party code) or change it in CocoaLumberjack (which also goes against our policy…but is the lesser evil).

Frankly, your tag needs to be changed to something else. Its incorrectly named, it conflicts with Cocoa's conventions, and other libraries. That's really the only acceptable solution in any point of view. 

I'm fine with it being anything - I'm not saying it needs to be downgraded to "int", but it needs to be renamed. We renamed ours to referenceObject as per standard AppKit naming conventions in Apple's own classes. 

Its just a pain to merge in the future - but its better to be a pain in one spot than in dozens.

**Comment by rivera-ernesto** [comment]
> Frankly, your tag needs to be changed to something else. Its incorrectly named, it conflicts with Cocoa's conventions, and other libraries.

There is not such convention, a tag can be anything we want it to be, and definitely an object is more expressive and flexible than an `int`.

>  The problem is that just existing means that other frameworks that may have a method of (id)sender and then call [sender tag] will get a compiler error because it doesn't know which tag is being used.

Frameworks don't call the method directly but call a macro. If they import `DDLog.h` they would automatically import the legacy macros. We could work there so they call a new method with a `legacyTag:` parameter and converts those `int`'s into objets.

If they import the new `CocoaLumberjack.h` then they would already be using objects as tags.

Again the **real** problem is not having a common [logging façade](https://github.com/SLF4C/SLF4C) that abstracts the underlying log framework which would prevent frameworks from _requiring_ a log framework and version and would just fallback nicely to whatever the user chooses to use for logging.

**Comment by akac** [comment]
If its in AppKit that way in every single UIView and NSView - then its a de-facto convention. 

But I don't think you're getting my point. I am not saying to change it to an int. I am saying that you are using the name "tag" - which the coreOS and therefore many other apps and frameworks use as an int, thereby polluting the interface when calling an "id" type object. 

Cocoa uses the name "representationObject" with an "id" to denote what you are using as the named parameter "tag". I'm fine with your property being an "id" type. I am not fine with it being called a tag. 

And it doesn't matter whether frameworks or anything calls it directly. The problem is that IT EXISTS. I NEVER call DDLog directly - its always in the macro. But the fact that you have a property called tag that is an id - just the fact that it is in a public interface that the compiler can see means that it will conflict.

This should be blindingly obvious. I'm not trying to get into an argument regarding "real" problem - this is a simple issue where CocoaLumberjack has a property whose **name and type** conflicts with the name and type used throughout AppKit and UIKit. That's it.

**Comment by rivera-ernesto** [comment]
> If its in AppKit that way in every single UIView and NSView - then its a de-facto convention.

Those are properties in two UI classes. Not a convention or standard.

Feel free to propose your changes in a pull request so we can discuss over the implementation.

**Comment by akac** [comment]
UI classes that are used thousands of times...kind of the cornerstone of Apple development in general. And just including CocoaLumberjack into a project conflicts with them. 

Anything that conflicts with Apple's own classes - which are the de-facto conventions - is a problem. I'll give you my changes in a pull request.

**Comment by mutech** [comment]
> other frameworks that may have a method of (id)sender and then call [sender tag] will get a compiler error because it doesn't know which tag is being used

They get this error because they deserve it.

I would not trust and thus not use a piece of code that relies on nobody ever naming a method "tag" returning something else than an int. If you use third party code that makes such adventurous assumptions and you do not want to request from them to fix their code (or fix your own) then you should - in my humble opinion - not use conflicting libraries such as Lumberjack.

My not-so-humble opinion is that the compiler should not issue an error message, it should delete the source file.

... going to add a tag property somewhere now... ;-)

**Comment by shenyyi** [comment]
Will this be fixed in Obj-C version releases?

**Comment by ffried** [comment]
I agree with @rivera-ernesto that there is no real convention on how to use `tag`. However, if there's a better name, please open a PR.
