### ISSUE TITLE
Get a notification when a new message is logged?

### ISSUE THREAD

**Issue by gmaletic** [CocoaLumberjack/CocoaLumberjack#540]
I want some code in my app to be called whenever a message is logged. Do I need to make this code a "logger" itself…or can I register for a notification, or a callback, or…something? What's the best way to accomplish this?

Thanks very much.

**Comment by bpoplauschi** [comment]
I think the easiest way to achieve this is to write a logger yourself and do whatever you want in the `logMessage:` method.
