### ISSUE TITLE
Easing the migration from 1.9.x

### ISSUE THREAD

**Issue by chrisballinger** [CocoaLumberjack/CocoaLumberjack#541]
It looks like we are reaching the point where occasionally a library will have a dependency on 2.0 but most other libraries still depend on 1.9. I am aware of the migration guide, but it is simply not realistic to expect all library authors to all upgrade to 2.0 at the same time. Maintaining separate forks is costly and not all library authors are interested in merging PRs for 2.0 support.

I think it would make a lot of sense to consider one of the following:

1. Add back the old APIs but mark its usage as deprecated.
2. Make 2.0 a hard fork with no API collisions with 1.9, allowing both to co-exist.

Apologies if this has been addressed before, but a quick search didn't show anything.

Thanks!

**Comment by bpoplauschi** [comment]
You have a valid point, but I think in your case, you should just keep using 1.9.x until all your dependencies are upgraded. 

As for the 2.0 version, if we don't remove all the deprecated stuff here, then when. That is what a major release is really about, making breaking changes that allow your library to move forward. It would be very hard to maintain all those versions you want. 
I don't see this as a realistic objective for us, given the time we have for maintaining this project.

Out of curiosity, could you list the libraries that haven't upgraded to CL 2.0 yet? Maybe we can create PRs for them or contact the maintainers. Or if they are abandoned, you could fork them and switch to CL 2.0 if you need to.

**Comment by rivera-ernesto** [comment]
Ideally libraries shouldn't require a given version, or even require a given log framework bu simply a façade such as https://github.com/SLF4C/SLF4C/issues/1.

**Comment by chrisballinger** [comment]
@bpoplauschi CocoaAsyncSocket, XMPPFramework, YapDatabase. I've only seen one library using 2.0 so far (SVGKit) and I ended up not using it for that reason.

**Comment by bpoplauschi** [comment]
Closing, as there is little we can do here.
