### ISSUE TITLE
Unused Entitiy Issue (2.0.1)

### ISSUE THREAD

**Issue by x2on** [CocoaLumberjack/CocoaLumberjack#543]
I get a warning with the 2.0.1 release:
```
Unused Entitiy Issue
DDTTYLogger.h:44:22: Unused function 'DDMakeColor'
```

**Comment by ileitch** [comment]
Same issue here, pretty annoying if CocoaLumberjack is a dependency of many pods. I get a total of 8 warnings :)

**Comment by Landsi** [comment]
+1, also getting this

I'm turning warnings to errors, so when linting my pod:

    (...) error: unused function 'DDMakeColor' [-Werror,-Wunused-function]

**Comment by DD-P** [comment]
+1
I'm in the *there shall be no warnings* camp too :)
I've temporarily silenced this by setting -Wno-unused-function in the relevant targets for my OS X project.

For me ed317015 introduced this warning and reverting that commit returns my build to no warnings.

**Comment by rivera-ernesto** [comment]
Well that commit is only good practices, so it may be better to check the preprocessor `#if` checks.

**Comment by nonstriater** [comment]
+1, maybe "#pragma clang diagnostic ignored "can be used

**Comment by rivera-ernesto** [comment]
Please feel free to propose your solution in a pull request.

**Comment by iziz** [comment]
You can close this issue. (https://github.com/CocoaLumberjack/CocoaLumberjack/pull/553)

**Comment by rivera-ernesto** [comment]
Thanks!

**Comment by x2on** [comment]
Thanks a lot - would you please provide a bugfix release with that fix?

**Comment by lomaverde** [comment]
I have temperately added some code in my project to get ride of the warning 
   // Just to get ride of the warning
    __unused DDColor* dummyColor = DDMakeColor(1.0, 1.0, 1.0);

**Comment by timbodeit** [comment]
@iziz What about Mac OS? As far as I can tell you're only silencing the warning for the iOS Part.

If you're adding silencing pragmas to the header file, why not put them around the `#if` block, so they apply to both platforms?

**Comment by DD-P** [comment]
Please see #559, which has already been merged.

**Comment by timbodeit** [comment]
Cool ... thanks :)
Thought I had been looking at the code on master, when I was looking at `iziz/Cocoalumberjack`s master

**Comment by timbodeit** [comment]
+1 on the bugfix release that @x2on suggested :+1:
