### ISSUE TITLE
#import <CocoaLumberjack/CocoaLumberjack.h> error in the project Prefix.pch 

### ISSUE THREAD

**Issue by z8323664** [CocoaLumberjack/CocoaLumberjack#549]
tips :Could not build module 'Foundation'

**Comment by z8323664** [comment]
![ab hqjyc8klu21pbs2tb0_i](https://cloud.githubusercontent.com/assets/10832417/8496457/dd0071a6-21a7-11e5-8fe1-8afcaa7751f6.jpg)

**Comment by rivera-ernesto** [comment]
Erros in `NSObject.h` and other Foundation files look like a serious errors unrelated to CocoaLumberjack.

**Comment by z8323664** [comment]
Thank you for your answer, but I can use the <CocoaLumberjack/CocoaLumberjack.h> #import in AppDelegate.m.
In this case, I can't use CocoaLumberjack in every file.

**Comment by z8323664** [comment]
No problem, the new project is OK. thanks

**Comment by rivera-ernesto** [comment]
Good to know.
