### ISSUE TITLE
Use of unresolved identifier 'DDLogDebug'

### ISSUE THREAD

**Issue by apouche** [CocoaLumberjack/CocoaLumberjack#556]
Hey guys, i'm having trouble using `CocoaLumberjack 2.0.0` with swift 1.2 and cocoapods 0.37.2.
Because the `Podfile` has the `use_frameworks!`  command, adding:
 
```#import <CocoaLumberjack/CocoaLumberjack.h>``` 

in the bridging header is now useless but using `import Cocoalumberjack` seems to fail to retrieve the `DDLogMacros` and I get:

```Use of unresolved identifier 'DDLogDebug'``` 

When I take a look at the generated Cocoalumberjack module I do not see the macros (hence the issue) but I'm surprised to be the first one posting about this issue. How do you guys overcome that ?

**Comment by rivera-ernesto** [comment]
Please discuss in #383 so you can get more visibility.
