### ISSUE TITLE
#import <CocoaLumberjack/DDLegacyMacros.h> causing compile issues.

### ISSUE THREAD

**Issue by robotive** [CocoaLumberjack/CocoaLumberjack#558]
```
// DD_LEGACY_MACROS is checked in the file itself
#import <CocoaLumberjack/DDLegacyMacros.h>
```
... in DDLog.h causing the compiling to fail.

If you add CocoaLumberjack sources to your own project, it will fail to compile because of the #import change above, introduced in commit 717c54a7c5ddb8612777866bdc4c48a7c44a1e13

Replacing it with the following fixes the issue:
```
#import "DDLegacyMacros.h"
```
Thanks.

**Comment by rivera-ernesto** [comment]
We want to prevent as much as possible people from using legacy macros.

If you want to enable them just define `DD_LEGACY_MACROS` before importing the headers, it shouldn't matter if you manually added the source files to your project.

**Comment by robotive** [comment]
Even if i drop the legacy calls, by replacing DDLog.h imports with #import "CocoaLumberjack.h" and so on, it still won't compile, because of the #import i've mentioned in the issue description.

And you probably want that import to be guarded anyways (like it was until recently) or? Why would i wan't to add DDLegacyMacros.h to the project if i don't need the legacy code?

**Comment by DD-P** [comment]
I had the same issue as @robotive despite not using legacy calls.  I made the PR (#560) above which I hope fixes this for those manually including framework files, without damaging the more automated framework inclusions (i.e. CocoaPods).

Sadly I suspect this may not work, however as Travis looks to have failed on this branch.

**Comment by rivera-ernesto** [comment]
Travis is failing due to some Unit Tests as well. You better check what are the actual errors that show up.

**Comment by bpoplauschi** [comment]
Right now, Travis fails because of the Swift code during pod spec lint

**Comment by robotive** [comment]
Works fine after @DD-P's pull request was merged.

Thanks.

**Comment by bpoplauschi** [comment]
Closing, issue was fixed
