### ISSUE TITLE
[DDLogFileManagerDefault initWithLogsDirectory:defaultFileProtectionLevel:]: unrecognized selector

### ISSUE THREAD

**Issue by sahara108** [CocoaLumberjack/CocoaLumberjack#561]
My app have a lot of work in background, so that, it is sometime crashed due to permission to write log into file. I am trying to set the permission to NSFileProtectionCompleteUntilFirstUserAuthentication. I can see the method initWithLogsDirectory:defaultFileProtectionLevel: in DDLogFileManagerDefault, but it is throw error like that. 
I am working on iOS.

**Comment by bpoplauschi** [comment]
Does this issue still happen?

**Comment by bpoplauschi** [comment]
Closing the issue, please reopen if you can provide more info (Lumberjack version, Xcode version, ...)
