### ISSUE TITLE
Cocoapods install incomplete

### ISSUE THREAD

**Issue by joshwand** [CocoaLumberjack/CocoaLumberjack#562]
When I do pod install, cocoapods doesn't do a full install-- it only installs CocoaLumberjack.swift (none of the objc .m and .h files).

I have created a simple project (using xcode simple single-view project) with the following Podfile:

    platform :ios
    
    pod "CocoaLumberjack" 

but all I get when do `pod install` is:

<img width="411" alt="classes 2015-07-15 11-23-48" src="https://cloud.githubusercontent.com/assets/22531/8706279/cec2d31e-2ae3-11e5-968a-b3866d803052.png">

cocoapods versions:

    cocoapods (0.37.2, 0.37.0)
    cocoapods-core (0.37.2, 0.37.0)
    cocoapods-downloader (0.9.0)
    cocoapods-plugins (0.4.2)
    cocoapods-trunk (0.6.1, 0.6.0)
    cocoapods-try (0.4.5, 0.4.3)

**Comment by rivera-ernesto** [comment]
Please check here https://github.com/CocoaLumberjack/CocoaLumberjack/issues/405#issuecomment-116450615.

**Comment by joshwand** [comment]
I should clarify that I am using ObjC. When I do #import it cannot find CocoaLumberjack.h.

This worked for me a few months ago-- when I did `pod install` I got the full set of .m and .h files. But I had to kill that branch and now when I try it again it no longer works.

**Comment by joshwand** [comment]
Removing `platform :ios` from the Podfile installs CocoaLumberjack ObjC files correctly. My cocoapods-fu is not strong, so not sure why this would be?

**Comment by rivera-ernesto** [comment]
Could you try opening an issue in https://github.com/CocoaPods/CocoaPods?
