### ISSUE TITLE
Undefined symbols for architecture x86_64 or arm64

### ISSUE THREAD

**Issue by minglini** [CocoaLumberjack/CocoaLumberjack#563]
I'm getting linking errors when trying to compile my app that uses CocoaLumberjack (latest version with cocoa pods) in iOS 8, under a 64 bits architecture. It happens with x86_64 (emulator) or arm64 (device):

Example when running with arm64:

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_DDTTYLogger", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_DDASLLogger", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_DDLog", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture arm64

Could you please let me know how to fix this issue?
Thanks

**Comment by psulak** [comment]
Very similar problem here. Had CocoaLumberjack v2.0.0 release running smoothly for the past 6 weeks or so. Yesterday I updated to v2.0.1 release. With v2.0.1, my iOS project builds and runs fine in the Simulator. But when I target the Device I'm getting similar linker errors to what minglini is seeing.

In Xcode's Build Phases -> Link Binary With Libraries, "linkCocoaLumberjack-iOS-Static.a" is always red. I'm not quite sure what I screwed up:-/

**Comment by minglini** [comment]
I solved the problem in my project. I don't know why but when i ran "pod install" for the first time, the pod was not added to the project property "Other Linker Flags". I ran again and the "pod install" was added the pod configuration to the "Other Linker Flags" property. The project then was built with success.

**Comment by dms90** [comment]
I have the same error using v2.3.0.

`Undefined symbols for architecture x86_64:
  "CocoaLumberjack.DDLogError (@autoclosure () -> Swift.String, level : __C.DDLogLevel, context : Swift.Int, file : Swift.StaticString, function : Swift.StaticString, line : Swift.UInt, tag : Swift.AnyObject?, asynchronous : Swift.Bool) -> ()", referenced from:`

**Comment by Guicai-Li** [comment]
I used pod 'CocoaLumberjack/Core', '~> 2.3.0' can fix this problem.
