### ISSUE TITLE
    - WARN  |  Headers/Private/CocoaLumberjack/DDTTYLogger.h:44:22: warning: unused function 'DDMakeColor' [-Wunused-function]

### ISSUE THREAD

**Issue by danfeng** [CocoaLumberjack/CocoaLumberjack#565]
- WARN  |  Headers/Private/CocoaLumberjack/DDTTYLogger.h:44:22: warning: unused function 'DDMakeColor' [-Wunused-function]

**Comment by bpoplauschi** [comment]
Fixed by #553 and extended fix with #559. Those will get published into a new release soon.

**Comment by 0xced** [comment]
Do you have an ETA for the next release?

**Comment by rivera-ernesto** [comment]
I think we shouldn't be afraid of making 2.0.x releases more often, people can always go back to a previous version while exposing the code to more users for testing.
