### ISSUE TITLE
Cannot install via CocoaPods

### ISSUE THREAD

**Issue by vomako** [CocoaLumberjack/CocoaLumberjack#567]
I have installed CocoaPods and I added CocoaLumberjack to the Podfile. I also added #import <CocoaLumberjack/CocoaLumberjack.h>. My project compiles without errors.

After adding [DDLog addLogger:[DDASLLogger sharedInstance]], I get the following error message:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_DDASLLogger", referenced from:
      objc-class-ref in vmkAppDelegate.o
  "_OBJC_CLASS_$_DDLog", referenced from:
      objc-class-ref in vmkAppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I've tried so many things and spent hours trying to make this work:
- Re-installed CocoaPods
- Tried to install CocoaLumberjack manually (did not work)

I use: Xcode 7 beta 4
Target: iOS 9

**Comment by rivera-ernesto** [comment]
Please take a look at [similar issues](https://github.com/CocoaLumberjack/CocoaLumberjack/search?q=cocoapods&type=Issues&utf8=✓) first.

**Comment by abuttlemur** [comment]
I'm receiving the same error using Cocoapods 0.38.2, I've tried every suggestion I could find, these included:
-using an olderversion of CocoaLumberjack (I've tried 2.0 and 2.0.1)
-removing the "platform" section from the Podfile
-Manually installing (The instructions for this seem to be outdated, as files mentioned in the steps do not appear in the project)

After installing the Pod I have changed the "Build Active Architecture Only" to NO.
I have no other Pods in my Podfile, its just CocoaLumberjack.  At this point any help would be appreciated.

**Comment by bpoplauschi** [comment]
Guys: can you properly install other libraries via cocoapods?

**Comment by rivera-ernesto** [comment]
2.0.3 seems to be installing fine as well as 2.1.0-beta. Feel free to reopen this otherwise.

**Comment by dms90** [comment]
I'm having the same error using 2.3.0. Do you have any update?

**Comment by bpoplauschi** [comment]
@dms90 try to delete the derived data folder.

**Comment by dms90** [comment]
Thanks @bpoplauschi ! It works :) 👏

**Comment by bpoplauschi** [comment]
Glad to hear that.
