### ISSUE TITLE
Add possibility to turn off asynchronous logging without framework code editing

### ISSUE THREAD

**Issue by krypt-lynx** [CocoaLumberjack/CocoaLumberjack#569]
it will be very useful in case if CocoaLumberjack is installed using cocoa pods.

**Comment by bpoplauschi** [comment]
Would you be interested with making a pull request with this feature?

**Comment by krypt-lynx** [comment]
This feature is actually implemented, but not referenced in documentation. So, it is a reason why request is closed.
You need to define special definition in prefix.pch before including CocoaLumberjack.
I have no access to source code right now and I can not to copypaste details right now.
