### ISSUE TITLE
Xcode 7 beta 5 incompatibility (swift2)

### ISSUE THREAD

**Issue by vadim-fueled** [CocoaLumberjack/CocoaLumberjack#572]
.../CocoaLumberjack.swift:66:203: error: 'UWord' has been renamed to 'UInt'
.../CocoaLumberjack.swift:70:202: error: 'UWord' has been renamed to 'UInt'
.../CocoaLumberjack.swift:74:202: error: 'UWord' has been renamed to 'UInt'
.../CocoaLumberjack.swift:78:205: error: 'UWord' has been renamed to 'UInt'
.../CocoaLumberjack.swift:82:203: error: 'UWord' has been renamed to 'UInt'
.../CocoaLumberjack.swift:89:26: error: 'lastPathComponent' is unavailable: Use lastPathComponent on NSString instead.
.../CocoaLumberjack.swift:89:44: error: 'stringByDeletingPathExtension' is unavailable: Use stringByDeletingPathExtension on NSString instead.

**Comment by MaddTheSane** [comment]
I’ll look into it.

**Comment by rivera-ernesto** [comment]
Thanks @MaddTheSane just next time lets make a pull request to add commits ;)

**Comment by MaddTheSane** [comment]
Okay. Will do.

**Comment by vadim-fueled** [comment]
Thanks!
