### ISSUE TITLE
Swift 2 branch broken with Carthage

### ISSUE THREAD

**Issue by jschmid** [CocoaLumberjack/CocoaLumberjack#582]
#581 removed some project targets. Since the PR has been merged, Carthage is not able to build an iOS framework anymore. We are also unable to take the "Mac" version of the framework.

Is there a reason other than "There are too many targets just for framework" to have removed those?

**Comment by sinoru** [comment]
I didn't think about Carthage. Sorry. So I reverted it. Now Carthage can build all platforms (Mac, iOS, watchOS)

**Comment by jschmid** [comment]
Thx!
