### ISSUE TITLE
How to use CocoaLumberjack with Xcode 7 and Swift 2.0 while deploying to iOS 7?

### ISSUE THREAD

**Issue by mman** [CocoaLumberjack/CocoaLumberjack#584]
Swift 2.0 supports deployment to iOS 7 and OS X 10.9.

Lumberjack itself is working fine on iOS 5 +

What's the best way to make Lumberjack play well in Swift 2.0 based projects that deploy back to iOS 7?

The framework based approach is available only from iOS 8.

If I understand it correctly this will require to link the static lumberjack library into the project and then manually import CocoaLumberjack.swift file and generate a bridging header including CocoaLumberjack.h, correct?

It's not necessary to import CocoaLumberjack in any of the swift files, just use the DDLogInfo and other functions, they will be available.

works like a charm, closing the issue as noise...

**Comment by superZhen** [comment]
Correct, i have already adopted the static library solution. By the way, there is no need to import CocoaLumberjack.swift since it will automatically be imported, and also it needs a fat static library to support platforms of  armv7, armv7s and arm64, x86_64, i386.
