### ISSUE TITLE
Any Guideline on how to use CocoaLumberjack in Swift 1.2

### ISSUE THREAD

**Issue by KingWu** [CocoaLumberjack/CocoaLumberjack#585]
Any Guideline on how to use CocoaLumberjack in Swift 1.2?

**Comment by rivera-ernesto** [comment]
[Lots](https://github.com/CocoaLumberjack/CocoaLumberjack/search?q=swift&type=Issues&utf8=✓).

Please make search before opening a new issue.

**Comment by KingWu** [comment]
As search before, the information is abused. No document

**Comment by rivera-ernesto** [comment]
Probably yes. But it is still better to discuss there than to have it separated over duplicate issues.
