### ISSUE TITLE
Per file log level doesn't work for me.

### ISSUE THREAD

**Issue by shawnmorrison** [CocoaLumberjack/CocoaLumberjack#591]
I have a feeling I'm doing something wrong but I don't see anything in the documentation to clear this up. When I add the following to one of my files:

```static const DDLogLevel ddLogLevel = DDLogLevelOff;```

The DDLog messages in this file are still logged to the console. Additionally that line warns `Unused variable 'ddLogLevel'`. Do I need to define ddLogLevel globally somewhere?

**Comment by rivera-ernesto** [comment]
Please check here https://github.com/CocoaLumberjack/CocoaLumberjack/issues/478#issuecomment-81632833.

**Comment by bpoplauschi** [comment]
@shawnmorrison does the [#478 (comment)](https://github.com/CocoaLumberjack/CocoaLumberjack/issues/478#issuecomment-81632833) reply to your question?

**Comment by bpoplauschi** [comment]
Closing due to lack of response.
