### ISSUE TITLE
Designated Initializer Issues

### ISSUE THREAD

**Issue by stephencelis** [CocoaLumberjack/CocoaLumberjack#592]
Both DDLogMessage and DDLogFileInfo define designated initializers (using `NS_DESIGNATED_INITIALIZER`), but do not fulfill the requirement that their superclass's initializer (`init`) is overridden. This causes two of these warnings:

> Method override for the designated initializer of the superclass '-init' not found

Any reason not to drop `NS_DESIGNATED_INITIALIZER` in these two cases? Designated initializers seem to be most important for classes intended to be subclassed, and I'm not sure these are.

**Comment by rivera-ernesto** [comment]
You are right. Do you want to propose a pull request?

**Comment by stephencelis** [comment]
Done!

**Comment by timbodeit** [comment]
When trying to merge the current `swift_2.0` branch into `master`, 58ae9482 conflicts with b765caf.

To me it looks like you both meant to fix the same issue in two different ways.
You dropped the `NS_DESIGNATED_INITIALIZER` argument, whereas @sinoru added
`- (instancetype)init NS_UNAVAILABLE;`

On first sight, I personally like @sinoru s approach better. 

Any input on why one is objectively better than the other or  how the merge conflict should be resolved?

**Comment by stephencelis** [comment]
I also like @sinoru's approach. Hadn't noticed `NS_UNAVAILABLE` pop up in iOS 8.

**Comment by rivera-ernesto** [comment]
One could merge `swift_2.0` into `master` in a fork, fix que conflict and pull request that to update `swift_2.0` here.

**Comment by bpoplauschi** [comment]
@rivera-ernesto we need to take care of this fast, no point in delaying it. I will allocate some time for this (merge the 2.0 swift branch into master and cut a beta release).

**Comment by rivera-ernesto** [comment]
I think we should be less afraid of releasing both a 2.0.2 and a 2.1.0 beta. Thanks @bpoplauschi !

**Comment by timbodeit** [comment]
I'm currently working on getting the merge conflicts resolved. Will push a proposed resolution in around 20 minutes.

**Comment by timbodeit** [comment]
@bpoplauschi See [#614](https://github.com/CocoaLumberjack/CocoaLumberjack/pull/614)
