### ISSUE TITLE
segfault when compiling with swift

### ISSUE THREAD

**Issue by andyyan** [CocoaLumberjack/CocoaLumberjack#594]
I'm trying to integrate cocoaLumberjack with a swift project.  
I tried the following in my podfile:

pod 'CocoaLumberjack/Swift', :git => 'https://github.com/CocoaLumberjack/CocoaLumberjack.git', :branch => 'swift_2.0'
pod 'CocoaLumberjack', :git => 'https://github.com/CocoaLumberjack/CocoaLumberjack.git', :branch => 'swift_2.0'

or only:
pod 'CocoaLumberjack', '~>2.0.1'

In the latter case I had to manually added CocoaLumberjack.swift into the pod project.  But in either cases I get a compile error saying:

CompileSwift normal x86_64 ..../Pods/CocoaLumberjack/Classes/CocoaLumberjack.swift
Build/Intermediates/Pods.build/Debug-iphonesimulator/CocoaLumberjack.build/unextended-module.modulemap:7:5: error: expected umbrella, header, submodule, or module export
    textual header "DDLogMacros.h"
Command failed due to signal: Segmentation fault: 11

Any ideas?

**Comment by andyyan** [comment]
I think i figured out the problem.  I need xCode 7 for this to work.

For xcode 6.3 I should use the branch "swift_support" ?

**Comment by rivera-ernesto** [comment]
For 6.3 you should use the master branch. swift_support was old and already merged so I just deleted it now.
