### ISSUE TITLE
Cocoapods + use_frameworks: Missing headers in modulemap

### ISSUE THREAD

**Issue by appsforall** [CocoaLumberjack/CocoaLumberjack#596]
I'm running a project with CocoaLumberjack for logging (which is a great tool btw). We are now migrating to use modules / frameworks for the pods we are depending on. However with the use_frameworks! in our podfile, we run into the issue that the CocoaLumberjack module cannot be built. We investigated it and searched for similar problems and came to the conclusion that the issue is the same as this one described within the cocoa pods project: https://github.com/CocoaPods/CocoaPods/issues/3847.

As Cocoapods describes there, the problem lies in the module map of the project and should be fixed there. I tried that solution by updating the .modulemap file of the cocoa lumberjack framework and that works as expected. 

Now, however, each time after a pod update, we have to manually change the module map back. Would be great if you could incorporate this change in your next update. I will make a PR for you to investigate.

Thanks!
Wim

**Comment by appsforall** [comment]
Going through your code I do see btw that the .modulemap of your actual framework  is way more extended than the .modulemap in your classes folder. Maybe making those match each other will already resolve it?

**Comment by appsforall** [comment]
Adding another comment :-) I see this is already solved with the swift_support branch, which is already integrated into master. When will the version with this update be released in cocoa pods? Version 2.0.1 does not contain these changes yet. Thanks!!

**Comment by rivera-ernesto** [comment]
Closing this in favor of https://github.com/CocoaLumberjack/CocoaLumberjack/issues/405#issuecomment-114543517.
Please let try to keep the discussion in one place.

**Comment by rivera-ernesto** [comment]
Also check https://github.com/CocoaLumberjack/CocoaLumberjack/issues/588 where we are trying to come up with a new release.
