### ISSUE TITLE
Swift 2.0 Branch + Use of undeclared type '...'

### ISSUE THREAD

**Issue by Luissoo** [CocoaLumberjack/CocoaLumberjack#598]
Hi,

I'm using CocoaLumberjack 2.0.1 of the Swift 2.0 branch in my project.
I install it with Pods here is the line in my PodFile
```
pod 'CocoaLumberjack/Swift', :git => "https://github.com/CocoaLumberjack/CocoaLumberjack.git", :branch => 'swift_2.0'
```

But when i try to compile i got differents errors on the file CocoaLumberjack.swift who is in my project.
<img width="307" alt="capture d ecran 2015-09-23 a 17 26 19" src="https://cloud.githubusercontent.com/assets/5419579/10049542/400640d6-6218-11e5-99ec-b34d4d40bdf5.png">

I don't understand why i got those errors that i didn't have in the previous version.

Thanks

**Comment by rivera-ernesto** [comment]
Closing in favor of #588. Please search before opening new issues.
