### ISSUE TITLE
Carthage build Failure : Swift

### ISSUE THREAD

**Issue by wm-j-ray** [CocoaLumberjack/CocoaLumberjack#599]
Environment:
     - xCode 7 AppStore Version
    - Carthage 0.9.2
    - Cartfile is:
          github "CocoaLumberjack/CocoaLumberjack"

    	CompileSwift normal x86_64       ~/Desktop/test/Carthage/Checkouts/CocoaLumberjack/Classes/CocoaLumberjack.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler

    A shell task failed with exit code 65:

    Two Failures

    Carthage/Checkouts/CocoaLumberjack/Classes/DDLog.m:844:17: warning: method override for the designated initializer of the superclass '-init' not found [-Wobjc-designated-initializers]
    Carthage/Checkouts/CocoaLumberjack/Classes/DDFileLogger.m:1103:17: warning: method override for the designated initializer of the superclass '-init' not found [-Wobjc-designated-initializers]
    Carthage/Checkouts/CocoaLumberjack/Classes/CocoaLumberjack.swift:59:236: error: '#' has been removed from Swift; 'string' already has an argument label
    Carthage/Checkouts/CocoaLumberjack/Classes/CocoaLumberjack.swift:67:194: error: 'UWord' has been renamed to 'Uint'

Any idea how I can fix this?
Thanks in advance

**Comment by rivera-ernesto** [comment]
I think this is not pointing to the current `swift_2.0` branch.

**Comment by wm-j-ray** [comment]
I looked at Master which is constantly updated vs Swift branch which is 28 days old. 
So should I point to Swift 2.0?

**Comment by rivera-ernesto** [comment]
As you can tell by the name of the branch, `swift_2.0` is the only one that supports Swift 2.

**Comment by wm-j-ray** [comment]
I just wanted to use Carthage. The Swift reference was just the portion of the Carthage error message.  I'll try again with the Swift branch.

**Comment by rivera-ernesto** [comment]
Yes please. Also we should be updating it with master changes once we make a release.

**Comment by rivera-ernesto** [comment]
Seems it now builds, although showing warnings (#623).
