### ISSUE TITLE
Doesn't log to TTY after break to debugger 

### ISSUE THREAD

**Issue by hyling** [CocoaLumberjack/CocoaLumberjack#601]
I have CocoaLumberjack setup to log to DDASLLogger, DDTTYLogger, and DDFileLogger.  After the debugger is tripped in Xcode 7 I noticed no logs are sent to the console for the entire method.  Luckily it seems to still log to the FileLogger.

**Comment by bpoplauschi** [comment]
Please create a demo project with this issue, if possible. It doesn't sound like an issue with the library itself.

**Comment by rivera-ernesto** [comment]
Version?

**Comment by hyling** [comment]
CocoaLumberjack version 2.1.0, installed via CocoaPods.

**Comment by hyling** [comment]
I'll create one as soon as I get a chance, probably next week.

On Wed, Oct 21, 2015 at 4:28 PM, Bogdan Poplauschi <notifications@github.com

**Comment by hyling** [comment]
I can't reproduce this in the demo app.  Closing it for now.
