### ISSUE TITLE
Per file log level in swift

### ISSUE THREAD

**Issue by alak** [CocoaLumberjack/CocoaLumberjack#603]
Hey,

How can I use per file log level in swift ?

In objective-C I use : 

```
static DDLogLevel ddLogLevel = DDLogLevelOff;

@implementation MyClass
#pragma mark - DDLog

+ (DDLogLevel)ddLogLevel {
    return ddLogLevel;
}

+ (void)ddSetLogLevel:(DDLogLevel)logLevel {
    ddLogLevel = logLevel;
}
@end
```

Thank you :)

**Comment by rivera-ernesto** [comment]
Probably a #591 duplicate. Also may be better to check/ask in #405.

**Comment by chbeer** [comment]
You can do this:

- add a static variable to each class: `public static var logLevel: DDLogLevel = defaultDebugLevel`
- add the `level` parameter to DDLogXYZ: `DDLogError("… log msg...", level: ClassName.logLevel)`
- configure the log level per class: `ClassName.logLeve = DDLogLevel.Error`

It's a bit more complicated, but I'm glad I found this solution.

**Comment by Alak** [comment]
Thank you for this response, I'll try it now !
