### ISSUE TITLE
CocoaLumberjack for tvOS

### ISSUE THREAD

**Issue by ckrey** [CocoaLumberjack/CocoaLumberjack#606]
I started doing some work on tvOS and would like to continue to use CocoaLumberjack.
Any plans yet to make it available under tvOS?
If not, I would be happy to prepare a PR

**Comment by rivera-ernesto** [comment]
You can check the related pull requests by making a [search](https://github.com/CocoaLumberjack/CocoaLumberjack/search?q=tvOS&type=Issues&utf8=✓).

Feel free to comment on them and contribute. Thanks.
