### ISSUE TITLE
currentLogFileInfo not safe to get immediately after creating a fileLogger

### ISSUE THREAD

**Issue by rickpasetto** [CocoaLumberjack/CocoaLumberjack#607]
I am using CocoaLumberjack in my iOS app and have the following in my code:

```
    DDFileLogger *fileLogger = [[DDFileLogger alloc] init];
    fileLogger.rollingFrequency = 60 * 60 * 24; // 24 hour rolling
    fileLogger.logFileManager.maximumNumberOfLogFiles = 3;
    fileLogger.maximumFileSize = 1024 * 1024; // 1 MB max file size
    [DDLog addLogger:fileLogger];
    // Log file location
    DDLogInfo(@"File Logger logging to \"%@\"", fileLogger.currentLogFileInfo.filePath);
```

Unfortunately, sometimes I get a crash accessing `fileLogger.currentLogFileInfo` because, I think, there is a race condition between when `DDFileLogger` is added and when `currentLogFileInfo` is safe to get (this only happens the very first time the app is initialized).  To work around it I use `fileLogger.logFileManager.logsDirectory` instead of `fileLogger.currentLogFileInfo.filePath` (although I would really prefer the latter).

Is this a known problem, or am I doing something wrong?
https://guides.github.com/features/mastering-markdown/

**Comment by rivera-ernesto** [comment]
There are some [related](https://github.com/CocoaLumberjack/CocoaLumberjack/search?q=currentLogFileInfo&type=Issues&utf8=✓) issues and pull requests but tis sounds slightly different.

Anyway this shouldn't crash. Could you experiment and make a pull request if you find a fix?

**Comment by rickpasetto** [comment]
I will give it a shot but it may take some time.  Stay tuned.
