### ISSUE TITLE
swift_2.0 branch should not require Xcode 7.1

### ISSUE THREAD

**Issue by atheken** [CocoaLumberjack/CocoaLumberjack#609]
It appears that the Swift 2.0 branch has added tvOS support (which is great). 

However, 7.1 is currently in Beta, while Swift 2.0 is supported in Xcode 7.0.x (which is GM'd).

I'm using Carthage to pull and build the `swift_2.0` branch, but cannot build the latest because I don't have (or want) to build with a Beta Xcode.

I'm not really sure about the how the team wants to use branches, but I think features/changes that require new betas of XCode should probably be segregated from previous version of Xcode.

**Comment by rivera-ernesto** [comment]
Right, I didn't think about it.

Would revert #605 be enough? We can merge that pull request to a separate branch if so.

**Comment by atheken** [comment]
@rivera-ernesto, thanks for the reply, and all your work on this project. It's great.

I resolved this by targeting my Cartfile to the rev before:

`github "CocoaLumberjack/CocoaLumberjack" "479279f102a8ab23084290697bafa77aac0d1bd"`

But as far as process goes, I'd recommend reverting and then putting those changes on a `tvOS` branch. Just my 2 cents.

**Comment by ekimia** [comment]
totally agree with @atheken here

**Comment by rivera-ernesto** [comment]
@atheken  Reverting it, just let me know if that fixes it please.

Also creating a separate tvOS branch.

**Comment by atheken** [comment]
Sure did! 

Thanks for being awesome, @rivera-ernesto!
