### ISSUE TITLE
Using Lumberjack on other threads

### ISSUE THREAD

**Issue by czuvichEvernote** [CocoaLumberjack/CocoaLumberjack#61]
It looks like there may be an issue using the DDLog macros on other threads.  I initialized the framework on the main thread (appDidFinishLaunching), but whenever I try to use the DDLog macros on a background thread nothing is written.  I am writing logs out on a subclassed NSOperation class.

**Comment by alakoring** [comment]
I just ran into a problem here too. I had a custom log in a thread, and an error-level log in the main thread. Looks like the main thread is blocked by `dispatch_sync(_loggingQueue, logBlock)`.
