### ISSUE TITLE
iOS 9 warning

### ISSUE THREAD

**Issue by zveljkovic** [CocoaLumberjack/CocoaLumberjack#612]
In new XCode and iOS 9 using objc there is "Method override for the designated initializer of the superclass '-init' not found" warning in DDLog.m and DDFileLogger.m

**Comment by rivera-ernesto** [comment]
Please make a [search](https://github.com/CocoaLumberjack/CocoaLumberjack/search?q=Method+override+for+the+designated+initializer+&type=Issues&utf8=✓) before. 

Seems that this was fixed by #590.

**Comment by bpoplauschi** [comment]
Fixed by #590 as @rivera-ernesto noted.
