### ISSUE TITLE
Two instances of CocoaLumberjack

### ISSUE THREAD

**Issue by ajitam** [CocoaLumberjack/CocoaLumberjack#616]
Hi, I'm developing an SDK which is using CocoaLumberjack. It will be distributed over CocoaPods, so in SDK's .podspec file I have dependency to CocoaLumberjack.

What I will like to do is to use logging separately for SDK. So I don't know if user will use CocoaLumberjack or not, but I will like to toggle logging on/off for SDK.

Is there any example which covers this situation?

thx, matija

**Comment by rivera-ernesto** [comment]
CocoaLumberjack ideally shouldn't be a "dependency" of 3rd party libraries but use CL in case the user is using it.

I did than with a library as explained [here](https://github.com/CyberAgent/NBULog#1-conditionally-use-nbulog) but that may have changed a little bit.

In any case you should try to avoid forcing the library into the user project and at least provide subspecs with and without CL.

**Comment by ajitam** [comment]
Good point, I'll take a look at it.

**Comment by rivera-ernesto** [comment]
Also there's an effort to create a logging "façade" to abstract the logging framework and use just whatever the user decides in this project: https://github.com/SLF4C/SLF4C
