### ISSUE TITLE
What is required for 2.1.0 to be released?

### ISSUE THREAD

**Issue by parfeon** [CocoaLumberjack/CocoaLumberjack#625]
As title shows, what is required for 2.1.0 to be released? Maybe it is possible to provide assistance from community side to make it happen?

Best regards,
Sergey Mamontov

**Comment by bpoplauschi** [comment]
Those the items marked for the 2.1.0 release. Even though some of them are discussions, we need to make sure we cover everything.  Other than that, I don't see major showstoppers for the 2.1.0 release. 
@rivera-ernesto what do you think?

Regarding backwards compatibility, our latest 2.0.3 release works with Xcode 6 and the 2.1.0 release will require Xcode 7. We also have an Xcode6 branch that can be used for potential 2.0.x releases.

**Comment by rivera-ernesto** [comment]
I think that as far as major changes are not planned for 2.1.x we could make an initial 2.1.0 release.

In the mean time you can use the beta release just as well, we haven't got many issues for that release so either it was pretty good or more people should be trying it ;)

**Comment by parfeon** [comment]
@rivera-ernesto Is there any timeline for initial release? We use CocoaLumberjack as dependency in our project and if user will notice during update "beta" keyword in version name, I think he will start worry :)

Best regards,
Sergey

**Comment by rivera-ernesto** [comment]
We should make are least one last beta release as some potentially API-changing merges were made to master. Give that a try and release.

As for making Lumberjack a dependency, it should be used if present but fallback to `NSLog` [otherwise](https://github.com/CocoaLumberjack/CocoaLumberjack/issues/337#issuecomment-150193964).

**Comment by bpoplauschi** [comment]
I just released a new version of 2.1.0, this time a release candidate. From my point of view, we need to update the documentation and we are good to go for a 2.1.0 official release.

**Comment by parfeon** [comment]
Noticed what very few macro failed to evaluate correct conditions for tvOS, but watch OS is fine now!
Waiting for 2.1.0 release announcement. Thanks for your hard work on this project!

Best regards,
Sergey

**Comment by bpoplauschi** [comment]
The official 2.1.0 has been released. Please try it out and let us know if there are any issues.

**Comment by parfeon** [comment]
Hi @bpoplauschi 
Thanks for release!

There is still issue with warnings because of NS_DESIGNATED_INITIALIZER and not implemented -init methods for those classes, who declared designated initialisers. Because of this issue, when I push my own pod to trunk I need to tell it what it should ignore warnings from check on CocoaLumberjack library (with --allow-warnings )

Best regards,
Sergey

**Comment by rivera-ernesto** [comment]
There was some discussion about how to solve that https://github.com/CocoaLumberjack/CocoaLumberjack/pull/619#issuecomment-147705557.
