### ISSUE TITLE
Removal of xcodeproj now instructions are invalid

### ISSUE THREAD

**Issue by ichibod** [CocoaLumberjack/CocoaLumberjack#632]
You cannot install manually with the instructions provided as the .xcodeproj file was removed from the repo. https://github.com/CocoaLumberjack/CocoaLumberjack/commit/f2d82835f53a4f33d80ac2ac5551ceb68346cc70

**Comment by bpoplauschi** [comment]
Updated the manual install instructions. Please note that we only recommend the install via CocoaPods or Carthage.

**Comment by rivera-ernesto** [comment]
Off course you can still try to do it manually and a pull request to update the instructions would be appreciated.

**Comment by ichibod** [comment]
@rivera-ernesto Oh of course. Already had to do that at least once. We'll see if I can get that going with the deadline on the horizon...
