### ISSUE TITLE
Swift 2.0 branch merged not working

### ISSUE THREAD

**Issue by vCrespoP** [CocoaLumberjack/CocoaLumberjack#635]
Hello! Until now I've been working with the branch Swift_2.0

But now it has disappeared and by using the pod as it follows I'm getting some old mistakes in CocoaLumberjack.swift:
    pod 'CocoaLumberjack/Swift'

Errors:
"CocoaLumberjack.swift:57:246: '#' has been removed from Swift; 'string' already has an argument label"
"CocoaLumberjack.swift:17:8: Cannot import module being compiled"

Any idea? Should I use the pod in any different way?
Thanks in advance.

**Comment by sinoru** [comment]
Please use master branch, currently Swift_2.0 branch merged into master branch.

**Comment by vCrespoP** [comment]
Hi thanks for your quick response :)

Ok, so no subspec, like this:
pod 'CocoaLumberjack'

Now it compiles but it's not recognizing any macro like:
DDLogError("Test Log") // Or Info, Debug, ...
* Use of unresolved identifier 'DDLogError' *

**Comment by bpoplauschi** [comment]
I will update the documentation soon. You need the `pod 'CocoaLumberjack/Swift'` to get the Swift code as well.

**Comment by vCrespoP** [comment]
Hi @bpoplauschi  

Yes, that's what I had, but then is the case I was getting: Not compiling... Don't close it yet please.

**Comment by bpoplauschi** [comment]
Which version of Lumberjack did you get from CocoaPods?

**Comment by vCrespoP** [comment]
pod 'CocoaLumberjack/Swift'
CocoaLumberjack (2.0.3)

**Comment by vCrespoP** [comment]
From the podfile:
pod 'CocoaLumberjack/Swift'

and I get the version:
Using CocoaLumberjack (2.0.3)

**Comment by bpoplauschi** [comment]
What is your Xcode version?

**Comment by vCrespoP** [comment]
Xcode 7.0.1 and I will update today or tomorrow to the latest, but anyways, Swift 2.0 minimum for sure.

**Comment by bpoplauschi** [comment]
So the problem (I think) is that Lumberjack 2.0.3 requires Xcode 6. For Xcode 7, you should use the latest master or one of the two 2.1.0 (beta or rc) versions. We will release an official 2.1.0 this week, and that has Xcode 7 support.

**Comment by vCrespoP** [comment]
I thought that master was the branch that was used when you didn't specify any branch/tag and is the one I was using as I understood the branch swift_2.0 had been merged into master correctly.

Anyways, seems that using this works:
    pod 'CocoaLumberjack/Swift',
        :git => 'https://github.com/CocoaLumberjack/CocoaLumberjack',
        :branch => '2.1.0-rc'

Thanks for your help! Keep it up

**Comment by bpoplauschi** [comment]
When you just specify `pod CocoaLumberjack` you get the latest stable version (meaning beta or rc versions are not included). In this case, 2.0.3.

You can get the rc version easier, with just `pod 'CocoaLumberjack/Swift', '~> 2.1.0-rc'`.

To get the latest master code, you can specify that directly but it's not recommended since it's in the middle of development: `pod 'CocoaLumberjack/Swift', :head`.
