### ISSUE TITLE
CFBundleShortVersionString can't say 2.0.0-rc anymore

### ISSUE THREAD

**Issue by kballard** [CocoaLumberjack/CocoaLumberjack#638]
iTunes Connect changed the rules yesterday, and framework versions must now be up to 3 dotted numbers with nothing else. [TN2420](https://developer.apple.com/library/prerelease/ios/technotes/tn2420/_index.html) has more info.

CocoaLumberjack currently has its CFBundleShortVersionString as "2.0.0-rc". This causes applications that embed CocoaLumberjack to fail to upload to the store:

![screen shot 2015-10-22 at 10 26 08 am](https://cloud.githubusercontent.com/assets/714/10673314/09c811cc-78aa-11e5-9dbd-32c2e6fc6627.png)

**Comment by kballard** [comment]
Note: the Technote actually claims that framework versions must use the same build number/string as the app. This was actually true yesterday, but they reverted that change already. The only requirement on frameworks now seems to be the format of the build string.

**Comment by bpoplauschi** [comment]
Fixed in the latest master with 9f93bb2

**Comment by bpoplauschi** [comment]
@kballard thanks for the details
