### ISSUE TITLE
Dynamic log levels not working

### ISSUE THREAD

**Issue by mutech** [CocoaLumberjack/CocoaLumberjack#641]
From what I see in the code, log levels defined in classes [DDLog setLevel:forClass:] are not used anywhere (anymore?). And if I'm wrong and they are used, it's not working for me,
- neither as filter for default level (ddLogLevel=all, class-loglevel=warning -> no effect; expected no logs)
- nor  as override for defaults (ddLogLevel=warning, class-loglevel=all -> no effect; expected log msgs).

My class is recognized as registered class, but the getters are never called.

Is this not yet implemented or not yet removed or am I not yet smart enough to understand how it's supposed to work?

Since there are no more custom log levels and seemingly no class scope log levels either, how can I reasonably implement my requirements: I have a reusable framework (objective-c) depending on cocoa lumberjack. How can users of the framework selectively enable logging for one of my framework's modules without interfering with their application logging configuration?

**Comment by rivera-ernesto** [comment]
Please make a [search](https://github.com/CocoaLumberjack/CocoaLumberjack/search?q=registered+class&type=Issues&utf8=✓) before opening new issues. You could ask to reopen #102 or add to the discussion in #364 for instance.

I think the functionality got broken with the 2.0.0 refactoring but feel free to re-enable it and make a pull request.

**Comment by mutech** [comment]
I don't see how #102 or #364 are related to my issue, it's not the same problem, at least it does not look like it would be. I don't get any crashes. Please read issues before closing them.

If you don't care whether some functionality is broken that you formerly cared to document, then why would I?

**Comment by rivera-ernesto** [comment]
As you may have noticed this is not a very used feature, so asking for help in existing related issues may get you more help than opening new ones. Just mentioning them for you added links to your issue for instance.

Moreover this is a collaborative/do-it-yourself-and-pull-request-please project. Documentation as well, so if you know how to help please do so. Otherwise please search and try to add your questions to existing issues first.
