### ISSUE TITLE
DDAbstractLogger with Swift

### ISSUE THREAD

**Issue by joelrfcosta** [CocoaLumberjack/CocoaLumberjack#643]
I needed to implement my own logger to integrate with Logentries but the only way I was able to do it was by overriding the `onInternalLoggerQueue` method:

``` swift
import Foundation
import LogEntries
import CocoaLumberjack

class SCLogEntriesLogger: DDAbstractLogger {

    override func logMessage(logMessage: DDLogMessage!) {
        var message = logMessage.message

        if ((logFormatter) != nil) {
            message = logFormatter.formatLogMessage(logMessage)
        }

        if (message != nil) {
            LELog.sharedInstance().log(message)
        }
    }

    override var onInternalLoggerQueue: Bool {
        get {
            return false
        }
    }
}
```

On Objective-C we would use the `_logFormatter` variable to not cause the deadlock on `NSAssert(![self isOnInternalLoggerQueue], @"MUST access ivar directly, NOT via self.* syntax.");` but on Swift language there is no way to access the _internal_ variable because there is no such thing. 

**My questions are:**
1. Will this approach cause any side effect? 
2. There is any other way to bypass the `NSAssert` on Swift?
3. Should we change the CL library to fix this issue (maybe a specific `DDAbstractLogger`for Swift)?

**Comment by rivera-ernesto** [comment]
Probably the Assert is no longer pertinent as more people start using Swift.

**Comment by JoelRFCosta** [comment]
After more testing this solution doesn't work because of how the `logFormatter ` getter method is designed to *sync* the formatter to be applied on correct serial queue position. 

```swift
- (id <DDLogFormatter>)logFormatter {
    // [...]
    // IMPORTANT NOTE:
    //
    // Methods within the DDLogger implementation MUST access the formatter ivar directly.
    // [...]

    NSAssert(![self isOnGlobalLoggingQueue], @"Core architecture requirement failure");
    NSAssert(![self isOnInternalLoggerQueue], @"MUST access ivar directly, NOT via self.* syntax.");

    dispatch_queue_t globalLoggingQueue = [DDLog loggingQueue];

    __block id <DDLogFormatter> result;

    dispatch_sync(globalLoggingQueue, ^{
        dispatch_sync(_loggerQueue, ^{
            result = _logFormatter;
        });
    });

    return result;
}
``` 
I didn't figure it out why the `return result;` is never called but it is related with the `dispatch_sync` calls. Any thoughts?

**Comment by mackuba** [comment]
FYI, I had the exact same problem and worked around it this way ;)

```swift
override func logMessage(logMessage: DDLogMessage!) {
    var message = logMessage.message

    let ivar = class_getInstanceVariable(object_getClass(self), "_logFormatter")
    if let formatter = object_getIvar(self, ivar) as? DDLogFormatter {
        message = formatter.formatLogMessage(logMessage)
    }

    logentries.log(message)
}
```

But I'd also appreciate a better long term solution for this.

**Comment by bpoplauschi** [comment]
I also ran into this issue and it's kind of bothering. @mackuba's solution sounds interesting. I solved it by creating another `logFormatter` property which I can access whenever I want to:
```
private var internalLogFormatter: DDLogFormatter?

override internal var logFormatter: DDLogFormatter! {
    set {
        super.logFormatter = newValue
        internalLogFormatter = newValue
    }
    get {
        return super.logFormatter
    }
}

override func logMessage(logMessage: DDLogMessage!) {
    var messageText = logMessage.message
    if let logFormatter = internalLogFormatter {
        messageText = logFormatter.formatLogMessage(logMessage)
    }
    
    // do something with messageText
}
```

But those are all hacky solutions and we need to rethink this sync architecture, for all the Swift users.

**Comment by joelrfcosta** [comment]
Both @bpoplauschi and @mackuba are nice workarounds and I agree that there should be a better architecture with Swift in mind but, I think for now, these "solutions" should be made available on documentation.

**Comment by RVijay007** [comment]
We are experiencing the same issue when backgrounding, then foregrounding the app. Namely, the app freezes once foregrounded, and looks like a race condition on access to _loggerQueue. I have implemented all the solutions presented above, but none are addressing this issue.

**Comment by joelrfcosta** [comment]
I think we don't need this anymore :)
