### ISSUE TITLE
How can I route NSZombie statements through Cocoa Lumberjack ?

### ISSUE THREAD

**Issue by navaneet** [CocoaLumberjack/CocoaLumberjack#644]
I have enabled nszombie for my project... how can I route the statements that nszmobie writes to console via cocoa lumberjack... the reason I am asking is because I have a file logger attached to my lumberjack instance so any nszombie statements will automatically be written to the log file if appropriately routed through lumberjack...

**Comment by rivera-ernesto** [comment]
Try using `[DDASLLogCapture](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Classes/DDASLLogCapture.h)` which should reroute logs to Lumberjack.

**Comment by navaneet** [comment]
Thanks for the quick reply... also, would the DDASLLogCapture be also able to capture crash logs when say the app crashed and iOS creates a crash log... I have heard that it internally uses ASL only... not sure if it's true though

**Comment by rivera-ernesto** [comment]
Pretty sure it won't. You could try to do that in a crash/unhandled exception handler but they are not easy to implement right.

**Comment by navaneet** [comment]
Yes, it's a tough job... thanks for your help :)
