### ISSUE TITLE
Remove the need to define ddLogLevel in any class 

### ISSUE THREAD

**Issue by bpoplauschi** [CocoaLumberjack/CocoaLumberjack#648]
To make installation easier, we need to get rid of the need to define `ddLogLevel`, especially since this needs to be defined in every file that wants to log (precompiled headers are narrowly used).

See #542 for details.

**Comment by rivera-ernesto** [comment]
We should both:

- Provide a default implementation that "just works" for general users.
- Allow advanced users to customize/override it to use their current approaches.

And make that possible from both Swift and Objective-C.

**Comment by warpling** [comment]
Currently is there a solution that doesn't use precompiled headers?

**Comment by mgill404** [comment]
I would love to be able to define the global log level, and override this per file.
