### ISSUE TITLE
Question about OSSpinLockLock

### ISSUE THREAD

**Issue by PhilCai1993** [CocoaLumberjack/CocoaLumberjack#652]
According to ``OSAtomic.h``: ``  You should always initialize a spinlock to {@link OS_SPINLOCK_INIT} before using it. ``
I'm wondering whether if we should add ``lock = OS_SPINLOCK_INIT`` before using  ``OSSpinLockLock(&lock)`` in ``DDContextFilterLogFormatter.m``?

**Comment by bpoplauschi** [comment]
I didn't work with `OSSpinLock` before, but from what the documentation says, we should be doing that. Would you be interested in making a PR?

**Comment by PhilCai1993** [comment]
I'm glad to do that

**Comment by bpoplauschi** [comment]
Many thanks, @PhilCai1993
