### ISSUE TITLE
Use of Unresolved Identifier "****"

### ISSUE THREAD

**Issue by YilunLiu** [CocoaLumberjack/CocoaLumberjack#654]
I integrated CocoaLumberjack via Carthage and put the builds into my project.

I am using Swift. when I do "DDLogWarn " or other DDLog Marcos. The compiler is telling me that it cannot find these methods. (Use of unresolved identifier "****") Other things like DDLog works fine.

Any ideas ?

**Comment by rivera-ernesto** [comment]
Have you tried checking [here](https://github.com/CocoaLumberjack/CocoaLumberjack/search?q=Carthage&type=Issues&utf8=✓)?

**Comment by iosengineer** [comment]
Yeah. I've got this as well. New Swift project, Carthage 0.1. Directions for Carthage inclusion followed to the letter.

**Comment by hirad** [comment]
Same thing's happening for me with Cocoapods.

**Comment by Ryandev** [comment]
I'm getting this too on release 2.3.0 & tip. If I use version 2.2.0 carthage builds fine

**Comment by livecano** [comment]
Same thing here, is not working with version 2.3.0 using Cocoapods.

**Comment by pbush25** [comment]
Has this been resolved? Running into the issue with a fresh installation from Carthage

**Comment by kinddevelopment** [comment]
I'm also having this issue with a fresh installation of 2.3.0 from CocoaPods.

**Comment by pavel-zdenek** [comment]
I have switched CocoaLumberjack dependency creation from CocoaPods to Carthage and this started popping up. It got fixed for me by `import CocoaLumberjackSwift` instead of `import CocoaLumberjack` which worked for Pods.

**Comment by bpoplauschi** [comment]
Good point @pavel-zdenek, for Carthage, one needs to `import CocoaLumberjackSwift` separately, as for CocoaPods the Swift comes within `import CocoaLumberjack` - we should clean this up.
