### ISSUE TITLE
CocoaLumberjack iOS framework compiles swift file

### ISSUE THREAD

**Issue by nrbrook** [CocoaLumberjack/CocoaLumberjack#658]
The normal CocoaLumberjack framework compiles the swift file. This is a problem if the App project is not swift and does not have `EMBEDDED_CONTENT_CONTAINS_SWIFT` enabled.

I'm not sure if there is a reason the swift file is being compiled in the normal framework, but removing it seems ok in both swift and non-swift projects.

**Comment by rivera-ernesto** [comment]
Could you make a pull request?

**Comment by nrbrook** [comment]
Sorry, I thought I had. Done: https://github.com/CocoaLumberjack/CocoaLumberjack/pull/659

**Comment by rivera-ernesto** [comment]
Closing this to move discussion to #659.
