### ISSUE TITLE
Synchronous logging in Swift?

### ISSUE THREAD

**Issue by mark-anders** [CocoaLumberjack/CocoaLumberjack#665]
Is it possible to enable synchronous logging globally when using Swift? All links that I've seen reference doing it with macros.

**Comment by ffried** [comment]
This is actually an interesting idea. It could be solved similar to the log level in #952.

**Comment by StevenMagdy** [comment]
Is there any way to currently achieve this?

**Comment by ffried** [comment]
@StevenMagdy Not _currently_, but with #1019 will be 😉

**Comment by bpoplauschi** [comment]
Fixed by #1019
