### ISSUE TITLE
Clickable logs in Xcode and AppCode.

### ISSUE THREAD

**Issue by krzysztofzablocki** [CocoaLumberjack/CocoaLumberjack#669]
Hey guys,
I made an XCode plugin (https://github.com/krzysztofzablocki/KZLinkedConsole) that turns fileName.extension:lineNumber into clickable logs, since that's already supported in AppCode.

Would you consider making syntax like that the default log formatter? or if you don't want to, we can add info about integrating it here, I love CocoaLumberjack :+1:

**Comment by rivera-ernesto** [comment]
You can always propose new log formatters including one like the one you describe.

As for making it the "default" logger we can see once its implemented, but as formatters are easy to set that may not be necessary.

**Comment by ffried** [comment]
Closing since Xcode plugins are no longer a thing. If this is still possible in AppCode, feel free to open a PR with a formatter that supports this..
