### ISSUE TITLE
Suggestion: How about rewrite Obj-C classes codes in Swift?

### ISSUE THREAD

**Issue by sinoru** [CocoaLumberjack/CocoaLumberjack#670]
You guys know that Apple release Swift as Open Source project few days ago. And they release Swift Package Manager too.
It will be great some days my favorite project can be used in Swift project with Swift Package Manager (include other platform, i.e: Linux)
As that part, not whole big transition, with Obj-C compatibility layer. How about move some codes to Swift?

**Comment by rivera-ernesto** [comment]
It is a good idea, but I think starting from scratch would be better as to not to disrupt current users and to have a separate project/organization where we have more freedom to manage projects/collaborators.

**Comment by ffried** [comment]
Linking #869...
