### ISSUE TITLE
Add ASLLogCapture filter by process sender

### ISSUE THREAD

**Issue by Autoc0diq** [CocoaLumberjack/CocoaLumberjack#672]
Currently the ASLLogCapture captures all logs sent to ASL.
There's no way to filter by only the current process. This would be useful for example to capture logs outputted by 3rd party frameworks or the system using NSLog when running without a debugger attached. 

Unfortunately since it captures everything right now, it is too verbose (and expensive) to be useful.

**Comment by ffried** [comment]
Closing this, since ASL has been replaced by os_log.
