### ISSUE TITLE
log file cannot be found in a device running iOS 8.4.1

### ISSUE THREAD

**Issue by smartiothome** [CocoaLumberjack/CocoaLumberjack#673]
I have an application that is running on a iOS 9 device and a iOS 8.4 device.  The log files are being created in the iOS 9 device under /AppData/Library/Caches/Logs/ but nothing is present in the /AppData/Library/Caches folder in the iOS 8.4 devices.

Can someone give me some pointers on how I can fix the issue?

**Comment by rivera-ernesto** [comment]
Did you try this [search](https://github.com/CocoaLumberjack/CocoaLumberjack/search?utf8=✓&q=file+logger&type=Issues) first?
