### ISSUE TITLE
memory leak in device with iOS9 or above

### ISSUE THREAD

**Issue by qiny** [CocoaLumberjack/CocoaLumberjack#675]
In device with iOS9 or above, I find the memory usage is growing fast and doesn't drop. you could verify this issue with below simple code:
    for (int i = 0; i < 100; i ++) {
        DDLogInfo(@"Test" );
    }

**Comment by rivera-ernesto** [comment]
Do you have `NSZombies` enabled?

**Comment by isqinyang** [comment]
NO, I don't enable NSZombies

**Comment by isqinyang** [comment]
does anyone have the same issue ?

**Comment by zhangguotao** [comment]
i have same issue,  version2.2, and phone6s with ios9.2 。 i just run this code 
for (int i = 0; i < 10000; i++) {
        DDLogInfo(@"test");
    }

![eb135fb2-1273-4d78-b1f1-95eebb9c4d4a](https://cloud.githubusercontent.com/assets/2094804/12288023/9d8dc47c-ba0b-11e5-953d-39a6a15a4fa5.png)

**Comment by tinymind** [comment]
I have the same issue. Any idea?

**Comment by Autoc0diq** [comment]
Same here.

**Comment by rivera-ernesto** [comment]
No way to know for sure unless we profile one of your test projects with Instruments.

**Comment by tinymind** [comment]
It's easy to confirm. Just new a single view application project, and add this code to AppDelegate.m
``` obj-c
for (int i = 0; i < 10000; i++) {
    DDLogInfo(@"test");
}
```

Build and run on iOS 9 device, you will see the memory is growing fast.

**Comment by rivera-ernesto** [comment]
Yes, but to understand *why* you need to profile it and check where its retain count gets incremented.

**Comment by pujiaxin33** [comment]
i have same issue, cocoaLumberjack version1.9, and iphone6s with ios9.2 。

**Comment by tinymind** [comment]
By the way, this issue only happens at debug mode. Release mode works fine.

**Comment by rivera-ernesto** [comment]
Release mode is the important one. Debug builds are not optimized for memory or performance, just for build speed and debug ease.

**Comment by neilt** [comment]
I also have this issue.

**Comment by rivera-ernesto** [comment]
Please make sure this happen on non-Debug builds.

**Comment by bpoplauschi** [comment]
Old issue - closing, not sure if it's still applicable.
