### ISSUE TITLE
Disabling adding a logger multiple times

### ISSUE THREAD

**Issue by manuyavuz** [CocoaLumberjack/CocoaLumberjack#676]
Hi, 

I want to use Lumberjack in a library which will be added to other projects. I'm adding default DDTTYLogger as the logger inside the library. However, if application developers also add the same logger, any log will we printed multiple times. 

How can I prevent this? I check `[DDLog allLoggers]` and do not add if DDTTYLogger exists, however, it's not enough because developers themselves can add the same again and I can't control this. 

It there a reason why _loggers variable is not an NSSet but an NSArray? Is there really a use case where  somebody needs to log to the same logger multiple times? I think it can be converted to an NSSet to provide uniqueness.

If that's not an alternative, how can I handle the scenario? Suggestions would be very welcome!

**Comment by rivera-ernesto** [comment]
I think that 3rd party libraries forcing TTY logging is too invasive. On the other hand adding their own file logger could make sense as well as allowing multiple file loggers.

Maybe we could fix it by proposing `defaultInstance` singletons for each logger that gets added to a `NSSet` while still allowing creating custom instances.

**Comment by manuyavuz** [comment]
Hmm, I see your point now, if the library adds the TTY logger, application's own logs would also be logged to TTY, which is not a pretty thing.

That makes me think about the second proposal: Do you think is it reasonable to add an API which enables to log a message only to a particular logger? If such an API exists, I think third party libraries would easily use Lumberjack without affecting the configuration for the application code itself.

**Comment by rivera-ernesto** [comment]
3rd parties can make custom loggers that log only their own messages which is good.

It would be better though to let the user to choose which libraries should log and the desired levels. Something I tried to achieve with [NBULog](https://github.com/CyberAgent/NBULog#modules) and [LumberjackConsole](https://github.com/PTEz/LumberjackConsole#b-embeded-console).

**Comment by bpoplauschi** [comment]
Closing this ticket - per #682 we prevent adding the same logger multiple times.
