### ISSUE TITLE
Thread lock

### ISSUE THREAD

**Issue by legacydev** [CocoaLumberjack/CocoaLumberjack#680]
On version 2.2.0 (and prior)

I have been seeing intermittent thread locks. I believe I have narrowed down the issue to this:
```objc
# define DDLogError(frmt, ...)   LOG_MAYBE(NO, ...
# define DDLogWarn(frmt, ...)    LOG_MAYBE(LOG_ASYNC_ENABLED ...
# define DDLogInfo(frmt, ...)    LOG_MAYBE(LOG_ASYNC_ENABLED ...
# define DDLogDebug(frmt, ...)   LOG_MAYBE(LOG_ASYNC_ENABLED ...
# define DDLogVerbose(frmt, ...) LOG_MAYBE(LOG_ASYNC_ENABLED ...
```
Logging errors is not async - so it can potentially lock threads. Is there a particular reason for this?

**Comment by bpoplauschi** [comment]
The reason for logging errors synchronously is that you want to log the error as soon and as fast as possible, since the app might crash due to that error and you will not see that log if you do it async (postpone it).

**Comment by legacydev** [comment]
Is there a way to ensure that thread locks for multiple errors do not occur? The code base I work in logs several errors that indicate configuration issues, but does not generally prevent normal operations when these errors occur. Currently, I have just changed error logs to be async because continuing to operate is more important for us

**Comment by bpoplauschi** [comment]
@legacydev if that is the case, you can use the async version, but for most people, the error logs need to be sync.
