### ISSUE TITLE
Colors in Xcode are applied only to some entries

### ISSUE THREAD

**Issue by deville** [CocoaLumberjack/CocoaLumberjack#681]
I am using **Xcode 7.2 (7C68)** with the latest versions of **XcodeColors** plugin and `CocoaLumberjack/Swift` pod.

Here is how I set up logging:
```
private func setUpLogging() {
    DDLog.addLogger(DDASLLogger.sharedInstance(), withLevel: .Warning)
    
    let ttyLogger = DDTTYLogger.sharedInstance()
    ttyLogger.colorsEnabled = true
    ttyLogger.setForegroundColor(UIColor(red: 0.0, green: 0.5, blue: 0, alpha: 1.0), backgroundColor: nil, forFlag: .Info)
    ttyLogger.setForegroundColor(UIColor(red: 0.0, green: 0, blue: 0.7, alpha: 1.0), backgroundColor: nil, forFlag: .Debug)
    ttyLogger.setForegroundColor(UIColor(red: 0.5, green: 0.5, blue: 0.5, alpha: 1.0), backgroundColor: nil, forFlag: .Verbose)

    #if DEBUG
        let logLevel: DDLogLevel = .Verbose
    #else
        let logLevel: DDLogLevel = .Off
    #endif
    DDLog.addLogger(ttyLogger, withLevel: logLevel)
}
```

The problem is that color is applied only to some log entries, others remain black. It is reproduced both for `Warn` (which is colored by default) and for `Debug` (for which I set up color myself).

**Comment by rivera-ernesto** [comment]
I had a similar problem where some color combinations are not picked up by Xcode's console. Could you try some color variations?

**Comment by deville** [comment]
@rivera-ernesto I tried setting `UIColor.blueColor()` and removing other color customizations:
```
ttyLogger.setForegroundColor(UIColor.blueColor(), backgroundColor: nil, forFlag: .Debug)
```

the issue persists.

**Comment by deville** [comment]
Here's how the raw log output looks (attached as screenshot to make sure ESC characters are visible):
![screen shot 2016-01-20 at 14 04 17](https://cloud.githubusercontent.com/assets/4421971/12449628/daec73fe-bf7e-11e5-9457-10795f9b28bb.png)

Seems a bit inconsistent to me.

**Comment by deville** [comment]
This problem was caused by MCLog plugin.  After I removed it, everything works just fine.

**Comment by rivera-ernesto** [comment]
Thanks for posting back your findings for others to see!
