### ISSUE TITLE
Custom Formatter in Swift?

### ISSUE THREAD

**Issue by eflyjason** [CocoaLumberjack/CocoaLumberjack#683]
Here is Objective-C codes in documentation:

MyCustomFormatter.h

```
#import <Foundation/Foundation.h>
#import "DDLog.h"

@interface MyCustomFormatter : NSObject <DDLogFormatter>

@end
```

MyCustomFormatter.m

```
#import "MyCustomFormatter.h"

@implementation MyCustomFormatter

- (NSString *)formatLogMessage:(DDLogMessage *)logMessage {
    NSString *logLevel;
    switch (logMessage->_flag) {
        case DDLogFlagError    : logLevel = @"E"; break;
        case DDLogFlagWarning  : logLevel = @"W"; break;
        case DDLogFlagInfo     : logLevel = @"I"; break;
        case DDLogFlagDebug    : logLevel = @"D"; break;
        default                : logLevel = @"V"; break;
    }

    return [NSString stringWithFormat:@"%@ | %@\n", logLevel, logMessage->_message];
}

@end
```

How can I create it in Swift?

I've tried:

```
class MyCustomFormatter: DDLogFormatter {
    func formatLogMessage(logMessage: DDLogMessage!) -> String! {
        return "haha"
    }
}
```

but it show error. :(

**Comment by eflyjason** [comment]
Fixed by:

```
class MyCustomFormatter: NSObject, DDLogFormatter {
    func formatLogMessage(logMessage: DDLogMessage!) -> String! {
        //...
    }
}
```

**Comment by MaddTheSane** [comment]
What is the specific error?

**Comment by DQ92** [comment]
`class DefaultLogFormatter: NSObject, DDLogFormatter {

    public override init() {
        super.init()
}
  
    func format(message logMessage: DDLogMessage) -> String? { return "" }
}`

It works!

**Comment by amatig** [comment]
> ` class DefaultLogFormatter: NSObject, DDLogFormatter {
> 
> ```
> public override init() {
>     super.init()
> }
> 
> func format(message logMessage: DDLogMessage) -> String? { return "" }
> }
> ```
> `
> 
> It works!

This is ok, but if I check the log file inside the device they don't have the same format. Why??
