### ISSUE TITLE
How to solve the duplicate logs with frameworks using CocoaLumberjack also

### ISSUE THREAD

**Issue by ylorn** [CocoaLumberjack/CocoaLumberjack#685]
Here is my situation. I'm writing a framework for others to use, and I've chosen CocoaLumberjack (as a static library) to take charge of the logging stuff. I added MyTTYLogger (a subclass of DDTTYLogger) to DDLog. And I've created my own macros for easy use. They look like following:

``` objective-c
MyLogInfo(frmt, ***)
```

And I also customized my own formatter to make it provide more detailed information like process id, thread id, and so on.

And I was informed by people who are using my framework that duplicated logs will be printed to the console. Here is their environment:
- they linked my framework in build phases
- they installed their own CocoaLumberjack through CocoaPods

So, when they are doing 

``` objective-c
NSLog(@"%@", [DDLog allLoggers]);
```

The console will show:

```
2016-01-29 15:42:07.158 logtest[14457:2077847] (
    "<MyTTYLogger: 0x7feb0351ad00>",
    "<DDTTYLogger: 0x7feb0351bc80>"
)
```

So there are 2 TTY loggers in DDLog. An if they do:

``` objective-c
DDLogInfo(@"This is an info from DDLog");
```

The console will display:

```
2016-01-29 15:42:07:159 logtest[14457:2077847] -[AppDelegate applicationDidBecomeActive:] [Line:55][I]: This is an info from DDLog
2016-01-29 15:42:07:159 logtest[14457:2077847] This is an info from DDLog
```

And I fixed this by writing a `- (void)logMessage:(DDLogMessage *)logMessage;` method in MyTTYLogger to override the one in DDTTYLogger:

``` objective-c
- (void)logMessage:(DDLogMessage *)logMessage {
    BOOL isMyLog = [(NSString *)(logMessage->_tag) isEqualToString:@"thisIsMyLog"];
    if (isMyLog) {
        [super logMessage:logMessage];
    }
}
```

So basically it will check if the logMessage is tagged with `@"thisIsMyLog"`. If it is, it will call the same name method in its super class DDTTYLogger to print the log on the Xcode console. Which means the log message fired by DDLogInfo or other DDLog macros will never be accepted by MyTTYLogger, because by default, the DDLog macros are tagged with **nil**.

Now if I do following again:

``` objective-c
DDLogInfo(@"This is an info from DDLog");
```

It will only show one log on the Xcode console, which is exactly what I expected:

```
2016-01-29 15:50:42:124 logtest[14457:2077847] This is an info from DDLog
```
### But,

either before or after I made the change I described above, if do:

``` objective-c
MyLogInfo(@"This is an info from MyLog");
```

they always give me two duplicate log which have different formatters like following:

```
2016-01-29 17:09:21:191 logtest[22553:2198909] -[AppDelegate applicationDidBecomeActive:] [Line:54][I]: This is an info from MyLog
2016-01-29 17:09:21:191 logtest[22553:2198909] This is an info from MyLog
```

I understand that within the method `+ (void)lt_log:(DDLogMessage *)logMessage` in `DDLog.m`, it will try to send the log message to every loggers that are available. If the log message's `_flag` meets the `_level` of whichsoever loggers, the message will be accepted by that logger and be either printed or stored locally.
#### So here is my question:

**Although I can prevent logs triggered by other macros from being accepted by my own logger, but how can I make sure that logs targeted for my logger only won't be accepted by other loggers available? Is there a way to make a log message go directly to a specific logger regardless of how many available loggers there are?**

Thank you very much!

P.S. I thought about using flag & level to filter logs, but if the global log level is set to `NSUIntegerMax`, nothing will be filtered out.

**Comment by rivera-ernesto** [comment]
I don't think you should need two TTY Loggers as I don't see what important distinction would there be between then as they only output to the console.

To formatters however has more sense, but I'm afraid there's no proper support to filter what messages go to which formatter (I guess that's one reason for your custom TTY Logger).

Anyway you can't (and shouldn't) force users to use your TTY Logger, so I recommend you to just append/prepend the extra info your log messages need to a regular log messages. You can automate that with your own macros.

**Comment by ylorn** [comment]
@rivera-ernesto I agree with your opinion that there is no reason to have 2 TTY Loggers, but from what I understand, although `DDTTYLogger` is a singleton instance, you can add `[DDTTYLogger sharedinstance]` multiple times to `DDLog`, which will cause duplicate logs as well.

From my side, I can revise my code to make it check every time if there is already a **TTY** logger there and prevent it from adding another **TTY** logger. But how can I be sure that my users will do this as well? They probably will read your document and do a `[DDLog addLogger:[DDTTYLogger sharedInstance]];` and then find there is always a duplicate log.

Besides, I am not sure if the idea of checking the existence of `[DDTTYLogger sharedInstance]` every time before every single one log is sent to the `DDLog` is a good idea. I suspect that this will beat the purpose of using CocoaLumberjack - it will make it slow and inefficient.

So I am wondering if we can separate the CocoaLumberjack in the framework and the one used by users, with technology like using **different namespace**. I'm not sure if this will work, but ideally what I hope is that the CocoaLumberjack in the framework and the one used by users should be living in different thread.

**I'm not sure if this is achievable, please advise.**

Thanks a lot!

**Comment by rivera-ernesto** [comment]
I think you should only send log messages without caring (or imposing) a particular log output to users. Especially if it's a TTY output (log files could be different).

**Comment by ylorn** [comment]
@rivera-ernesto Yes, I agree that I should only care about the file logs. But what I'm suggesting here is that should we add an option to make DDLog be able to only have one TTY logger?

**Comment by rivera-ernesto** [comment]
Check #682.
