### ISSUE TITLE
Logs are not saved to a file using DDFileLogger 

### ISSUE THREAD

**Issue by Saurman** [CocoaLumberjack/CocoaLumberjack#688]
I have an app that works on foreground and on background. App writes logs to a files using following setup:
```objc
fileLogger = [DDFileLogger new];
fileLogger.maximumFileSize = 1024 * 1024 * 5;  // 5MB
fileLogger.rollingFrequency = 60 * 60 * 6;     // 6h
fileLogger.logFileManager.maximumNumberOfLogFiles = 10;
[DDLog addLogger:fileLogger];
[DDLog addLogger:[DDTTYLogger sharedInstance]];
```

App has a view that lists all log files using 
`NSArray *sortedLogFileInfos = [fileLogger.logFileManager sortedLogFileInfos];`

Tapping log file opens MFMailComposeViewController and emails it to my address.
Sometimes after background sessions when i receive log files - there is no any records that app was executing (even tho log was sent to me with the app on foreground). Before presenting MFMailComposeViewController i am calling `[DDLog flushLog];`to ensure that i get most latest logs but this isnt working for me. Please advise

**Comment by SteffenL** [comment]
I believe I have just experienced the same thing, and it is causing a major problem for me. In my case, it is critical that logging works reliably.

My app receives push notifications in the background, and I must be able to log errors, debug messages, etc. When the device is locked, no logs appear to be saved to file.

Any assistance would be much appreciated! Thank you!

Device: iPhone 5s
OS: iOS v9.2.1
CocoaLumberjack: v2.2.0

**Comment by ogkent** [comment]
@SteffenL What's your data protection setting for your logs files? If it's set to complete, you won't be able to write to the files while the device is locked.

**Comment by Saurman** [comment]
how do i set data protection?

**Comment by rivera-ernesto** [comment]
I guess everything is in the sources. Take a look at the current implementation.

**Comment by bpoplauschi** [comment]
Old issue - closing
