### ISSUE TITLE
CocoaLumberjack.h not found with MANY targets

### ISSUE THREAD

**Issue by CavalcanteLeo** [CocoaLumberjack/CocoaLumberjack#691]
I have an APP that has 3 targets:

Development, Staging and APP STORE
![captura de tela 2016-02-19 as 18 00 36](https://cloud.githubusercontent.com/assets/1735944/13187527/b1169cfa-d732-11e5-9ecb-f378739b955c.png)

![targets](https://cloud.githubusercontent.com/assets/1735944/13187577/1778ad4e-d733-11e5-8c66-11f7a89763db.png)

But xcode cant find the  <CocoaLumberjack/CocoaLumberjack.h>
![captura de tela 2016-02-19 as 18 01 34](https://cloud.githubusercontent.com/assets/1735944/13187548/d91a1b3c-d732-11e5-88a2-7b6bcf5bc50c.png)

**Comment by rivera-ernesto** [comment]
CocoaPods?

**Comment by CavalcanteLeo** [comment]
Yep

**Comment by rivera-ernesto** [comment]
Please take a look [here](https://github.com/CocoaLumberjack/CocoaLumberjack/search?q=CocoaLumberjack.h+not+found&type=Issues&utf8=✓).

**Comment by CavalcanteLeo** [comment]
tried all, none of them worked, 

working around, i found this solution:

    #import "DDLog.h"
    #import "DDTTYLogger.h"
    #import "DDASLLogger.h"
    #import "DDFileLogger.h"


instead of  #import <CocoaLumberJack/CocoaLumberjack.h>

**Comment by rivera-ernesto** [comment]
I think that importing `DDLog.h` will trigger legacy macros?
