### ISSUE TITLE
I don't know how to use CocoaLumberjack in a static library.

### ISSUE THREAD

**Issue by medisean** [CocoaLumberjack/CocoaLumberjack#694]
As title.

**Comment by rivera-ernesto** [comment]
Please take a look at #337, #676 and #172. I can't find the proper documentation we had. @bpoplauschi did we delete it because it was outdated?

Ideally static libraries (3rd party frameworks) should not require CocoaLumberjack, but use it only when available.

**Comment by medisean** [comment]
Thank you.

**Comment by rivera-ernesto** [comment]
Also feel free to update/add documentation with your findings if you can.

**Comment by bpoplauschi** [comment]
@rivera-ernesto all the documentation was moved to https://github.com/CocoaLumberjack/CocoaLumberjack/tree/master/Documentation so we version it properly and allow people to edit it via PR. I don't remember deleting any docs.

**Comment by hons82** [comment]
I'm currently writing a framework in swift where I have a dependency on CocoaLumberjack, now I've read this issue, so I'd like to ask if there is a documentation on how this "use it only when available." can be achieved in a Swift framework

Thanks

**Comment by bpoplauschi** [comment]
@hons82 I have no idea

**Comment by hons82** [comment]
@bpoplauschi :-)

**Comment by max-potapov** [comment]
I'm using well CocoaLumberjack in all my libraries and frameworks – they all produces logs, not loggers (http://stackoverflow.com/a/39594499/2778645).
