### ISSUE TITLE
add license to SPDX License List

### ISSUE THREAD

**Issue by jlovejoy** [CocoaLumberjack/CocoaLumberjack#696]
This is not so much an issue, but an attempt to reach Robbie Hanson as we want to add your license to the SPDX License List and as you seem to be the primary user of this license (and "author"?) we wanted to have a chance to consult with you on the license name and short identifier (proposed as: BSD Source Code Attribution - BSD-Source-Code  as per notes here: http://wiki.spdx.org/view/Legal_Team/Minutes/2016-03-03

Can you please contact me via: opensource (at) jilayne.com 
thanks,
Jilayne, SPDX legal team co-lead

**Comment by rivera-ernesto** [comment]
Good luck trying to reach @robbiehanson . It has been pretty hard for us to add new maintainers to repository in the past.
