### ISSUE TITLE
Is it possible to log object with debugDescription by default

### ISSUE THREAD

**Issue by lolgear** [CocoaLumberjack/CocoaLumberjack#697]
Is it possible to add something like DDLogMessage object (function target) description/ object debug description by default?

I would like to have logs with timestamp, loglevel, object debug description and function name.
"{date}|{level}|{object debug description}|{function name}: {message}"

DDLogMessage doesn't have object debug description ivar now.

Is there any limitations in concurrency/dispatching?

It would be great to see this feature later ( if it not implemented and planned )

**Comment by rivera-ernesto** [comment]
Well you would need your own macros to create a [DDLogMessage](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Classes/DDLog.h#L319) and put your extra information in `tag`.

Then you need a formatter to output it in your desired format.
