### ISSUE TITLE
Lumberjack Context logging example

### ISSUE THREAD

**Issue by koblee** [CocoaLumberjack/CocoaLumberjack#698]
Hi,

i've been very interested in using[ lumberjack context](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/CustomContext.md) to enable selective debugging on different modules. I've create a header file with most of the framework configuration and a separate Cocoa class to customize the format of logs (which worked straight out of the [CustomFormatters](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/CustomFormatters.md) example).

I've defined the following macros trying to use the context flag APP_PROTO:

```
#define APP_PROTO 80

#define DDProtoE(frmt, ...)SYNC_LOG_OBJC_MAYBE(ddLogLevel, LOG_FLAG_ERROR,   APP_PROTO, frmt, ##__VA_ARGS__)
#define DDProtoW(frmt, ...)ASYNC_LOG_OBJC_MAYBE(ddLogLevel, LOG_FLAG_WARN,   APP_PROTO, frmt, ##__VA_ARGS__)
#define DDProtoI(frmt, ...)ASYNC_LOG_OBJC_MAYBE(ddLogLevel, LOG_FLAG_INFO,   APP_PROTO, frmt, ##__VA_ARGS__)
#define DDProtoD(frmt, ...)ASYNC_LOG_OBJC_MAYBE(ddLogLevel, LOG_FLAG_DEBUG,  APP_PROTO, frmt, ##__VA_ARGS__)
#define DDProtoV(frmt, ...)ASYNC_LOG_OBJC_MAYBE(ddLogLevel,LOG_FLAG_VERBOSE,APP_PROTO, frmt, ##__VA_ARGS__)
```

and included `#import "DDLog.h"` but i get the following error:

`Implicit declaration of function 'ASYNC_LOG_OBJC_MAYBE' is invalid in C99`

on the CocoaHTTPServer the macro `ASYNC_LOG_OBJC_MAYBE` is actually defined in "DDLog.h" but not on the pod installed. I found a "LOG_OBJC_MAYBE" in DDLegacyMacros.h

what is the correct way of using Contexts?

**Comment by rivera-ernesto** [comment]
You could take a look at how [NBULog](https://github.com/CyberAgent/NBULog/blob/master/Source/NBULog.h#L61) uses CocoaLumberjack to do that.

**Comment by tracefoundation** [comment]
Thanks @rivera-ernesto ! i think that it might be helpful to add a more comprehensive example to  [CustomFormatters](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/CustomFormatters.md)

I've interpreted contexts and levels in this way:

`#define APP_NO_LOG          0
#define APP_FLAG_DEFAULT    (1 << 0)
#define APP_FLAG_PROTO      (1 << 1)

//Enable disable modules by adding removing FLAGS
#define APP_CONTEXT_LOG     (APP_NO_LOG | APP_FLAG_PROTO)

#define LOG_FLAG_ERROR    (1 << 0)  // 0...0001
#define LOG_FLAG_WARN     (1 << 1)  // 0...0010
#define LOG_FLAG_INFO     (1 << 2)  // 0...0100
#define LOG_FLAG_DEBUG    (1 << 3)  // 0...1000
#define LOG_FLAG_VERBOSE  (1 << 4)  // 0..10000

#define LOG_MAYBE_CONTEXT(async, lvl, flg, ctx, tag, fnct, frmt, ...) \
    do { if((lvl & flg) && (APP_CONTEXT_LOG & ctx)) LOG_MACRO(async, lvl, flg, ctx, tag, fnct, frmt, ##__VA_ARGS__); } while(0)

/// Async/sync logging
#define APP_ASYNC_ERROR    ( NO && LOG_ASYNC_ENABLED)
#define APP_ASYNC_WARN     (LOG_ASYNC_ENABLED)
#define APP_ASYNC_INFO     (LOG_ASYNC_ENABLED)
#define APP_ASYNC_DEBUG    (LOG_ASYNC_ENABLED)
#define APP_ASYNC_VERBOSE  (LOG_ASYNC_ENABLED)

#define DDProtoE(frmt, ...)   LOG_MAYBE_CONTEXT(APP_ASYNC_ERROR,   ddLogLevel, LOG_FLAG_ERROR,   APP_FLAG_PROTO, nil, __PRETTY_FUNCTION__, frmt, ##__VA_ARGS__)
#define DDProtoW(frmt, ...)    LOG_MAYBE_CONTEXT(APP_ASYNC_WARN,    ddLogLevel, LOG_FLAG_WARN, APP_FLAG_PROTO, nil, __PRETTY_FUNCTION__, frmt, ##__VA_ARGS__)
#define DDProtoI(frmt, ...)    LOG_MAYBE_CONTEXT(APP_ASYNC_INFO,    ddLogLevel, LOG_FLAG_INFO,    APP_FLAG_PROTO, nil, __PRETTY_FUNCTION__, frmt, ##__VA_ARGS__)
#define DDProtoD(frmt, ...)   LOG_MAYBE_CONTEXT(APP_ASYNC_DEBUG,   ddLogLevel, LOG_FLAG_DEBUG,   APP_FLAG_PROTO, nil, __PRETTY_FUNCTION__, frmt, ##__VA_ARGS__)
#define DDProtoV(frmt, ...) LOG_MAYBE_CONTEXT(APP_ASYNC_VERBOSE, ddLogLevel, LOG_FLAG_VERBOSE, APP_FLAG_PROTO, nil, __PRETTY_FUNCTION__, frmt, ##__VA_ARGS__)
#define DDProtoT()            APPDebug(@"%s", __PRETTY_FUNCTION__)`

hope it helps !

**Comment by tracefoundation** [comment]
Note that the comments on DDLog.h for the following structure are incorrect

```
typedef NS_OPTIONS(NSUInteger, DDLogFlag){
    /**
     *  0...00000 DDLogFlagError
     */
    DDLogFlagError      = (1 << 0),

    /**
     *  0...00001 DDLogFlagWarning
     */
    DDLogFlagWarning    = (1 << 1),

    /**
     *  0...00010 DDLogFlagInfo
     */
    DDLogFlagInfo       = (1 << 2),

    /**
     *  0...00100 DDLogFlagDebug
     */
    DDLogFlagDebug      = (1 << 3),

    /**
     *  0...01000 DDLogFlagVerbose
     */
    DDLogFlagVerbose    = (1 << 4)
};
```

**Comment by koblee** [comment]
Thanks @rivera-ernesto ! i think that it might be helpful to add a more comprehensive example to CustomFormatters

I've interpreted contexts and levels in this way:
```
#define APP_NO_LOG          0
#define APP_FLAG_DEFAULT    (1 << 0)
#define APP_FLAG_PROTO      (1 << 1)

//Enable disable modules by adding removing FLAGS
#define APP_CONTEXT_LOG     (APP_NO_LOG | APP_FLAG_PROTO)

#define LOG_FLAG_ERROR    (1 << 0)  // 0...0001
#define LOG_FLAG_WARN     (1 << 1)  // 0...0010
#define LOG_FLAG_INFO     (1 << 2)  // 0...0100
#define LOG_FLAG_DEBUG    (1 << 3)  // 0...1000
#define LOG_FLAG_VERBOSE  (1 << 4)  // 0..10000

#define LOG_MAYBE_CONTEXT(async, lvl, flg, ctx, tag, fnct, frmt, ...) \
    do { if((lvl & flg) && (APP_CONTEXT_LOG & ctx)) LOG_MACRO(async, lvl, flg, ctx, tag, fnct, frmt, ##__VA_ARGS__); } while(0)

/// Async/sync logging
#define APP_ASYNC_ERROR    ( NO && LOG_ASYNC_ENABLED)
#define APP_ASYNC_WARN     (LOG_ASYNC_ENABLED)
#define APP_ASYNC_INFO     (LOG_ASYNC_ENABLED)
#define APP_ASYNC_DEBUG    (LOG_ASYNC_ENABLED)
#define APP_ASYNC_VERBOSE  (LOG_ASYNC_ENABLED)

#define DDProtoE(frmt, ...)   LOG_MAYBE_CONTEXT(APP_ASYNC_ERROR,   ddLogLevel, LOG_FLAG_ERROR,   APP_FLAG_PROTO, nil, __PRETTY_FUNCTION__, frmt, ##__VA_ARGS__)
#define DDProtoW(frmt, ...)    LOG_MAYBE_CONTEXT(APP_ASYNC_WARN,    ddLogLevel, LOG_FLAG_WARN, APP_FLAG_PROTO, nil, __PRETTY_FUNCTION__, frmt, ##__VA_ARGS__)
#define DDProtoI(frmt, ...)    LOG_MAYBE_CONTEXT(APP_ASYNC_INFO,    ddLogLevel, LOG_FLAG_INFO,    APP_FLAG_PROTO, nil, __PRETTY_FUNCTION__, frmt, ##__VA_ARGS__)
#define DDProtoD(frmt, ...)   LOG_MAYBE_CONTEXT(APP_ASYNC_DEBUG,   ddLogLevel, LOG_FLAG_DEBUG,   APP_FLAG_PROTO, nil, __PRETTY_FUNCTION__, frmt, ##__VA_ARGS__)
#define DDProtoV(frmt, ...) LOG_MAYBE_CONTEXT(APP_ASYNC_VERBOSE, ddLogLevel, LOG_FLAG_VERBOSE, APP_FLAG_PROTO, nil, __PRETTY_FUNCTION__, frmt, ##__VA_ARGS__)
#define DDProtoT()            APPDebug(@"%s", __PRETTY_FUNCTION__)

```
hope it helps !

**Comment by koblee** [comment]
Note that the comments on DDLog.h for the following structure are incorrect
```
typedef NS_OPTIONS(NSUInteger, DDLogFlag){
    /**
     *  0...00000 DDLogFlagError
     */
    DDLogFlagError      = (1 << 0),

    /**
     *  0...00001 DDLogFlagWarning
     */
    DDLogFlagWarning    = (1 << 1),

    /**
     *  0...00010 DDLogFlagInfo
     */
    DDLogFlagInfo       = (1 << 2),

    /**
     *  0...00100 DDLogFlagDebug
     */
    DDLogFlagDebug      = (1 << 3),

    /**
     *  0...01000 DDLogFlagVerbose
     */
    DDLogFlagVerbose    = (1 << 4)
};
```

**Comment by Johennes** [comment]
Is there any reason why context filtering is not built into CocoaLumberjack? Having to define a custom `LOG_MAYBE_CONTEXT` macro feels like something the framework should do itself. It seems that the only place contexts are actually handled is `DDContextWhitelistFilterLogFormatter` (and the black list formatter). These are, however, not enabled by default. Just wondering if there is any bigger reasoning behind that?

**Comment by ffried** [comment]
> It seems that the only place contexts are actually handled is DDContextWhitelistFilterLogFormatter (and the black list formatter). These are, however, not enabled by default. Just wondering if there is any bigger reasoning behind that?

CocoaLumberjack has a pretty simple default setup but offers flexibility if needed. If you feel that this should be added as default, please open a PR.
