### ISSUE TITLE
In XCode7.3 compile error import by cathage

### ISSUE THREAD

**Issue by medisean** [CocoaLumberjack/CocoaLumberjack#699]
module file was created by an older version of the compiler; rebuild 'CocoaLumberjackSwift' and try again: /Users/zouliangming/Teambition-Universal/Carthage/Build/iOS/CocoaLumberjackSwift.framework/Modules/CocoaLumberjackSwift.swiftmodule/x86_64.swiftmodule

**Comment by wzs** [comment]
Just run `carthage build` and it should work fine

**Comment by Nathan187** [comment]
would this happen to fix:  dyld: Symbol not found: __TMPdCSs18_HeapBufferStorage

started getting this.

**Comment by medisean** [comment]
It doesn't work. Maybe it's a CocoaLumberjack bug.

**Comment by kdaniel123** [comment]
carthage update --no-use-binaries

**Comment by medisean** [comment]
Thank you. @kdaniel123

**Comment by rivera-ernesto** [comment]
If its solved then we should keep it closed. People will still find it.
