### ISSUE TITLE
Custom Log Level for Swift

### ISSUE THREAD

**Issue by kunalbshah** [CocoaLumberjack/CocoaLumberjack#703]
Hi,

I am trying to setup a custom log level. I followed the steps mentioned at [Custom Log Level](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/CustomLogLevels.md). With those steps, I am able to access the custom log level from Objective C files but not from Swift file. It seems that the swift file take reference from CocoaLumberjack.swift. Can you please point me to some documentation in this regard?

Kind regards,
Kunal

**Comment by rivera-ernesto** [comment]
Try searching [here](https://github.com/CocoaLumberjack/CocoaLumberjack/search?q=Custom+Log+Level&type=Issues&utf8=✓).

**Comment by romk1n** [comment]
same question, in obj-c i can do 
```
#undef LOG_LEVEL_DEF
#define LOG_LEVEL_DEF DDLogLevelError
```

but not sure about swift. would be great to have it added in readme

**Comment by kunalbshah** [comment]
I added an Obj-C wrapper to access it from Swift files. Please refer [DDLogWrapper](http://stackoverflow.com/questions/24144404/cocoalumberjack-with-swift-calling-preprocessor-macros)

**Comment by imran20487** [comment]
@kunalbshah DDLogLevel is an enum and we can't change the enum. Can you please tell me how did you add new DDLogLevel.?
