### ISSUE TITLE
Rebuilding Dynamic Framework for Swift 2.2

### ISSUE THREAD

**Issue by bvanderw** [CocoaLumberjack/CocoaLumberjack#705]
I have been using the dynamic frameworks that are made available on the official release. WIth Xcode 7.3, I am getting the 'module file was created by an older version of the compiler'  error. I was able to successfully rebuild for the Mac, but I haven't been able to do this for iOS. I don't get the error above, but I am now getting unresolved identifier errors on defaultDebugLevel and DDLogVerbose, etc.

What procedure should I be using to rebuild CocoaLumberjackSwift as a dynamic framework for iOS?

**Comment by bpoplauschi** [comment]
@bvanderw sorry about this, it seems that Swift code should not be distributed as pre-built binaries (see #608), so we even removed the existing prebuild binaries from our releases. You need to retry and get the library as a regular Carthage dependency: https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos
