### ISSUE TITLE
Can I change logging level globaly for a logger

### ISSUE THREAD

**Issue by sethkor** [CocoaLumberjack/CocoaLumberjack#706]
Wondering if I can change the logging level for a logger on the fly across the board (i.e. not for a specific class).

I can see I can do this by removing and adding the logger again, but wondering if there is another way to do it on the fly.

I'm using Swift.

Cheers
Seth

**Comment by rivera-ernesto** [comment]
For a single logger you better create your own logger (by subclassing one of the existing ones) and filter there the log messages according to their levels.

**Comment by sethkor** [comment]
Can't I just do that via the log formatter?

**Comment by rivera-ernesto** [comment]
You could try I guess, but it would be cleaner to ignore log messages directly in the logger before passing it to the formatter.

**Comment by yacir** [comment]
A solution suggestion, i can open a pull request if needed : 

```obj-c
+ (void)updateLogger:(id <DDLogger>)logger level:(DDLogLevel)level {
    [self.sharedInstance updateLogger:logger level:level];
}

- (void)updateLogger:(id <DDLogger>)logger level:(DDLogLevel)level {
    if (!logger) {
        return;
    }
    
    dispatch_async(_loggingQueue, ^{ @autoreleasepool {
        [self lt_updateLogger:logger level:level];
    } });
}

- (void)lt_updateLogger:(id <DDLogger>)logger level:(DDLogLevel)level {
    // Find associated loggerNode in list of added loggers
    
    NSAssert(dispatch_get_specific(GlobalLoggingQueueIdentityKey),
             @"This method should only be run on the logging thread/queue");
    
    DDLoggerNode *loggerNode = nil;
    
    for (DDLoggerNode *node in self._loggers) {
        if (node->_logger == logger) {
            if (node->_level == level) {
                // Exactly same logger already added with same level, exit
                return;
            }
            loggerNode = node;
            break;
        }
    }
    
    if (!loggerNode) {
        NSLogDebug(@"DDLog: Request to update logger which wasn't added");
        return;
    }
    
    // Remove from loggers array
    [self._loggers removeObject:loggerNode];
    
    // Add updated node to loggers array
    loggerNode = [DDLoggerNode nodeWithLogger:logger loggerQueue:loggerNode->_loggerQueue level:level];
    [self._loggers addObject:loggerNode];
}
```

**Comment by bpoplauschi** [comment]
@yacir I remember I wanted to implement something similar to your solution at some point. I can't remember why I haven't added it to the project (maybe it didn't work).
Anyway, feel free to create a PR, we will need to add some unit tests to make sure it works fine, especially in a multithreading environment.
Are you still interested in doing this?

**Comment by yacir** [comment]
@bpoplauschi Of course i ll open a PR and add some tests.
