### ISSUE TITLE
Swift 2.2 support

### ISSUE THREAD

**Issue by ldi13** [CocoaLumberjack/CocoaLumberjack#708]
Hello Guys,

Would it be possible to ship a new version of your pod, integrating Swift 2.2 support ?
By that, I mean replacing all warnings regarding __LINE__, __FILE__, __FUNCTION__, with #line, #file & #function, ++ && -- operators by +=1 and -= 1, and for loop with ..< operator.

Thanks in advance for your support,

Best regards,

Lorenzo.

**Comment by gravera** [comment]
+1

**Comment by rivera-ernesto** [comment]
Addressed in #704.

Please do a [quick search](https://github.com/CocoaLumberjack/CocoaLumberjack/search?q=Swift+2.2&type=Issues&utf8=✓) before opening new issues.

**Comment by ldi13** [comment]
I did.
I searched into issues and nothing came up regarding this topic.
Anyway, thanks for your support Ernesto.

**Comment by rivera-ernesto** [comment]
Thanks to you.
