### ISSUE TITLE
DDLogLevelAll versus DDLogLevelVerbose

### ISSUE THREAD

**Issue by sethkor** [CocoaLumberjack/CocoaLumberjack#709]
Whats the difference?

**Comment by rivera-ernesto** [comment]
As you can see from the [code](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/37eff3ecff38db1f40e4420a48ac6f9749d5c693/Classes/DDLog.h#L166) `DDLogLevelAll` encompasses all levels, both current and future.

In practice and right now they are the same but that could change at some point or with custom levels.
