### ISSUE TITLE
Update for xcode 7.3 to remove deprecation warnings

### ISSUE THREAD

**Issue by sharafat** [CocoaLumberjack/CocoaLumberjack#711]
Please update CocoaLumberjack for xcode 7.3 to remove deprecation warnings.

**Comment by robotive** [comment]
Looks like there is a separate branch for this. Any ideas when this is going to be merged?
Thanks.

**Comment by rivera-ernesto** [comment]
There is a separate branch [here](https://github.com/CocoaLumberjack/CocoaLumberjack/tree/Xcode_7.3) and it will be merged when submissions to the Apple Store will require Xcode 7.3. Until then we will keep Xcode 7.2 compatibility on the master branch.

Also please [search](https://github.com/CocoaLumberjack/CocoaLumberjack/search?q=7.3&type=Issues&utf8=✓) before opening a new issue.

**Comment by ogkent** [comment]
@rivera-ernesto Are you guys going to create a new release for download in the meantime?

**Comment by rivera-ernesto** [comment]
We will at some point but in the mean time you can use this branch with [Carthage](https://github.com/CocoaLumberjack/CocoaLumberjack/issues/608#issuecomment-200599251) or [CocoaPods](https://github.com/CocoaLumberjack/CocoaLumberjack/issues/405#issuecomment-115064656). We should add these instructions to the README too.
