### ISSUE TITLE
Filename, function and line number is not output.

### ISSUE THREAD

**Issue by VincentSit** [CocoaLumberjack/CocoaLumberjack#717]
I've noticed this Issus #403 , but this one is opened in 2014, I do not know at that time whether to support output these things.

I found that each log message instance have the filename, function and line number, but there is no output,  is my configuration is not correct?

I'm using version 2.2.0, Xcode 7.3 (7D175), the following is my configuration code:

```
- (void)setupCocoaLumberjack {
  setenv("XcodeColors", "YES", 0);
  [DDLog addLogger:[DDTTYLogger sharedInstance]];
  [[DDTTYLogger sharedInstance] setColorsEnabled:YES];
}
```

Debug screenshot:   
![qq20160415-1](https://cloud.githubusercontent.com/assets/4084679/14553771/ff4c87cc-031a-11e6-9f45-d60ec68f09fd.png)
![qq20160415-0](https://cloud.githubusercontent.com/assets/4084679/14553780/078ec968-031b-11e6-8cb3-7e0cc720c94a.png)

More screenshot:   
![qq20160415-2](https://cloud.githubusercontent.com/assets/4084679/14553848/88fcf092-031b-11e6-9e32-059aae2ee76c.png)

**Comment by rivera-ernesto** [comment]
I think it depends on the formatter used to print the log message. Check which one is used. It may be ignoring this information but you can set another formatter or configure your own.

**Comment by VincentSit** [comment]
@rivera-ernesto 
Thank you very much! 
I didn't look at the code in detail and did not notice it has this feature. 
I will write my own custom formatter.
