### ISSUE TITLE
CocoaLumberjack generates lots of warnings in Xcode 7.3

### ISSUE THREAD

**Issue by rickpasetto** [CocoaLumberjack/CocoaLumberjack#721]
You all probably know this, but building CocoaLumberjack on Xcode 7.3 generates lots of Swift warnings, such as:

`CocoaLumberjack.swift:82:138: warning: __FILE__ is deprecated and will be removed in Swift 3, please use #file`

Please fix so it builds clean on Xcode 7.3.

**Comment by ogkent** [comment]
Check out the [Xcode_7.3](https://github.com/CocoaLumberjack/CocoaLumberjack/tree/Xcode_7.3) branch.

**Comment by rickpasetto** [comment]
Thanks, that worked!

**Comment by bpoplauschi** [comment]
@rickpasetto we just released a new version (2.3.0) which contains those fixes. No need to explicitly work with the branch.
