### ISSUE TITLE
[documentation] What's the unit for maximumFileSize?

### ISSUE THREAD

**Issue by cbowns** [CocoaLumberjack/CocoaLumberjack#725]
[DDFileLogger's `maximumFileSize` property](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/a837c8890e0d2d9f53fc7075dbf42c6afaf0ab69/Classes/DDFileLogger.h#L317-L348) doesn't have an associated unit anywhere in the header or CocoaLumberjack docs.

Is it in bytes?

**Comment by carllindberg** [comment]
Given that it is an unsigned long long variable, it's probably safe to assume bytes.  The value is compared against NSFileHandle's -offsetInFile value, which is in bytes.

**Comment by bpoplauschi** [comment]
@carllindberg you are right, it is in bytes. I've added this to the docs in a9f54c9
