### ISSUE TITLE
[documentation/headers] Need explanation for doNotReuseLogFiles

### ISSUE THREAD

**Issue by cbowns** [CocoaLumberjack/CocoaLumberjack#726]
[`doNotReuseLogFiles`](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/a837c8890e0d2d9f53fc7075dbf42c6afaf0ab69/Classes/DDFileLogger.h#L355-L358) says:

```
    /**
     *  See description for `maximumFileSize`
     */
    public var doNotReuseLogFiles: Bool
```

But the docs for `maximumFileSize` contain no mention of it. What does `doNotReuseLogFiles` do?

**Comment by rivera-ernesto** [comment]
We do need some help with the documentation. So if you can please edit it and make a pull request.

Same thing for #725.

**Comment by cbowns** [comment]
@rivera-ernesto sure, sure, but I still have a question: what does `doNotReuseLogFiles` *do*? (I can't write docs for things which are incomprehensible to me.)

**Comment by DD-P** [comment]
Looking at the code and testing set to on or off, this flag looks to have the following behaviour:

When set to true, creates a new log file with every application launch.  When set to false, the application can continue to append log messages to the most recent log file.  Note: a new file may be created anyway, depending on the settings of `rollingFrequency` and `maximumFileSize`.

**Comment by bpoplauschi** [comment]
Closing per latest comment.
