### ISSUE TITLE
CocoaLumberjack with Carthage

### ISSUE THREAD

**Issue by umeshjavastar** [CocoaLumberjack/CocoaLumberjack#728]
I am trying to install CocoaLumberjack with carthage but unable to build.
Facing some exception on terminal..

*** Fetching CocoaLumberjack
*** Checking out CocoaLumberjack at "2.3.0"
*** xcodebuild output can be found in /var/folders/xs/vjmbpvfd7l33lc7zn3pm030w0000gn/T/carthage-xcodebuild.ymfG4X.log
*** Building scheme "CocoaLumberjackSwift" in Lumberjack.xcworkspace
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal arm64 /Downloads/Starter-Swift2/Carthage/Checkouts/CocoaLumberjack/Classes/CocoaLumberjack.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

/Downloads/Starter-Swift2/Carthage/Checkouts/CocoaLumberjack/Classes/CocoaLumberjack.swift:58:128: error: expected initial value after '='
/Downloads/Starter-Swift2/Carthage/Checkouts/CocoaLumberjack/Classes/CocoaLumberjack.swift:58:214: error: expected ',' separator

**Comment by rivera-ernesto** [comment]
Please make a [search](https://github.com/CocoaLumberjack/CocoaLumberjack/search?q=carthage&type=Issues&utf8=✓) and this https://github.com/CocoaLumberjack/CocoaLumberjack/issues/608#issuecomment-200599251.

I think we should also modify the README to state that people shouldn't rely on precompiled binaries, no only for this library but for any library with Swift code in it.

**Comment by bpoplauschi** [comment]
@umeshjavastar Please note the latest version of Lumberjack requires Xcode 7.3 Do you have this version?

**Comment by umeshjavastar** [comment]
At that time I am not using xcode 7.3 but now I am using..Thanks
