### ISSUE TITLE
CocoaLumberjack project does not build bitcode enabled artifacts

### ISSUE THREAD

**Issue by ronak2121** [CocoaLumberjack/CocoaLumberjack#730]
Hi,

The project file for CocoaLumberjack doesn't seem to have the proper settings for bitcode enabled.

I had to modify the project file to include:

-fembed-bitcode inside every non OSX target to obtain proper bitcode enabled artifacts.

**Comment by rivera-ernesto** [comment]
Could you pull request those changes?

**Comment by jqsilver** [comment]
I ran into this, too, but I can't figure out what setting to fix. I'm using the Cocoalumberjack/Swift pod

**Comment by bpoplauschi** [comment]
Bitcode is enabled inside our project targets. For CocoaPods, you can control this as well. Everything should work (now that bitcode enabled is the default Xcode setting).

**Comment by Motti-Shneor** [comment]
The issue is still there - but it is a little more subtle. Although all targets have "Bitcode enabled" (except on MacOS) in the Shared.xcconfig - any target (my Framework for instance) linking against CocoaLumberjack-static, will fail to build-for-profiliing, with this error:  ```
ld: bitcode bundle could not be generated because '/Users/myUser/Library/Developer/Xcode/DerivedData/mySDK-eporqzissbedhfazciqqygcaiqjx/Build/Products/Release-iphoneos/libCocoaLumberjack.a(DDASLLogger.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/Users/myUser/Library/Developer/Xcode/DerivedData/mySDK-eporqzissbedhfazciqqygcaiqjx/Build/Products/Release-iphoneos/libCocoaLumberjack.a' for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```
