### ISSUE TITLE
Potentially dangerous behaviour of DDLogFileManagerDefault isLogFile:

### ISSUE THREAD

**Issue by sdrpa** [CocoaLumberjack/CocoaLumberjack#731]
I played with the lib. today and in order to customize the log file name I sub classed DDLogFileManagerDefault, methods:

```
- (NSString *)newLogFileName
- (BOOL)isLogFile:(NSString *)fileName
```

I set:

```
- (BOOL)isLogFile:(NSString *)fileName {
    return YES;
}
```

and ended up with the content of the log directory deleted (Unfortunately, I set the log dir. to be my Desktop dir :( and all the files inside the Desktop folder were deleted).
Luckily, I had time machine backup so it was painless ... I suggest that may be some kind of warning/comment should be placed in the context of:

```
@property (readonly, copy) NSString *newLogFileName;
- (BOOL)isLogFile:(NSString *)fileName;
```

to prevent this from happening, although it was completely my fault. Anyway, CocoaLumberjack is great and I integrated it successfully.

**Comment by rivera-ernesto** [comment]
Could you pull request a comment/warning for the code?
