### ISSUE TITLE
Importing and setting global level in mixed swift/legacy obj-c project

### ISSUE THREAD

**Issue by chrissearle** [CocoaLumberjack/CocoaLumberjack#733]
I'm struggling a bit in finding how to get this to play correctly in a mixed swift/obj-c environment - need some help in sorting this out.

If I don't import CocoaLumberjack in swift files then swift can't see the cocoalumberjack stuff since they don't use the PCH file.

But - if I do import in swift then I have to remove from the pch otherwise I get lots and lots of warnings about multiply defined DDLog\* stuff (since that appears to be both from the PCH and also brought into the obj-c world from swift when I import the Project-Swift.h file)

And I can't seem to get things to log much at all - it looks like logging from the AppDelegate is fine, but not a lot else.

In other projects that are pure swift or pure objective-c this all works just fine - I have both of those situations working just as they should be.

It's just in a mixed environment - I can't see how to get the loggers to play together.

So - how should I be handling the setting of global log level, and importing CocoaLumberjack in a mixed project?

It's 2.3 imported via cocoapods as pod 'CocoaLumberjack/Swift', '~> 2.3'

**Comment by bpoplauschi** [comment]
@CocoaLumberjack/collaborators need to try this and make sure it still works (I mean a mixed ObjC-Swift project).
