### ISSUE TITLE
Run demos - missing Pods.xcodeproj

### ISSUE THREAD

**Issue by Michal1313** [CocoaLumberjack/CocoaLumberjack#734]
Hi,

I was trying to run Lumberjack demos but I have problem with missing Pods.xcodeproj files. I downloaded CocoaLumberjack with demos from [https://github.com/CocoaLumberjack/CocoaLumberjack](url). 

Then I opened Demos.xcworkspace from "Demos" subfolder. When I tried to run any example I'm getting such error: 
![screen shot 2016-05-14 at 19 58 48](https://cloud.githubusercontent.com/assets/14864255/15271775/809ed03c-1a0e-11e6-9232-d0cc3df41033.png)

Project structure after opening looks like this:
![screen shot 2016-05-14 at 20 00 04](https://cloud.githubusercontent.com/assets/14864255/15271782/92248f40-1a0e-11e6-81fe-084583c9c1ec.png)

How can I run examples?

**Comment by rivera-ernesto** [comment]
I think you need to `pod install` them.

**Comment by drjhy** [comment]
same issue, however, they are install in xcworkspace but not in xcodeproj. uninstalled and reinstalled--nothing.
