### ISSUE TITLE
Custom logFormatter to output without timestamp forces mutable copy

### ISSUE THREAD

**Issue by dxclancy** [CocoaLumberjack/CocoaLumberjack#737]
In order to produce messages without the threading info/timestamping, it is my understanding that you have to create a custom formatter, and I've done so. (Perhaps I'm mistaken about this?)

However, taking this approach forces you to make a mutableCopy for each message, as DDTYLogger logMessage decides to apply default formatting in if the logMessage.message ptr is equal to the ptr returned by formatLogMessage.

My implementation of custom formatter:

```
- (NSString*)formatLogMessage:(DDLogMessage*)logMessage
{    NSString *mutableCopy = [logMessage.message mutableCopy];
    return mutableCopy;
}

```

It's not a big deal, but it does mean needlessly duplicating strings.  It would be preferable to not have to write a custom formatter simply to turn off the default formatting.  Barring that, it would be preferable not to have to copy the log message simply to print it without default formatting.

Perhaps the DDLogFormatter protocol could include flags for the various pieces of default formatting, and a default implementation of this could be added that can easily be configured such that a client needn't make a custom object.  Would you accept a PR for this, or is that not desirable?

**Comment by rivera-ernesto** [comment]
I don't see why we need to return a mutable copy when the function has a non-mutable string return signature. Sure you can make a PR for this.
