### ISSUE TITLE
Could you make prebuilt framework for Carthage?

### ISSUE THREAD

**Issue by RyogaK** [CocoaLumberjack/CocoaLumberjack#738]
Recently often, there is a case of it failures building by carthage with following message.
```
xcodebuild timed out while trying to read Demos.xcworkspace 😭
```
Could you make prebuilt framework for Carthage?

**Comment by rivera-ernesto** [comment]
We no longer distribute Swift binaries as they are not compatible with newer Xcode/Swift versions as there are released. Please [use](https://github.com/CocoaLumberjack/CocoaLumberjack/issues/608#issuecomment-200527945) the sources instead.
