### ISSUE TITLE
Error messages: Ambiguous use of internal linkage declaration '...' defined in multiple modules

### ISSUE THREAD

**Issue by vomako** [CocoaLumberjack/CocoaLumberjack#739]
I have recently received hundreds of the following errors:

Ambiguous use of internal linkage declaration 'DDLogFlagError' defined in multiple modules

My podfile contains the following:

use_frameworks!
pod 'CocoaLumberjack/Swift'

What can I do?

**Comment by vomako** [comment]
I have solved the issue by moving "#import <CocoaLumberjack/CocoaLumberjack.h>" to the top of my xxx-Prefix.pch file. I then could remove some "#import "CocoaLumberjack.h" from my files.

**Comment by rivera-ernesto** [comment]
Thanks for sharing!

**Comment by christosc** [comment]
I fixed it by using `@import CocoaLumberjack;` in the .pch file.
