### ISSUE TITLE
DDASLLogger sends nil messages to asl_send

### ISSUE THREAD

**Issue by nnesiba** [CocoaLumberjack/CocoaLumberjack#742]
### Issue Description and Steps

In projects that use a formatter to filter out messages, (https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/CustomFormatters.md) and also use the DDASLLogger, nil logs appear in the ASL Log. I'd expect there to be no logs if they're filtered out.  

I'm pretty sure DDASLLogger.m line 71 is just checking the wrong value.

**Comment by stevenkramer** [comment]
@nnesiba You're right. I compared with the other implementations of logMessage: and they all exit when the formatter returns nil.
