### ISSUE TITLE
Feature request - log browser

### ISSUE THREAD

**Issue by levey** [CocoaLumberjack/CocoaLumberjack#743]
Is it possible to add a log browser UI with this library?

**Comment by johndpope** [comment]
https://github.com/s4nchez/LogIO-CocoaLumberjack 
We should merge this code into this app and add @s4nchez as a contributor.

**Comment by kolyuchiy** [comment]
Also, see https://github.com/0xced/XCDLumberjackNSLogger

**Comment by johndpope** [comment]
@bpoplauschi  - you should add these repos to readme. save people wasting time.

**Comment by bpoplauschi** [comment]
Good idea @johndpope - see https://github.com/CocoaLumberjack/CocoaLumberjack#extensions
