### ISSUE TITLE
CLIColor.h not found if CLANG_ENABLE_MODULES=NO and no AppKit (or DD_CLI is defined)

### ISSUE THREAD

**Issue by thibault-ml** [CocoaLumberjack/CocoaLumberjack#744]
### Issue Info

| Info | Value |
| --- | --- |
| Platform Name | OS X |
| Platform Version | 10.11 |
| CocoaLumberjack Version | master (b9fa35c) |
| Integration Method | manually |
| Xcode Version | Xcode 7.3.1 (7D1014) |
| Repro rate | all the time (100%) |
| Demo project link | https://github.com/thibault-ml/CocoaLumberjackWithoutClangModules/ |
### Issue Description and Steps

I have a project where I am extensively using `CocoaLumberjack.framework`, which is located in a static place on the system, so it is used by different projects, apps or CLI tools.

The problem is that CLI tools do not link against AppKit, so they need `CLIColor`. But the other problem is that my project is resetting the `CLANG_ENABLE_MODULES` value to `NO` (which is the default, but every new project you create will override it to `YES`).

The fix I have found is simply to add CLIColor.h/m to the project, and make sure CLIColor.h is shipped as a public header. Not sure if there's a reason for it, or if it's an oversight.

As for steps, just checkout my project, and hit compile :-).
### Pull Request

https://github.com/CocoaLumberjack/CocoaLumberjack/pull/745

**Comment by bpoplauschi** [comment]
Fixed by #745 in 2.4.0
