### ISSUE TITLE
Undefined symbols error using CocoaLumberjack in Obj-C/Swift project

### ISSUE THREAD

**Issue by mpd518** [CocoaLumberjack/CocoaLumberjack#748]
I have been using CocoaLumberjack painlessly for a while in an objective-C project until recently, while I added some Swift classes into the project and added the following lines to the podfile:

platform :ios, '8.0'
use_frameworks!

and changed the line that reference the CocoaLumberjack pod from
 pod 'CocoaLumberjack'
to:
 pod 'CocoaLumberjack/Swift'

The pod install ran successfully. But then I could no longer build the project. Xcode kept complaining:

Undefined symbols for architecture i386:
  "_DDLogDebug", referenced from:
      ....
  "_DDLogVerbose", referenced from:
     ...
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I checked the "Linking -> Other Linker Flags" setting under Build Settings and it did contain the "CocoaLumberjack" item in it.

Any guidance will be appreciated.

**Comment by warpling** [comment]
Seems related to #654 and #733

I've been running into the same build issues while using Obj-C CocoaLogger in Xcode 8. I can't find the post now but solving it involved putting CocoaLogger back in my prefixHeader.pch file. I remember seeing discussion that we needed to move away from anything requiring prefix headers but for the time being this might be the only solution.
````
        #import <CocoaLumberjack/CocoaLumberjack.h>
        #if IN_QA
        static const DDLogLevel ddLogLevel = DDLogLevelVerbose;
        #else
        static const DDLogLevel ddLogLevel = DDLogLevelWarning;
        #endif
````

Also possibly unrelated is attempting to import CocoaLogger with quotes. Really wish I understood C/build voodoo better:
````
#import "CocoaLumberjack/CocoaLumberjack.h"
````

**Comment by mpd518** [comment]
Thanks for the response. With your hint I added this line to pch file and it fixed the problem!

#import "CocoaLumberjack/CocoaLumberjack.h"

**Comment by warpling** [comment]
Great! If anyone comes across this issue and understand why this works I'd love to learn…
