### ISSUE TITLE
DDFileLogger mixed log messages from different threads

### ISSUE THREAD

**Issue by truebucha** [CocoaLumberjack/CocoaLumberjack#749]
### New Issue Checklist
- [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
- [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
- [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none
### Issue Info

| Info | Value |
| --- | --- |
| Platform Name | ios |
| Platform Version | 9.3 |
| CocoaLumberjack Version | 2.3.0 |
| Integration Method | cocoapods |
| Xcode Version | Xcode 7.3 |
| Repro rate | all the time (100%) |
| Demo project link | no |
### Issue Description and Steps

When a file logger logs messages to a file it smashes them up by mixing different messages.
It happens when multithreading logic occurs.

I am using default configuration with global info log level.
I am also using define statement
# define NSLog(args...) DDLogInfo(args...)

Example is
```
2016/06/27 13:55:22:168  Error retrieving values from parse: Error D2016/06/27 13:55:22:168  Error retrieving values from parse: Error Domain=Parse Code=101 "No results matched the query." UserInfo={error=No results matched the quer2016/06/27 13:55:36:736  removing duplicates started
```
The same time TTY console logger do fine.

**Comment by georgbachmann** [comment]
I can confirm that (was just about to report the same problem)

**Comment by kainjow** [comment]
We're seeing this too, but only on 1 out of 3 projects, oddly enough, and that project is a very small project.

I wonder if #878 is the problem?

**Comment by alexandre-g** [comment]
Hmm my first 5 minutes with CL dont seem very promising. Logging 5 logs to file on button press stuffs up quite badly:
```2018/03/30 17:24:19:853  Verbose
2018/03/30 17:24:19:854  Debug
2018/03/30 17:24:19:854  Info
2018/03/30 17:24:19:854  Warn
2018/03/30 17:24:19:854  Something bad
2018/03/30 17:24:40:296  Verbose
2018/03/30 17:24:40:296  Debug
2018/03/30 17:24:40:296  Info
2018/03/30 17:24:40:296  Warn
2018/03/30 17:24:40:296  Somethin2018/03/30 17:24:40:296  Something bad
2018/03/30 17:29:08:789  Verbose
2018/03/30 17:29:08:789  Debug
2018/03/30 17:29:08:789  Info
2018/03/30 17:29:08:789  Warn
2018/03/30 17:29:08:789  Something bad
2018/03/30 17:29:19:815  Verbose
2018/03/30 17:29:19:815  Debug
2018/03/30 17:29:19:815  Info
2018/03/30 17:29:19:815  Warn
2018/03/30 17:29:19:815  Something bad
2018/03/30 17:29:35:817  Verbose
2018/03/30 17:29:35:817  Debug
2018/03/30 17:29:35:817  Info
2018/03/30 17:29:35:817  Warn
2018/03/30 17:29:35:817  Somethin2018/03/30 17:29:35:817  Somethin2018/03/30 17:29:35:817  Something bad```

**Comment by bpoplauschi** [comment]
Please retry with the latest version of the library and open a clean new issue if the problem still occurs.
