### ISSUE TITLE
CocoaLumberjack in Swift with ASL

### ISSUE THREAD

**Issue by zixun** [CocoaLumberjack/CocoaLumberjack#752]
Hi:
    As you know. in swift api of `print()` will not put the log to the Apple System Logs(ASL).and CocoaLumberjack is work with ASL, how did ASL works in Swift.
    in another word, how did CocoaLumberjack  get the logs in swift where ASL is unavailable

**Comment by MaddTheSane** [comment]
The Swift code is a wrapper around Objective-C where ASL available.
I don't know of any place in the Swift code in the framework that uses `print()`
