### ISSUE TITLE
Build hangs with XCode 8 Swift 2.3 and Carthage

### ISSUE THREAD

**Issue by guidomb** [CocoaLumberjack/CocoaLumberjack#755]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 10
 CocoaLumberjack Version | 2.3.0
 Integration Method      |  carthage
 Xcode Version           | 8 beta 3
 Repro rate              |  all the time (100%
 Demo project link       | ---

### Issue Description and Steps

When using the latest stable release of CocoaLumberjack and XCode 8 beta 3 with Swift 2.3 and Carthage 0.17.2 I get the following error

```
TOOLCHAINS=com.apple.dt.toolchain.Swift_2_3 carthage update --platform ios --no-use-binaries
*** Fetching CocoaLumberjack
*** Checking out CocoaLumberjack at "b9fa35c444a1f037bf58823b4000afaaddb6d456"
*** xcodebuild output can be found in /var/folders/gf/dslbq4t94zg44sz7wnk2lg2r0000gp/T/carthage-xcodebuild.genvPs.log
xcodebuild timed out while trying to read CoreDataLogger.xcodeproj
```

**Cartfile**

```
github CocoaLumberjack ~> 2.3.0
```

**Comment by guidomb** [comment]
Maybe this is a Carthage issue -> https://github.com/Carthage/Carthage/issues/1396#issuecomment-235101948

**Comment by ikesyo** [comment]
Answered on the Carthage issue: https://github.com/Carthage/Carthage/issues/1396#issuecomment-235122980.
