### ISSUE TITLE
CustomLogLevels.md documentation seems out of date...

### ISSUE THREAD

**Issue by andpor** [CocoaLumberjack/CocoaLumberjack#758]
[Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/CustomLogLevels.md) for customizing log levels seems to be completely dated unless I am totally confused.

I am finding references to a DDLog.h file that does not seem to exist. References to macros that do not exist either.

Does not seem to describe how to customized log levels in the latest release

Example:
```objc
# define DDLogFatal(frmt, ...)    SYNC_LOG_OBJC_MAYBE(ddLogLevel, LOG_FLAG_FATAL,  0, frmt, ##**VA_ARGS**)
# define DDLogError(frmt, ...)    SYNC_LOG_OBJC_MAYBE(ddLogLevel, LOG_FLAG_ERROR,  0, frmt, ##**VA_ARGS**)
# define DDLogWarn(frmt, ...)    ASYNC_LOG_OBJC_MAYBE(ddLogLevel, LOG_FLAG_WARN,   0, frmt, ##**VA_ARGS**)
# define DDLogNotice(frmt, ...)  ASYNC_LOG_OBJC_MAYBE(ddLogLevel, LOG_FLAG_NOTICE, 0, frmt, ##**VA_ARGS**)
# define DDLogInfo(frmt, ...)    ASYNC_LOG_OBJC_MAYBE(ddLogLevel, LOG_FLAG_INFO,   0, frmt, ##**VA_ARGS**)
# define DDLogDebug(frmt, ...)   ASYNC_LOG_OBJC_MAYBE(ddLogLevel, LOG_FLAG_DEBUG,  0, frmt, ##**VA_ARGS**)
```

**Comment by andpor** [comment]
Could someone post proper/uptodate instructions for customizing log levels please?

**Comment by bpoplauschi** [comment]
Seems up to date now
