### ISSUE TITLE
Custom Log Level Demo does not demonstrate how to create custom log levels

### ISSUE THREAD

**Issue by andpor** [CocoaLumberjack/CocoaLumberjack#759]
### New Issue Checklist
- [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
- [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
- [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none
### Issue Description and Steps

The demo for custom log levels does not seem to be really demonstrating how to create custom log levels?

Despite defining custom log levels as below:
```objc
# define LOG_LEVEL_FATAL   (LOG_FLAG_FATAL)                     // 0...000001
# define LOG_LEVEL_ERROR   (LOG_FLAG_ERROR  | LOG_LEVEL_FATAL ) // 0...000011
# define LOG_LEVEL_WARN    (LOG_FLAG_WARN   | LOG_LEVEL_ERROR ) // 0...000111
# define LOG_LEVEL_NOTICE  (LOG_FLAG_NOTICE | LOG_LEVEL_WARN  ) // 0...001111
# define LOG_LEVEL_INFO    (LOG_FLAG_INFO   | LOG_LEVEL_NOTICE) // 0...011111
# define LOG_LEVEL_DEBUG   (LOG_FLAG_DEBUG  | LOG_LEVEL_INFO  ) // 0...111111
```
the various LOG_MAYBE calls are not using any of the custom log levels, instead they all use ddLogLevel debug level which is hardcoded to DDLogLevelDebug. Essentially none of the new log levels are used.
```objc
static const DDLogLevel ddLogLevel = DDLogLevelDebug;
# define DDLogFatal(frmt, ...)   LOG_MAYBE(NO,  ddLogLevel, LOG_FLAG_FATAL,  0, nil, **PRETTY_FUNCTION**, frmt, ##**VA_ARGS**)
# define DDLogError(frmt, ...)   LOG_MAYBE(NO,  ddLogLevel, LOG_FLAG_ERROR,  0, nil, **PRETTY_FUNCTION**, frmt, ##**VA_ARGS**)
# define DDLogWarn(frmt, ...)    LOG_MAYBE(YES, ddLogLevel, LOG_FLAG_WARN,   0, nil, **PRETTY_FUNCTION**, frmt, ##**VA_ARGS**)
# define DDLogNotice(frmt, ...)  LOG_MAYBE(YES, ddLogLevel, LOG_FLAG_NOTICE, 0, nil, **PRETTY_FUNCTION**, frmt, ##**VA_ARGS**)
# define DDLogInfo(frmt, ...)    LOG_MAYBE(YES, ddLogLevel, LOG_FLAG_INFO,   0, nil, **PRETTY_FUNCTION**, frmt, ##**VA_ARGS**)
# define DDLogDebug(frmt, ...)   LOG_MAYBE(YES, ddLogLevel, LOG_FLAG_DEBUG,  0, nil, **PRETTY_FUNCTION**, frmt, ##**VA_ARGS**)
```
So what would be the point of creating these custom log levels if they are not USED anywhere in the app.

The problem is that the original log levels are all part of a enum that cannot be changed. If they are  in an enum, any new log levels will not be part of that enum and consequently using them inside LOG_MAYBE is going to create a compile time warning that a value is not part of the enum.

**Comment by bpoplauschi** [comment]
@CocoaLumberjack/collaborators we need to update the docs on Custom Log Levels, as the legacy macros are not used by default

**Comment by sushichop** [comment]
Hi, guys!
I have updated demo and docs about CustomLogLevels. See #1023.
@CocoaLumberjack/collaborators

**Comment by bpoplauschi** [comment]
Fixed by #1023

**Comment by imran20487** [comment]
@bpoplauschi Do you know how it can be done for swift? How to create a new level inside of the enum DDLogLevel?

**Comment by bpoplauschi** [comment]
I really don't know @imran20487. @CocoaLumberjack/collaborators can anyone answer the above question?

**Comment by ffried** [comment]
You can't change `DDLogLevel` (since it's an enum), but you can extend `DDLogFlag` (which is imported as an `OptionSet`).
