### ISSUE TITLE
iOS 10 support

### ISSUE THREAD

**Issue by oscahie** [CocoaLumberjack/CocoaLumberjack#765]
In iOS 10, the "standard" practice of using two loggers (ASL and TTY) results in duplicated log messages in the Xcode console. This can be easily worked around by adding the TTY logger only on iOS devices running iOS < 10.0 and always on the iOS simulator, unless things change before the GM version is released.

Another issue I came across is that (the now deprecated) ASL on iOS 10 is limited to 1024 chars strings, and anything longer than that will be trimmed. This does not affect NSLog, which I'd guess now uses the new os_log() APIs.

So, has anyone created a proper iOS 10 logger that makes use of os_log yet?

**Comment by dustturtle** [comment]
all logs duplicated! waiting for new release!

**Comment by MaddTheSane** [comment]
A *very* simple `os_log` logger can be found [here](https://github.com/MaddTheSane/CocoaLumberjack/tree/sierraLogging).

**Comment by hons82** [comment]
Actually we noticed that as well and used the "DEBUG" flag to use either the TTY or the ASL logger to overcome the double logs issue.

To implement the [new API ](https://developer.apple.com/reference/os/1891852-logging#overview)provided there could be a new _DDOSLogger_ that would always write to the new API, which would be possible and probably the cleanest solution with the drawback of having to check manually in the projects if we're on iOS10+ or not.

The other solution that I see is to make this check in the _DDASLLogger_ and write to the right API depending on the OS version. This could happen already in the singleton call, so that _DDASLLogger_ would return the sharedInstance of _DDOSLogger_ in case we're on the actual OS versions (to remain backward compatible)

**Comment by acacio88** [comment]
You guys might want to have a look at my related PR : https://github.com/CocoaLumberjack/CocoaLumberjack/pull/850

**Comment by judos** [comment]
@oscahie I'm confused about your comment. Since the issue occurs on iOS10 devices, did you mean to only add TTY logger on iOS devices running iOS > 10.0 (instead of iOS<10.0) ?
Changing anything for iOS<10 doesn't make sense.
Thanks

**Comment by oscahie** [comment]
@judos the issue with duplicated logs occurs when you have both loggers (ASL and TTY) on iOS 10.0+, hence why you'd add the TTY logger only on devices running iOS < 10. In other words, the ASL logger alone is enough from iOS 10 onwards. Sadly I haven't had time to look into using os_log yet.

**Comment by follyxing** [comment]
you can try 
1.Xcode menu ->Product ->Scheme -> Edit Scheme -> Run ->Arguments ->Arguments Passed On Launch  add 'disableTTY'
![wx20170329-170921](https://cloud.githubusercontent.com/assets/4349448/24447173/ac40fbcc-14a2-11e7-8466-b7bc07d54c1e.png)

2.
`
NSArray * args = [[NSProcessInfo processInfo] arguments];
if (![args containsObject:@"disableTTY"]) {
      [DDLog addLogger:[DDASLLogger sharedInstance]]; // ASL = Apple System Logs
}
`

**Comment by zolivier** [comment]
Alternatively, ASL logging can be disabled (at least at `DEBUG` time) by setting the `OS_ACTIVITY_MODE` environment variable to `disable` for the active scheme.

![image](https://i.stack.imgur.com/p7BlV.png)
(source: <http://stackoverflow.com/questions/37800790/hide-strange-unwanted-xcode-8-logs>)

**Comment by revolter** [comment]
@oscahie, Isn't it the other way around? Meaning that the new `os_log` **is** truncated at 1024 bytes:

https://github.com/darlinghq/darling/blob/2e341e8c7c3ac5d0559ecbe2dd7dc64efa110bf4/src/libc/os/log.h#L225-L228

**Comment by oscahie** [comment]
That's correct as of today, yes, but at least in the beta versions of iOS 10 and I believe also in the first GM release, strings logged via NSLog were *not* being truncated. I'm not sure when this changed but yeah, now it is like that.

**Comment by bpoplauschi** [comment]
I think #850 closes this.
