### ISSUE TITLE
Won't compile with Carthage due to SWIFT_VERSION in Xcode 8 beta 6

### ISSUE THREAD

**Issue by lvandal** [CocoaLumberjack/CocoaLumberjack#766]
I've reported this a week ago and then the issue was closed even though this is still a problem. The project needs to be updated in order to compile with the latest Xcode 8 beta.

###Steps to reproduce

- Try to compile CocoaLumberJack via Carthage

###Output

=== BUILD TARGET CocoaLumberjackSwift OF PROJECT Lumberjack WITH CONFIGURATION Release ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

**Comment by danielgalasko** [comment]
Can you link the original issue you reported? So weird that there is no word on Swift3 support, not even an experimental branch ¯\_(ツ)_/¯

**Comment by bpoplauschi** [comment]
Should be fixed now by #747 and #773
