### ISSUE TITLE
AppCode colors related code looks broken

### ISSUE THREAD

**Issue by arietis** [CocoaLumberjack/CocoaLumberjack#768]
Hello!

I have read https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/AppCode-support.md and still can't achieve the proper result.

Currently colored logs appear as if TERM=color is missing from env variables in AppCode. Perhaps this is because AppCode supports ANSI colors internally now.

https://blog.jetbrains.com/objc/2016/04/appcode-2016-1-2-rc/

I tried to make it work with Grep Console, without it and still no success.

But such Swift code works perfectly without any additional plug-ins:
`print("\u{001B}[1;32mGreen text here\u{001B}[m normal text here")`
![screen shot 2016-09-05 at 10 59 09](https://cloud.githubusercontent.com/assets/887107/18241140/52b6fe4e-7358-11e6-8b96-50886c7bc152.png)

**Comment by Abnerzj** [comment]
Also i can't get color in xcode console for Xocode 9.2.
![image](https://user-images.githubusercontent.com/7877559/35269784-02c44196-0068-11e8-918b-ea86238ea11c.png)

**Comment by bpoplauschi** [comment]
I don't think the XcodeColors plugin still works (due to Apple changes in supporting plugins).
