### ISSUE TITLE
Redirect all console logs to File

### ISSUE THREAD

**Issue by GusevAndrey** [CocoaLumberjack/CocoaLumberjack#770]
### Issue Info

| Info | Value |
| --- | --- |
| Platform Name | ios |
| Platform Version | 9.0 |
| CocoaLumberjack Version | 2.3.0 |
| Integration Method | manually |
| Xcode Version | Xcode 8.0 GM |
| Lang | Swift/ObjC |
### Issue Description and Steps

Hi!
Searched and didn't find any ways to get all the logs I see in the console to the log file.

I use DDFileLogger and there are great .log files containing the logs I sent via DDLog<Level>.
But system produces some more logs (like constraints warnings, canOpenUrl: failures and many more) that I want in .log file too.

So is there any way to get all the logs (at e.g. verbose level) in .log file?

For now the only way I see is to use TTY-logger and redirect plain old stderr-stream to file.
But: 
all the great file-managment staff provided by DDFileLogger would be missed
and would that make some performance impact?

**Comment by bpoplauschi** [comment]
@GusevAndrey you can look at the CaptureASL demo project, it basically shows you how to capture all the AppleSystemLogs.

**Comment by GusevAndrey** [comment]
@bpoplauschi thx. I've looked at the demo, but or I do something wrong or the DDASLLogCapture isn't thing I'm looking for.

First of all the result logs (via DDFileLogger) doesn't contain any other logs then my DDLog, but console has many more logs I wanted to capture.

Second, as far as I can understand I do not need ASL log capture but only (or with ASL?) the stderr-logs presented in console (TTY logs). 

Any way - I see in console more logs then in log file configured this way:

`let logger = DDFileLogger(logFileManager: fileManager)!`
`DDLog.add(logger)`
`DDASLLogCapture.start()`

**Comment by pbush25** [comment]
@GusevAndrey I believe that you're experience the same problem that other people, including myself, have been experiencing due to the changes in the logging that's done by the system in iOS 10. If my suspicions are correct, I would expect that if you ran your code on an iOS 9 device which allows the app to poll the ASL log file, it would work, but if you did this in iOS 10, it would not. My team is facing the same problem right now, and have yet to find a workaround. I created an issue for it, and posted a question to SO. Anyways, in summation, your code is correct in that it is how I was previously gathering system logs, but will now not work in iOS 10.

**Comment by GusevAndrey** [comment]
@pbush25, thx for comment. I really tryed it on iOS10. Will try it on iOS9. 
For now my solution is to log into console and redirect logs to file old way style (stderr...)

**Comment by kishykumar** [comment]
I am also facing the same issue. 
Isn't DDTTYLogger supposed to log the Xcode console logs to the same file? 

@GusevAndrey Can you share your solution/workaround to this (log into console and redirect logs to file)?

**Comment by GusevAndrey** [comment]
Hey @kishykumar,

The workaround is simple: 

1. Configure DDTTYLogger to send all the logs to the console. That leads to messages logged via CocoaLumberjack to be printed along with the system logs.

2. Redirect all stderr stream to a file (e.g. like so: http://stackoverflow.com/a/8379047/609998)

Sorry for its to take so long.

**Comment by bpoplauschi** [comment]
Closing - nothing to do here
