### ISSUE TITLE
Swift 3 Support

### ISSUE THREAD

**Issue by jlaws** [CocoaLumberjack/CocoaLumberjack#771]
What is the plan/schedule for adding Swift 3 support?

**Comment by avielg** [comment]
For now, pushed Xcode 8GM/Swift3 support through a fork: https://github.com/avielg/CocoaLumberjack.git

**Comment by ffried** [comment]
See PR #769

**Comment by virl** [comment]
Please add Swift 3 support.

**Comment by 8masterofpuppets8** [comment]
Any plans when support for Swift 3, or at least 2.3, will be released?

**Comment by bpoplauschi** [comment]
Fixed by #769. Version 3.0.0 is released.
