### ISSUE TITLE
Xcode8 support

### ISSUE THREAD

**Issue by Creolophus** [CocoaLumberjack/CocoaLumberjack#772]
hello , when will you guys support Xcode 8 , i love this tool so much!!

**Comment by avielg** [comment]
For now, pushed Xcode 8GM/Swift3 support through a fork: https://github.com/avielg/CocoaLumberjack.git

**Comment by hons82** [comment]
PR #769

**Comment by bpoplauschi** [comment]
Fixed by #769. Version 3.0.0 is out.
