### ISSUE TITLE
3.0.0 build fails on Xcode 7.3.1 due to unknown macro FOUNDATION_SWIFT_SDK_EPOCH_AT_LEAST

### ISSUE THREAD

**Issue by mkujalowicz** [CocoaLumberjack/CocoaLumberjack#775]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 9.1
 CocoaLumberjack Version | 3.0.0
 Integration Method      | cocoapods
 Xcode Version           | 7.3.1
 Repro rate              | 100%
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

I'm getting compilation error:
DDFileLogger.h:429:40: Token is not a valid binary operator in a preprocessor subexpression
while building the pod with Xcode 7.3.1

**Comment by max-potapov** [comment]
You should use version 2.4.0 for Xcode 7.3.1. See updated `requirements` in README for details.

**Comment by mkujalowicz** [comment]
Ah, ok, I missed that part. You're right! Sorry for trouble. I'm closing it.

**Comment by bpoplauschi** [comment]
Thanks @max-potapov

**Comment by a-radwan** [comment]
I'm using Xcode 7.3.1 and Swift version is 2.2
the version for CocoaLumberJack is '2.3.0.
And the sane error appeared.
Any new?
