### ISSUE TITLE
Logs appear as optionals with Swift 3.0

### ISSUE THREAD

**Issue by moray95** [CocoaLumberjack/CocoaLumberjack#776]
### New Issue Checklist
- [X] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
- [X] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
- [X] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none
### Issue Info

| Info | Value |
| --- | --- |
| Platform Name | iOS |
| Platform Version | 10.0 |
| CocoaLumberjack Version | 3.0 |
| Integration Method | Cocoapods |
| Xcode Version | Xcode 8.0 |
| Repro rate | 100% |
| Language | Swift 3.0 |
### Issue Description and Steps

After upgrading my project to use CocoaLumberjack 3.0, the logs started appearing as optionals.
For instance, when using `DDLogInfo("Some log")`, we expect the `Some log` to appear on the console, but instead `Optional("Some log")` appears. I believe this a Swift bridging problem with the missing nullability annotations. Adding `NS_ASSUME_NONNUL_BEGIN` at the start and `NS_ASSUME_NONNUL_END` at the end of DDLog.h fixes the issue.

**Comment by MaddTheSane** [comment]
Have a look at [this fork](https://github.com/MaddTheSane/CocoaLumberjack/tree/nullability) and see if the problem persists.

Is your logger written in Swift?

**Comment by moray95** [comment]
I haven't implemented a logger, I am using the default `DDTTYLogger` with a log formatter written in Swift. Your fork does indeed solves the issue.

**Comment by florianheller** [comment]
@MaddTheSane The solution from the fork works, in my case I had to add `()` to the lines like `public func DDLogDebug(_ message: @autoclosure () -> String, level: DDLogLevel = defaultDebugLevel, context: Int = 0, file: StaticString = #file, function: StaticString = #function, line: UInt = #line, tag: Any? = nil, asynchronous async: Bool = true, ddlog: DDLog = DDLog.sharedInstance())` in CocoaLumberjack.swift to remove all warnings, but now everything works fine.

**Comment by mandoonandy** [comment]
@MaddTheSane would you be able to send a pull request to get your fixes into the main repo?

Seeing "Optional()" everywhere in the logs makes this framework frustrating to use in Swift.

**Comment by mservidio** [comment]
@MaddTheSane  I tried your forked version at https://github.com/MaddTheSane/CocoaLumberjack/tree/nullability but the issue still occurs.

**Comment by rendion** [comment]
Any word on merging this?

**Comment by MaddTheSane** [comment]
It was merged in commit 57c9b592b596017714e7f81ab43839dea720cead.
