### ISSUE TITLE
Unable to see log inside the console window in iOS application.

### ISSUE THREAD

**Issue by qureship786** [CocoaLumberjack/CocoaLumberjack#780]
I want to implement an in app log viewer that not only shows the list of all log files inside that application (using DDLogger to perform message logging) and enables user to view the logs of a particular log file. This functionality also allows to perform a search inside a given log file. I have tried [LumberjackConsole](https://github.com/PTEz/LumberjackConsole) but it is not working for file logging. The [issue](https://github.com/PTEz/LumberjackConsole/issues/14) is related to this. I am referring that issue in here too as that console is using CocoaLumberJack as its base. One probable reason seems to me behind this is that the console is creating a different logging instance then referring to the file logger that I created.

Any idea on how to resolve this issue ?

Thanks

**Comment by bpoplauschi** [comment]
Per the linked issue, need to use the latest versions of both.
