### ISSUE TITLE
CLIColor.h is missing from working copy

### ISSUE THREAD

**Issue by Nathan187** [CocoaLumberjack/CocoaLumberjack#785]
### New Issue Checklist
- [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
- [ ] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
- [ ] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none
### Issue Info

| Info | Value |
| --- | --- |
| Platform Name | iOS |
| Platform Version | +10.0 |
| CocoaLumberjack Version | latest? |
| Integration Method | carthage |
| Xcode Version | Xcode 8 |
| Repro rate | n/a |
| Demo project link | n/a |
### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

cartfile:  
...
# cocoaLumberjack

github "CocoaLumberjack/CocoaLumberjack"

performed carthage update --platform ios

i get this warning...what am i doing wrong , please

.../Carthage/Build/iOS/CocoaLumberjack.framework/Headers/CLIColor.h: warning: Missing file: /Project Work/Source Code/SportDxMobile/Carthage/Build/iOS/CocoaLumberjack.framework/Headers/CLIColor.h is missing from working copy

**Comment by bpoplauschi** [comment]
Please try again. I tried it just now and it worked without any issue.
