### ISSUE TITLE
Log file rename notification

### ISSUE THREAD

**Issue by KarthikV710** [CocoaLumberjack/CocoaLumberjack#787]
Hi Team, 

Is it possible for CocoaLumberjack to post a notification or a provide a delegate method to get notified when a new log file is generated once the current log file is over the specified size limit?

One such example for this feature would help in renaming the concurrent log files generated for the same instance of the application.

Example:
I can rename the first log file using - (void)renameFile:(NSString *)newFileName;, but after the first file is over the specified size(specified using @property (readwrite, assign) unsigned long long maximumFileSize;) I have found no way of renaming my subsequent log file.

Please let me know if this feature already exists (I may have missed it).

Thanks,
Karthik

**Comment by bpoplauschi** [comment]
You could try
```
DDLogFileManager

- (void)didArchiveLogFile:(NSString *)logFilePath;
- (void)didRollAndArchiveLogFile:(NSString *)logFilePath;
```
