### ISSUE TITLE
DDFileLogger.h: Token is not a valid binary operator in a preprocessor subexpression

### ISSUE THREAD

**Issue by yogesh-zendrive** [CocoaLumberjack/CocoaLumberjack#788]
### Issue Info

| Info | Value |
| --- | --- |
| Platform Name | ios / osx |
| Platform Version | All |
| CocoaLumberjack Version | 3.0.0 |
| Integration Method | cocoapods |
| Xcode Version | Xcode 7.3 |
| Repro rate | all the time (100%) |
### Issue Description and Steps
- Create an Objetive-C based project
- Install 3.0.0 through pods
- Import DDFileLogger.h in any class (eg. AppDelegate.m)
- Build

**Comment by yogesh-zendrive** [comment]
The error comes at this line: #if FOUNDATION_SWIFT_SDK_EPOCH_AT_LEAST(8)

**Comment by shaharukhs** [comment]
same error for me

Info	Value
Platform Name	ios / osx
Platform Version	All
CocoaLumberjack Version	3.0.0
Integration Method	cocoapods
Xcode Version	Xcode 7.3.1
Repro rate	all the time (100%)

**Comment by 00rain00** [comment]
save error for me

**Comment by shaharukhs** [comment]
use 

> platform :ios, '7.0'
> pod 'CocoaLumberjack', '~> 2.4.0'

**Comment by 00rain00** [comment]
For me, only 2.3 work

**Comment by ronak2121** [comment]
This is also failing in Xcode 8/Swift 3 with CocoaLumberjack 3.0.0.

**Comment by danielgalasko** [comment]
We using swift 3 so downgrading isnt really an option. More info can be derived in the console, cant even use `po` anymore now because this happens:

```
error: in auto-import:
failed to get module 'MyApp' from AST context:
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/CocoaLumberjack-umbrella.h"
        ^

MyApp/Pods/Target Support Files/CocoaLumberjack/CocoaLumberjack-umbrella.h:7:9: note: in file included from MyApp/Pods/Target Support Files/CocoaLumberjack/CocoaLumberjack-umbrella.h:7:
#import "DDFileLogger.h"
        ^

error: MyApp/Pods/CocoaLumberjack/Classes/DDFileLogger.h:429:40: error: token is not a valid binary operator in a preprocessor subexpression
#if FOUNDATION_SWIFT_SDK_EPOCH_AT_LEAST(8)
                                       ^

error: could not build Objective-C module 'CocoaLumberjack'
```

**Comment by huig1149** [comment]
I solved this problem by modifying the CocoaLumberjack version. In the link "https://github.com/CocoaLumberjack/CocoaLumberjack",can see some details.Like this 
for Xcode 7.3 and Swift 2.3, use the 2.4.0 version
for Xcode 7.3 and Swift 2.2, use the 2.3.0 version
for Xcode 7.2 and 7.1, use the 2.2.0 version
for Xcode 7.0 or earlier, use the 2.1.0 version
for Xcode 6 or earlier, use the 2.0.x version
for OS X < 10.7 support, use the 1.6.0 version

1. so, if you use Xcode 7.3, go to the directory of the ios workspace, then open the file "Podfile", modify the line {pod 'CocoaLumberjack’} to {pod 'CocoaLumberjack’, '~> 2.4.0'}
2. open the Terminal, use the command: $ pod install --no-repo-update	
3. Rebuild the iOS project

**Comment by danielgalasko** [comment]
@yogesh-zendrive I dont think you can use Swift 2.3 with Xcode 7? What about Xcode 8?

**Comment by MaddTheSane** [comment]
Swift 2.2 and 2.3 are similar enough that only minor changes would be needed.

**Comment by a-radwan** [comment]
I'm using xcode 7.3.1 and Swift version is 2.2
the version for CocoaLumberJack  is  '2.3.0.
And the sane error appeared. 
Any new?

**Comment by JLau-cy** [comment]
I am using Xcode 8.0 and Swift version 3.
Using **pod 'CocoaLumberjack/Swift'** which is pulling version 3.0.0

I am still getting the same issue as @danielgalasko 

Any updates on using Swift 3?

**Comment by danielgalasko** [comment]
@JLau-cy its working for me again FYI. But we are not supporting iOS 8 anymore so I cant comment on that I am afraid 😞

**Comment by bpoplauschi** [comment]
Probably not applicable, since a lot has changed since then
