### ISSUE TITLE
It is all about Carthage and xcodeproj.

### ISSUE THREAD

**Issue by lolgear** [CocoaLumberjack/CocoaLumberjack#789]
Well, I need an advice.
And it could be a part of tutorial for Carthage distribution.
I integrated CocoaLumberjack folder structure in project JWT.
It works fine and it is really clean. I've never seen before so simple and pure structure.
However, troubles come with Carthage support.

Before Carthage.
Project has one dependency, it is specified in podspec.
`Framework/` folder contains `.xcworkspace` and `.xcodeproj` files.
It also contains build targets, Podfile and dependent `Pods/`.

Try Carthage.
Carthage doesn't allow you to add dependent Pods or frameworks in your framework easily and, as I know, it is impossible now.
I made weak linking for that dependency ( only one dependency ). It is unnecessary for building now.
But targets still contains `CocoaPods build phases`.

And `xcodebuild` ( as part of `carthage` ) fails in case of missing .xcconfig file ( it is not copying or so ).

CocoaLumberjack, as I understand, doesn't contain pods ( they are unnecessary for building frameworks, only for apps and tests ).
So, it is compiled perfectly without messy configuration of `Pods`.

**Comment by bpoplauschi** [comment]
@lolgear I'm not sure I properly understood.
Are you switching from CocoaPods to Carthage?
You can specify dependencies with Carthage as well using a Cartfile.
Our library supports both ways to install.
Feel free to reopen the issue if you want to continue the conversation
