### ISSUE TITLE
Carthage build error:

### ISSUE THREAD

**Issue by medisean** [CocoaLumberjack/CocoaLumberjack#790]
### Issue Info

| Info | Value |
| --- | --- |

 Platform Name          iOS
 Platform Version       8.0
 CocoaLumberjack Version 2.3.0
 Integration Method      carthage
 Xcode Version          Xcode 7.3.1
 Repro rate              100%
 Demo project link       none
### Issue Description and Steps

Use carthage to build CocoaLumberjack error. Message like this:

**\* Building scheme "CocoaLumberjackSwift-watchOS" in Lumberjack.xcworkspace
*\* CLEAN FAILED **

The following build commands failed:
    Check dependencies
(1 failure)
*\* BUILD FAILED **

The following build commands failed:
    Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/zouliangming/Teambition-Universal/Carthage/Checkouts/CocoaLumberjack/Framework/Lumberjack.xcworkspace -scheme CocoaLumberjackSwift-watchOS -configuration Release -sdk watchsimulator ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
*\* CLEAN FAILED **

The following build commands failed:
    Check dependencies
(1 failure)
*\* BUILD FAILED **

The following build commands failed:
    Check dependencies
(1 failure)

**Comment by sushichop** [comment]
I encountered the similar error even with master branch(https://github.com/CocoaLumberjack/CocoaLumberjack/commit/a42a14b92ad1450021284393f75de8a5e73ceda5).

 Info                    | Value                               |
-------------------------|-------------------------------------|
Carthage Version | 0.18
Xcode Version | 8.2.1
Repro rate | 100%

Then I made a PR(#819). This PR should solve the issue.
At least I confirmed that Carthage build has been successful about every framework target(iOS, macOS, tvOS, and watchOS).

Cheers.

**Comment by bpoplauschi** [comment]
Fixed by #819

**Comment by medisean** [comment]
Thanks.

**Comment by bolee** [comment]
really fix it? my xcode is 8.2.1 and swift is 3.0.2,carthage update show error:Check dependencies!

**Comment by bpoplauschi** [comment]
@bolee it was fixed, but in the meantime we released some new versions. The latest (3.3.0) requires Xcode 9 and Swift 4, so you need to force using a version up to 3.2.1 (latest one with Xcode 8 and Swift 3 support). See the [Requirements](https://github.com/CocoaLumberjack/CocoaLumberjack#requirements) and [Backwards compability](https://github.com/CocoaLumberjack/CocoaLumberjack#backwards-compability) sections from our docs.

**Comment by bolee** [comment]
@bpoplauschi I check 3.2.1 version,it is right. The last version can work Swift 4.0 but not Swift 3.x?

**Comment by bpoplauschi** [comment]
@bolee I think so (that version 3.3.0 requires Swift 4 so it won't work with Swift 3).
