### ISSUE TITLE
Retrieving System logs on top of regular logs in iOS 10

### ISSUE THREAD

**Issue by pbush25** [CocoaLumberjack/CocoaLumberjack#791]
### New Issue Checklist
- [X] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
- [X] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
- [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none
### Issue Info

| Info | Value |
| --- | --- |
| Platform Name | iOS |
| Platform Version | 10.0 |
| CocoaLumberjack Version | 2.3.0 |
| Integration Method | manually |
| Xcode Version | Xcode 8.0 |
| Repro rate | all the time (100%) |
### Issue Description and Steps

Prior to iOS 10, I could create an instance of an ASL Logger, and set it up to capture the system logs coming out of NSLog in other frameworks that our app was using, like so: 
        `DDASLLogCapture.setCaptureLevel(.All)`
        `DDASLLogCapture.start()`

However, with iOS 10 now, this no longer works. In the file `DDASLLogCapture.m`, the entirety of capturing the system logs comes out of banking off of notifications from the system that there's new log messages in the database with the key `kNotifyASLDBUpdate` which is equal to "com.apple.system.logger.message". This key doesn't seem to have changed in iOS 10, as I can inspect the `notify_keys.h` file in order to view them, but the notifications don't occur in iOS 10, I'm assuming as a result of moving over to os_log. 

This being the case, what can be done now to retrieve system logs that were being directed to console output that are no longer being picked up by the `DDASLLogCapture` object?

**Comment by CodeLife2012** [comment]
Any progress?

**Comment by pbush25** [comment]
@CodeLife2012 well yes and no. I know _why_ this doesn't work anymore. In iOS 10, Apple no longer puts the asl log file in a place that's accessible and poll-able by the user, as it was in iOS 9. I get why they did, for security reasons anyways, as sometimes we log stuff that maybe shouldn't be visible to everyone. However, as a result of this change, CCL no longer works the way that it did before in this respect. In fact, I'm not sure if there's any way to circumvent this, unless you redirect everything to the stderr stream which you would still be able to access from my understanding but kind of defeats the whole purpose. I'd be interested if anyone from the team or community had thoughts on this issue and whether there was a way to get back all the system logs we now miss out on in iOS 10.

**Comment by ffried** [comment]
ASL was replaced by os_log. And with os_log, AFAIK there's no way to gather logs inside the app. So I don't think this is solvable.
