### ISSUE TITLE
Wrong default levels in CocoaLumberjack.swift

### ISSUE THREAD

**Issue by rmaddy** [CocoaLumberjack/CocoaLumberjack#792]
In the CocoaLumberjack.swift file, all of the `DDLogWarn`, `DDLogDebug`, _etc._ functions all specify a default value for the `level` parameter as `defaultDebugLevel`. Shouldn't each of these functions specify the appropriate level? _e.g._ `DDLogWarn` should specify `.warn` and `DDLogDebug` should specify `.debug.`

These changes would make them more like their Objective-C counterparts defined in the DDLogMacros.h file.

**Comment by MaddTheSane** [comment]
The `level` is to specify what the current debug level is set at. The level checked via the `flag:` variable passed to `_DDLogMessage`.

**Comment by rmaddy** [comment]
Ugh! I'm blind. I stared at that Swift file for quite some time and didn't notice the different `flag` value being passed for each of the `DDLogWarn`, `DDLogDebug`, _etc._ functions. I'm closing this. Sorry folks.
