### ISSUE TITLE
timed out while trying to read CoreDataLogger.xcodeproj

### ISSUE THREAD

**Issue by daver234** [CocoaLumberjack/CocoaLumberjack#793]
I'm using Carthage, Xcode 8 and swift 2.3, on Mac Sierra, carthage version 0.17.2  In my cartfile I have:
github "CocoaLumberjack/CocoaLumberjack" "2.4.0"

I run Carthage bootstrap --platform iOS and I get this error:
timed out while trying to read CoreDataLogger.xcodeproj

Any suggestions?

Thanks.

**Comment by daver234** [comment]
Solved it.  Need to be on Carthage 0.18.1 at least

**Comment by dodikk** [comment]
> Solved it. Need to be on Carthage 0.18.1 at least

@daver234 , did you update it with homebrew?
Which approach have you used?

**Comment by bpoplauschi** [comment]
Closing, based on the previous comments.
