### ISSUE TITLE
Convenience Macros (DDLogDebug, DDLogInfo, DDLogError) are are not found in Swift3

### ISSUE THREAD

**Issue by gtennis** [CocoaLumberjack/CocoaLumberjack#794]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 10.0
 CocoaLumberjack Version | 3.0
 Integration Method      | cocoapods
 Xcode Version           | e.g. Xcode 8.0 (8A218a)
 Repro rate              | all the time (100%)

### Issue Description and Steps

I have created a new project with Swift3 and installed CocoaLumberhack via 1.0.1 CocoaPods:

`pod` 'CocoaLumberjack', '~> 3.0'

And then I added import at the top of the file where I want to use logging:

`import` CocoaLumberjack

The problem I have is none of the macros is available:

```
DDLogVerbose("Verbose");
DDLogDebug("Debug");
DDLogInfo("Info");
DDLogWarn("Warn");
DDLogError("Error");
```

Compiler says "Use of unresolved identifier...". Then I looked what's inside the imported CocoaLumberjack module:

```
import CocoaLumberjack.CocoaLumberjack
import CocoaLumberjack.DDASLLogCapture
import CocoaLumberjack.DDASLLogger
import CocoaLumberjack.DDAbstractDatabaseLogger
import CocoaLumberjack.DDAssertMacros
import CocoaLumberjack.DDContextFilterLogFormatter
import CocoaLumberjack.DDDispatchQueueLogFormatter
import CocoaLumberjack.DDFileLogger
import CocoaLumberjack.DDLegacyMacros
import CocoaLumberjack.DDLog
import CocoaLumberjack.DDLogMacros
import CocoaLumberjack.DDLog_LOGV
import CocoaLumberjack.DDMultiFormatter
import CocoaLumberjack.DDTTYLogger
import UIKit
```

And then I looked at DDLogMacros and DDLegacyMacros, and was surprised both are completely empty:

`import` UIKit

I'm wondering, has anyone used 3.0 version on a project?

**Comment by agathe** [comment]
Had the same issue, but using `import CocoaLumberjackSwift` everything seems to work ok.

**Comment by gtennis** [comment]
If I replace my import with import CocoaLumberjackSwift then I get no such module. Guys already merged Swift code into 3.0 version, and so there's no point in having "Swift" suffix at the end. Maybe it was a temporal solution some time ago.

**Comment by MonkeyDMat** [comment]
Hi,

I've had the same problem, and I changed my Podfile

from :
pod 'CocoaLumberjack', '~> 3.0'

to :
pod 'CocoaLumberjack/Swift', '~> 3.0'

and it worked.

**Comment by gtennis** [comment]
Thanks @MonkeyDMat, it helped. Also, in code, we need to use:

`import CocoaLumberjack`

not import CocoaLumberjackSwift
