### ISSUE TITLE
Using CocoaLumberjack in a Cocoapod

### ISSUE THREAD

**Issue by AtharvaVaidya** [CocoaLumberjack/CocoaLumberjack#795]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 10.0
 CocoaLumberjack Version | 3.0.0
 Integration Method      | Cocoapods
 Xcode Version           | Xcode 8.0
 Repro rate              | 100%

### Issue Description and Step

I'm having trouble using CocoaLumberjack in my Cocoapod. I've set it as a dependency in the PodSpec, and I've imported CocoaLumberjack in my cocoapod's .pch file, but it can't pass the linter. 
This is the error the linter throws: 

` - ERROR | [iOS] xcodebuild:  /Users/atharvavaidya/Developer/BMUtilities-JHBI/BMUtilities-JHBI/Classes/Constants.m:11:18: error: use of undeclared identifier 'DDLogLevelVerbose'`

My prefix header looks like this:

````
#ifdef __OBJC__
#import <UIKit/UIKit.h>
#define LOG_LEVEL_DEF ddLogLevel
@import CocoaLumberjack;
#import "Constants.h"
#endif
````
Constants.m looks like:
````
#import "Constants.h"
int ddLogLevel = DDLogLevelVerbose;
````

Constants.h looks like: 
````
FOUNDATION_EXPORT int ddLogLevel;
````

**Comment by maksutovic** [comment]
I'm having the same exact issue , I'm able to get Cocoalumberjack integrated into my main project, however with my large library of private cocoapods, I am unable to integrate CocoaLumberjack in the same way that @AtharvaVaidya is attempting.

**Comment by imbaZLN** [comment]
I think adding this line to the PodSpec may be helpful.

`s.prefix_header_contents = '#define LOG_LEVEL_DEF FOOBAR', '#import <CocoaLumberjack/CocoaLumberjack.h>', 'extern DDLogLevel FOOBAR'`

And don't forget to define the variable `FOOBAR ` somewhere in your implementation files.

**Comment by imbaZLN** [comment]
I think adding this line to the PodSpec may be helpful.

s.prefix_header_contents = '#define LOG_LEVEL_DEF FOOBAR', '#import <CocoaLumberjack/CocoaLumberjack.h>', 'extern DDLogLevel FOOBAR;'

And don't forget to define the variable FOOBAR somewhere in your implementation files.

**Comment by bpoplauschi** [comment]
Closing this old issue. Feel free to comment/reopen if the problem still applies to our latest version.
