### ISSUE TITLE
Why DDLogMessage has a 'level'?

### ISSUE THREAD

**Issue by CodeLife2012** [CocoaLumberjack/CocoaLumberjack#797]
Can't understand the usage of this property.

**Comment by bpoplauschi** [comment]
@CodeLife2012 I think it's not used - or at least that is how it looks. And it doesn't make sense.
Could you create a PR for this?

**Comment by CodeLife2012** [comment]
Ok, I will do it later.

**Comment by CodeLife2012** [comment]
I think again, and  find `level ` can be  used when define a custom formatter. Delete it will break the API, so just keep  it there.

**Comment by bpoplauschi** [comment]
Ok @CodeLife2012. Thanks for looking into this and making it clear.
