### ISSUE TITLE
LOG_LEVEL_DEF not defined when integrated as a dynamic framework.

### ISSUE THREAD

**Issue by CodeLife2012** [CocoaLumberjack/CocoaLumberjack#799]
I see LOG_LEVEL_DEF is defined in the header file, why report this.

Preprocess code :
`do { if(LOG_LEVEL_DEF & DDLogFlagError) [DDLog log : __objc_no level : LOG_LEVEL_DEF flag : DDLogFlagError context : 0 file : "/Code/TtyDDLog/TtyDDLog/Classes/Test.m" function : __PRETTY_FUNCTION__ line : 15 tag : ((void *)0) format : (@"Why")]; } while(0);`

Should be ddLogLevel here.

**Comment by CodeLife2012** [comment]
This is very strange, because I can see the `LOG_LEVEL_DEF` is defined in `DDLogMacros.h`,

**Comment by CodeLife2012** [comment]
I create[ a small project](https://github.com/CodeLife2012/DDLog) to demonstrate this issue.

**Comment by Zatoichy** [comment]
Add `static const DDLogLevel ddLogLevel = DDLogLevelVerbose;`

**Comment by CodeLife2012** [comment]
Not the existence of `ddLogLevel ` but  can't find the define of`LOG_LEVEL_DEF `.
@Zatoichy

**Comment by Zatoichy** [comment]
In documents written, you need to declare yourself LOG_LEVEL_DEF. https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/GettingStarted.md
