### ISSUE TITLE
DDFileLogger doesn't write files in distributed (enterprise) app

### ISSUE THREAD

**Issue by 7mllm7** [CocoaLumberjack/CocoaLumberjack#800]
### Issue Description and Steps

I experience that `DDFileLogger` with default configuration doesn't write log files *only* in released versions (in my case it's enterprise ("In-House") release.
When I run the app by debugging with Xcode, it does save them to the expected location, but in the distributed version not only I can't find the logs files (using different iPhone file system explorers apps), and especially `.logFileManager.sortedLogFilePaths` returns an empty array.

Anyone has an idea what I might be doing wrong?

Thanks!

### Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name      |     ios
 Platform Version    |    10.1.1
 CocoaLumberjack Version | 2.4.0
 Integration Method   |  cocoapods
 Xcode Version         |  8.1

**Comment by galblank** [comment]
I'm trying to make this work in Swift and it seems that with latest XCode and Swift 2.3 CocoaLumberjack is no longer works at all.

**Comment by bpoplauschi** [comment]
@7mllm7 @galblank can you try with our 3.x latest version?

**Comment by bpoplauschi** [comment]
Probably an old issue, since we are at Swift 4.2 and Xcode 10. Closing
