### ISSUE TITLE
Multiple line logs

### ISSUE THREAD

**Issue by danielwmsun** [CocoaLumberjack/CocoaLumberjack#805]
I see that if I add a carriage return to my logs, I only see the first line logged. I also noticed this while trying to log an NSArray with just it's default description, I don't see the actual contents of the array because each object in the array is printed on a new line. Is there a way to override this behavior?

**Comment by plivesey** [comment]
Seems to be the same issue as #841 btw. I'm also seeing this problem.

**Comment by sushichop** [comment]
Can you refer to #841 ?
Thanks.
