### ISSUE TITLE
Logs don't print anymore

### ISSUE THREAD

**Issue by colasbd** [CocoaLumberjack/CocoaLumberjack#817]
I'm using CocoaLumberjack (2.3.0) installed with CocoaPods with `use_frameworks!`.

The classical way to define `ddLogLevel` does not work anymore. I had to do
```obj-c
// MyConstantsForCocoaLumberJack.m
#import "MyConstantsForCocoaLumberJack.h"

#import <CocoaLumberjack/CocoaLumberjack.h>

#ifdef DEBUG
//const int ddLogLevel = DDLogFlagVerbose;
const int ddLogLevel = DDLogFlagVerbose | DDLogFlagDebug | DDLogFlagInfo | DDLogFlagWarning | DDLogFlagError;
#else
//const int ddLogLevel = DDLogFlagWarning;
const int ddLogLevel = DDLogFlagWarning | DDLogFlagError;
#endif
```

The header `MyConstantsForCocoaLumberJack.h` is just
```obj-c
extern const int ddLogLevel;
```

I import  `MyConstantsForCocoaLumberJack.h` in the `.pch` file.

**Comment by mcstoufer** [comment]
I'm seeing the same as well. Xcode 8.2 using the latest CocoaLumberjack pod (3.0.0) for Obj-C
I even pulled out all the deprecated Colorization code and env vars.

**Comment by mcstoufer** [comment]
I think I know what went wrong. As part of the upgrade to 8.2, I accepted the "upgrade to recommended settings. The DEBUG preprocessor marco was removed. I do not think this was part of the preprocessor macro section in the build settings for a given target. I added it back in and, whammo, all my CL messages reappear and honor the log level I've set.

**Comment by maniak-dobrii** [comment]
Did you register any loggers? For example, like this:
```
 [DDLog addLogger:[DDTTYLogger sharedInstance]];
 [DDLog addLogger:[DDASLLogger sharedInstance]];
```

**Comment by colasbd** [comment]
@mcstoufer Can you give more details? Screenshot? Thanks.

**Comment by bpoplauschi** [comment]
You should look at the latest version and see the Migration guide to 3.0, might solve your problems.

**Comment by optionals** [comment]
@colasbd https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/XcodeTricks.md
