### ISSUE TITLE
Msg: Undefined symbols for architecture x86_64: when iOS simulator is the target

### ISSUE THREAD

**Issue by ctgreybeard** [CocoaLumberjack/CocoaLumberjack#821]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 10.1
 CocoaLumberjack Version | 3.0.0
 Integration Method      | cocoapods
 Xcode Version           | 8.1
 Repro rate              | all the time
 Demo project link       | None

### Issue Description and Steps

I am upgrading my app to Swift 3 and I have run into a problem linking when the iOS simulator is the target.

I get several messages of the sort:

```
Undefined symbols for architecture x86_64:
  "CocoaLumberjack.DDLogDebug (@autoclosure () -> Swift.String, level : __C.DDLogLevel, context : Swift.Int, file : Swift.StaticString, function : Swift.StaticString, line : Swift.UInt, tag : Any?, asynchronous : Swift.Bool, ddlog : __ObjC.DDLog) -> ()", referenced from:
      ScanmonListener.SMLViewController.buttonTitle.didset : Swift.String in SMLViewController.o
      ScanmonListener.SMLViewController.viewDidLoad () -> () in SMLViewController.o
      ...
```

I have tried a `pod deintegrate` and then an install and that had no effect.

**Comment by sushichop** [comment]
With Xcode 8.1, I recommend you  use master branch because it has been tested with Xcode 8.1.
And if you'd like to Swift version(CocoaLumberjack/Swift subspec), ensure the followings **before you integrate the project with CocoaPods**.

1. Check the CocoaPods version is 1.1.0 or later.
2. In your main app project's Build Settings, set `Use Legacy Swift Language Version` to `No`.

I hope this will clear up the problem.

**Comment by ctgreybeard** [comment]
Unfortunately I still have the problem.

My cocoapods versions is 1.2.0.beta.3

I deintegrated the project, verified the Legacy Swift setting is No.

Changed my Podfile to:

```
platform :ios, '10.2'

target 'ScanmonListener' do
    pod 'CocoaLumberjack/Swift', :git => 'https://github.com/CocoaLumberjack/CocoaLumberjack.git', :branch => 'master'
    use_frameworks!
end

...
```

But I still get:

```
Undefined symbols for architecture x86_64:
  "CocoaLumberjack.(DDLogVerbose (@autoclosure () -> Swift.String, level : __C.DDLogLevel, context : Swift.Int, file : Swift.StaticString, function : Swift.StaticString, line : Swift.UInt, tag : Any?, asynchronous : Swift.Bool, ddlog : __ObjC.DDLog) -> ()).(default argument 1)", referenced from:
      ScanmonListener.SMLViewController.buttonTouch (__ObjC.UIButton) -> () in SMLViewController.o
```

31 times when I build against the iOS Simulator but if I choose "Generic iOS Device" it compiles and links fine.

I haven't built this in a while, probably against XCode 7.x last, but it did build and run on the simulator.

**Comment by ctgreybeard** [comment]
Solved!

For each of the targets under Pods I had to edit the __`Valid Architectures`__ setting to add __`x86_64`__

Compile and link against the iOS Simulator now works and my app now runs under the simulator again.

**Comment by sushichop** [comment]
Just an Information.
At my local machine(Xcode: 8.2.1, toolchain: Swift 3.0.2), I was actually able to build CocoaLumberjack only with a normal procedure.

IMHO, if you reinstall a library with CocoaPods, `pod deintegrate` is not enough.
You need to execute not only `pod deintegrate` but also `pod cache clean CocoaLumberjack` and `rm -rf /Library/Developer/Xcode/DerivedData`.

Summary is here.

Podfile
```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.2'
use_frameworks!
inhibit_all_warnings!

target 'CocoaLumberjackSample' do
  pod 'CocoaLumberjack/Swift', :git => 'https://github.com/CocoaLumberjack/CocoaLumberjack.git'
end
```

Check `Use Legacy Swift Language Version` is set to `No` and close xcworkspace.
Then execute the followings.

```
pod deintegrate
pod cache clean CocoaLumberjack
rm -rf /Library/Developer/Xcode/DerivedData
pod install
```

I hope this will be helpful for someone.
