### ISSUE TITLE
Custom LogFormatter - Thread safety with NSDateFormatter

### ISSUE THREAD

**Issue by philhinco** [CocoaLumberjack/CocoaLumberjack#827]
According to the [CustomFormatters.md](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/CustomFormatters.md), if one wants to use a formatted date in the log message, we need to implement custom thread-safety for the formatter.

What confuses me is that, according to [NSDateFormatters entry on thread safety](https://developer.apple.com/reference/foundation/nsdateformatter#1680059), since iOS7 it is thread safe.

If an app using CocoaLumberjack targets iOS versions higher than iOS7, is it still needed to implement the custom thread safety measures in a custom formatter?

**Comment by bpoplauschi** [comment]
@philhinco according to Apple docs, you shouldn't need the safety measures. But better to test this before.
