### ISSUE TITLE
Renaming of LOG_ macros to DDLOG_

### ISSUE THREAD

**Issue by jcbertin** [CocoaLumberjack/CocoaLumberjack#839]
### New Issue Checklist

* [X] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [X] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [X] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Description and Steps

Not really an issue but I think that a robust framework needs to be explicit when naming its API. However I understand that it breaks compatibility with existing code: what do you think of this?

**Comment by bpoplauschi** [comment]
Fixed by #845
