### ISSUE TITLE
Static analyzer gives warnings of "value stored never read" despite values used in DDLogs

### ISSUE THREAD

**Issue by sorinc03** [CocoaLumberjack/CocoaLumberjack#840]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 10.2 (deployment target 9.0)
 CocoaLumberjack Version | 2.2.0, updated to 3.0.0
 Integration Method      | carthage
 Xcode Version           | 8.2.1
 Repro rate              | 100%
 Demo project link       | N/A

### Issue Description and Steps

Clang seems to show some warnings of the

`Value stored to 'variable' during its initialization is never read` despite the fact that it's used in `DDLogVerbose` calls.

Any thoughts on the best way to make those warnings go away?

**Comment by bpoplauschi** [comment]
Can you add more details about the warnings? Are they in your code or the library code?
Also, I strongly recommend you upgrade to the latest version (3.x).

**Comment by sorinc03** [comment]
@bpoplauschi there are a few situations I'm dealing with where I initialize various variables and then want to `DDLogVerbose` them. For example:

```
NSString *myString = @"Test String";

DDLogVerbose(@"The value of myString is %@", myString);
```

This would cause a clang warning saying `Value stored to myString` is never read` if the only place it's used is the DDLog statement. This wasn't an issue before Xcode 8 so I'm not sure what changed on that end.

Any thoughts on how to avoid these clang warnings?

BTW, I updated to CocoaLumberjack 3.0 and I still get these so it doesn't seem like it's 2.2 related necessarily.

**Comment by bpoplauschi** [comment]
@sorinc03 sorry I didn't respond to this, my bad, I was busy with other things and just let the issues pile up. If this issue still happens, it's probably due to `DDLogVerbose` just being resolved to nothing by the pre-compiler. You should make sure that gets executed/compiled (maybe use the Xcode preprocess assistant).
