### ISSUE TITLE
Swift 3 Line breaks

### ISSUE THREAD

**Issue by jhanzo** [CocoaLumberjack/CocoaLumberjack#841]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 9.0
 CocoaLumberjack Version | 3.0.0
 Integration Method      | cocoapods
 Xcode Version           | 8.2
 Repro rate              | 100%
 Demo project link       | N/A

### Issue Description and Steps

Since my project has been updated from swift 2.3 to swift 3.0, Xcode console log doesn't display line breaks anymore.

Test has been done with : 

```swift
DDLogDebug("Hello\nWorld")
```

which previously worked on version **2.4.0**.

Thanks in advance for any support.

**Comment by haritowa** [comment]
Any updates?

**Comment by sushichop** [comment]
@jhanzo 
Thanks for reporting.

Can you try to use the latest version(CocoaLumberjack 3.4.2 and Swift 4)?
If you want to display line break as Xcode console log,  you need to escape like `DDLogDebug("Hello\\nWorld")`.

```objective-c
DDLogDebug("Hello\\nWorld")
# Displays as following.
# Hello\nWorld

DDLogDebug("Hello\nWorld")
# Displays as following.
# Hello
# World
```

Thanks.

**Comment by sushichop** [comment]
I'm going to close this issue based on the last comments.
Please feel free to reopen it if you still encounters this problem.
