### ISSUE TITLE
Unified logging system support

### ISSUE THREAD

**Issue by gal-orlanczyk** [CocoaLumberjack/CocoaLumberjack#843]
Hi,

Is there any plan to support apple new unified logging system in case it is available?

Thanks

**Comment by werediver** [comment]
We have [some docs](https://developer.apple.com/reference/os/logging) and a [sample project](https://developer.apple.com/library/prerelease/content/samplecode/Logging/Introduction/Intro.html) now. But note that...

> Unified logging is available in iOS 10.0 and later, macOS 10.12 and later, tvOS 10.0 and later, and watchOS 3.0 and later, and supersedes ASL (Apple System Logger) and the Syslog APIs.

Are there some specific use cases where Unified Logging outperforms ASL and/or other CocoaLumberjack backends?

**Comment by gal-orlanczyk** [comment]
@werediver Not sure if it outperforms, but if we could see the logs in new console would be nice and if unified logging was used in case you will support it we can know that ASL is only backward compatibility.

**Comment by abbeycode** [comment]
I would also appreciate Unified Logging compatibility

**Comment by bpoplauschi** [comment]
I think this is resolved by #850
