### ISSUE TITLE
Issue with custom logger in swift 3

### ISSUE THREAD

**Issue by buscarini** [CocoaLumberjack/CocoaLumberjack#844]
I have a custom logger in swift. Everything was working fine, but I updated the pods and now I see this error message:

`Type of 'logFormatter' has different optionality than required by protocol 'DDLogger'`

This is how the logFormatter property is written:

` public var logFormatter: DDLogFormatter?`

This protocol is written in Objective-C, and the var is supposed to be optional according to the comments, but there is no nullability specifiers, so for some reason swift is interpreting that this shouldn't be null. Any ideas how to solve this?

**Comment by buscarini** [comment]
This doesn't happen on version 3.0, so it's related to some changes in 3.1

**Comment by bpoplauschi** [comment]
@buscarini does this issue still apply to Swift 4? I haven't seen anything similar in my Swift projects that use CocoaLumberjack. Also make sure you are using the latest version

**Comment by buscarini** [comment]
I haven't seen this in recent projects, so I think it's safe to close it
