### ISSUE TITLE
the use of DDAbstractDatabaseLogger's maxAge

### ISSUE THREAD

**Issue by Archerlly** [CocoaLumberjack/CocoaLumberjack#846]
Hi, i like the CocoaLumberJack, but i am confuse at the use of maxAge.
In the code, maxAge compare only with oldValue and zero, how can it do that provides a way to specify how old a log statement can get before it should get deleted from the database. I need you help, thanks!

**Comment by bpoplauschi** [comment]
@Archerlly do you still need this? Or did you figure it out?
