### ISSUE TITLE
Provide Package.swift?

### ISSUE THREAD

**Issue by ericcj** [CocoaLumberjack/CocoaLumberjack#847]
Should CocoaLumberJack provide a Package.swift so it can be imported by those using the swift package manager, or is there a better alternative for them to use it?

I got "swift package build" kind of working with:

import PackageDescription

let package = Package(
    name: "CocoaLumberjack",
    exclude: ["Classes/CocoaLumberjack.swift", "Documentation", "Framework", "Benchmarking", "Demos", "Classes/Extensions"]
)

but excluding the swift header from a swift package seems odd but required due to https://github.com/apple/swift-package-manager/blob/master/Sources/PackageLoading/PackageBuilder.swift#L563

**Comment by ffried** [comment]
This is tracked in #869.

**Comment by bpoplauschi** [comment]
We need somebody with some experience with SPM to do this. I played a bit with it and got to (need to exclude `DDAssert.swift`
```swift
import PackageDescription

let package = Package(
    name: "CocoaLumberjack",
    exclude: ["Classes/CocoaLumberjack.swift", "Classes/DDAssert.swift", "Documentation", "Framework", "Benchmarking", "Demos", "Classes/Extensions", "Tests"]
)
```
but when running `swift build` I get
```
warning: PackageDescription API v3 is deprecated and will be removed in the future; used by package(s): CocoaLumberjack
warning: no include directory found for target 'Classes'; libraries cannot be imported without public headers
```
so I guess SPM needs the folder structure in a certain way.
More details: http://ankit.im/swift/2016/05/21/creating-objc-cpp-packages-with-swift-package-manager/

**Comment by bpoplauschi** [comment]
I see. Maybe symlinks could work.
Also, I think we still need to build 2 modules: CocoaLumberjack (contains only the Obj-C part) and CocoaLumberjackSwift that links against the 1st one.

**Comment by ffried** [comment]
Definitively needs to modules, yea. Also I don't think it'll currently work on Linux, since AFAIK it's not possible to compile ObjC code on Linux.

**Comment by bpoplauschi** [comment]
I think Linux support is out of the question, at least for now. ObjC is not supported and even Swift is limited, Foundation is still being ported to Linux, so I don't think our code can run there at this point.
SPM support is for people using that on MacOS targeting the 4 Apple platforms, more like a parity to CocoaPods and Carthage.

**Comment by ffried** [comment]
Totally agree as long as ObjC is used.
With Swift however, I think Linux support should already be possible. At least for the core features of CocoaLumberjack. Of course some loggers would be unavailable (like ASLLogger), but that‘s nothing unexpected.

But yea, it‘s probably an easier short term goal to add SwiftPM support for what exists today (limited to macOS).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
