### ISSUE TITLE
Problem in integrating CocoaLumberjackSwift using carthage in my iOS project source code.

### ISSUE THREAD

**Issue by devIleaf** [CocoaLumberjack/CocoaLumberjack#848]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [ ] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        | e.g. 8.0 and above
 CocoaLumberjack Version | 3.1.0
 Integration Method      | carthage
 Xcode Version           | e.g. Xcode 8.2
 Repro rate              | e.g. all the time (100%) 
 Demo project link       | none

### Issue Description and Steps

I was trying to use carthage to integrate CocoaLumberJack to my iOS Source code.But it is showing error provided below, when I am doing it via Terminal by giving the command "carthage update". I think it is happening because of the code mismatches between different swift versions. The error is happening when it is building scheme for CocoaLumberjackSwift.Please help me to sort out this problem.

The problem I am facing is in building scheme for CocoaLumberjackSwift. I changed "Use Legacy Swift Language Version" from 'NO' to 'Yes' in build settings of my Project & Targets.But that didn't work either.

LBTA-12181:GGDining harikrishnan$ carthage update
*** Fetching CocoaLumberjack
*** Fetching SlideMenuControllerSwift
*** Fetching NaOH
*** Checking out CocoaLumberjack at "3.1.0"
*** Checking out NaOH at "1.5"
*** Checking out SlideMenuControllerSwift at "3.0.1"
*** xcodebuild output can be found in /var/folders/_w/wqjl00fx7mngk6lq3mv0g9yr0000gn/T/carthage-xcodebuild.wE5Isz.log
*** Building scheme "CocoaLumberjack-iOS" in Lumberjack.xcworkspace
*** Building scheme "CocoaLumberjackSwift-macOS" in Lumberjack.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/bobinlouis/Desktop/Projects/GGDining/Carthage/Checkouts/CocoaLumberjack/Framework/Lumberjack.xcworkspace -scheme CocoaLumberjackSwift-macOS -configuration Release -derivedDataPath /Users/bobinlouis/Library/Caches/org.carthage.CarthageKit/DerivedData/CocoaLumberjack/3.1.0 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/_w/wqjl00fx7mngk6lq3mv0g9yr0000gn/T/carthage-xcodebuild.wE5Isz.log

The error I am getting in the log specified above is 

=== BUILD TARGET CocoaLumberjackSwift-macOS OF PROJECT Lumberjack WITH CONFIGURATION Release ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)

Please help me to sort it out as early as possible, as I am running under a tight schedule.

**Comment by ikesyo** [comment]
Okay this is the project setting issue. ~~The value of `SWIFT_VERSION` is `3.0.1`: https://github.com/CocoaLumberjack/CocoaLumberjack/blob/40f1852a00434f717238bbaf46882fe37131db80/Lumberjack.xcodeproj/project.pbxproj#L2420. Unfortunately the value is only valid in Xcode 8.1. The correct value which is valid for all of Xcode 8.0, 8.1 and 8.2 is `3.0`.~~

@bpoplauschi @dvor @rivera-ernesto 

But if you have Xcode 8.2.1 that should not happen according to the release note: https://developer.apple.com/library/content/releasenotes/DeveloperTools/RN-Xcode/Introduction.html#//apple_ref/doc/uid/TP40001051-CH1-SW157

> Fixed an issue that could cause building a project to fail with the error message “"Use Legacy Swift Language Version" (SWIFT_VERSION) is required to be configured correctly for targets which use Swift” when using a supported version of Swift. (29667880)

**Comment by ikesyo** [comment]
Anyway the value should be changed to `3.0` which will be set if you changed the setting in Xcode 8.2.

**Comment by devIleaf** [comment]
I have already changed the setting Use Legacy Swift Language Version to "YES" already. But still it fails.

**Comment by devIleaf** [comment]
Do you think that updating my Xcode to 8.2.1 would solve the issue?

**Comment by ikesyo** [comment]
> I have already changed the setting Use Legacy Swift Language Version to "YES" already.

This is incorrect. That mean you use Swift 2.3, but the project should only build with Swift 3.0.

> Do you think that updating my Xcode to 8.2.1 would solve the issue?

Yes.

**Comment by devIleaf** [comment]
Actually How I was updating carthage file was, opening the terminal from Mac OSX, and moving to the particular source code directory where carthage file resides,and run "carthage update" command. Could you just tell me what is its connection with Xcode version actually?

**Comment by ikesyo** [comment]
Related to the original build issue

> “Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

**Comment by devIleaf** [comment]
You mean after changing the value of “Use Legacy Swift Language Version” to YES using xcode 8.2.1, we can call carthage update from the terminal, which will not make issues anymore.

**Comment by ikesyo** [comment]
@devIleaf No, that's opposite. You should not change anything in this repo but just should update Xcode to 8.2.1 instead.

**Comment by ikesyo** [comment]
https://github.com/CocoaLumberjack/CocoaLumberjack/issues/848#issuecomment-284991997

This is not for you @devlleaf, but for the project maintainers. You are misunderstanding my comments.

**Comment by sushichop** [comment]
@devIleaf 

Instruction is roughly as follows.
1) Update Xcode to 8.2.1
2) Set `Use Legacy Swift Language Version` to `NO`. (This means you use Swift 3.0.)
3) Execute `carthage update`

I hope this will help you.

**Comment by sushichop** [comment]
@bpoplauschi @rivera-ernesto

Anyway I bumped Xcode to 8.2 and set SWIFT_VERSION to 3.0.
See #853.

Cheers!

**Comment by sushichop** [comment]
I'm going to close this issue because it have already been fixed by #853 basically.
