### ISSUE TITLE
implicit declaration of function 'LOG_OBJC_MAYBE' is invalid in C99

### ISSUE THREAD

**Issue by dcwy1130** [CocoaLumberjack/CocoaLumberjack#852]
![image](https://cloud.githubusercontent.com/assets/7902192/23780126/e181575a-057f-11e7-9c98-32853dfe2209.png)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | e.g. 8.0
 CocoaLumberjack Version | e.g. 2.3.0
 Integration Method      | e.g. carthage / cocoapods / manually
 Xcode Version           | e.g. Xcode 8.3
 Repro rate              | e.g. all the time (100%) / sometimes x% / only once
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Comment by bpoplauschi** [comment]
Hope you have found the solution for this.
