### ISSUE TITLE
[Embedded Framework] DDLog does not call lt_log:logMessage

### ISSUE THREAD

**Issue by lolgear** [CocoaLumberjack/CocoaLumberjack#854]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 10.2
 CocoaLumberjack Version | 2.0.2
 Integration Method      | cocoapods
 Xcode Version           | Xcode 8.2.1
 Repro rate              | all the time (100%)

### Issue Description and Steps

Note: I faced with this issue in version 2.0.2 ( Because I use MagicalRecord, hah :( )

Steps:
1. Create project with embedded framework in Objective-C
2. Ensure that both project and framework are in Objective-C
3. Setup cocoa pods Podfile with Cocoalumberjack as a dependency.
4. Ensure that both project and framework targets use this `pod "CocoaLumbejack", "~> 2.0.2"`
5. Try to log something in embedded framework.
6. See nothing in console.

However, everything fine in application target.

Configuration:

Example .m file in embedded framework:

```objective-c
static const DDLogLevel ddLogLevel = DDLogLevelDebug;

- (void)outputSomething {
  DDLogDebug(@"output something"); // nothing in console :(
}
```

Setup in application:

```objective-c
// ApplicationSetup
- (void)setupLogging {
    [DDLog addLogger:[DDTTYLogger sharedInstance]];
}
```

Investigation:

```objective-c
// DDLog.m
- (void)queueLogMessage:(DDLogMessage *)logMessage asynchronously:(BOOL)asyncFlag {

    dispatch_semaphore_wait(_queueSemaphore, DISPATCH_TIME_FOREVER);

    // We've now sure we won't overflow the queue.
    // It is time to queue our log message.

    dispatch_block_t logBlock = ^{
        @autoreleasepool {
            // called from application fine.
            // not called from embedded framework.
            [self lt_log:logMessage];
        }
    };

    if (asyncFlag) {
        // embedded framework invocation stops here.

        dispatch_async(_loggingQueue, logBlock);
    } else {
        dispatch_sync(_loggingQueue, logBlock);
    }
}
```

Output in embedded framework:

```
// in function above: 
// breakpoint at `if (asyncFlag)`

po _loggingQueue

<OS_dispatch_queue: cocoa.lumberjack[0x174360f00] = { xrefcnt = 0x1, refcnt = 0x1, target = com.apple.root.default-qos.overcommit[0x100e7d5c0], width = 0x1, state = 0x000fffe000000000, in-flight = 0}>

po _loggingSemaphore

<OS_dispatch_semaphore: semaphore[0x17409c5c0] = { xrefcnt = 0x1, refcnt = 0x1, port = 0x0, value = 999, orig = 1000 }>
```

### P.S:
I also created private pod ( not an embedded framework ) which works fine with application setup (setupLogging function) above.

**Comment by bpoplauschi** [comment]
@lolgear any change this is still an issue? Could you check with our latest version (3.4.x)?

**Comment by lolgear** [comment]
@bpoplauschi 

I rid of MagicalRecord and integrate CocoaLumberjack as submodule.

I haven't seen this issue since, well, 2017? 😄

**Comment by bpoplauschi** [comment]
:) As expected. Closing then.
