### ISSUE TITLE
Custom LogFormatter Swift3

### ISSUE THREAD

**Issue by galblank** [CocoaLumberjack/CocoaLumberjack#855]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 10.0
 CocoaLumberjack Version | 3.1.0
 Integration Method      | cocoapods 
 Xcode Version           | Xcode 8,1
 Repro rate              | all the time (100%)

### Issue Description and Steps
Compilation Error - Does not conform to protocol DDLogFormatter
```swift
public class CCLogFormatter:NSObject,DDLogFormatter{
    var loggerCount = 0
    var threadUnsafeDateFormatter:NSDateFormatter? = nil
    
    override init() {
        super.init()
    }

    public func format(message logMessage: DDLogMessage!) -> String! {
        var logLevel = "E"
        switch logMessage.flag {
        case DDLogFlag.Error:
            logLevel = "E"
            break
        case DDLogFlag.Warning:
            logLevel = "W"
            break
            
        case DDLogFlag.Info:
            logLevel = "I"
            break
        case DDLogFlag.Debug:
            logLevel = "D"
            break
        case DDLogFlag.Verbose:
            logLevel = "V"
            break
        default:
            logLevel = "V"
            break
        }
        
        threadUnsafeDateFormatter = NSDateFormatter()
        threadUnsafeDateFormatter!.dateFormat = "yyyy/MM/dd HH:mm:ss.SSS"
        let dateAndTime =  threadUnsafeDateFormatter?.stringFromDate(logMessage.timestamp)
        let logMsg = logMessage.message
        
        return "\(logLevel), \(dateAndTime), \(logMsg)"
    }

}
```

**Comment by bpoplauschi** [comment]
We've already moved to Swift 4, so this issue is out of date. For cases like this, the compiler will probably say why it doesn't conform (maybe a change in naming ...).
