### ISSUE TITLE
What is the difference between `context` and `tag`

### ISSUE THREAD

**Issue by skerkewitz** [CocoaLumberjack/CocoaLumberjack#861]
Hello,

I recently notice that additionally to the ability to `tag` a log message there is also a `context` parameter. It seems that `context` is used to determine from which subsystem a log message is coming. If thats the case; what is the use-case for `tag`?

Or is `tag` just a more flexibel replacement of `context`?

**Comment by sushichop** [comment]
To be precise, I don't know the difference between `context` and `tag`.
But I feel `tag` is more flexible than `context` because `tag` is treated as `Any?` and `context` is as `Int` in Swift.

And I actually use `tag` entirely for my custom logging.

**Comment by bpoplauschi** [comment]
I also don't know exactly, but `context` was definitely created so you can isolate a specific area of your app. For instance the network component can do all the logging using the same context so it can be turned off easily.
A tag is something that you use to mark some logs, not necessarily from within the same component. Also, the type is more flexible for tags. It's like a metadata.
