### ISSUE TITLE
Use of undeclared type 'DDLog' in CocoaLumberjack Swift 3.1.0

### ISSUE THREAD

**Issue by Morkos** [CocoaLumberjack/CocoaLumberjack#865]
## New issue Request

* [x] I have read the https://github.com/CocoaLumberjack/CocoaLumberjack#documentation 
* [x] I have searched for a similar issue here (https://github.com/CocoaLumberjack/CocoaLumberjack/issues/405) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | Simulator 
 CocoaLumberjack Version | 3.0.0 or 3.1.0 (same issue)
 Integration Method      | Cocoapods
 Xcode Version           | Xcode 8.2
 Repro rate              | 100%
 Demo project link       | http://pasteboard.co/8Dno9COwI.png
<img width="1406" alt="screen shot 2017-04-25 at 11 17 43 am" src="https://cloud.githubusercontent.com/assets/1535201/25401050/6b6f7512-29a9-11e7-8447-f090e27176df.png">

### Issue Description and Steps

Hi there,

I recently upgraded to CocoaLumberjack/Swift for my pod as I'm currently doing a Swift 2 to Swift 3 migration because I had to upgrade to XCode 7.3 to 8.2 to test on iOS 10 devices.

As I was finishing up the Swift migration, I came across "Use of undeclared type 'DDLog'" and not sure why this is occurring.

My Pods/ has the proper files. My ObjCBridge.h contains the CocoaLumberjack.h and that file imports DDLog.h and the other proper files.

Build phases seems to include all the proper files as well so not sure what's going on.

Please advise

Thank you,

**Comment by Morkos** [comment]
Rawwwr. Disregard. Solution is this:

   pod 'CocoaLumberjack',
        :git => 'https://github.com/CocoaLumberjack/CocoaLumberjack.git',
        :branch => 'swift_3'

**Comment by adib** [comment]
@Morkos Your solution didn't seem to solve the issue. I encounter the same issue *but* with tvOS 10.2

**Comment by Morkos** [comment]
@adib , you're correct. I had to import the module "import CocoaLumberjack" in CocoaLumberjack.swift. see if that works

**Comment by adib** [comment]
That and adding `CocoaLumberjack.swift` manually to my project's common module seem to made the project compile.

**Comment by njoseph79** [comment]
In my case the error was solved by changing
#import <CocoaLumberjack/CocoaLumberjack.h>
to
@import CocoaLumberjack;
in the bridging header

**Comment by fukemy** [comment]
@njoseph79  still not working to me
