### ISSUE TITLE
Swift Package Manager Package.swift support

### ISSUE THREAD

**Issue by ekimia** [CocoaLumberjack/CocoaLumberjack#869]
Would love this, someone has found a workaround to make a Package.swift but it would be best to have an official version in the repo.

### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

**Comment by ffried** [comment]
#847 has some additional info, that may be relevant for an initial support for Swift PM.

**Comment by lolgear** [comment]
Necromancer!

I have found one interesting point about swift package manager. It doesn't rely on information from Xcode project, so, it don't know about targets and search paths.

What does it for this feature?

Neither `#import "File.h"` nor `#import <Framework/File.h>` are valid.
Instead, we should use #import "Relative/Path/To/Source/File.h"

```
-- Foo.h
-- Folder
---- |
---- Bar.h
```

In `Bar.h` you should write relative path to `Foo.h` file.

```objective-c
#import "../Foo.h"
```

**Comment by ffried** [comment]
It depends. SPM sets up search paths, but restricted to targets. Targets are based on folders.
In a traditional SPM package the structure is as follows:
```
- Package.swift
- Sources
   - Target1
       - Folder1
            - Source1.swift
       - Folder2
            - Source2.swift
   - Target2
       - Folder1
            - Source1.h
            - Source1.m
       - Folder2
            - Source2.h
            - Source2.m
- Tests
   - Target1Tests
       - Folder1
            - Test1.swift
       - Folder2
            - Test2.swift
   - Target2Tests
       - Folder1
            - Test1.h
            - Test1.m
       - Folder2
            - Test2.h
            - Test2.m
```

If we were to introduce SPM support, we'd have to slightly restructure our sources and likely also provide custom paths to SPM. The Header-Lookup _should_ work as expected afterwards. If not, SPM will search them in an include folder. So, in the worst case we have to put all our headers into a single folder.

**Comment by lolgear** [comment]
@ffried 
Your example contains an inversion of folders ( CocoaLumberjack/Classes vs Sources/Target1 ).

**Comment by lolgear** [comment]
@ffried 
By the way, how should it handle umbrella header?

**Comment by ffried** [comment]
@lolgear 

> Your example contains an inversion of folders ( CocoaLumberjack/Classes vs Sources/Target1 ).

My example is the structure of what an SPM package looks like by default. It has nothing (yet) to do with our current structure. SPM is quite configurable, so for some paths we might be able to tell SPM where the sources reside.

> By the way, how should it handle umbrella header?

It also has to be named and placed in a specific way. But for some (even most) cases it can even be left away and will be generated by SPM (which in this case is even a little more advanced than Xcode)

**Comment by lolgear** [comment]
@ffried 
Heh, do you have an example of ObjC project with custom setup?
I would like to add support to another GitHub project, but I stuck at figuring out how to configure all paths.
I even asked at Swift Forums, but given example project is too plain :/

**Comment by ffried** [comment]
@lolgear Not ObjC, but C/C++: https://github.com/marmelroy/Zip/pull/155/files

**Comment by ffried** [comment]
But ObjC should work similarly. I assume that the headers could stay with the implementation files. But like I mentioned, it could also be that they'd need to go into the include folder.

**Comment by lolgear** [comment]
@ffried 
I've tried.
No, they can't work remotely, they should relocate :(

I suggest to add `Classes/Include` folder to store them.

**Comment by SlashDevSlashGnoll** [comment]
This has become a much more desirable feature because XCode11 has first-class support for SPM for all project types.  This is going to make carthage and pods much less the norm so adding proper support for SPM would be fantastic.

**Comment by ffried** [comment]
@SlashDevSlashGnoll It's already underway. See #1083 😉

**Comment by SlashDevSlashGnoll** [comment]
Oohhhh that's awesome, thanks!

**Comment by ffried** [comment]
Since #1083 has landed, I'm closing this issue.
