### ISSUE TITLE
Add documentation - Fine Grained Log Levels in Swift

### ISSUE THREAD

**Issue by omerlh** [CocoaLumberjack/CocoaLumberjack#876]
I found the [documentation](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/FineGrainedLogging.md) here, but it does not cover Swift. After trying a few things, I got it to work, so I can create a PR with the relevant documentation.  I add a simple documentation in my original [question](https://stackoverflow.com/a/44692158/4792970) in SO.

**Comment by bpoplauschi** [comment]
@omerlh feel free to create that PR, if it's still at hand. just let us know.

**Comment by bpoplauschi** [comment]
@omerlh I added the entry to the docs: https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/FineGrainedLogging.md#swift-equivalent

Many thanks for your contribution. I will close the issue now.

**Comment by omerlh** [comment]
Thanks!

**Comment by bpoplauschi** [comment]
Sure, no probl. Glad it was just copy paste from your SO post :)
