### ISSUE TITLE
Xcode 9 beta 3: strange compilation error in DDOSLogger.m

### ISSUE THREAD

**Issue by garnett** [CocoaLumberjack/CocoaLumberjack#882]
Note: I'm building the library as a dependency of my project, I haven't tried to build it from the source directly.

Xcode 9 beta3

<img width="1377" alt="screen shot 2017-07-10 at 19 40 11" src="https://user-images.githubusercontent.com/829783/28034120-3bf83284-65a8-11e7-8631-564bd855e79b.png">

**Comment by patricks** [comment]
I got the same error with Xcode 9 Beta 3

**Comment by paradoxally** [comment]
[Looks like it has been fixed](https://github.com/CocoaLumberjack/CocoaLumberjack/issues/883), but you'll need to apply the changes manually for now.

**Comment by garnett** [comment]
Thanks for the link @paradoxally!

I wonder why it was closed instead of be landed somewhere in upstream though..

**Comment by djbe** [comment]
I honestly didn't notice it wasn't on the main repo, my bad.

**Comment by DinosaurDad** [comment]
It has now been merged.

**Comment by HofiOne** [comment]
could you please make this change available in cocoapods, TIA!

**Comment by DinosaurDad** [comment]
@HofiOne - it looks like the next release isn't quite ready. You can use the latest code from `master` by using this line in your `Podfile`:

```
pod 'CocoaLumberjack', :git => 'https://github.com/CocoaLumberjack/CocoaLumberjack.git', :branch => 'master'
```

**Comment by HofiOne** [comment]
thanks, than i'll do that till it's not ready

**Comment by jcavar** [comment]
What is not ready for next release? If something is broken, then pulling from master is not really great option.

**Comment by bpoplauschi** [comment]
We will make a release very soon

**Comment by jcavar** [comment]
I don't want to bother, but quite some time passed since latest update. I would like to understand what is the problem with release? Maybe someone can help with that.

**Comment by zettlunic** [comment]
Still occurring in Xcode 9.0 beta 5 (9M202q)

**Comment by Kastet** [comment]
Hopefully, 3.2.1 is coming soon...

**Comment by LiorApp** [comment]
Waiting for 3.2.1 to get released aswell, is there any estimation when?

**Comment by bpoplauschi** [comment]
Ok, I will make a release tomorrow.

**Comment by LiorApp** [comment]
🤔

**Comment by bpoplauschi** [comment]
Version 3.2.1 is now available. Sorry for the delay, but hope this makes things easier for you.

**Comment by LiorApp** [comment]
Thanks! 😍
