### ISSUE TITLE
OSSPinLock is not safe again

### ISSUE THREAD

**Issue by helloyokoy** [CocoaLumberjack/CocoaLumberjack#886]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name         | ios
 Platform Version      | 10.0
 CocoaLumberjack Version | 3.2.0
 Integration Method     | cocoapods 
 Xcode Version          | Xcode 8
 

OSSpinlock is not safe again ,please use pthread_mutex_t instead!!!

http://blog.ibireme.com/2016/01/16/spinlock_is_unsafe_in_ios/

**Comment by rbrightwell** [comment]
Apple has deprecated OSSpinlock. They say to replace it with os_unfair_lock.  This is stated in the compiler warnings and also this slide deck, slide #24.
 
http://devstreaming.apple.com/videos/wwdc/2016/412jzguxz4h8hykgjlm/412/412_thread_sanitizer_and_static_analysis.pdf

**Comment by chrisamanse** [comment]
Replaced with pthread_mutex_t in #889. Okay to close?

**Comment by bpoplauschi** [comment]
Fixed by #889
