### ISSUE TITLE
New feature: A KVO notification when a new file has been rolled.

### ISSUE THREAD

**Issue by mumensh** [CocoaLumberjack/CocoaLumberjack#894]
### New Issue Checklist

* [X] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [X] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [X] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Description and Steps

After Using this awesome library, I've got in a situation that my app needs to know if a new log file was generated due to file size limit, so, I think it will be nice to have a KVO to let the application know that the library has rolled a new file due to a file size limit, manually, Age or the current file has been moved/removed.

**Comment by bpoplauschi** [comment]
@mumensh can you maybe achieve this by subclassing `DDFileLogger`? Any other ideas?

**Comment by bpoplauschi** [comment]
Closing. Feel free to continue the conversation if still applicable
