### ISSUE TITLE
Ambiguous macro definition in mixed Obj-C and Swift project

### ISSUE THREAD

**Issue by tylerjames** [CocoaLumberjack/CocoaLumberjack#900]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

I'm using the CocoaLumberjack-Swift pod in a mixed Objective-C and Swift project. I had previously been using the Objective-C version and have the macros defined in my prefix.pch

Now, everything works technically, but I get all kinds of errors everywhere in my code that the DDLog macro being used is ambiguous and I'm not sure how to get rid of these errors.

<img width="234" alt="screenshot 2017-11-09 11 13 51" src="https://user-images.githubusercontent.com/1138573/32615977-2c0f9b68-c53f-11e7-9f33-16cbc9cb487f.png">

The errors seem to only show up in classes where I am also importing my bridging header to access some of my Swift code: `#import "MyApp-Swift.h"` So obviously the macros are also defined in the bridging header.

**Is there any way around this? What is the proper way of using Cocoa Lumberjack in a mixed environment?** The code still builds and runs fine but it's annoying seeing all these "errors" everywhere.

Thanks

My prefix file includes all this:
```
#define LOG_ASYNC_ENABLED YES
#define LOG_LEVEL_DEF ddLogLevel
#import <CocoaLumberjack/CocoaLumberjack.h>
static const DDLogLevel ddLogLevel = DDLogLevelAll;

#ifdef DEBUG
#define DLogError(fmt, ...) DDLogError((@"%s [Line %d] " fmt), __PRETTY_FUNCTION__, __LINE__, ##__VA_ARGS__)
#define DLogWarn(fmt, ...) DDLogWarn((@"%s [Line %d] " fmt), __PRETTY_FUNCTION__, __LINE__, ##__VA_ARGS__)
#define DLogInfo(fmt, ...) DDLogInfo((@"%s [Line %d] " fmt), __PRETTY_FUNCTION__, __LINE__, ##__VA_ARGS__)
#define DLogDebug(fmt, ...) DDLogDebug((@"%s [Line %d] " fmt), __PRETTY_FUNCTION__, __LINE__, ##__VA_ARGS__)
#define DLogVerbose(fmt, ...) DDLogVerbose((@"%s [Line %d] " fmt), __PRETTY_FUNCTION__, __LINE__, ##__VA_ARGS__)
#else
#define DLogError(fmt, ...)
#define DLogWarn(fmt, ...)
#define DLogInfo(fmt, ...)
#define DLogDebug(fmt, ...)
#define DLogVerbose(fmt, ...)
#endif
```

**Comment by alexpopov** [comment]
Have you (or anyone else) found a solution to this issue? My project won't build due to the errors.

**Comment by sushichop** [comment]
@alexpopov @tylerjames 
Thanks for reporting.

I have ever encountered the same problem before with old version's CocoaLumberjack,
but I haven't recent version's.

Could you try the latest `CocoaLumberjack`(3.4.2) and Swift 4.0?
If you still encounter this problem let me know.

Thanks.

**Comment by bpoplauschi** [comment]
I remember using the 3.x version in a mixed Swift-ObjC project without issues.
Can you setup a small demo project with this?

**Comment by sushichop** [comment]
Just an additional Info.
I confirmed CocoaLumberjack CocoaLumberjack(3.4.2) and Swift 4.0 worked fine at least with my project.
And this issue should be fixed by #784 .

**Comment by bpoplauschi** [comment]
Thanks @sushichop. Should we close the issue then?

**Comment by sushichop** [comment]
@bpoplauschi 
Yes!

**Comment by tylerjames** [comment]
I still have the issue using 3.4.2. I used to use the Objective-C version then migrated to the Swift version. I suspect my setup is somehow incorrect as a result. Maybe one of the other libraries I'm using is also using CocoaLumberjack? I'm not sure.

**Comment by tylerjames** [comment]
Sorry everyone. Was away from iOS for a bit. 

My project is old, formerly only Obj-C, now a mixed Obj-C and Swift. I previously used the Objective-C Lumberjack library, now I use the Swift one. At some point we had to define all the macros in a our prefix.pch file. Now it seems to be recommended that we not even use a prefix file *at all*. 

I'm in the process of removing my prefix file to see if that fixes things.

**Comment by bpoplauschi** [comment]
@tylerjames don't worry, we can assist. Just let us know how it goes.

**Comment by tylerjames** [comment]
Okay, I no longer have the macros defined in the pch file (because I no longer have a pch file)

Now I get a bunch of `Use of undeclared identifier 'ddLogLevel'` errors anywhere that I'm using the macros.

**Comment by bpoplauschi** [comment]
Based on https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/GettingStarted.md#access-and-configure-the-framework
you need to define `ddLogLevel` before all imports of Lumberjack. That is why the precompiled header was useful.

What I usually do when using Lumberjack in a project is:
- A) wrap it up in a class of my own so I only need to define that `ddLogLevel` once
- OR
- B) define it every time, if that is not too time consuming

**Comment by tylerjames** [comment]
So you basically create a file that does the `@import CocoaLumberjack;` as well as the `#define LOG_LEVEL_DEF ddLogLevel` and then you just import that file into the places where you want to use logging?

**Comment by bpoplauschi** [comment]
@tylerjames yes, in general. It depends on the type of project:
- for a Swift only project, I would also create a `Logger` class that hides the `Lumberjack` implementation, so that my internal logging code is not tightly coupled to a particular implementation
- for ObjC, where it's a lot easier/nicer to use macros, I can do the simple one like you said, or, for more advanced use cases, I can redefine the log levels like: https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/CustomLogLevels.md

**Comment by bpoplauschi** [comment]
Closing, per lack of response.
