### ISSUE TITLE
Linker error using DDOSLogger

### ISSUE THREAD

**Issue by gredman** [CocoaLumberjack/CocoaLumberjack#901]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 11.1
 CocoaLumberjack Version | 3.3.0
 Integration Method      | carthage
 Xcode Version           | Xcode 9.1
 Repro rate              | 100%
 Demo project link       | -

### Issue Description and Steps

Hi there,

I'm getting a linker error when I try to add DDOSLogger to my projects using Carthage.

My code is:

    if #available(iOS 10.0, *) {
        DDLog.add(DDOSLogger.sharedInstance)
    } else {
        DDLog.add(DDTTYLogger.sharedInstance)
        DDLog.add(DDASLLogger.sharedInstance)
    }

Error is:

        Undefined symbols for architecture x86_64:
          "_OBJC_CLASS_$_DDOSLogger", referenced from:
              objc-class-ref in AppDelegate.o
        ld: symbol(s) not found for architecture x86_64
        clang: error: linker command failed with exit code 1 (use -v to see invocation)

Thanks!

**Comment by sushichop** [comment]
@gredman 

Thanks for your opening issue. I encountered the same error even in the latest version(`master branch`).
And I fixed this issue by #903  😄

Or if you are in a hurry, you can also using CocoaPods. This error does not occur when using it.

Cheers!

**Comment by gredman** [comment]
Thank you @sushichop!
