### ISSUE TITLE
Thoughts about weak linking and project dependencies

### ISSUE THREAD

**Issue by lolgear** [CocoaLumberjack/CocoaLumberjack#902]
Well, it is common to install CocoaLumberjack via CocoaPods or Carthage ( or Swift Package Manager ? ).
It is nice that community has fast reliable library that provides logging.
However, I would like to have an approach, which eliminates strong coupling to this library.

I start to inspect my current project and tell myself, "wait! it is not good!".
I have nearly 1000 occurrences of DDLog. ( Both DDLog logging and DDLogLevel definition ).
Even if I change search to DDLogLevel, the result drops down to 300 entries.

Project has several modules and, of course, this number is good ( ~ 700 log events ).

However, I would like to have an approach which could be described on wiki page or in readme.

It is simple to redefine ```MY_PROJECT_LOG_VERBOSE```. But it is not simple to decoupling usage of DDLogLevel variable. 
In most cases logging is scoped to module ( or framework ). Yes, we have situations in which logging should be turned off by configuration. 
And in these assumptions I could tell that the static nature of this variable is needless.

**Comment by bpoplauschi** [comment]
@lolgear sorry it took so long to respond to this. Any ideas how to implement this? Are you interested in trying it out?

**Comment by lolgear** [comment]
@bpoplauschi yes, I am interested in it.

I thought about some kind of compiler flags, for example. However, it will solve only "static variable".

However, I would like to discuss also some "architecture" decisions and, moreover, "build configurations" decisions.

For example, I have found that Filtering uses NSArray as storage for filter flags. But wait, simple Set could fit this position well.
