### ISSUE TITLE
High CPU Usage when uint_64 overflow occurs

### ISSUE THREAD

**Issue by akutta** [CocoaLumberjack/CocoaLumberjack#908]
Should be a low priority, but simple fix.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | all
 CocoaLumberjack Version | latest
 Integration Method      | cocoapods
 Xcode Version           | latest
 Repro rate              | all the time (100%)

### Issue Description and Steps

Set `DDFileLogger.rollingFrequency` to > `uint_64` max value.  ( Test value: 1000 years )

Not exactly a normal use case.  But in the off chance that someone doesn't realize the can disable by setting to <= 0.0 to disable the logger, the overflow that occurs causes `scheduleTimerToRollLogFileDueToAge` to trigger every nanosecond increasing CPU utilization to a full core on an iPhone and simulator.  

A guard should probably be put around this to us from ourselves.  
https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Classes/DDFileLogger.m#L763

**Comment by bpoplauschi** [comment]
@akutta thanks for your interest in our project.
Are you interested in creating a PR with this fix? I can assist you

**Comment by bpoplauschi** [comment]
Won't fix for now. Will re-evaluate if it becomes a problem.
