### ISSUE TITLE
can DDFileLogger delete prefix log when reach max size?

### ISSUE THREAD

**Issue by MountainHill** [CocoaLumberjack/CocoaLumberjack#917]
Does CocoaLumberjack support deleting ahead log when the file reaches setted maximumFileSize?
Now DDFileLogger move log data to another file and delete all log when reaching maximumFileSize.
I wonde how I can fulfill this function, can you give me some tips?

**Comment by bpoplauschi** [comment]
I assume you found your answer @MountainHill

**Comment by MountainHill** [comment]
@bpoplauschi yes, thank you very much.
