### ISSUE TITLE
Linking issue in Objective-C++ with THIS_FILE macro

### ISSUE THREAD

**Issue by simonwagner** [CocoaLumberjack/CocoaLumberjack#920]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | osx
 Platform Version        | 10.12
 CocoaLumberjack Version | 2.3.0
 Integration Method      | manually
 Xcode Version           | Xcode 8.3
 Repro rate              | all the time (100%)
 Demo project link       | 

### Issue Description and Steps

When using the `THIS_FILE` macro in an Objective-C++ file (.mm), I get the following linker error:

```
Undefined symbols for architecture x86_64:
  "DDExtractFileNameWithoutExtension(char const*, signed char)", referenced from:
      -[SomeClass someMethod] in SomeClass.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This is caused by not declaring the `DDExtractFileNameWithoutExtension` method as `extern "C"` which we unfortunately have to do if we want to call C functions from C++ (or in this case, Objective-C++).

The solution is to add the following:

```
#ifdef __cplusplus
    #define DDLOG_EXTERN_C extern "C"
#else
    #define DDLOG_EXTERN_C
#endif

DDLOG_EXTERN_C NSString * DDExtractFileNameWithoutExtension(const char *filePath, BOOL copy);
```

**Comment by sushichop** [comment]
@simonwagner 

Thanks for your creating issue with great suggestion.
I fixed this issue using `FOUNDATION_EXTERN` macro and sent pull request(#922).

Cheers🥂

**Comment by sushichop** [comment]
[CocoaLumberjack 3.4.2](https://github.com/CocoaLumberjack/CocoaLumberjack/releases/tag/3.4.2) has been released! 
Fix for this issue is included in it😁
