### ISSUE TITLE
Log files from previous day are missing

### ISSUE THREAD

**Issue by vandzi** [CocoaLumberjack/CocoaLumberjack#935]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 11.3.1
 CocoaLumberjack Version | 3.4.2
 Integration Method      |  cocoapods
 Xcode Version           | Xcode 9.3
 Repro rate              |  all the time (100%)

### Issue Description and Steps

I have this fileLogger config

```swift
fileLogger.rollingFrequency = -1  //don't rollout 
self.fileLogger.maximumFileSize = 1024 * 1024 * 10 //10mb file size
self.fileLogger.logFileManager.maximumNumberOfLogFiles = 5
```

Logging seems to work fine but when I open app next day I see only 1 log file with size smaller then `maximumFileSize` which contains data only since app started that day. There are no archived log files. Any idea what can be problem? Did I miss something in config? Thanks

**Comment by bpoplauschi** [comment]
@vandzi thanks for your interest in CocoaLumberjack. Can you debug your case? Check `maybeRollLogFileDueToSize` and `maybeRollLogFileDueToAge`, see if they are called.

**Comment by bpoplauschi** [comment]
Closing - lack of response.
