### ISSUE TITLE
rollLogFile sometimes crashes when setting _currentLogFileVnode to NULL

### ISSUE THREAD

**Issue by marcusbuffett** [CocoaLumberjack/CocoaLumberjack#945]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 12.0
 CocoaLumberjack Version | 4.3.2
 Integration Method      | carthage
 Xcode Version           | Reproduced on 10 and 9
 Repro rate              | takes a while, but 100%
 Demo project link       | https://github.com/marcusbuffett/cocoalumberjack-crash

### Issue Description and Steps

I'm encountering an issue with the `DDFileLogger` that results in a crash when rolling the log files. The demo project link above reproduces the issue w/ timers to simulate rolling the log file, logging to it, and reading from it (the three things that I'm doing in my project). I realize the frequencies are crazy, I just put them that low to make the problem more reproducible, the rolling frequency in my project is more like a minute, and the crash still occurs often for users.

To reproduce the issue, just check out that demo project, run the `iOSSwiftTest` target, and wait ~5 minutes, it should happen.

This is the crash I get:
<img width="1643" alt="screen shot 2018-08-31 at 6 53 22 pm" src="https://user-images.githubusercontent.com/1834328/44941298-2a63b800-ad4f-11e8-84a2-10ed292ae2de.png">

**Comment by bpoplauschi** [comment]
@marcusbuffett thanks for your interest in our project and for putting together a demo for reproducing the issue. We will investigate this problem based on your findinds.

**Comment by marcusbuffett** [comment]
FYI we were able to solve this issue by not writing to the files until the completion block for `rollLogFiles` is called.

**Comment by sushichop** [comment]
The pull request is #946 . Can you review this?

**Comment by bpoplauschi** [comment]
Great job @sushichop
