### ISSUE TITLE
Migrate Pods to Carthage function missing

### ISSUE THREAD

**Issue by Max0u** [CocoaLumberjack/CocoaLumberjack#948]
### New Issue Checklist

* [X] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 9.0
 CocoaLumberjack Version | 3.4
 Integration Method      | Carthage
 Xcode Version           | Xcode 9.4.1

### Issue Description and Steps

I migrate from Pods to Carthage but since I added the CocoaLumberjack.framework and CocoaLumberjackSwift.framework I got an error here :

```swift
public func verbose(_ string: String, function: StaticString = #function, file: StaticString = #file, line: UInt = #line) {
    #if DEBUG
        _DDLogMessage(string, level: defaultDebugLevel, flag: .verbose, context: 0, file: file, function: function, line: line, tag: nil, asynchronous: true, ddlog: DDLog.sharedInstance)
    #endif
}
```
Both _DDLogMessage and defaultDebugLevel are not recognized.

To add the frameworks I added to the _Linked Frameworks and Libraries_ of the project.
Then I added this script in _Build Phase_ :  
```bash
/usr/local/bin/carthage copy-frameworks
```
And this to the _Input Files_ :

```
$(SRCROOT)/Carthage/Build/iOS/CocoaLumberjack.framework
$(SRCROOT)/Carthage/Build/iOS/CocoaLumberjackSwift.framework
```

Then add frameworks in _Copy Files_.

What did I do wrong ?

Thanks guys !

**Comment by sushichop** [comment]
@Max0u 
Thanks for reporting. 
Try to confirm followings.
- Set SWIT_VERSION to 4.0 before integrating app witch Carthage.
- Use latest CocoaLumberjack (3.4.2).
- Add not `import CocoaLumberjack` but `import CocoaLumberjackSwift`.

Actually I had no error with `CocoaLumberjack 3.4.2` and Xcode 9.4.1.

Thanks.

**Comment by bpoplauschi** [comment]
Closing per latest comment. Feel free to reopen if you still have an issue.
