### ISSUE TITLE
Cannot build LumberJack in a Framework from Carthage build

### ISSUE THREAD

**Issue by SjoerdPerfors** [CocoaLumberjack/CocoaLumberjack#951]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 12
 CocoaLumberjack Version | 3.4.2
 Integration Method      | carthage
 Xcode Version           | Xcode 10.0
 Repro rate              | 100%
 Demo project link       | [cannot build from carthage build.zip](https://github.com/CocoaLumberjack/CocoaLumberjack/files/2441121/cannot.build.from.carthage.build.zip)

### Issue Description and Steps

I have created an empty framework with Lumberjack included. From command line I run:

    carthage build --no-skip-current --platform iOS

And although I specify the platform I still get this error:

    error: Multiple commands produce

```
error: Multiple commands produce '/Users/sjoerd/Library/Developer/Xcode/DerivedData/FMSdk-fngcjtzwjzacjmeynucgsyrvgbux/Build/Intermediates.noindex/ArchiveIntermediates/FMSdk/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/CocoaLumberjack.framework':
1) Target 'CocoaLumberjack-macOS' has create directory command with output '/Users/sjoerd/Library/Developer/Xcode/DerivedData/FMSdk-fngcjtzwjzacjmeynucgsyrvgbux/Build/Intermediates.noindex/ArchiveIntermediates/FMSdk/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/CocoaLumberjack.framework'
2) Target 'CocoaLumberjack-tvOS' has create directory command with output '/Users/sjoerd/Library/Developer/Xcode/DerivedData/FMSdk-fngcjtzwjzacjmeynucgsyrvgbux/Build/Intermediates.noindex/ArchiveIntermediates/FMSdk/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/CocoaLumberjack.framework'
```

### Workaround:

1. In Xcode, go to File->Project/Workspace settings.
1. Change the build system to Legacy Build system.

**Comment by bpoplauschi** [comment]
@SjoerdPerfors thanks for reporting. Need to look into this issue

**Comment by sushichop** [comment]
It seems to be OK to add only CocoaLumberjack.framework(from 
'CocoaLumberjack-iOS' target in 'Lumberjack' project) to `Linked Frameworks and Libraries` in your xcworkspace(FMSdk.xcworkspace). 
You don't need to add CocoaLumberjackSwift.framework (though I don't know why).

Then the following command has passed.

```bash
$ carthage build --no-skip-current --platform iOS
*** xcodebuild output can be found in /var/folders/_4/fw8wl0js5bl724zfmf95h8c40000gn/T/carthage-xcodebuild.KpWb3w.log
*** Building scheme "CocoaLumberjack-iOS" in Lumberjack.xcworkspace
*** Building scheme "CocoaLumberjackSwift-iOS" in Lumberjack.xcworkspace
*** Building scheme "FMSdk" in FMSdk.xcworkspace
```

Good luck.

**Comment by SjoerdPerfors** [comment]
Thanks ! I will try it out.

**Comment by bpoplauschi** [comment]
@SjoerdPerfors @sushichop 

#959 was merged into master - meaning `CocoaLumberjack-ios` + `CocoaLumberjack-tvos` + ... = `CocoaLumberjack`. Same for `CocoaLumberjackSwift`.

Based on that, I tried re-running your scenario:

Cartfile: `github "CocoaLumberjack/CocoaLumberjack" "master"`
Command: `$ carthage build --no-skip-current --platform iOS` works fine - will just create `Build/iOS/CocoaLumberjack.framework` and `Build/iOS/CocoaLumberjackSwift.framework`

I think we can now close this issue.
