### ISSUE TITLE
Add Danger support for PR checks

### ISSUE THREAD

**Issue by bpoplauschi** [CocoaLumberjack/CocoaLumberjack#956]
Per #941 and #954, need to add [Danger](https://github.com/danger/danger) support for auto-linting the PRs.
Take a look at https://danger.systems/ruby/ - Show me some dangerfiles (no link :) )

ToDos:
- [ ] after adding xcconfig support, warn when someone tries to add settings to xcodeproj instead of xcconfig (basically shadowing the xcconfig).

Ideas aka to be discussed:
- [ ] check on spaces in file names
- [ ] check on files not added to all the CocoaLumberjack targets
- [ ] check if PR is too big (more than x lines)
```ruby
warn("Big PR, try to keep changes smaller if you can") if git.lines_of_code > 500
```
- [ ] Changelog entries are required for changes to library files.
- [ ] check when any of the package manifest(s) updated but not others (for example podspec changed)
- [ ] run Swiftlint
...

**Comment by lolgear** [comment]
@bpoplauschi check prose in PRs/commits/files.

**Comment by bpoplauschi** [comment]
#962 resolves most of the requirements here.

@lolgear I wasn't able to properly work with prose. Feel free to create a PR with this is you have the time and interest :)
