### ISSUE TITLE
Demos and tests are abusing Pods relentlessly.

### ISSUE THREAD

**Issue by lolgear** [CocoaLumberjack/CocoaLumberjack#963]
Well...

I have checked `Demos.xcworkspace` located in Demos directory.

It has nearly 40 projects ( 20 apps + 20 `Pods.xcodeproj` )

I suppose that all these Pods projects could be removed and be simply replaced by one dependency - `Lumberjack.xcodeproj`.

Moreover, Tests directory contains `CocoaLumberjack Tests.xcodeproj` which also abuses CocoaPods dependencies manager which is *especially* for tests is super-extremely-bad in case of internal parts access. ( if needed )

I suppose that all `- pod install` in travis could be removed easily after cleaning up `Lumberjack.xcodeproj` from `App targets`.

#961

**Comment by rivera-ernesto** [comment]
Feel free to do all the changes you think are necessary and PR them.

**Comment by lolgear** [comment]
#969 
#970

**Comment by bpoplauschi** [comment]
Great work @lolgear - once #970 is merged, we can close this one.

**Comment by lolgear** [comment]
@bpoplauschi 
Yes!
#970 is waiting for review.

**Comment by bpoplauschi** [comment]
Closing.- #970 was merged
