### ISSUE TITLE
Improve / unify copyright notes in source files

### ISSUE THREAD

**Issue by ffried** [CocoaLumberjack/CocoaLumberjack#964]
Currently, the copyright notes in source files aren't really unified. Some have the BSD clause, some have the Xcode default, and I'm sure I haven't checked all files.
We should unify this so that all source files show the same copyright notice. Since Xcode 9, we can even change the default for new files.

@CocoaLumberjack/collaborators: Any suggestions on what we should use? I think the license should definitively be there.

**Comment by ffried** [comment]
I‘ll see if I can open a PR for this tomorrow.

For the example files, I‘d remove all „created by“ lines and use CocoaLumberjack as Organisation name.
The created by line does not add much info and the Organisation is nice to identify them as demos of CocoaLumberjack in case they’re copied.

**Comment by bpoplauschi** [comment]
Sounds good

**Comment by bpoplauschi** [comment]
@ffried I see the branch [copyright](https://github.com/CocoaLumberjack/CocoaLumberjack/tree/copyright) :) looks good. Why no PR yet?

**Comment by ffried** [comment]
Demos... Lots of them 😆

**Comment by ffried** [comment]
Closing this since there is now #968...
