### ISSUE TITLE
How to get rid of this public log?

### ISSUE THREAD

**Issue by ripperhe** [CocoaLumberjack/CocoaLumberjack#989]
![image](https://user-images.githubusercontent.com/13943595/48754893-4f245780-ecce-11e8-9fde-58df319f6999.png)

How to get rid of this public log?

![image](https://user-images.githubusercontent.com/13943595/48754935-82ff7d00-ecce-11e8-8bc5-904132657803.png)

I only need the string returned by this method.

**Comment by ffried** [comment]
Unfortunately you can't. This is added by os_log (used by `OSLogger`). If you have a file logger, however, only the string returned by your log formatter will be logged.
