### ISSUE TITLE
scheduleTimerToRollLogFileDueToAge causing high CPU / Energy Consumption

### ISSUE THREAD

**Issue by lewis-smith** [CocoaLumberjack/CocoaLumberjack#990]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. watchos
 Platform Version        | e.g. 5.0
 CocoaLumberjack Version | e.g. 3.4.2
 Integration Method      | e.g. cocoapods
 Xcode Version           | e.g. Xcode 10.0
 Repro rate              | not sure
 Demo project link       | n/a

### Issue Description and Steps

This is half an issue half a question.

![screenshot 2018-11-20 at 11 34 17](https://user-images.githubusercontent.com/1905433/48771489-74f33180-ecb9-11e8-90dd-dc1f30407cf3.png)

I am seeing some energy consumption issues with rolling the logs on Apple Watch.

The frequency of log rolling was about once every 10 minutes. I have scaled this back for our next release as watchOS 5 fixed a lot of crash issues.

That said, we are still rolling logs and I'd be interested to know if anyone else has experienced this? Or if anyone has any suggestions.

**Comment by lewis-smith** [comment]
I have just seen this happen in the simulator. I am not sure of what the exact cause is yet, but `maybeRollLogFileDueToAge` is going into an infinite loop.

This line seems to be the cause:

`fileLogger.rollingFrequency = 10000000000;`

**Comment by sushichop** [comment]
Thanks for reporting issue.

I think this issue has been improved at master branch (probably).
If you are interested in it, could you try it?
Thanks again.

**Comment by debookee** [comment]
Same super high CPU here, app is useless since I've upgraded to 3.5.0.

I'm looping cause creationDate is (null) in my case and roll date is weird as calculated with creationDate.

Logs are looping with:
Debookee[34897:855437] DDFileLogger: scheduleTimerToRollLogFileDueToAge
DDFileLogger: logFileCreationDate: (null)
DDFileLogger: logFileRollingDate : Mon Jan  8 01:00:00

Digging in:
```
- (NSDate *)creationDate {
    if (_creationDate == nil) {
        _creationDate = self.fileAttributes[NSFileCreationDate];
```

-> My fileAttributes is an empty dictionary:
`_fileAttributes	__NSDictionary0 *	0 key/value pairs	0x0000600000008020`

When digging in 
```
- (NSDictionary *)fileAttributes {
    if (_fileAttributes == nil && filePath != nil) {
        NSError *error = nil;
        _fileAttributes = [[NSFileManager defaultManager] attributesOfItemAtPath:filePath error:&error];

        if (error) {
            NSLogError(@"DDLogFileInfo: Failed to read file attributes: %@", error);
        }
    } else {
        _fileAttributes = [NSDictionary new];
    }
```

- fileAttributes is well set on first loop
- Then it goes every time in [NSDictionary new];

Don't know the history of the code, but my guess is that this **else** condition is really wrong in my case.

**Comment by debookee** [comment]
Found this addition __fileAttributes = [NSDictionary new];_ in commit 50ec5b6feaa02f208d028cb02f564f8825102bba by @hhanesand

**Comment by astrokin** [comment]
i had the same issue. resolved it by downgrading version

**Comment by tomlabaude** [comment]
Thanks for your reactivity !
I don't have the experience of PR, committing code, reviewing and all GitHub stuff, but at least, this experience motivates to report problems with as much details and debug to you guys.

Thanks for your awesome work.
