### ISSUE TITLE
Where does the define ddLogLevel use?

### ISSUE THREAD

**Issue by MountainHill** [CocoaLumberjack/CocoaLumberjack#992]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |ios
 Platform Version        | 8.0
 CocoaLumberjack Version | 3.4.2
 Integration Method      | cocoapods
 Xcode Version           | Xcode 10.1

### Issue Description and Steps

I comment `_level` in **DDLogMessage**
```
@interface DDLogMessage : NSObject <NSCopying>
{
    // Direct accessors to be used only for performance
    @public
    NSString *_message;
//    DDLogLevel _level;
    DDLogFlag _flag;
```
```
if ((self = [super init])) {
        BOOL copyMessage = (options & DDLogMessageDontCopyMessage) == 0;
        _message      = copyMessage ? [message copy] : message;
//        _level        = level;
        _flag         = flag;
```
```
- (id)copyWithZone:(NSZone * __attribute__((unused)))zone {
    DDLogMessage *newMessage = [DDLogMessage new];
    
    newMessage->_message = _message;
//    newMessage->_level = _level;
    newMessage->_flag = _flag;
```
**No error throws!!!** So why should I define `ddLogLevel`.I can't see it has any effect but I have to define only because of compile error.

**Comment by ffried** [comment]
First of all, this is only the backing instance variable, that you commented out. You'd also have to comment out the property definition. Furthermore, if you wanted to check where `DDLogLevel` is used, you'd have to comment out [its definition](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/354ddbdcb7df3e2bbbde134b307449de7e3012fa/Classes/DDLog.h#L136-L171).
Once you do that, there'll be enough errors...
<img width="517" alt="build errors" src="https://user-images.githubusercontent.com/1689782/49357423-8a138b80-f6cf-11e8-9064-dbe00b3f516b.png">


To answer your question: `DDLogLevel` is a very basic part of CocoaLumberjack. It is used to specify what level a log message has. The `ddLogLevel` define is used to check, whether your log message needs to be written in the first place. If you log a debug message (using e.g. `DDLogDebug(...)`), but your `ddLogLevel` is set to `DDLogLevelWarning`, then your debug message won't show up.
Next, `DDLogLevel` is heavily used in Log Formatters to distinguish log message. E.g. a log formatter could prefix the log message with the level that was used, so your log could look like this:
```
[DEBUG] This is a debug log message
[INFO] This is an info log message
[WARNING] This is a warning log message
[ERROR] This is an error log message
```

**Comment by MountainHill** [comment]
Actually I say this `ddLogLevel`,not the `ENUM DDLogLevel`
```
#ifndef LOG_LEVEL_DEF
    #define LOG_LEVEL_DEF ddLogLevel
#endif
```

**Comment by MountainHill** [comment]
@ffried

**Comment by ffried** [comment]
Again, as I described above:
> The ddLogLevel constant is used to check, whether your log message needs to be written in the first place. If you log a debug message (using e.g. DDLogDebug(...)), but your ddLogLevel is set to DDLogLevelWarning, then your debug message won't show up.

The `ddLogLevel` constant is your entry point to define what log level should be used. You can set it to `DDLogLevelAll` and nothing will be filtered. But CocoaLumberjack can't make that decision for you.

For more information, also see the introduction header comment in DDLog.h:
```
/**
 * Welcome to CocoaLumberjack!
 *
 * The project page has a wealth of documentation if you have any questions.
 * https://github.com/CocoaLumberjack/CocoaLumberjack
 *
 * If you're new to the project you may wish to read "Getting Started" at:
 * Documentation/GettingStarted.md
 *
 * Otherwise, here is a quick refresher.
 * There are three steps to using the macros:
 *
 * Step 1:
 * Import the header in your implementation or prefix file:
 *
 * #import <CocoaLumberjack/CocoaLumberjack.h>
 *
 * Step 2:
 * Define your logging level in your implementation file:
 *
 * // Log levels: off, error, warn, info, verbose
 * static const DDLogLevel ddLogLevel = DDLogLevelVerbose;
 *
 * Step 2 [3rd party frameworks]:
 *
 * Define your LOG_LEVEL_DEF to a different variable/function than ddLogLevel:
 *
 * // #undef LOG_LEVEL_DEF // Undefine first only if needed
 * #define LOG_LEVEL_DEF myLibLogLevel
 *
 * Define your logging level in your implementation file:
 *
 * // Log levels: off, error, warn, info, verbose
 * static const DDLogLevel myLibLogLevel = DDLogLevelVerbose;
 *
 * Step 3:
 * Replace your NSLog statements with DDLog statements according to the severity of the message.
 *
 * NSLog(@"Fatal error, no dohickey found!"); -> DDLogError(@"Fatal error, no dohickey found!");
 *
 * DDLog works exactly the same as NSLog.
 * This means you can pass it multiple variables just like NSLog.
 **/
```
