### ISSUE TITLE
Memory Leak for macOS

### ISSUE THREAD

**Issue by Whirlwind** [CocoaLumberjack/CocoaLumberjack#995]
in `DDLog.m`, there are some code for macos:
```
- (id)init {
    self = [super init];
    
    if (self) {
        self._loggers = [[NSMutableArray alloc] initWithCapacity:4];
        
#if TARGET_OS_IOS
        NSString *notificationName = @"UIApplicationWillTerminateNotification";
#else
        NSString *notificationName = nil;
        
        // On Command Line Tool apps AppKit may not be avaliable
#ifdef NSAppKitVersionNumber10_0
        
        if (NSApp) {
            notificationName = @"NSApplicationWillTerminateNotification";
        }
        
#endif
        
        if (!notificationName) {
            // If there is no NSApp -> we are running Command Line Tool app.
            // In this case terminate notification wouldn't be fired, so we use workaround.
            
            atexit_b (^{
                [self applicationWillTerminate:nil];
            });
        }
        
#endif /* if TARGET_OS_IOS */
        
```

There is a workaround:
```
            atexit_b (^{
                [self applicationWillTerminate:nil];
            });
```

It will cause DDLog will be retained and never be released. Right?

**Comment by ffried** [comment]
Only for CLI apps, but yes, the block passed to `atexit_b` will be copied and `self` is strongly captured.
Would you mind opening a PR for this and simply capture `self` weakly?

**Comment by Whirlwind** [comment]
It is maybe a bug. The `notificationName` always is nil, and my app is not a CLI, it is an App.

**Comment by ffried** [comment]
One #996 is merged, this should be fixed. Thanks for reporting this!

**Comment by ffried** [comment]
While I'm not 100% sure if those two places really leak, I've also captured self `weakly` there now.
Those dispatch sources are removed when the log file is rolled, so in theory it might not completely leak. But better safe than sorry.
Thanks for reporting these!

**Comment by Whirlwind** [comment]
In my app, the DDFileLogger will still live when I close the window ( the window use a logger, many windows will use many loggers). I use the Instrument to debug it and find the logger be captured.
